'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useMemo, useState } from 'react'
import { Search } from 'lucide-react'
import { useLanguage } from '@/lib/language-context'
import { DOMAIN_LABELS, STORE_ITEMS, storeItemHref, type StoreItem } from '@/lib/store-catalog'

const REFERENCE_SLUGS = ['assistante-de-direction','responsable-projet','commercial','charge-prospection','responsable-marketing','content-strategist','responsable-relation-client','support-client','charge-de-recrutement','charge-formation','analyste-financier','conseiller-transformation-ia']
const PROFILE_HREF = '/collaborateurs-ia/profils-metier/conseiller-transformation-ia'

export function ProfilsFinalContent() {
  const { lang } = useLanguage()
  const fr = lang === 'fr'
  const [query, setQuery] = useState('')
  const [family, setFamily] = useState('all')
  const [added, setAdded] = useState(false)
  const profiles = useMemo(() => REFERENCE_SLUGS.map(slug => STORE_ITEMS.find(item => item.type === 'profil' && item.slug === slug)).filter(Boolean) as StoreItem[], [])
  const filtered = profiles.filter(profile => {
    if (family !== 'all' && profile.facet !== family) return false
    const haystack = [profile.name[lang], profile.description[lang], profile.roleInOrg?.[lang], ...(profile.knowHow?.map(x => x[lang]) ?? []), ...(profile.exampleMissions?.map(x => x[lang]) ?? []), ...profile.keywords].join(' ').toLowerCase()
    return haystack.includes(query.trim().toLowerCase())
  })

  return (
    <main className="bg-[#F3EFE6] text-[#1C1A17]">
      <section className="px-5 pb-14 pt-24 sm:px-8 sm:pt-28"><div className="mx-auto grid max-w-[1200px] items-center gap-12 lg:grid-cols-[1.05fr_0.95fr]"><div><p className="font-mono text-[11px] font-bold uppercase tracking-[0.18em] text-[#B00C54]">{fr ? 'Profils métier' : 'Job profiles'}</p><h1 className="mt-4 font-sf text-[46px] font-bold leading-[0.97] tracking-[-0.055em] sm:text-[66px]">{fr ? <><span className="block">Il garde son identité.</span><span className="block text-[#6E665A]">Il apprend un nouveau métier.</span></> : <><span className="block">Its identity remains.</span><span className="block text-[#6E665A]">It learns a new profession.</span></>}</h1><p className="mt-6 max-w-2xl text-[17px] leading-8 text-[#4E483F]">{fr ? 'Ajoutez à votre Collaborateur IA une responsabilité durable, les compétences nécessaires et de nouvelles missions à prendre en charge.' : 'Add a lasting responsibility, the necessary skills and new missions to your AI Collaborator.'}</p><p className="mt-7 font-sf text-[32px] font-bold text-[#B00C54]">{fr ? 'Profils métier illimités.' : 'Unlimited job profiles.'}</p><div className="mt-7 flex flex-wrap gap-4"><a href="#catalogue" className="bg-[#D10E63] px-6 py-3 text-sm font-bold text-white">{fr ? 'Explorer les profils métier' : 'Explore job profiles'} ↓</a><Link href="/decouvrir" className="px-2 py-3 text-sm font-bold text-[#B00C54]">{fr ? 'Vous partez d’une mission ? Parlez à Alma' : 'Starting from a mission? Talk to Alma'} →</Link></div></div><LucasProfileCard added={added} /></div></section>

      <section className="bg-[#151310] px-5 py-20 text-[#FAF8F3] sm:px-8"><div className="mx-auto max-w-[1100px]"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#F2A4C5]">Une identité. Des expertises qui évoluent.</p><h2 className="mt-4 max-w-5xl font-sf text-[40px] font-bold leading-tight sm:text-[56px]">Une nouvelle responsabilité ne demande pas toujours un nouveau Collaborateur IA.</h2><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_1fr]"><div><p className="text-sm text-[#BDB7AC]">Mission</p><h3 className="mt-2 font-sf text-2xl font-bold">Suivre chaque réclamation client jusqu’à sa résolution.</h3><p className="mt-7 text-sm text-[#F2A4C5]">Profil métier nécessaire</p><p className="mt-2 text-xl font-bold">Responsable relation client</p><p className="mt-7 text-sm text-[#F2A4C5]">Compétences à ajouter</p><ul className="mt-3 grid gap-2 text-sm text-[#BDB7AC] sm:grid-cols-2">{['Qualifier une réclamation','Analyser un dossier client','Planifier les relances','Suivre les engagements','Synthétiser la résolution','Demander une validation humaine'].map(x=><li key={x}>{x}</li>)}</ul></div><div><h3 className="font-sf text-2xl font-bold">Lucas peut prendre en charge cette responsabilité.</h3><p className="mt-4 leading-7 text-[#BDB7AC]">Il connaît déjà les clients, dispose du contexte utile et peut recevoir les accès nécessaires.</p><button onClick={()=>setAdded(true)} disabled={added} className="mt-7 bg-[#D10E63] px-6 py-3 text-sm font-bold disabled:bg-[#2E7D4F]">{added ? 'Profil ajouté à Lucas' : 'Ajouter le profil à Lucas'}</button><div className="mt-8"><LucasProfileCard added={added} dark /></div></div></div><h3 className="mt-12 font-sf text-[38px] font-bold">Le même Lucas. Une nouvelle responsabilité.</h3><p className="mt-5 text-[#BDB7AC]">Un profil métier change ce qu’il sait prendre en charge. Il ne remplace pas celui qui travaille.</p></div></section>

      <section id="catalogue" className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-[1240px]"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#B00C54]">Explorer les profils métier</p><h2 className="mt-4 font-sf text-[40px] font-bold sm:text-[56px]">Quelle responsabilité voulez-vous lui confier ?</h2><div className="relative mt-8 max-w-3xl"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-[#6E665A]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un métier, une responsabilité ou une compétence…" className="h-14 w-full border border-[#DED6C8] bg-white pl-12 pr-4"/></div><p className="mt-3 text-xs text-[#6E665A]">Prospection · Support client · Recrutement · Finance · Automatisation</p><div className="mt-10 grid gap-8 lg:grid-cols-[224px_1fr]"><aside className="h-fit lg:sticky lg:top-24"><p className="font-mono text-[10px] uppercase text-[#6E665A]">Familles</p><div className="mt-3 flex gap-2 overflow-x-auto pb-2 lg:flex-col">{[['all',fr?'Tous les profils':'All profiles'],...Object.entries(DOMAIN_LABELS).map(([key,value])=>[key,value[lang]])].map(([key,label])=><button key={key} onClick={()=>setFamily(key)} className={`shrink-0 px-3 py-2 text-left text-sm ${family===key?'bg-[#151310] text-white':'border border-[#DED6C8]'}`}>{label}</button>)}</div></aside><div>{filtered.length>0?<div className="grid gap-5 xl:grid-cols-2">{filtered.map(profile=><ProfileCard key={profile.slug} profile={profile} lang={lang}/>)}</div>:<AlmaFallback query={query}/>}<AlmaFeature /></div></div></div></section>

      <section className="bg-[#151310] px-5 py-10 text-[#FAF8F3] sm:px-8"><div className="mx-auto flex max-w-[1100px] flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#F2A4C5]">Transmettre un savoir-faire</p><h2 className="mt-2 font-sf text-2xl font-bold">Vous avez une méthode à formaliser et partager ?</h2></div><Link href="/co-createur-ia" className="shrink-0 bg-[#D10E63] px-5 py-3 text-sm font-bold">Devenir Co-créateur IA →</Link></div></section>

      <section className="bg-[#EAE4D9] px-5 py-20 sm:px-8"><div className="mx-auto max-w-[1100px]"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#B00C54]">Une responsabilité durable</p><h2 className="mt-4 font-sf text-[40px] font-bold leading-tight sm:text-[56px]">Le profil apporte un rôle.<br/>Les compétences apportent la méthode.</h2><ol className="mt-10 grid gap-7 sm:grid-cols-2 lg:grid-cols-4">{[['1','Vous partez d’une responsabilité ou d’une mission'],['2','Alma prépare son adaptation'],['3','Vous l’ajoutez à un Collaborateur IA'],['4','Il commence une mission']].map(([n,t])=><li key={n}><span className="font-mono text-xs text-[#B00C54]">0{n}</span><p className="mt-3 font-semibold">{t}</p></li>)}</ol><p className="mt-10 font-sf text-2xl font-bold">Une mission définit le travail. Un profil métier apporte un rôle. Une compétence ajoute une méthode.</p></div></section>

      <section className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-[1100px]"><h2 className="font-sf text-[40px] font-bold sm:text-[56px]">Faire progresser avant de créer.</h2><p className="mt-5 max-w-3xl text-[17px] leading-8 text-[#4E483F]">Un Collaborateur IA peut exercer plusieurs responsabilités. Alma recommande une nouvelle identité uniquement lorsqu’une présence professionnelle distincte, des ressources dédiées ou un environnement isolé sont réellement nécessaires.</p><p className="mt-7 font-sf text-2xl font-bold text-[#B00C54]">Plus de savoir-faire ne signifie pas automatiquement plus d’identités.</p></div></section>

      <section className="bg-[#D10E63] px-5 py-16 text-white sm:px-8"><div className="mx-auto max-w-[1000px]"><h2 className="font-sf text-[42px] font-bold leading-tight sm:text-[58px]">Une identité qui vous appartient.<br/>Des expertises qui évoluent.</h2><p className="mt-5 text-white/80">Ajoutez autant de profils métier que les responsabilités de votre Collaborateur IA l’exigent.</p><div className="mt-7 flex flex-wrap gap-4"><a href="#catalogue" className="bg-[#151310] px-6 py-3 text-sm font-bold">Explorer les profils métier</a><Link href="/decouvrir" className="px-3 py-3 text-sm font-bold underline">Décrire une mission à Alma →</Link></div><p className="mt-4 text-xs text-white/75">Profils métier illimités · Adaptation avec Alma · Mises à jour proposées par Unitalk</p><p className="mt-7 font-sf text-xl font-bold">Des Collaborateurs IA qui progressent avec votre entreprise.</p></div></section>
    </main>
  )
}

function LucasProfileCard({added,dark=false}:{added:boolean;dark?:boolean}){return <div className={`border p-5 ${dark?'border-white/15 bg-white/5':'border-[#DED6C8] bg-[#FAF8F3]'}`}><div className="flex justify-between"><div><h3 className="font-sf text-2xl font-bold">Lucas</h3><p className={dark?'text-[#BDB7AC]':'text-[#6E665A]'}>Collaborateur IA · Votre entreprise</p></div><span className="text-xs font-bold text-[#2E9E5B]">Prêt</span></div><p className="mt-6 font-mono text-[9px] uppercase tracking-[0.12em]">Identité</p><p className={`mt-2 text-sm ${dark?'text-[#BDB7AC]':'text-[#4E483F]'}`}>lucas@entreprise.fr · Agenda · Téléphone · Mémoire et expérience</p><p className="mt-6 font-mono text-[9px] uppercase tracking-[0.12em]">Profils métier</p><ul className="mt-2 space-y-2 text-sm"><li>Responsable du développement commercial</li>{added?<li className="font-bold text-[#2E9E5B]">Responsable relation client · ajouté</li>:<li className={dark?'text-[#F2A4C5]':'text-[#B00C54]'}>+ Ajouter un profil métier</li>}</ul></div>}
function ProfileCard({profile,lang}:{profile:StoreItem;lang:'fr'|'en'}){return <article className="group flex min-h-[310px] flex-col border border-[#DED6C8] bg-[#FAF8F3] p-6"><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-[#B00C54]">{DOMAIN_LABELS[profile.facet]?.[lang]??profile.facet}</p><h3 className="mt-3 font-sf text-2xl font-bold">{profile.name[lang]}</h3><p className="mt-3 text-sm leading-6 text-[#4E483F]">{profile.description[lang]}</p><div className="mt-5 flex flex-wrap gap-2">{profile.knowHow?.slice(0,4).map(x=><span key={x[lang]} className="text-xs text-[#6E665A]">{x[lang]}</span>)}</div><div className="mt-5 border-t border-[#DED6C8] pt-4"><p className="font-mono text-[9px] uppercase text-[#6E665A]">Missions accessibles</p><p className="mt-2 text-xs leading-5 text-[#4E483F]">{profile.exampleMissions?.slice(0,3).map(x=>x[lang]).join(' · ')}</p></div><Link href={storeItemHref(profile)} className="mt-auto pt-5 text-sm font-bold text-[#B00C54]">Voir le profil →</Link></article>}
function AlmaFeature(){return <section className="mt-12 grid gap-8 border-y border-[#1C1A17]/15 py-10 lg:grid-cols-[280px_1fr]"><Image src="/alma-avatar.png" alt="Alma" width={280} height={280} className="w-full max-w-[280px]"/><div><p className="font-mono text-[10px] uppercase text-[#B00C54]">Profil créé chez Unitalk</p><h3 className="mt-3 font-sf text-[34px] font-bold">Conseiller en transformation IA</h3><p className="mt-4 leading-7 text-[#4E483F]">Créé par Patrick Chassany. Exercé et amélioré avec Alma chez Unitalk.</p><div className="mt-5 flex flex-wrap gap-4 text-sm"><Link href="/@patrickchassany" className="font-bold text-[#B00C54]">Voir Patrick →</Link><Link href="/@unitalk/alma" className="font-bold text-[#B00C54]">Voir Alma →</Link></div><Link href={PROFILE_HREF} className="mt-6 inline-flex bg-[#151310] px-5 py-3 text-sm font-bold text-white">Découvrir le profil métier</Link><p className="mt-4 font-semibold">Alma ne se clone pas. Son savoir-faire se transmet.</p></div></section>}
function AlmaFallback({query}:{query:string}){return <div className="bg-[#151310] p-7 text-[#FAF8F3]"><p className="font-mono text-[10px] uppercase text-[#F2A4C5]">Préparé par Alma</p><h3 className="mt-3 font-sf text-3xl font-bold">Vous ne trouvez pas la bonne responsabilité ?</h3><p className="mt-4 text-[#BDB7AC]">Aucun profil ne correspond précisément à votre recherche. Alma peut préparer une réponse à partir de votre objectif.</p><Link href={`/decouvrir?q=${encodeURIComponent(query)}`} className="mt-6 inline-flex bg-[#D10E63] px-5 py-3 text-sm font-bold">Continuer avec Alma</Link></div>}
