import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const hub = readFileSync(new URL('../components/unitalk-store-hub.tsx', import.meta.url), 'utf8')
const models = readFileSync(new URL('../lib/ai-models-catalog.ts', import.meta.url), 'utf8')
const page = readFileSync(new URL('../app/marketplace/page.tsx', import.meta.url), 'utf8')
const catalog = readFileSync(new URL('../lib/store-catalog.ts', import.meta.url), 'utf8')
const discoverAccount = readFileSync(new URL('../components/discover/screen-account.tsx', import.meta.url), 'utf8')

describe('Marketplace IA hub', () => {
  it('centralizes missions, AI Collaborators and the five equipment categories', () => {
    expect(page).toContain('MarketplaceOverview')
    for (const label of ['Missions','Collaborateurs IA','Profils métier','Compétences','Applications','Modèles IA','Serveurs IA']) expect(`${page}${hub}`).toContain(label)
    expect(hub).toContain('STORE_CATEGORIES')
    expect(hub).toContain("heroTitle: { fr: 'Choisissez le Collaborateur IA qui rejoindra votre équipe.'")
  })

  it('shows canonical public AI Collaborators first', () => {
    expect(hub.indexOf("id: 'collaborateurs-ia'")).toBeLessThan(hub.indexOf("id: 'profils-metier'"))
    expect(hub).toContain('MARKETPLACE_COLLABORATOR_SLUGS')
    expect(hub).toContain('ROLE_DETAILS[slug]')
    expect(hub).toContain('collaboratorHref(detail.slug)')
    expect(hub).toContain('detail.avatar')
    expect(hub).toContain("explain: { fr: 'Comment fonctionne un Collaborateur IA ?'")
  })

  it('states the catalog and knowledge-work positioning', () => {
    expect(hub).toContain('Choisissez le Collaborateur IA qui rejoindra votre équipe.')
    expect(hub).toContain('Un profil métier de référence pour chaque métier de la connaissance')
  })

  it('starts directly with the catalog', () => {
    expect(hub).not.toContain('AlmaMissionComposer')
    expect(hub).not.toContain('getSpeechRecognition')
    expect(hub).toContain('px-5 pt-28 sm:px-8 sm:pt-40')
    expect(hub).not.toContain("'pb-9 pt-20 sm:pb-11 sm:pt-24")
    expect(hub).not.toContain('Marketplace · Collaborateurs IA')
    expect(hub).not.toContain('border-t border-[#CFC3B2]')
  })

  it('uses one crawlable horizontal category navigation', () => {
    expect(hub).not.toContain("w-[220px] shrink-0")
    expect(hub).not.toContain('sticky top-24')
    expect(hub).toContain('<nav className="mx-auto flex w-full max-w-6xl overflow-x-auto scrollbar-hide"')
    expect(hub).toContain("href={localizedHref('missions', lang)}")
    expect(hub).toContain('overflow-x-auto scrollbar-hide')
    expect(hub).toContain("localizePublicHref('/marketplace', lang)")
    expect(hub).not.toContain('window.history.pushState')
    expect(hub).not.toContain("window.addEventListener('popstate'")
  })

  it('centralizes real catalogs with search and featured cards', () => {
    expect(hub).toContain('STORE_ITEMS')
    expect(hub).toContain('itemsForCategory')
    expect(hub).toContain('MarketplaceItemCard')
    expect(hub).toContain('Rechercher un profil métier')
    expect(hub).toContain('category={activeCategory}')
    expect(hub).not.toContain('useLayoutEffect')
  })

  it('makes skills concrete and filterable', () => {
    for (const text of ["skillCategories: 'Catégories de compétences'", 'Contexte d’application', 'Résultat produit', 'Profils compatibles', 'Méthode à valider sur votre cas']) expect(hub).toContain(text)
    expect(hub).toContain('Ajoutez gratuitement les compétences nécessaires à chaque mission.')
    expect(hub).toContain('Chaque compétence est adaptée au profil et aux missions de votre Collaborateur.')
    expect(hub).toContain("storeType === 'competence' ? { fr: 'Gratuite', en: 'Free' }")
    expect(hub).toContain("skillHeroProofs: ['Sans coût unitaire avec une offre compatible', 'Méthodes documentées', 'Réutilisables par mission']")
    expect(hub).toContain('<SkillMarketplaceCard')
    expect(hub).toContain('min-h-[245px]')
    expect(hub).toContain('sm:min-h-[265px]')
    expect(hub).toContain('group-hover:opacity-100')
    expect(hub).toContain('absolute inset-0 hidden translate-y-2')
    expect(hub).not.toContain("lang === 'fr' ? 'Compétence' : 'Skill'")
  })

  it('uses the shared featured hero for profiles, skills, applications and models', () => {
    expect(hub).toContain("['profils-metier', 'competences', 'applications', 'modeles-ia', 'serveurs-ia'].includes(activeCategory.id)")
    expect(hub).toContain('Connectez uniquement les applications nécessaires à chaque mission.')
    expect(hub).toContain('Votre Collaborateur IA utilise les applications pour réaliser les actions que vous lui autorisez.')
    expect(hub).toContain("applicationHeroProofs: ['Accès définis par votre entreprise', 'Actions autorisées']")
    expect(hub).toContain("modelHeroProofs: ['Sélection automatique', 'Fournisseurs sous votre contrôle']")
    expect(hub).toContain('Utilisez les modèles avec vos crédits Unitalk prépayés ou vos propres clés API.')
    expect(hub).toContain("serverHeroProofs: ['Infrastructure privée', 'Capacité évolutive', 'Déploiement gouverné']")
    expect(hub).toContain('featuredHeroProofs.map((proof)')
    expect(hub).toContain('<MarketplaceSidebarCatalog')
    expect(hub).toContain("category.id === 'competences' ? Object.fromEntries(PROFILE_DEPARTMENTS.map")
    expect(hub).toContain("facetKeys: storeType === 'competence' ? profileDomainsFor(item.relatedProfiles)")
    expect(hub).toContain("skillCategories: 'Catégories de compétences', applicationCategories: 'Catégories d’applications', serverCategories: 'Types d’infrastructure'")
    expect(models).toContain("modalities: ['texte', 'multimodal']")
  })

  it('orders job profiles by broad SMB demand', () => {
    expect(hub).toContain('PROFILE_DEMAND_ORDER')
    const demandOrder = hub.slice(hub.indexOf('const PROFILE_DEMAND_ORDER = ['), hub.indexOf('const PROFILE_DEMAND_RANK'))
    const commercial = demandOrder.indexOf("'commercial'")
    const administrative = demandOrder.indexOf("'gestionnaire-administratif'")
    const executive = demandOrder.indexOf("'assistante-de-direction'")
    const transformation = demandOrder.indexOf("'conseiller-transformation-ia'")
    expect(commercial).toBeGreaterThan(-1)
    expect(commercial).toBeLessThan(administrative)
    expect(administrative).toBeLessThan(executive)
    expect(executive).toBeLessThan(transformation)
    expect(hub).toContain("PROFILE_DEMAND_RANK.get(a.slug)")
  })

  it('offers a clear path for a missing job profile', () => {
    expect(hub).toContain('Vous ne trouvez pas le profil métier adapté ?')
    expect(hub).toContain('adapter un profil existant ou à préparer un nouveau profil métier')
    expect(hub).toContain('Créer mon profil métier')
    expect(hub).toContain('Proposer un profil à la Marketplace')
    expect(hub).not.toContain("lang === 'fr' ? 'Profil sur mesure'")
  })

  it('keeps each category explanation on its reference route', () => {
    for (const href of ['/collaborateurs-ia/profils-metier','/marketplace/competences','/marketplace/applications','/capacite-ia','/marketplace/serveurs-ia']) expect(hub).toContain(`href: '${href}'`)
  })

  it('frames models as access and servers as scalable execution infrastructure', () => {
    expect(hub).toContain('Une interface unique pour accéder aux meilleurs modèles d’IA adaptés à chaque mission.')
    expect(hub).toContain('Unitalk sélectionne automatiquement le modèle pertinent parmi ceux autorisés par votre entreprise.')
    expect(hub).toContain('Où votre Collaborateur travaille. Une infrastructure qui évolue.')
    expect(hub).toContain('Augmentez ses ressources lorsque le travail l’exige.')
    expect(hub).toContain("'unitalk-ai-cloud': { fr: 'Unitalk AI Cloud'")
    expect(hub).toContain("'open-source': { fr: 'Applications open source'")
    expect(hub).toContain("hebergeurs: { fr: 'Hébergeurs'")
    expect(hub).toContain("facetKey: 'unitalk-ai-cloud'")
    expect(hub).toContain("facetKey: 'hebergeurs'")
    expect(hub).toContain("href: '/hebergeurs'")
    for (const size of ["name: { fr: 'Small'", "name: { fr: 'Medium'", "name: { fr: 'Large'", "name: { fr: 'XL'", "name: { fr: 'XXL'"]) expect(catalog).toContain(size)
    for (const capacity of ['1 CPU · 4 Go de RAM', '2 CPU · 8 Go de RAM', '4 GPU · 16 Go de RAM', '8 GPU · 32 Go de RAM', '16 GPU · 64 Go de RAM']) expect(catalog).toContain(capacity)
    for (const host of ['OVHcloud', 'Scaleway', 'OUTSCALE', 'Clever Cloud', 'IONOS', 'Hetzner', 'Open Telekom Cloud', 'Infomaniak', 'Exoscale', 'UpCloud', 'Gcore', 'Hostinger', 'Amazon Web Services', 'Microsoft Azure', 'Google Cloud', 'Oracle Cloud']) expect(hub).toContain(host)
    for (const app of ['Hermes', 'Paperclip', 'GBrain', 'Honcho', 'Stalwart', 'Buzz', 'n8n', 'OpenCode', 'Twenty', 'Payload', 'Jitsi', 'Plane']) expect(hub).toContain(app)
    expect(catalog).toContain("if (item.type === 'server') return `/decouvrir?store=${item.slug}&source=marketplace-servers`")
    expect(hub).not.toContain('/collaborateurs-ia/serveurs')
  })

  it('shows popular proprietary and open-weight models with focused cards', () => {
    const modelCard = hub.slice(hub.indexOf('function ModelMarketplaceCard'), hub.indexOf('function ModelProviderLogo'))
    for (const model of ['GPT-5.6 Luna', 'GPT-5.6 Sol', 'GPT-5.6 Terra', 'Claude Opus 5', 'Claude Sonnet 5', 'Claude Fable 5', 'Claude Haiku 4.5', 'Gemini 3.6 Flash', 'DeepSeek V4 Flash', 'Hy3', 'GLM 5.3', 'DeepSeek V4 Pro']) expect(models).toContain(model)
    expect(models).toContain("title: 'Kimi K3'")
    expect(models).toContain("title: 'GPT-5 mini'")
    expect(models).toContain("title: 'GPT-5 nano'")
    expect(models).toContain("title: 'Mistral Large 3'")
    expect(models).toContain("title: 'MiniMax M3'")
    for (const model of ['Veo 3.1', 'Veo 3.1 Fast', 'Veo 3.1 Lite', 'Kling 3.0', 'Wan 3.0', 'Seedance 2.0']) expect(models).toContain(`title: '${model}'`)
    for (const maker of ['Google', 'Kling AI', 'Alibaba', 'ByteDance']) expect(models).toContain(`maker: '${maker}'`)
    expect(models.match(/modalities: \['video'\]/g)).toHaveLength(3)
    expect(models).toContain("modalities: ['video', 'audio']")
    expect(models).toContain("modalities: ['video', 'multimodal']")
    expect(models).toContain('séquences multi-plans jusqu’à 15 secondes, avec audio natif, synchronisation labiale et cohérence des personnages')
    expect(models).toContain("modalities: ['video', 'audio', 'multimodal']")
    expect(models).toContain('séquences jusqu’à 15 secondes en 1080p à partir d’images, de vidéos et d’audio, avec édition et extension précises')
    for (const model of ['Nano Banana 2', 'Nano Banana Pro', 'Seedream 5.0', 'ChatGPT Images 2.0', 'Flux 2 Pro', 'Flux 2 Flex', 'Grok Imagine', 'Ideogram v4']) expect(models).toContain(`title: '${model}'`)
    for (const maker of ['Google Gemini', 'Black Forest', 'xAI', 'Ideogram']) expect(models).toContain(`maker: '${maker}'`)
    expect(models.match(/modalities: \['image'\]/g)).toHaveLength(9)
    for (const model of ['Gladia', 'Whisper', 'GPT-4o Transcribe', 'GPT-4o Mini Transcribe', 'Nova-3']) expect(models).toContain(`title: '${model}'`)
    for (const maker of ['Gladia', 'Deepgram']) expect(models).toContain(`maker: '${maker}'`)
    expect(models.match(/capabilities: \['transcription'\]/g)).toHaveLength(6)
    expect(models).toContain("title: 'GPT Audio'")
    expect(models).toContain("modalities: ['audio', 'multimodal']")
    for (const model of ['Eleven v3', 'GPT-4o Mini TTS', 'Gemini 2.5 Flash TTS', 'Gemini 2.5 Pro TTS']) expect(models).toContain(`title: '${model}'`)
    expect(models.match(/capabilities: \['speech'\]/g)).toHaveLength(4)
    expect(hub).toContain("fr: 'Modèle propriétaire'")
    expect(hub).toContain("fr: 'Modèle open source'")
    expect(hub).toContain("item.modelTypeKey === 'open-source' ? 'Open source'")
    expect(hub).toContain("item.modelTypeKey === 'poids-ouverts'")
    expect(hub).toContain("lang === 'fr' ? 'Propriétaire' : 'Proprietary'")
    expect(hub).toContain('<ModelMarketplaceCard')
    expect(hub).toContain('item.modelModalities?.map')
    expect(hub).toContain('min-h-[190px]')
    expect(hub).toContain("!['competences', 'modeles-ia'].includes(category.id)")
    expect(modelCard).toContain('<Link')
    expect(modelCard).toContain('Sélectionner ce modèle')
    expect(hub).toContain('Ajoutez n’importe quel modèle ou fournisseur grâce à un endpoint personnalisé.')
    expect(hub).toContain('border border-dashed border-[#AFA596] bg-transparent')
    expect(hub).not.toContain("'border-[#216641]/30 bg-[#E4F3E8] text-[#216641]' : 'border-[#CFC5B5]")
    expect(hub).toContain('<ModelProviderLogo maker={item.origin} />')
    for (const logo of ['kling.svg', 'bytedance.svg', 'alibaba.svg', 'ideogram.svg', 'grok.svg', 'deepgram.svg']) expect(hub).toContain(`/logos/${logo}`)
    expect(hub).toContain('className="size-6 object-contain brightness-0"')
    for (const provider of ['OpenAI', 'Anthropic', 'Gemini', 'DeepSeek', 'Tencent', 'XiaomiMiMo', 'Zhipu', 'Nvidia', 'Flux', 'Qwen', 'Mistral']) expect(hub).toContain(`<${provider}`)
    expect(hub).toContain('modelTypeKey: item.type')
    expect(hub).not.toContain('border-[#216641]/30 bg-[#E4F3E8]')
    expect(hub).toContain("multimodal: { fr: 'Multimodal', en: 'Multimodal' }")
    expect(hub).toContain("speech: { fr: 'Synthèse vocale', en: 'Speech synthesis' }")
    expect(hub).toContain("transcription: { fr: 'Transcription', en: 'Transcription' }")
    expect(hub).toContain("'deep-research': { fr: 'Recherche approfondie', en: 'Deep research' }")
    expect(hub).toContain("'generation-image': { fr: 'Génération d’images', en: 'Image generation' }")
    expect(hub).toContain("'generation-video': { fr: 'Génération vidéo', en: 'Video generation' }")
    expect(hub).toContain("['Modalités', 'Modalities', MODEL_MODALITY_ORDER]")
    expect(hub).toContain("['Capacités', 'Capabilities', MODEL_CAPABILITY_ORDER]")
    expect(hub).toContain('item.modelCapabilities?.map')
    for (const model of ['o3 Deep Research', 'o4-mini Deep Research']) expect(models).toContain(`title: '${model}'`)
    expect(hub).not.toContain("rerank: { fr: 'Rerank'")
    expect(models).not.toContain("title: 'Qwen3 Reranker 8B'")
    expect(hub).not.toContain("embeddings: { fr: 'Embeddings'")
    expect(models).not.toContain("title: 'Qwen3 Embedding'")
    expect(discoverAccount).toContain("speech: 'Synthèse vocale'")
    expect(discoverAccount).toContain("multimodal: 'Multimodal'")
    expect(discoverAccount).not.toContain("rerank: 'Classement des résultats'")
    expect(discoverAccount).not.toContain("embeddings: 'Recherche sémantique'")
    expect(models).toContain("modalities: ['texte', 'multimodal']")
    expect(hub).toContain("lang === 'fr' ? 'Type de modèle' : 'Model type'")
    expect(hub).toContain("lang === 'fr' ? 'Tous les modèles IA' : 'All AI models'")
    expect(hub).toContain("modelType === type.id ? '' : type.id")
  })

  it('uses fully clickable profile and skill cards with a progressive add action', () => {
    expect(hub).toContain('aria-label={`${labels.addProfile} : ${item.title}`}')
    expect(hub).toContain('group-hover:bg-[var(--profile-accent)]')
    expect(hub).toContain('group-focus-visible:bg-[var(--profile-accent)]')
    expect(hub).toContain('sm:group-hover:opacity-0')
    expect(hub).toContain('absolute inset-0 hidden translate-y-2')
    expect(hub).toContain('aria-label={`${labels.addProfile} : ${item.title}`}')
    expect(hub).not.toContain('>Profil métier</p>')
    expect(hub).not.toContain("lang === 'fr' ? 'Compétence' : 'Skill'")
  })

  it('keeps desktop filter sidebars independently scrollable', () => {
    expect(hub.match(/max-h-\[calc\(100dvh-180px\)\] overflow-y-auto/g)).toHaveLength(2)
  })

  it('uses the compact progressive action treatment for application cards', () => {
    expect(hub).toContain("category.id === 'applications' && href")
    expect(hub).toContain('aria-label={`${applicationAction} : ${item.title}`} className="group relative flex min-h-[210px]')
    expect(hub).toContain('bg-[#C80B5B] px-4 text-xs font-bold text-white opacity-0')
    expect(hub).toContain('<h3 className="min-w-0 line-clamp-2 text-[22px]')
  })

  it('uses the compact progressive action treatment for server cards', () => {
    expect(hub).toContain("category.id === 'serveurs-ia'")
    expect(hub).not.toContain('Préparer la demande')
    expect(hub).toContain('item.status && !item.pending')
    expect(hub).toContain("hideEyebrow={category.id === 'serveurs-ia'}")
    expect(hub).toContain('return href ? <Link')
    expect(hub).toContain('text-[#B00C54]')
    expect(hub).not.toContain('Infrastructure d’exécution')
  })

  it('shares catalog filters in the URL and keeps application availability honest', () => {
    expect(hub).toContain("params.get('q')")
    expect(hub).toContain("params.get('statut')")
    expect(hub).toContain("params.get('categorie')")
    expect(hub).toContain("params.get('createur')")
    expect(hub).toContain('window.history.replaceState')
    expect(hub).toContain("{ fr: 'Bientôt disponible', en: 'Coming soon' }")
    expect(hub).toContain("{ fr: 'Disponible', en: 'Available' }")
    expect(hub).toContain('MarketplaceFaq')
    for (const question of ['Est-ce disponible ?', 'Qu’est-ce qui est inclus ?', 'Quel est le prix ?', 'Quels sont les prérequis ?', 'Un essai est-il prévu ?', 'Quelle version est proposée ?', 'Qui fournit et maintient ?']) expect(hub).toContain(question)
    const servers = catalog.slice(catalog.indexOf('const SERVERS'), catalog.indexOf('const PROFILE_ITEMS'))
    expect(servers).not.toContain("commercialStatus: 'draft'")
  })

  it('uses the same structured cards for skills, applications, models and servers', () => {
    expect(hub).toContain("['competences', 'applications', 'modeles-ia', 'serveurs-ia'].includes(category.id)")
    expect(hub).not.toContain('Bibliothèque de savoir-faire')
    expect(hub).not.toContain('Choisissez une compétence prête à ajouter.')
    expect(hub).not.toContain('Outils de travail')
    expect(hub).not.toContain('Connectez uniquement les applications utiles.')
    expect(hub).not.toContain('Le bon modèle est sélectionné pour chaque travail.')
    expect(hub).not.toContain('Intelligences disponibles')
    expect(hub).not.toContain('familles de modèles`')
    expect(hub).not.toContain('Dimensionnez un environnement adapté au travail.')
    expect(hub).toContain("category.id === 'applications' ? (lang === 'fr' ? 'Usage principal'")
    expect(hub).toContain("category.id === 'modeles-ia' ? (lang === 'fr' ? 'Sélection'")
    expect(hub).toContain("lang === 'fr' ? 'Contexte conseillé' : 'Recommended context'")
    expect(hub).not.toContain("lang === 'fr' ? 'Gratuite' : 'Free'")
  })
})
