'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { Check, ChevronRight, Clock3 } from 'lucide-react'

const STAGES = [
  { label: 'Mission confiée', time: '09:12', body: 'Hugo analyse l’offre, le marché et les critères définis par Claire.' },
  { label: 'Décision requise', time: '10:04', body: 'Autoriser l’envoi des douze messages préparés ?' },
  { label: 'Validation', time: '10:18', body: 'Claire valide dix messages et demande une vérification sur deux références client.' },
  { label: 'Travail repris', time: '10:21', body: 'Hugo exécute uniquement les actions validées.' },
  { label: 'Résultat livré', time: '11:03', body: 'Entreprises contactées, messages, sources, décisions et prochaines relances restent attachés à la mission.' },
]

export function WorkspaceFinalContent() {
  const [stage, setStage] = useState(1)
  const [decision, setDecision] = useState<'pending' | 'examining' | 'modified' | 'approved' | 'refused'>('pending')
  const [memory, setMemory] = useState<'pending' | 'kept' | 'corrected' | 'rejected'>('pending')

  return (
    <main className="bg-[#F3EFE6] text-[#1C1A17]">
      <section className="px-5 pb-14 pt-24 sm:px-8 sm:pt-28"><div className="mx-auto grid max-w-[1200px] items-center gap-10 lg:grid-cols-[0.86fr_1.14fr]">
        <div><p className="font-mono text-[11px] font-bold uppercase tracking-[0.18em] text-[#B00C54]">Workspace</p><h1 className="mt-4 font-sf text-[46px] font-bold leading-[0.96] tracking-[-0.055em] sm:text-[68px]"><span className="block">Le travail avance.</span><span className="block text-[#6E665A]">Vous gardez la main.</span></h1><p className="mt-6 max-w-xl text-[17px] leading-8 text-[#4E483F]">Le Workspace réunit vos équipes humaines, vos Collaborateurs IA, leurs missions, les décisions attendues et les résultats produits.</p><p className="mt-3 font-semibold">Une seule interface. Sur Desktop, le Web, vos messageries et le terminal.</p><div className="mt-7 flex flex-wrap gap-4"><Link href="/decouvrir" className="bg-[#D10E63] px-6 py-3 text-sm font-bold text-white">Confier une première mission</Link><a href="#mission-action" className="px-2 py-3 text-sm font-bold text-[#B00C54]">Voir le Workspace en action ↓</a></div><p className="mt-4 text-xs text-[#6E665A]">Utilisateurs humains gratuits · Chat gratuit · Application Desktop gratuite</p></div>
        <WorkspaceDemo stage={stage} setStage={setStage} decision={decision} setDecision={setDecision} />
      </div></section>

      <Section id="mission-action" eyebrow="Une mission en action" title={<>Pas seulement des conversations.<br/>Un travail qui va jusqu’au résultat.</>}><p>La même mission évolue sous vos yeux, du message initial au résultat livré.</p><ol className="mt-10 border-t border-[#1C1A17]/15">{STAGES.map((item, index)=><li key={item.label} className="grid gap-3 border-b border-[#1C1A17]/15 py-6 sm:grid-cols-[70px_180px_1fr]"><span className="font-mono text-[11px] text-[#B00C54]">{item.time}</span><strong>{item.label}</strong><span className="text-[#4E483F]">{item.body}</span></li>)}</ol><div className="mt-10 border-y border-[#1C1A17]/15 py-8 text-center"><h3 className="font-sf text-[34px] font-bold">Objectif. Travail. Décision. Résultat.</h3><p className="mt-3">Les conversations expliquent. La mission organise. Le résultat reste.</p></div></Section>

      <section className="bg-[#151310] px-5 py-20 text-[#FAF8F3] sm:px-8"><div className="mx-auto max-w-[1120px]"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#F2A4C5]">Collaboration</p><h2 className="mt-4 max-w-5xl font-sf text-[40px] font-bold leading-tight sm:text-[58px]">Humains et Collaborateurs IA.<br/><span className="text-[#BDB7AC]">La même mission. Le bon contexte. Des droits différents.</span></h2><div className="mt-12 grid border-y border-white/15 sm:grid-cols-2 lg:grid-cols-4"><Actor image="/images/claire-avatar.png" title="Claire donne le cap">Elle définit le résultat attendu et conserve les décisions engageantes.</Actor><Actor image="/images/hugo-avatar.png" title="Hugo fait avancer le travail" ai>Il analyse, planifie, exécute les actions autorisées et rend compte.</Actor><Actor image="/alma-avatar.png" title="Alma prépare ce qui manque" ai>Elle structure la mission et recommande profils, compétences, accès et validations.</Actor><Actor title="Un expert peut intervenir">Son identité, son périmètre, ses accès, son coût et sa durée sont validés avant son arrivée.</Actor></div><p className="mt-9 font-sf text-2xl font-bold text-[#F2A4C5]">L’expert intervient. Le Collaborateur IA progresse. L’entreprise conserve le savoir-faire.</p><div className="mt-14 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{CHANNELS.map(([a,b])=><div key={a} className="border-t border-white/15 pt-4"><h3 className="font-sf text-xl font-bold">{a}</h3><p className="mt-2 text-sm leading-7 text-[#BDB7AC]">{b}</p></div>)}</div><p className="mt-9 font-semibold">Une conversation peut commencer ailleurs. Le travail se poursuit dans le même Workspace.</p></div></section>

      <Section eyebrow="Vous gardez la main" title="Chacun sait ce qu’il peut faire."><p>Pour chaque mission, l’entreprise définit ce que le Collaborateur IA peut consulter, préparer, modifier, exécuter, dépenser ou soumettre à validation.</p><div className="mt-10 grid gap-10 lg:grid-cols-2"><div className="border border-[#DED6C8] bg-[#FAF8F3] p-6"><p className="font-mono text-[10px] uppercase text-[#B00C54]">Action proposée par Hugo</p><h3 className="mt-3 font-sf text-2xl font-bold">Envoyer douze messages de prospection.</h3><dl className="mt-6 divide-y divide-[#DED6C8]">{[['Lire le CRM','Autorisé'],['Préparer les messages','Autorisé'],['Envoyer les messages','Validation requise'],['Modifier les tarifs','Interdit'],['Engager une dépense','Interdit']].map(([a,b])=><div key={a} className="flex justify-between gap-4 py-3 text-sm"><dt>{a}</dt><dd className="font-semibold">{b}</dd></div>)}</dl><button onClick={()=>setDecision('approved')} className="mt-5 bg-[#D10E63] px-5 py-3 text-sm font-bold text-white">Valider cet envoi</button>{decision==='approved'&&<p className="mt-3 text-xs text-[#2E7D4F]">Validé par Claire · 10:18 · Autorisation limitée à cette mission</p>}</div><div><h3 className="font-sf text-3xl font-bold">Ce qui est conservé</h3><ul className="mt-5 space-y-3 text-[#4E483F]">{['L’action proposée','La recommandation du Collaborateur IA','Les sources','La décision humaine','L’action exécutée','Le résultat obtenu'].map(x=><li key={x}>{x}</li>)}</ul><p className="mt-7 font-semibold">L’autonomie ne supprime pas le contrôle. Elle concentre votre attention là où elle compte.</p></div></div></Section>

      <Section eyebrow="Mémoire gouvernée" title="Tout le monde ne voit pas tout."><div className="grid gap-10 lg:grid-cols-2"><div><h3 className="font-sf text-2xl font-bold">Le contexte de l’entreprise</h3><p className="mt-3 leading-7 text-[#4E483F]">Produits, clients, procédures, documents et décisions accessibles selon les droits.</p><h3 className="mt-8 font-sf text-2xl font-bold">L’expérience du Collaborateur IA</h3><p className="mt-3 leading-7 text-[#4E483F]">Méthodes éprouvées, corrections validées, préférences confirmées et savoir-faire acquis.</p></div><div className="border border-[#DED6C8] bg-[#FAF8F3] p-6"><p className="font-mono text-[10px] uppercase text-[#B00C54]">Proposition de mémoire</p><blockquote className="mt-4 text-lg">Claire préfère vérifier toute référence client avant l’envoi d’une campagne.</blockquote><div className="mt-6 flex flex-wrap gap-2">{[['rejected','Ne pas mémoriser'],['corrected','Corriger'],['kept','Conserver']].map(([key,label])=><button key={key} onClick={()=>setMemory(key as typeof memory)} className={`border px-3 py-2 text-xs font-bold ${memory===key?'border-[#D10E63] bg-[#D10E63] text-white':'border-[#DED6C8]'}`}>{label}</button>)}</div></div></div><p className="mt-8 font-semibold">Chacun reçoit le contexte nécessaire à son travail.</p></Section>

      <section className="bg-[#EAE4D9] px-5 py-20 sm:px-8"><div className="mx-auto max-w-[1120px]"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#B00C54]">Sous le Workspace</p><h2 className="mt-4 font-sf text-[42px] font-bold leading-tight sm:text-[58px]">Une interface simple.<br/>Un écosystème IA complet.</h2><p className="mt-5 max-w-3xl text-[17px] leading-8 text-[#4E483F]">Hermes fournit l’agent autonome. Unitalk lui donne une identité, une entreprise, une mémoire gouvernée, des outils et des collègues.</p><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{TECH.map(([a,b])=><div key={a} className="border-t border-[#1C1A17]/15 pt-4"><h3 className="font-sf text-xl font-bold">{a}</h3><p className="mt-2 text-sm leading-7 text-[#4E483F]">{b}</p></div>)}</div><h3 className="mt-14 font-sf text-[40px] font-bold">Changez de modèle.<br/>Pas de Collaborateur.</h3><p className="mt-6 font-mono text-xs text-[#6E665A]">Hermes · Clerk · AI Gateway · Honcho · Pipedream · Stalwart · Telnyx</p><Link href="/platform" className="mt-5 inline-flex text-sm font-bold text-[#B00C54]">Découvrir l’architecture Unitalk →</Link></div></section>

      <section className="bg-[#D10E63] px-5 py-16 text-center text-white sm:px-8 sm:py-20"><div className="mx-auto max-w-4xl"><h2 className="font-sf text-[42px] font-bold leading-tight sm:text-[60px]">Votre entreprise peut compter sur son propre Collaborateur IA.</h2><p className="mx-auto mt-5 max-w-3xl text-white/80">Confiez une première mission. Alma prépare le Collaborateur IA, les profils métier, les compétences, les applications et les validations nécessaires.</p><Link href="/decouvrir" className="mt-7 inline-flex bg-[#151310] px-7 py-3.5 text-sm font-bold">Confier une première mission</Link><p className="mt-4 text-xs text-white/75">7 jours gratuits · 1 million de tokens offerts · Aucune carte bancaire</p><p className="mt-2 text-xs text-white/75">Utilisateurs humains gratuits · Chat gratuit · Application Desktop gratuite</p><p className="mt-7 font-sf text-xl font-bold">Des Collaborateurs IA qui progressent avec votre entreprise.</p></div></section>
    </main>
  )
}

function WorkspaceDemo({stage,setStage,decision,setDecision}:{stage:number;setStage:(n:number)=>void;decision:string;setDecision:(n:'pending'|'examining'|'modified'|'approved'|'refused')=>void}){const item=STAGES[stage];return <div className="overflow-hidden border border-[#CFC7BA] bg-[#FAF8F3] shadow-[0_24px_60px_-42px_rgba(28,26,23,.35)]"><div className="grid min-h-[430px] grid-cols-[150px_1fr]"><aside className="border-r border-[#DED6C8] bg-[#EEE9DF] p-3"><p className="font-sf text-sm font-bold">Unitalk</p><nav className="mt-5 space-y-1 text-[11px] text-[#4E483F]">{['＋ Confier une mission','Aujourd’hui','Missions','Décisions · 1','Collaborateurs IA','Conversations'].map(x=><p key={x} className={x.startsWith('Missions')?'bg-white px-2 py-2 font-semibold':'px-2 py-2'}>{x}</p>)}</nav></aside><div className="p-5"><div className="flex items-center gap-3"><Image src="/images/claire-avatar.png" alt="Claire" width={32} height={32} className="rounded-full"/><p className="text-xs"><strong>Claire · Directrice commerciale</strong><br/>Hugo, prépare la prospection pour notre nouvelle offre.</p></div><div className="mt-4 flex items-center gap-3"><Image src="/images/hugo-avatar.png" alt="Hugo, Collaborateur IA" width={32} height={32} className="rounded-full"/><p className="text-xs"><strong>Hugo · Collaborateur IA commercial</strong><br/>Je prépare la sélection et demande confirmation avant tout envoi.</p></div><div className="mt-5 border-t border-[#DED6C8] pt-4"><div className="flex justify-between"><p className="font-mono text-[9px] uppercase text-[#B00C54]">Mission · {item.time}</p><span className="text-[10px] text-[#8A8175]">{item.label}</span></div><h3 className="mt-2 font-sf text-xl font-bold">Préparer la prospection de la nouvelle offre</h3><p className="mt-3 text-xs leading-5 text-[#4E483F]">{item.body}</p>{stage===1&&<div className="mt-4 bg-[#FFF7E6] p-3"><p className="text-xs font-bold">Autoriser l’envoi des douze messages ?</p><p className="mt-1 text-[10px]">Deux références client nécessitent une vérification.</p><div className="mt-3 flex flex-wrap gap-1">{[['examining','Examiner'],['modified','Modifier'],['approved','Valider'],['refused','Refuser']].map(([k,l])=><button key={k} onClick={()=>setDecision(k as any)} className={`border px-2 py-1 text-[9px] ${decision===k?'bg-[#D10E63] text-white':''}`}>{l}</button>)}</div></div>}</div><div className="mt-5 flex items-center justify-between"><button disabled={stage===0} onClick={()=>setStage(stage-1)} className="text-xs disabled:opacity-30">← Retour</button><span className="text-[10px]">{stage+1}/5</span><button disabled={stage===4} onClick={()=>setStage(stage+1)} className="text-xs disabled:opacity-30">Suivant →</button></div></div></div><p className="border-t border-[#DED6C8] px-5 py-3 text-center text-xs font-semibold">Un message devient une mission. La mission reste visible jusqu’au résultat.</p></div>}
function Section({id,eyebrow,title,children}:{id?:string;eyebrow:string;title:React.ReactNode;children:React.ReactNode}){return <section id={id} className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-[1080px]"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#B00C54]">{eyebrow}</p><h2 className="mt-4 font-sf text-[40px] font-bold leading-tight sm:text-[56px]">{title}</h2><div className="mt-6 text-[17px] leading-8 text-[#4E483F]">{children}</div></div></section>}
function Actor({image,title,ai,children}:{image?:string;title:string;ai?:boolean;children:React.ReactNode}){return <div className="border-b border-white/15 py-6 sm:px-5 lg:border-b-0 lg:border-r lg:last:border-r-0">{image&&<Image src={image} alt="" width={48} height={48} className="h-12 w-12 rounded-full object-cover"/>}<h3 className="mt-4 font-sf text-xl font-bold">{title}</h3>{ai&&<p className="mt-1 font-mono text-[9px] uppercase text-[#F2A4C5]">Intelligence artificielle</p>}<p className="mt-3 text-sm leading-7 text-[#BDB7AC]">{children}</p></div>}
const CHANNELS=[['Desktop','L’application complète pour suivre le travail, les décisions et les résultats.'],['Web','Le même Workspace depuis un navigateur.'],['Messageries','Les messages utiles rejoignent la mission avec leur contexte.'],['Terminal','Les équipes techniques travaillent avec Hermes sans environnement parallèle.'],['Email','Messages professionnels selon les règles définies.'],['Téléphone','Appels et rendez-vous lorsque cette capacité est autorisée.']]
const TECH=[['Hermes','Agent autonome dans un environnement isolé.'],['Clerk','Identités, entreprises, membres, rôles et accès.'],['AI Gateway','Point de contrôle unique des modèles autorisés.'],['Honcho','Contexte et mémoire selon identité, relation et droits.'],['Pipedream','Actions dans les applications autorisées.'],['Stalwart','Email professionnel natif.'],['Telnyx','Voix, appels et numéros professionnels.']]
