'use client'

import Image from 'next/image'
import { Check } from 'lucide-react'
import { Kicker } from '@/components/home/section-kicker'
import { PricingConfigurator } from './pricing-configurator'

export function PricingHero() {
  return <section className="relative overflow-hidden pb-14 pt-24 sm:pt-28"><div aria-hidden className="pointer-events-none absolute inset-0 opacity-[0.04] [background-image:linear-gradient(#1C1A17_1px,transparent_1px),linear-gradient(90deg,#1C1A17_1px,transparent_1px)] [background-size:72px_72px]" /><div className="editorial-shell relative"><div className="mb-8 max-w-2xl"><Kicker>Tarifs</Kicker><h1 className="hero-heading mt-5">Une seule identité IA.<br />Plusieurs responsabilités.</h1><p className="mt-5 text-[16px] leading-7 text-[#4E483F]">Configurez votre Organisation, choisissez le nombre de Collaborateurs IA et leur capacité. Votre estimation se met à jour immédiatement.</p><p className="mt-3 text-sm font-semibold">7 jours d’essai · Aucune carte bancaire</p></div><PricingConfigurator /></div></section>
}

export function PricingCollaboration() {
  return <section className="border-y border-[#DED6C8] bg-[#EAE3D4] py-16"><div className="editorial-shell"><Kicker>Ce que chaque ligne finance</Kicker><h2 className="mt-5 text-[34px] font-semibold tracking-[-.04em] sm:text-[44px]">Trois lignes. Aucun forfait caché.</h2><div className="mt-8 grid gap-4 lg:grid-cols-3"><Card title="Organisation Unitalk" price="50 €/mois par entreprise" items={['Alma','Workspace','Desktop','Membres humains sans licence par utilisateur','Rôles et droits','Portefeuille de crédits','Accès aux Stores','Facturation centralisée']} /><Card title="Collaborateur IA" price="49 €/mois par identité" items={['Identité durable','Environnement Hermes/VPS isolé','Rattachement à l’entreprise','Profils métier illimités','Compétences et applications selon droits','Expérience conservée']} /><Card title="Capacité IA" price="Par Collaborateur IA" items={['BYOK ou capacité Unitalk','Texte · Code · Image · Audio · Vidéo','Budget prévisible','Capacité ajustable','Frais du fournisseur exclus avec BYOK']} /></div></div></section>
}

export function PricingExplanations() {
  return <><section className="py-16"><div className="editorial-shell grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-center lg:gap-20"><div><Kicker>Une licence par identité</Kicker><h2 className="mt-5 text-[34px] font-semibold leading-[1.06] tracking-[-.04em] sm:text-[44px]">Ses responsabilités évoluent. Pas sa licence.</h2><p className="mt-5 text-[16px] leading-7 text-[#4E483F]">Vous ajoutez des profils métier sans payer une nouvelle Licence Collaborateur IA pour chaque responsabilité.</p></div><div className="rounded-[18px] border border-[#DED6C8] bg-[#FAF8F3] p-6 sm:p-8"><div className="flex items-center gap-4 border-b border-[#DED6C8] pb-5"><Image src="/images/lucas-avatar.png" alt="" width={52} height={52} className="size-[52px] rounded-full object-cover" /><div><h3 className="text-xl font-semibold">Lucas</h3><p className="mt-1 text-sm text-[#6E665A]">Collaborateur IA · Votre entreprise</p></div></div><p className="mt-5 font-mono text-[10px] font-bold uppercase tracking-[.16em] text-[#857C6E]">Profils métier</p><ul className="mt-4 grid gap-3 sm:grid-cols-3">{['Responsable développement commercial','Responsable relation client','Responsable SEO'].map(item=><li key={item} className="flex gap-2 text-sm font-semibold leading-6"><Check className="mt-1 size-4 shrink-0 text-[#D10E63]" />{item}</li>)}</ul><div className="mt-6 grid gap-2 border-t border-[#DED6C8] pt-5 text-center text-sm font-semibold sm:grid-cols-3"><span>1 identité IA</span><span>3 responsabilités</span><span>1 Licence Collaborateur IA</span></div></div></div></section><section className="bg-[#181615] py-16 text-[#FAF8F3]"><div className="editorial-shell"><Kicker dark>Besoins ponctuels</Kicker><h2 className="mt-5 max-w-3xl text-[34px] font-semibold tracking-[-.04em] sm:text-[44px]">Les crédits restent séparés de vos licences.</h2><div className="mt-8 grid gap-4 sm:grid-cols-3"><Dark title="Crédits IA">Usage de modèles au-delà ou en dehors d’une capacité, selon les règles réelles.</Dark><Dark title="Crédits d’assistance">Aide approfondie pendant une création, intégration ou migration.</Dark><Dark title="Crédits de mission">Missions ou services achetés selon leurs conditions.</Dark></div></div></section></>
}

function Card({ title, price, items }: { title: string; price: string; items: string[] }) {
  return <article className="rounded-[18px] border border-[#DED6C8] bg-[#FAF8F3] p-6"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-2 text-sm font-semibold text-[#B00C54]">{price}</p><ul className="mt-5 space-y-2.5 text-sm text-[#4E483F]">{items.map(item=><li key={item} className="flex gap-2"><Check className="mt-0.5 size-4 shrink-0 text-[#D10E63]" />{item}</li>)}</ul></article>
}

function Dark({ title, children }: { title: string; children: React.ReactNode }) {
  return <article className="rounded-[18px] border border-white/15 bg-white/[.04] p-5"><h3 className="text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-[#CFC6B8]">{children}</p></article>
}
