'use client'
import { Kicker } from '@/components/home/section-kicker'
import { PricingConfigurator } from './pricing-configurator'

export function PricingHero(){return <section className="pb-10 pt-16 sm:pt-20"><div className="editorial-shell grid gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-start"><div><Kicker>Tarifs</Kicker><h1 className="hero-heading mt-4">Une seule identité IA. Plusieurs responsabilités.</h1><p className="mt-4 text-[15px] leading-6 text-[#4E483F]">Composez votre Organisation, choisissez vos Collaborateurs IA et leur capacité, puis voyez immédiatement ce que vous paierez.</p><p className="mt-3 text-sm font-semibold">7 jours d’essai · Aucune carte bancaire</p><ul className="mt-3 space-y-1 text-[13px] text-[#6E665A]"><li>Membres humains sans licence par utilisateur</li><li>Profils métier illimités par Collaborateur IA</li><li>Capacité ajustable ou BYOK</li></ul></div><PricingConfigurator/></div></section>}

export function PricingCollaboration(){return <section className="py-12"><div className="editorial-shell"><Kicker>Ce que vous payez</Kicker><h2 className="mt-5 font-sf text-[36px] font-bold tracking-[-.035em] sm:text-[46px]">Trois lignes. Aucun forfait caché.</h2><div className="mt-8 grid gap-4 lg:grid-cols-3"><Card title="Organisation Unitalk" price="50 €/mois par entreprise" items={['Alma','Workspace','Desktop','Membres humains sans licence par utilisateur','Rôles et droits','Portefeuille de crédits','Accès aux Stores','Facturation centralisée']}/><Card title="Collaborateur IA" price="49 €/mois par identité" items={['Identité durable','Environnement Hermes/VPS isolé','Rattachement à l’entreprise','Profils métier illimités','Compétences et applications selon droits','Expérience conservée']}/><Card title="Capacité IA" price="Par Collaborateur IA" items={['BYOK ou capacité Unitalk','Texte · Code · Image · Audio · Vidéo','Budget prévisible','Capacité ajustable','Frais fournisseurs BYOK exclus']}/></div></div></section>}

export function PricingExplanations(){return <><section className="py-12"><div className="editorial-shell"><Kicker>Une licence par identité</Kicker><div className="mt-8 grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><h2 className="font-sf text-[36px] font-bold sm:text-[46px]">Ses responsabilités évoluent. Pas sa licence.</h2><p className="mt-5 text-[#4E483F]">Vous ajoutez des profils métier sans payer une nouvelle Licence Collaborateur IA pour chaque responsabilité.</p></div><div className="rounded-2xl border border-[#DED6C8] bg-[#FAF8F3] p-6"><h3 className="font-sf text-2xl font-bold">Lucas</h3><p className="text-sm text-[#6E665A]">Collaborateur IA · Votre entreprise</p><p className="label mt-6">Profils métier</p><p className="mt-2 leading-7">Responsable développement commercial<br/>Responsable relation client<br/>Responsable SEO</p><div className="mt-5 grid grid-cols-3 border-t border-[#DED6C8] pt-4 text-center text-sm"><strong>1 identité IA</strong><strong>3 responsabilités</strong><strong>1 licence</strong></div></div></div></div></section><section className="bg-[#151310] py-12 text-[#FAF8F3]"><div className="editorial-shell"><Kicker dark>Besoins ponctuels</Kicker><h2 className="mt-5 font-sf text-[36px] font-bold sm:text-[46px]">Les crédits restent séparés de vos licences.</h2><div className="mt-8 grid gap-6 sm:grid-cols-3"><Dark title="Crédits IA">Usage de modèles au-delà ou en dehors d’une capacité, selon les règles réelles.</Dark><Dark title="Crédits d’assistance">Aide approfondie pendant une création, intégration ou migration.</Dark><Dark title="Crédits de mission">Missions ou services achetés selon leurs conditions.</Dark></div></div></section></>}

export function PricingFinalCta(){return <section className="py-12"><div className="editorial-shell"><div className="rounded-2xl border border-[#DED6C8] bg-[#FAF8F3] p-7 sm:p-10"><h2 className="font-sf text-[36px] font-bold sm:text-[46px]">Commencez gratuitement. Ajustez ensuite.</h2><p className="mt-4 text-[#4E483F]">Votre configuration reste modifiable à mesure que vos missions et vos Collaborateurs IA évoluent.</p><a href="#configurateur" className="mt-7 inline-flex min-h-12 items-center rounded-full bg-[#D10E63] px-6 text-sm font-bold text-white">Commencer avec cette configuration →</a></div></div></section>}
function Card({title,price,items}:{title:string;price:string;items:string[]}){return <article className="rounded-2xl border border-[#DED6C8] bg-[#FAF8F3] p-6"><h3 className="font-sf text-2xl font-bold">{title}</h3><p className="mt-2 font-semibold text-[#B00C54]">{price}</p><ul className="mt-5 space-y-2 text-sm text-[#4E483F]">{items.map(x=><li key={x}>{x}</li>)}</ul></article>}
function Dark({title,children}:{title:string;children:React.ReactNode}){return <article className="rounded-xl border border-white/15 p-5"><h3 className="font-sf text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-[#CFC6B8]">{children}</p></article>}
