'use client'

import Link from 'next/link'
import { useState, type ReactNode } from 'react'
import { Anthropic, DeepSeek, Gemini, Mistral, OpenAI } from '@lobehub/icons'
import { Activity, ArrowRight, BarChart3, Check, Gauge, KeyRound, Network, RefreshCw, Route, ShieldCheck, WalletCards, Wrench } from 'lucide-react'
import { useLanguage } from '@/lib/language-context'

type ModelCategory = 'all' | 'reasoning' | 'image' | 'audio' | 'video' | 'multimodal' | 'open'

const MODELS: { name: string; maker: string; categories: ModelCategory[]; mark: ReactNode }[] = [
  { name: 'GPT', maker: 'OpenAI', categories: ['reasoning', 'image', 'audio', 'multimodal'], mark: <OpenAI size={28} /> },
  { name: 'Claude', maker: 'Anthropic', categories: ['reasoning', 'multimodal'], mark: <Anthropic size={28} /> },
  { name: 'Gemini', maker: 'Google', categories: ['reasoning', 'image', 'audio', 'video', 'multimodal'], mark: <Gemini size={28} /> },
  { name: 'Mistral', maker: 'Mistral AI', categories: ['reasoning', 'open'], mark: <Mistral size={28} /> },
  { name: 'DeepSeek', maker: 'DeepSeek', categories: ['reasoning', 'open'], mark: <DeepSeek size={28} /> },
  { name: 'Llama', maker: 'Meta', categories: ['open'], mark: <span className="text-xl font-black">L</span> },
  { name: 'Qwen', maker: 'Alibaba Cloud', categories: ['reasoning', 'image', 'audio', 'video', 'multimodal', 'open'], mark: <span className="text-xl font-black">Q</span> },
  { name: 'Grok', maker: 'xAI', categories: ['reasoning', 'image', 'multimodal'], mark: <span className="text-xl font-black">G</span> },
  { name: 'Kimi', maker: 'Moonshot AI', categories: ['reasoning'], mark: <span className="text-xl font-black">K</span> },
  { name: 'GLM', maker: 'Zhipu AI', categories: ['reasoning', 'open'], mark: <span className="text-xl font-black">GL</span> },
  { name: 'MiniMax', maker: 'MiniMax', categories: ['audio', 'video', 'multimodal'], mark: <span className="text-xl font-black">M</span> },
  { name: 'FLUX', maker: 'Black Forest Labs', categories: ['image'], mark: <span className="text-xl font-black">F</span> },
  { name: 'ElevenLabs', maker: 'ElevenLabs', categories: ['audio'], mark: <span className="text-lg font-black">11</span> },
  { name: 'Kling', maker: 'Kuaishou', categories: ['image', 'video'], mark: <span className="text-xl font-black">K</span> },
  { name: 'Runway', maker: 'Runway', categories: ['image', 'video'], mark: <span className="text-xl font-black">R</span> },
]

const COPY = {
  fr: {
    eyebrow: 'Unitalk / AI Gateway', titleA: 'Un accès.', titleB: 'Tous vos modèles.', titleC: 'Vos règles.',
    lead: 'Un seul accès gouverné à vos modèles d’IA. Le Gateway relie chaque mission au modèle autorisé, au bon budget et à la politique de votre entreprise.',
    primary: 'Configurer ma capacité IA', secondary: 'Voir les modèles',
    proofs: ['Crédits Unitalk ou BYOK', 'Routage et repli contrôlés', 'Budgets par entreprise'],
    console: { label: 'Politique active', mission: 'Mission', missionValue: 'Analyser 12 contrats', route: 'Route', routeValue: 'Qualité → coût → repli', budget: 'Plafond', budgetValue: '4,20 € / mission', result: 'Route autorisée' },
    catalogKicker: 'Catalogue multimodèle', catalogTitle: 'Le meilleur modèle n’est pas toujours le même.', catalogBody: 'Choisissez une famille explicitement ou laissez une politique router la mission. Les modèles effectivement accessibles dépendent de votre offre, de vos clés et de la configuration de votre entreprise.',
    filters: { all: 'Tous', reasoning: 'Raisonnement', image: 'Image', audio: 'Audio', video: 'Vidéo', multimodal: 'Multimodal', open: 'Open source' },
    modelCount: 'familles affichées', privateTitle: 'Vos modèles privés', privateBody: 'Ajoutez un endpoint compatible selon l’infrastructure et les autorisations de votre entreprise.', accessNote: 'Catalogue indicatif de familles de modèles. Les versions, régions, modalités et disponibilités peuvent évoluer.',
    flowKicker: 'Une requête, quatre décisions', flowTitle: 'Le Collaborateur demande. Votre politique décide.',
    flow: [['01', 'Contexte', 'La mission fournit le besoin et les droits utiles.'], ['02', 'Autorisation', 'Le Gateway vérifie modèles, clés, budget et règles.'], ['03', 'Routage', 'Il sélectionne la route configurée et son éventuel repli.'], ['04', 'Mesure', 'Usage et coût sont rattachés à la bonne entreprise.']],
    capabilitiesKicker: 'Plan de contrôle', capabilitiesTitle: 'La liberté du multimodèle, sans perdre la maîtrise.',
    capabilities: [['API unifiée', 'Une interface commune pour les usages texte, image, audio, embeddings et autres modalités compatibles.', Network], ['Routage intelligent', 'Priorités par qualité, coût ou latence, avec répartition entre les routes disponibles.', Route], ['Repli automatique', 'Nouvelles tentatives, délais contrôlés et bascule vers une route de secours autorisée.', RefreshCw], ['Clés virtuelles', 'Accès séparés par entreprise, équipe, usage ou application, sans exposer les clés fournisseurs.', KeyRound], ['Budgets et limites', 'Plafonds de coût, requêtes, tokens et concurrence selon les règles définies.', Gauge], ['Facturation centralisée', 'Une vue consolidée des abonnements, capacités, crédits et consommations de toute l’entreprise.', WalletCards], ['Coûts attribués', 'Consommation rattachée au modèle, à la mission, au Collaborateur IA et à la bonne entreprise.', BarChart3], ['Observabilité', 'Latence, erreurs, usage et état des routes réunis dans un même plan de contrôle.', Activity], ['Garde-fous', 'Politiques appliquées avant ou après l’appel selon le niveau de contrôle configuré.', ShieldCheck], ['Cache et fiabilité', 'Réutilisation des réponses admissibles, contrôles de santé et retrait des routes défaillantes.', RefreshCw]],
    adminKicker: 'Administration centralisée', adminTitle: 'Collaborateurs IA et humains, administrés au même endroit.', adminBody: 'AI Gateway mesure les usages et les coûts. Alma Entreprise centralise les membres humains, les Collaborateurs IA, leurs rôles, leurs droits, leurs budgets et leurs moyens de paiement dans une gouvernance commune.', adminItems: [['Équipe', 'Invitez les membres humains et rattachez chaque Collaborateur IA à un responsable.'], ['Droits', 'Gérez rôles, accès, validations et politiques depuis l’Entreprise.'], ['Budgets', 'Définissez des plafonds par entreprise, Collaborateur IA, usage ou application.'], ['Facturation', 'Retrouvez abonnements, capacités IA, crédits prépayés et consommation dans une vue consolidée.']], adminCta: 'Voir les tarifs et la facturation',
    includedKicker: 'Une connexion, un budget', includedTitle: 'Tout ce qui alimente le travail, derrière le même accès.', includedBody: 'Le Gateway ne relie pas seulement des modèles. Il peut aussi centraliser les services autorisés dont les Collaborateurs IA ont besoin pour accomplir leurs missions.', included: [['Modèles', 'Raisonnement, rédaction, vision, audio et code selon les fournisseurs autorisés.'], ['Recherche web', 'Recherche et extraction sur les sources accessibles à la mission.'], ['Médias', 'Génération ou traitement d’images, de voix et d’audio selon la configuration.'], ['Exécution', 'Navigation et environnements de calcul lorsque la mission et l’offre les autorisent.']], includedNote: 'Les intégrations disponibles dépendent de l’offre et de la configuration. Leur accès peut être inclus tandis que leur consommation est décomptée de la capacité IA ou facturée par le fournisseur.',
    modesKicker: 'Accès', modesTitle: 'Votre infrastructure. Votre économie.', modes: [['Crédits Unitalk', 'Unitalk gère l’accès aux modèles compatibles selon la capacité choisie.', 'SIMPLE'], ['BYOK', 'Vous connectez vos clés API et réglez directement les fournisseurs.', 'DIRECT'], ['Hybride', 'Vos clés habituelles, complétées par des crédits Unitalk lorsque nécessaire.', 'FLEXIBLE']],
    foundationKicker: 'Infrastructure Unitalk', foundationTitle: 'Une passerelle, pas un verrou.', foundationBody: 'Commencez avec une configuration gérée, connectez vos propres clés ou combinez les deux. Les Collaborateurs IA continuent d’utiliser une interface commune pendant que votre entreprise garde la maîtrise des fournisseurs, des routes et des budgets.', foundationNote: 'Les fournisseurs restent des services tiers indépendants. La disponibilité des modèles, outils, régions et modalités dépend de leurs conditions ainsi que de la configuration Unitalk choisie.', litellm: 'Voir l’architecture et les responsabilités',
    finalTitle: 'Un Collaborateur IA. Plusieurs intelligences. Une seule politique.', finalBody: 'Commencez avec les crédits Unitalk, vos propres clés ou une configuration hybride.', finalCta: 'Configurer AI Gateway',
  },
  en: {
    eyebrow: 'Unitalk / AI Gateway', titleA: 'One access point.', titleB: 'All your models.', titleC: 'Your rules.', lead: 'One governed access point for your AI models. The Gateway connects each mission to an authorized model, the right budget and your organization policy.', primary: 'Configure AI capacity', secondary: 'View models', proofs: ['Unitalk credits or BYOK', 'Controlled routing and fallback', 'Organization budgets'],
    console: { label: 'Active policy', mission: 'Mission', missionValue: 'Analyze 12 contracts', route: 'Route', routeValue: 'Quality → cost → fallback', budget: 'Cap', budgetValue: '€4.20 / mission', result: 'Route authorized' },
    catalogKicker: 'Multi-model catalog', catalogTitle: 'The best model is not always the same.', catalogBody: 'Choose a family explicitly or let a policy route the mission. Models actually available depend on your plan, keys and organization configuration.', filters: { all: 'All', reasoning: 'Reasoning', image: 'Image', audio: 'Audio', video: 'Video', multimodal: 'Multimodal', open: 'Open source' }, modelCount: 'families shown', privateTitle: 'Your private models', privateBody: 'Add a compatible endpoint according to your organization infrastructure and permissions.', accessNote: 'Indicative catalog of model families. Versions, regions, modalities and availability may change.',
    flowKicker: 'One request, four decisions', flowTitle: 'The Collaborator requests. Your policy decides.', flow: [['01', 'Context', 'The mission provides the need and useful permissions.'], ['02', 'Authorization', 'The Gateway checks models, keys, budget and rules.'], ['03', 'Routing', 'It selects the configured route and optional fallback.'], ['04', 'Measure', 'Usage and cost are attributed to the right organization.']],
    capabilitiesKicker: 'Control plane', capabilitiesTitle: 'Multi-model freedom, without losing control.', capabilities: [['Unified API', 'One interface for compatible text, image, audio, embeddings and other modalities.', Network], ['Smart routing', 'Quality, cost or latency priorities with distribution across available routes.', Route], ['Automatic fallback', 'Controlled retries, timeouts and failover to an authorized backup route.', RefreshCw], ['Virtual keys', 'Separate access by organization, team, use or application without exposing provider keys.', KeyRound], ['Budgets and limits', 'Cost, request, token and concurrency caps under defined policies.', Gauge], ['Centralized billing', 'One consolidated view of subscriptions, capacities, credits and usage across the organization.', WalletCards], ['Attributed costs', 'Consumption tied to the model, mission, AI Collaborator and right organization.', BarChart3], ['Observability', 'Latency, errors, usage and route health in one control plane.', Activity], ['Guardrails', 'Policies applied before or after calls according to the configured control level.', ShieldCheck], ['Cache and reliability', 'Reuse eligible responses, check route health and remove failing routes.', RefreshCw]],
    adminKicker: 'Centralized administration', adminTitle: 'AI Collaborators and people, administered in one place.', adminBody: 'AI Gateway measures usage and costs. Alma Organization centralizes human members, AI Collaborators, roles, permissions, budgets and payment methods under shared governance.', adminItems: [['Team', 'Invite human members and assign every AI Collaborator to an owner.'], ['Permissions', 'Manage roles, access, approvals and policies from the Organization.'], ['Budgets', 'Set caps by organization, AI Collaborator, use or application.'], ['Billing', 'Review subscriptions, AI capacities, prepaid credits and usage in one consolidated view.']], adminCta: 'View pricing and billing',
    includedKicker: 'One connection, one budget', includedTitle: 'Everything that powers the work, behind the same access point.', includedBody: 'The Gateway connects more than models. It can centralize the authorized services AI Collaborators need to complete their missions.', included: [['Models', 'Reasoning, writing, vision, audio and code under authorized providers.'], ['Web research', 'Search and extraction across sources available to the mission.'], ['Media', 'Image, voice and audio generation or processing under your setup.'], ['Execution', 'Browsing and compute environments when the mission and plan allow them.']], includedNote: 'Available integrations depend on the plan and configuration. Access may be included while usage is deducted from AI capacity or billed by the provider.',
    modesKicker: 'Access', modesTitle: 'Your infrastructure. Your economics.', modes: [['Unitalk credits', 'Unitalk manages compatible model access under your chosen capacity.', 'SIMPLE'], ['BYOK', 'Connect your API keys and pay providers directly.', 'DIRECT'], ['Hybrid', 'Your usual keys, complemented by Unitalk credits when needed.', 'FLEXIBLE']],
    foundationKicker: 'Unitalk infrastructure', foundationTitle: 'A gateway, not a lock-in.', foundationBody: 'Start with a managed setup, connect your own keys or combine both. AI Collaborators keep one common interface while your organization controls providers, routes and budgets.', foundationNote: 'Providers remain independent third-party services. Model, tool, region and modality availability depends on their terms and your chosen Unitalk configuration.', litellm: 'View architecture and responsibilities', finalTitle: 'One AI Collaborator. Multiple intelligences. One policy.', finalBody: 'Start with Unitalk credits, your own keys or a hybrid setup.', finalCta: 'Configure AI Gateway',
  },
} as const

export function AiGatewayContent() {
  const { lang } = useLanguage()
  const t = COPY[lang]
  const [category, setCategory] = useState<ModelCategory>('all')
  const models = category === 'all' ? MODELS : MODELS.filter((model) => model.categories.includes(category))

  return <main className="overflow-hidden bg-[#F3EFE6] font-sf text-[#1C1A17]">
    <section className="relative min-h-[760px] border-b border-[#D8D0C2] px-5 pb-16 pt-32 sm:px-8 sm:pt-40">
      <div aria-hidden className="absolute inset-0 opacity-[.055] [background-image:linear-gradient(#1C1A17_1px,transparent_1px),linear-gradient(90deg,#1C1A17_1px,transparent_1px)] [background-size:72px_72px]" />
      <div className="editorial-shell relative">
        <p className="font-mono text-[11px] font-black uppercase tracking-[.22em] text-[#B00C54]">{t.eyebrow}</p>
        <div className="mt-8 grid gap-12 lg:grid-cols-[1.3fr_.7fr] lg:items-end">
          <div><h1 className="text-[clamp(3.2rem,8.2vw,7.6rem)] font-semibold leading-[.82] tracking-[-.075em]"><span className="block">{t.titleA}</span><span className="block text-[#D10E63]">{t.titleB}</span><span className="block">{t.titleC}</span></h1></div>
          <div className="lg:pb-2"><p className="text-[17px] leading-8 text-[#4E483F]">{t.lead}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row lg:flex-col xl:flex-row"><Link href="/tarifs#configurateur" className="inline-flex min-h-12 items-center justify-center rounded-full bg-[#181615] px-6 text-sm font-bold text-white">{t.primary}<ArrowRight aria-hidden className="ml-2 size-4" /></Link><a href="#modeles" className="inline-flex min-h-12 items-center justify-center rounded-full border border-[#BFB5A5] bg-[#FAF8F3] px-6 text-sm font-bold">{t.secondary}</a></div></div>
        </div>
        <div className="mt-14 grid overflow-hidden rounded-[2rem] border border-[#292521] bg-[#181615] text-white shadow-[0_40px_90px_-55px_rgba(0,0,0,.8)] lg:grid-cols-[.72fr_1.28fr]">
          <div className="border-b border-white/10 p-6 lg:border-b-0 lg:border-r lg:p-8"><div className="flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#F2A4C5]"><span className="size-2 rounded-full bg-[#22C55E]" />{t.console.label}</div><dl className="mt-8 space-y-5"><PolicyRow label={t.console.mission} value={t.console.missionValue} /><PolicyRow label={t.console.route} value={t.console.routeValue} /><PolicyRow label={t.console.budget} value={t.console.budgetValue} /></dl></div>
          <div className="relative flex min-h-72 items-center justify-center p-6 sm:p-10"><div aria-hidden className="absolute inset-0 opacity-[.07] [background-image:linear-gradient(white_1px,transparent_1px),linear-gradient(90deg,white_1px,transparent_1px)] [background-size:36px_36px]" /><div className="relative flex w-full items-center justify-between gap-3"><Node label="MISSION" active /><ArrowRight className="size-4 shrink-0 text-[#F2A4C5]" /><Node label="POLICY" /><ArrowRight className="size-4 shrink-0 text-[#F2A4C5]" /><Node label="MODEL" active /></div><p className="absolute bottom-5 right-6 font-mono text-[9px] uppercase tracking-[.18em] text-[#8CE5AB]">{t.console.result}</p></div>
        </div>
        <ul className="mt-6 flex flex-wrap gap-x-8 gap-y-3 text-xs font-bold text-[#625B50]">{t.proofs.map((proof) => <li key={proof} className="flex items-center gap-2"><Check className="size-4 text-[#D10E63]" />{proof}</li>)}</ul>
      </div>
    </section>

    <section id="modeles" className="scroll-mt-24 bg-[#181615] px-5 py-20 text-white sm:px-8 sm:py-28">
      <div className="editorial-shell">
        <div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><SectionIntro dark kicker={t.catalogKicker} title={t.catalogTitle} /><p className="max-w-2xl text-[17px] leading-8 text-[#CFC6B8] lg:pt-10">{t.catalogBody}</p></div>
        <div className="mt-12 flex flex-wrap gap-2" role="group" aria-label={t.catalogKicker}>{(Object.keys(t.filters) as ModelCategory[]).map((key) => <button key={key} type="button" aria-pressed={category === key} onClick={() => setCategory(key)} className={`min-h-11 rounded-full border px-5 text-sm font-bold transition-colors ${category === key ? 'border-[#F2A4C5] bg-[#D10E63] text-white' : 'border-white/15 text-[#CFC6B8] hover:border-white/40 hover:text-white'}`}>{t.filters[key]}</button>)}</div>
        <div className="mt-8 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-4">
          {models.map((model, index) => <article key={model.name} className="group min-h-44 bg-[#211E1B] p-6 transition-colors hover:bg-[#292521]"><div className="flex items-start justify-between"><span aria-hidden className="flex size-11 items-center justify-center rounded-full border border-white/15 text-[#F2A4C5]">{model.mark}</span><span className="font-mono text-[9px] text-[#857C6E]">{String(index + 1).padStart(2, '0')}</span></div><h3 className="mt-8 text-2xl font-semibold tracking-[-.03em]">{model.name}</h3><p className="mt-1 text-xs text-[#AFA397]">{model.maker}</p></article>)}
          <article className="min-h-44 bg-[#D10E63] p-6 sm:col-span-2 lg:col-span-1"><p className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-white/70">+ ENDPOINT</p><h3 className="mt-8 text-2xl font-semibold">{t.privateTitle}</h3><p className="mt-3 text-sm leading-6 text-white/80">{t.privateBody}</p></article>
        </div>
        <div className="mt-5 flex flex-col justify-between gap-3 text-xs text-[#AFA397] sm:flex-row"><p>{models.length} {t.modelCount}</p><p className="max-w-2xl sm:text-right">{t.accessNote}</p></div>
      </div>
    </section>

    <section className="px-5 py-20 sm:px-8 sm:py-28"><div className="editorial-shell"><SectionIntro kicker={t.flowKicker} title={t.flowTitle} /><div className="mt-14 border-y border-[#CFC5B5]">{t.flow.map(([number, title, body]) => <article key={number} className="grid gap-4 border-b border-[#CFC5B5] py-7 last:border-b-0 sm:grid-cols-[80px_1fr_1.2fr] sm:items-center"><p className="font-mono text-xs font-black text-[#D10E63]">{number}</p><h3 className="text-2xl font-semibold tracking-[-.03em]">{title}</h3><p className="text-sm leading-7 text-[#625B50]">{body}</p></article>)}</div></div></section>

    <section className="border-y border-[#D8D0C2] bg-[#EAE3D4] px-5 py-20 sm:px-8 sm:py-28"><div className="editorial-shell"><SectionIntro kicker={t.capabilitiesKicker} title={t.capabilitiesTitle} /><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{t.capabilities.map(([title, body, Icon], index) => <article key={title as string} className={`rounded-3xl border p-6 ${index === 0 ? 'border-[#D10E63] bg-[#D10E63] text-white md:col-span-2 lg:col-span-1' : 'border-[#D8D0C2] bg-[#FAF8F3]'}`}><Icon aria-hidden className={`size-5 ${index === 0 ? 'text-white' : 'text-[#D10E63]'}`} /><h3 className="mt-12 text-xl font-bold">{title}</h3><p className={`mt-3 text-sm leading-7 ${index === 0 ? 'text-white/80' : 'text-[#625B50]'}`}>{body}</p></article>)}</div></div></section>

    <section className="px-5 py-20 sm:px-8 sm:py-28"><div className="editorial-shell"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><SectionIntro kicker={t.adminKicker} title={t.adminTitle} /><div className="lg:pt-10"><p className="max-w-2xl text-[17px] leading-8 text-[#4E483F]">{t.adminBody}</p><Link href="/tarifs" className="mt-7 inline-flex min-h-11 items-center rounded-full bg-[#181615] px-5 text-sm font-bold text-white">{t.adminCta}<ArrowRight className="ml-2 size-4" /></Link></div></div><div className="mt-14 grid gap-px overflow-hidden rounded-3xl border border-[#CFC5B5] bg-[#CFC5B5] sm:grid-cols-2 lg:grid-cols-4">{t.adminItems.map(([title, body], index) => <article key={title} className="min-h-60 bg-[#FAF8F3] p-6"><span className="font-mono text-[9px] font-black text-[#B00C54]">0{index + 1}</span><h3 className="mt-14 text-2xl font-semibold tracking-[-.03em]">{title}</h3><p className="mt-4 text-sm leading-7 text-[#625B50]">{body}</p></article>)}</div></div></section>

    <section className="bg-[#181615] px-5 py-20 text-white sm:px-8 sm:py-28"><div className="editorial-shell"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><SectionIntro dark kicker={t.includedKicker} title={t.includedTitle} /><div className="lg:pt-10"><p className="max-w-2xl text-[17px] leading-8 text-[#CFC6B8]">{t.includedBody}</p><p className="mt-5 max-w-2xl text-xs leading-6 text-[#AFA397]">{t.includedNote}</p></div></div><div className="mt-14 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-4">{t.included.map(([title, body], index) => <article key={title} className="min-h-64 bg-[#211E1B] p-6"><div className="flex items-center justify-between"><Wrench aria-hidden className="size-5 text-[#F2A4C5]" /><span className="font-mono text-[9px] text-[#857C6E]">0{index + 1}</span></div><h3 className="mt-20 text-2xl font-semibold">{title}</h3><p className="mt-4 text-sm leading-7 text-[#BDB5A9]">{body}</p></article>)}</div></div></section>

    <section className="px-5 py-20 sm:px-8 sm:py-28"><div className="editorial-shell"><SectionIntro kicker={t.modesKicker} title={t.modesTitle} /><div className="mt-12 grid gap-4 md:grid-cols-3">{t.modes.map(([title, body, tag], index) => <article key={title} className={`relative min-h-72 overflow-hidden rounded-3xl border p-7 ${index === 2 ? 'border-[#181615] bg-[#181615] text-white' : 'border-[#D8D0C2] bg-[#FAF8F3]'}`}><p className={`font-mono text-[10px] font-black tracking-[.18em] ${index === 2 ? 'text-[#F2A4C5]' : 'text-[#B00C54]'}`}>{tag}</p><p aria-hidden className="absolute -right-3 -top-8 text-[9rem] font-semibold leading-none tracking-[-.08em] opacity-[.05]">{index + 1}</p><h3 className="mt-24 text-2xl font-semibold">{title}</h3><p className={`mt-4 text-sm leading-7 ${index === 2 ? 'text-[#CFC6B8]' : 'text-[#625B50]'}`}>{body}</p></article>)}</div></div></section>

    <section className="bg-[#211E1B] px-5 py-20 text-white sm:px-8"><div className="editorial-shell grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><SectionIntro dark kicker={t.foundationKicker} title={t.foundationTitle} /><div><p className="text-[16px] leading-8 text-[#D8D0C2]">{t.foundationBody}</p><p className="mt-6 border-l border-[#D10E63] pl-5 text-xs leading-6 text-[#AFA397]">{t.foundationNote}</p><Link href="/architecture" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#F2A4C5]">{t.litellm}<ArrowRight className="size-4" /></Link></div></div></section>

    <section className="bg-[#D10E63] px-5 py-20 text-white sm:px-8 sm:py-24"><div className="editorial-shell flex flex-col justify-between gap-10 lg:flex-row lg:items-end"><div><h2 className="max-w-4xl text-[clamp(2.5rem,5vw,5rem)] font-semibold leading-[.95] tracking-[-.055em]">{t.finalTitle}</h2><p className="mt-6 text-[17px] text-white/80">{t.finalBody}</p></div><Link href="/tarifs#configurateur" className="inline-flex min-h-12 shrink-0 items-center justify-center rounded-full bg-[#181615] px-7 text-sm font-bold text-white">{t.finalCta}<ArrowRight className="ml-2 size-4" /></Link></div></section>
  </main>
}

function SectionIntro({ kicker, title, dark = false }: { kicker: string; title: string; dark?: boolean }) { return <div><p className={`font-mono text-[10px] font-black uppercase tracking-[.2em] ${dark ? 'text-[#F2A4C5]' : 'text-[#B00C54]'}`}>{kicker}</p><h2 className="mt-5 max-w-4xl text-[clamp(2.2rem,4.5vw,4.6rem)] font-semibold leading-[.95] tracking-[-.055em]">{title}</h2></div> }
function PolicyRow({ label, value }: { label: string; value: string }) { return <div className="border-b border-white/10 pb-4"><dt className="font-mono text-[9px] uppercase tracking-[.16em] text-[#857C6E]">{label}</dt><dd className="mt-2 text-sm font-bold">{value}</dd></div> }
function Node({ label, active = false }: { label: string; active?: boolean }) { return <div className={`flex aspect-square w-full max-w-28 items-center justify-center rounded-full border font-mono text-[9px] font-black tracking-[.14em] sm:text-[10px] ${active ? 'border-[#D10E63] bg-[#D10E63]/15 text-white' : 'border-white/20 text-[#CFC6B8]'}`}>{label}</div> }
