'use client'

import Link from 'next/link'
import { Activity, ArrowRight, BarChart3, Check, Gauge, KeyRound, Network, RefreshCw, Route, ShieldCheck } from 'lucide-react'
import { useLanguage } from '@/lib/language-context'

const COPY = {
  fr: {
    eyebrow: 'Unitalk / AI Gateway', title: 'Un accès gouverné à tous les modèles autorisés.', lead: 'AI Gateway relie chaque mission au bon fournisseur, applique vos règles et attribue l’usage au bon Collaborateur IA, sans exposer les clés de votre entreprise.', primary: 'Configurer AI Gateway', models: 'Voir les modèles disponibles', capacity: 'Choisir une capacité IA', proofs: ['API commune', 'Routage et repli contrôlés', 'Budgets par entreprise'],
    console: { label: 'Politique active', mission: 'Mission', missionValue: 'Analyser 12 contrats', route: 'Route', routeValue: 'Qualité → coût → repli', budget: 'Plafond', budgetValue: '4,20 € / mission', result: 'Route autorisée' },
    flowKicker: 'Une requête, quatre décisions', flowTitle: 'Le Collaborateur demande. Votre politique décide.', flow: [['01','Contexte','La mission fournit le besoin et les droits utiles.'],['02','Autorisation','Le Gateway vérifie fournisseurs, clés, budget et règles.'],['03','Routage','Il sélectionne la route autorisée et son éventuel repli.'],['04','Mesure','Usage et coût sont attribués à la bonne entreprise.']],
    controlsKicker: 'Plan de contrôle', controlsTitle: 'Le multimodèle sans perdre la maîtrise.', controls: [['API unifiée','Une interface commune pour les usages texte, image, audio et autres modalités compatibles.',Network],['Routage intelligent','Priorités par qualité, coût ou latence entre les routes disponibles.',Route],['Repli automatique','Nouvelles tentatives et bascule vers une route de secours autorisée.',RefreshCw],['Clés virtuelles','Accès séparés sans exposer les clés fournisseurs.',KeyRound],['Budgets et limites','Plafonds de coût, requêtes, tokens et concurrence.',Gauge],['Observabilité','Latence, erreurs, usage et état des routes.',Activity],['Coûts attribués','Consommation liée au modèle, à la mission et au Collaborateur IA.',BarChart3],['Garde-fous','Politiques appliquées avant et après chaque appel.',ShieldCheck]],
    adminKicker: 'Administration', adminTitle: 'Une politique commune à toute l’entreprise.', adminBody: 'Gérez les fournisseurs autorisés, les clés, les routes, les budgets et les limites depuis un même plan de contrôle.', adminItems: [['Fournisseurs','Autorisez uniquement les fournisseurs contractualisés.'],['Clés','Séparez les secrets par entreprise, usage ou environnement.'],['Budgets','Définissez les plafonds et règles de consommation.'],['Mesure','Suivez coûts, latence, erreurs et disponibilité.']],
    architectureKicker: 'Responsabilités', architectureTitle: 'Une passerelle, pas un verrou.', architectureBody: 'Le Gateway normalise l’accès et applique vos politiques. Les fournisseurs restent des services tiers indépendants, et leurs versions, régions et disponibilités peuvent évoluer.', architectureCta: 'Voir l’architecture et les responsabilités',
    finalTitle: 'Une seule politique pour toutes les intelligences autorisées.', finalBody: 'Commencez avec une configuration gérée, vos propres clés ou un environnement hybride.', finalCta: 'Configurer AI Gateway',
  },
  en: {
    eyebrow: 'Unitalk / AI Gateway', title: 'Governed access to every approved model.', lead: 'AI Gateway connects each mission to the right provider, applies your rules and attributes usage to the right AI Collaborator without exposing organization keys.', primary: 'Configure AI Gateway', models: 'View available models', capacity: 'Choose AI capacity', proofs: ['Common API', 'Controlled routing and fallback', 'Organization budgets'],
    console: { label: 'Active policy', mission: 'Mission', missionValue: 'Analyze 12 contracts', route: 'Route', routeValue: 'Quality → cost → fallback', budget: 'Cap', budgetValue: '€4.20 / mission', result: 'Route authorized' },
    flowKicker: 'One request, four decisions', flowTitle: 'The Collaborator requests. Your policy decides.', flow: [['01','Context','The mission supplies the need and useful permissions.'],['02','Authorization','The Gateway checks providers, keys, budget and rules.'],['03','Routing','It selects the approved route and optional fallback.'],['04','Measure','Usage and cost are attributed to the right organization.']],
    controlsKicker: 'Control plane', controlsTitle: 'Multi-model freedom without losing control.', controls: [['Unified API','One interface for compatible text, image, audio and other modalities.',Network],['Smart routing','Quality, cost or latency priorities across available routes.',Route],['Automatic fallback','Retries and failover to an approved backup route.',RefreshCw],['Virtual keys','Separate access without exposing provider keys.',KeyRound],['Budgets and limits','Cost, request, token and concurrency caps.',Gauge],['Observability','Latency, errors, usage and route health.',Activity],['Attributed costs','Usage tied to model, mission and AI Collaborator.',BarChart3],['Guardrails','Policies applied before and after each call.',ShieldCheck]],
    adminKicker: 'Administration', adminTitle: 'One policy across the organization.', adminBody: 'Manage approved providers, keys, routes, budgets and limits from one control plane.', adminItems: [['Providers','Allow only contracted providers.'],['Keys','Separate secrets by organization, use or environment.'],['Budgets','Define caps and usage policies.'],['Measurement','Track cost, latency, errors and availability.']],
    architectureKicker: 'Responsibilities', architectureTitle: 'A gateway, not a lock-in.', architectureBody: 'The Gateway normalizes access and applies your policies. Providers remain independent third-party services, and versions, regions and availability may change.', architectureCta: 'View architecture and responsibilities',
    finalTitle: 'One policy for every approved intelligence.', finalBody: 'Start with a managed setup, your own keys or a hybrid environment.', finalCta: 'Configure AI Gateway',
  },
} as const

export function AiGatewayContent() {
  const { lang } = useLanguage()
  const t = COPY[lang]
  return <main className="overflow-hidden bg-[#F3EFE6] font-sf text-[#1C1A17]">
    <section className="relative border-b border-[#D8D0C2] px-5 pb-16 pt-32 sm:px-8 sm:pb-20 sm:pt-40"><div aria-hidden className="absolute inset-0 opacity-[.055] [background-image:linear-gradient(#1C1A17_1px,transparent_1px),linear-gradient(90deg,#1C1A17_1px,transparent_1px)] [background-size:72px_72px]"/><div className="editorial-shell relative"><p className="font-mono text-[11px] font-black uppercase tracking-[.22em] text-[#B00C54]">{t.eyebrow}</p><div className="mt-7 grid gap-10 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><h1 className="max-w-5xl text-[clamp(3rem,7vw,6.8rem)] font-semibold leading-[.86] tracking-[-.075em]">{t.title}</h1><div><p className="text-[17px] leading-8 text-[#4E483F]">{t.lead}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row lg:flex-col xl:flex-row"><Link href="/tarifs#configurateur" className="inline-flex min-h-12 items-center justify-center rounded-full bg-[#181615] px-6 text-sm font-bold text-white">{t.primary}<ArrowRight className="ml-2 size-4"/></Link><Link href="/marketplace/modeles-ia" className="inline-flex min-h-12 items-center justify-center rounded-full border border-[#BFB5A5] bg-[#FAF8F3] px-6 text-sm font-bold">{t.models}</Link></div></div></div><div className="mt-12 grid overflow-hidden rounded-[2rem] border border-[#292521] bg-[#181615] text-white shadow-[0_40px_90px_-55px_rgba(0,0,0,.8)] lg:grid-cols-[.72fr_1.28fr]"><div className="border-b border-white/10 p-6 lg:border-b-0 lg:border-r lg:p-8"><div className="flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#F2A4C5]"><span className="size-2 rounded-full bg-[#22C55E]"/>{t.console.label}</div><dl className="mt-8 space-y-5"><PolicyRow label={t.console.mission} value={t.console.missionValue}/><PolicyRow label={t.console.route} value={t.console.routeValue}/><PolicyRow label={t.console.budget} value={t.console.budgetValue}/></dl></div><div className="relative flex min-h-64 items-center justify-center p-6 sm:p-10"><div aria-hidden className="absolute inset-0 opacity-[.07] [background-image:linear-gradient(white_1px,transparent_1px),linear-gradient(90deg,white_1px,transparent_1px)] [background-size:36px_36px]"/><div className="relative flex w-full items-center justify-between gap-3"><Node label="MISSION" active/><ArrowRight className="size-4 shrink-0 text-[#F2A4C5]"/><Node label="POLICY"/><ArrowRight className="size-4 shrink-0 text-[#F2A4C5]"/><Node label="ROUTE" active/></div><p className="absolute bottom-5 right-6 font-mono text-[9px] uppercase tracking-[.18em] text-[#8CE5AB]">{t.console.result}</p></div></div><ul className="mt-6 flex flex-wrap gap-x-8 gap-y-3 text-xs font-bold text-[#625B50]">{t.proofs.map(proof=><li key={proof} className="flex items-center gap-2"><Check className="size-4 text-[#D10E63]"/>{proof}</li>)}</ul></div></section>

    <section className="px-5 py-16 sm:px-8 sm:py-24"><div className="editorial-shell"><SectionIntro kicker={t.flowKicker} title={t.flowTitle}/><div className="mt-12 border-y border-[#CFC5B5]">{t.flow.map(([number,title,body])=><article key={number} className="grid gap-4 border-b border-[#CFC5B5] py-6 last:border-b-0 sm:grid-cols-[80px_1fr_1.2fr] sm:items-center"><p className="font-mono text-xs font-black text-[#D10E63]">{number}</p><h3 className="text-2xl font-semibold tracking-[-.03em]">{title}</h3><p className="text-sm leading-7 text-[#625B50]">{body}</p></article>)}</div></div></section>

    <section className="border-y border-[#D8D0C2] bg-[#EAE3D4] px-5 py-16 sm:px-8 sm:py-24"><div className="editorial-shell"><SectionIntro kicker={t.controlsKicker} title={t.controlsTitle}/><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{t.controls.map(([title,body,Icon])=><article key={title as string} className="rounded-3xl border border-[#D8D0C2] bg-[#FAF8F3] p-6"><Icon className="size-5 text-[#D10E63]"/><h3 className="mt-10 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-[#625B50]">{body}</p></article>)}</div></div></section>

    <section className="px-5 py-16 sm:px-8 sm:py-24"><div className="editorial-shell grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><SectionIntro kicker={t.adminKicker} title={t.adminTitle}/><div className="lg:pt-8"><p className="max-w-2xl text-[17px] leading-8 text-[#4E483F]">{t.adminBody}</p><div className="mt-8 grid gap-px overflow-hidden rounded-2xl border border-[#CFC5B5] bg-[#CFC5B5] sm:grid-cols-2">{t.adminItems.map(([title,body])=><article key={title} className="bg-[#FAF8F3] p-6"><h3 className="font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#625B50]">{body}</p></article>)}</div></div></div></section>

    <section className="bg-[#211E1B] px-5 py-16 text-white sm:px-8 sm:py-20"><div className="editorial-shell grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><SectionIntro dark kicker={t.architectureKicker} title={t.architectureTitle}/><div><p className="text-[16px] leading-8 text-[#D8D0C2]">{t.architectureBody}</p><div className="mt-7 flex flex-wrap gap-5"><Link href="/architecture" className="inline-flex items-center gap-2 text-sm font-bold text-[#F2A4C5]">{t.architectureCta}<ArrowRight className="size-4"/></Link><Link href="/capacite-ia" className="inline-flex items-center gap-2 text-sm font-bold text-white">{t.capacity}<ArrowRight className="size-4"/></Link></div></div></div></section>

    <section className="bg-[#D10E63] px-5 py-16 text-white sm:px-8 sm:py-20"><div className="editorial-shell flex flex-col justify-between gap-9 lg:flex-row lg:items-end"><div><h2 className="max-w-4xl text-[clamp(2.4rem,5vw,4.8rem)] font-semibold leading-[.95] tracking-[-.055em]">{t.finalTitle}</h2><p className="mt-5 text-[17px] text-white/80">{t.finalBody}</p></div><Link href="/tarifs#configurateur" className="inline-flex min-h-12 shrink-0 items-center justify-center rounded-full bg-[#181615] px-7 text-sm font-bold text-white">{t.finalCta}<ArrowRight className="ml-2 size-4"/></Link></div></section>
  </main>
}

function SectionIntro({ kicker, title, dark = false }: { kicker: string; title: string; dark?: boolean }) { return <div><p className={`font-mono text-[10px] font-black uppercase tracking-[.2em] ${dark?'text-[#F2A4C5]':'text-[#B00C54]'}`}>{kicker}</p><h2 className="mt-5 max-w-4xl text-[clamp(2.2rem,4.5vw,4.6rem)] font-semibold leading-[.95] tracking-[-.055em]">{title}</h2></div> }
function PolicyRow({ label, value }: { label: string; value: string }) { return <div className="border-b border-white/10 pb-4"><dt className="font-mono text-[9px] uppercase tracking-[.16em] text-[#857C6E]">{label}</dt><dd className="mt-2 text-sm font-bold">{value}</dd></div> }
function Node({ label, active=false }: { label: string; active?: boolean }) { return <div className={`flex aspect-square w-full max-w-28 items-center justify-center rounded-full border font-mono text-[9px] font-black tracking-[.14em] sm:text-[10px] ${active?'border-[#D10E63] bg-[#D10E63]/15 text-white':'border-white/20 text-[#CFC6B8]'}`}>{label}</div> }
