import Link from 'next/link'
import { unitalkPricing } from '@/lib/unitalk-pricing'

export function CoCreatorContent(){return <main className="bg-[#F3EFE6] text-[#1C1A17]">
  <section className="px-5 py-24 sm:px-8 sm:py-32"><div className="mx-auto grid max-w-[1140px] gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="label">Formation Co-créateur IA Unitalk</p><h1 className="mt-4 font-sf text-[48px] font-bold leading-[.96] tracking-[-.055em] sm:text-[70px]">Transformez le savoir-faire humain<span className="block text-[#6E665A]">en Collaborateurs IA.</span></h1><p className="mt-7 max-w-3xl text-[18px] leading-8 text-[#4E483F]">Apprenez à interviewer les équipes, formaliser leurs méthodes et créer les profils métier, compétences et missions dont leurs Collaborateurs IA ont besoin.</p><Link href="/tarifs?co-createur=1#configurateur" className="mt-7 inline-flex bg-[#D10E63] px-6 py-3 text-sm font-bold text-white">Devenir Co-créateur IA →</Link><p className="mt-4 text-sm text-[#6E665A]">Formation pratique · Propulsée par Hermes, agent autonome open source</p></div><Transformation/></div></section>
  <Act dark eye="Le métier" title="Un nouveau métier de transmission."><Four items={ACTS}/></Act>
  <Act eye="La preuve" title="Une conversation devient un actif."><div className="mt-10 grid gap-10 lg:grid-cols-2"><blockquote className="border-l border-[#D10E63] pl-6 text-2xl leading-10">« Je ne relance jamais un client lorsqu’un litige est encore ouvert. »</blockquote><div className="border-y border-[#1C1A17]/15">{[['Profil métier','Gestionnaire de recouvrement'],['Compétence','Qualifier une facture avant relance'],['Règle','Ne pas relancer si un litige est ouvert'],['Validation','Responsable financier']].map(([a,b])=><div key={a} className="grid gap-1 border-b border-[#1C1A17]/15 py-4 sm:grid-cols-[130px_1fr]"><span className="label">{a}</span><strong>{b}</strong></div>)}</div></div><p className="mt-8 font-sf text-2xl font-bold">Le Co-créateur ne remplace pas l’expert métier. Il rend son savoir-faire transmissible.</p></Act>
  <Act dark eye="Apprendre en construisant" title="Pas une formation aux prompts."><p className="max-w-3xl text-[#BDB7AC]">Vous interviewez, construisez, testez et améliorez de véritables profils métier, compétences et missions dans un environnement Hermes.</p><div className="mt-9 grid gap-4 sm:grid-cols-5">{['1 entretien métier','1 profil métier','1 compétence testée','1 mission personnalisable','1 Collaborateur IA configuré'].map(x=><p key={x} className="border-t border-white/15 pt-4 font-semibold">{x}</p>)}</div><p className="mt-8 font-mono text-xs text-[#BDB7AC]">Navigateur · Code · Terminal · Fichiers · Mémoire · Planification</p></Act>
  <Act eye="Licence Co-créateur IA Unitalk" title={`${unitalkPricing.aiCocreator.monthlyPrice} €/mois`}><p className="max-w-3xl">Après la formation, la licence permet de continuer à créer, versionner, publier et monétiser des profils métier, compétences et missions dans Unitalk.</p><div className="mt-10 grid gap-8 sm:grid-cols-2"><List title="Créer" items={['Profils métier','Compétences','Missions','Versions','Publications']}/><List title="Percevoir" items={['Revenus directs','Revenus indirects','Activations','Utilisations attribuées','Historique des règlements']}/></div><p className="mt-8 text-sm text-[#6E665A]">Aucun niveau de revenu n’est garanti. La rémunération dépend des créations publiées, de leur adoption et des conditions du programme.</p></Act>
  <section className="bg-[#D10E63] px-5 py-16 text-white sm:px-8"><div className="mx-auto max-w-[1000px]"><h2 className="font-sf text-[44px] font-bold leading-tight sm:text-[60px]">Le prochain Collaborateur IA peut commencer par un savoir-faire humain.</h2><p className="mt-5 text-white/80">Apprenez à écouter, formaliser, tester et transmettre.</p><Link href="/tarifs?co-createur=1#configurateur" className="mt-7 inline-flex bg-[#151310] px-6 py-3 text-sm font-bold">Ajouter la Licence Co-créateur IA →</Link><p className="mt-5 text-xs">Formation pratique · Environnement Hermes · Créations réelles · Licence Unitalk</p></div></section>
</main>}
function Transformation(){return <div className="border-y border-[#1C1A17]/15 py-6"><p className="label">Entretien humain</p><p className="mt-3 text-lg">« Avant d’envoyer une proposition, je vérifie le secteur, l’effectif, le besoin et la personne qui décide. »</p><p className="my-5 text-center text-[#D10E63]">↓</p>{[['Profil métier','Commercial B2B'],['Compétence','Qualifier une opportunité'],['Mission','Préparer une proposition commerciale']].map(([a,b])=><div key={a} className="border-t border-[#1C1A17]/15 py-3"><span className="label">{a}</span><strong className="mt-1 block">{b}</strong></div>)}</div>}
const ACTS=[['Interviewer','Comprendre ce que la personne fait vraiment, exceptions et décisions sensibles comprises.'],['Formaliser','Transformer sa méthode en responsabilités, compétences, règles et résultats.'],['Tester','Vérifier sur des cas réels et intégrer les corrections validées.'],['Transmettre','Partager avec les Collaborateurs IA et humains autorisés.']]
function Act({eye,title,dark,children}:{eye:string;title:string;dark?:boolean;children:React.ReactNode}){return <section className={`${dark?'bg-[#151310] text-[#FAF8F3]':''} px-5 py-20 sm:px-8`}><div className="mx-auto max-w-[1080px]"><p className={`label ${dark?'text-[#F2A4C5]':''}`}>{eye}</p><h2 className="mt-4 font-sf text-[42px] font-bold sm:text-[56px]">{title}</h2><div className="mt-7 text-[17px] leading-8">{children}</div></div></section>}
function Four({items}:{items:string[][]}){return <div className="mt-10 grid gap-7 sm:grid-cols-2 lg:grid-cols-4">{items.map(([a,b])=><div key={a}><h3 className="font-sf text-2xl font-bold">{a}</h3><p className="mt-3 text-sm leading-7 text-[#BDB7AC]">{b}</p></div>)}</div>}
function List({title,items}:{title:string;items:string[]}){return <div><h3 className="font-sf text-2xl font-bold">{title}</h3><ul className="mt-4 space-y-3">{items.map(x=><li key={x} className="border-b border-[#DED6C8] pb-3">{x}</li>)}</ul></div>}
