import Link from 'next/link'
import { ArrowDown, ArrowRight, BadgeCheck, Bot, Building2, Check, FileCheck2, MapPinned, Store, UsersRound } from 'lucide-react'

const LEVELS = [
  { number:'01', status:'APPRENDRE', title:'Co-créateur formé', body:'Vous savez partir d’une mission, interviewer l’expert, construire le Collaborateur IA et organiser ses tests.', gate:'Formation et création évaluée', output:'1 création démontrable', color:'bg-[#FBF9F3]' },
  { number:'02', status:'PROUVER', title:'Co-créateur agréé', body:'Vous pouvez présenter votre agrément et utiliser les ressources du réseau dans le respect de la charte qualité.', gate:'Méthode validée et charte acceptée', output:'Droit d’usage encadré', color:'bg-[#EAE3D4]' },
  { number:'03', status:'DÉPLOYER', title:'Partenaire de déploiement', body:'Vous vendez, configurez et accompagnez des Collaborateurs IA dans des environnements clients séparés.', gate:'Expérience client et capacités vérifiées', output:'Espace professionnel multi-clients', color:'bg-[#D10E63] text-white' },
  { number:'04', status:'ANIMER', title:'Partenaire territorial', body:'Vous animez une zone ou une spécialité lorsque le volume, la satisfaction et la capacité d’accompagnement sont démontrés.', gate:'Phase future après validation du pilote', output:'Aucune exclusivité promise', color:'bg-[#181615] text-white' },
] as const

const METHOD = [
  ['Trouver', 'Une mission réelle portée par une entreprise.'],
  ['Interviewer', 'La méthode, les exceptions et les décisions sensibles.'],
  ['Construire', 'Le profil, les compétences, les outils et l’application métier.'],
  ['Tester', 'Les cas nominaux, les limites, les erreurs et les validations.'],
  ['Vendre', 'Le résultat, le périmètre, le prix et les responsabilités.'],
  ['Transmettre', 'Une capacité que le client sait contrôler et améliorer.'],
] as const

const UNITalkProvides = ['Formation Co-créateur','Méthode et briefs de mission','Licence de création Unitalk','Alma et environnement Hermes','Modèles de démonstration et d’offre','Revues qualité et communauté','Espace Partner selon le niveau','Marketplace et attribution des créations']
const MEMBERProvides = ['Expertise métier ou sectorielle','Prospection et relation client','Entretiens avec les experts','Construction et tests','Déploiement et formation','Respect des droits et de la confidentialité','Suivi des résultats','Contribution aux retours du réseau']

export function CocreatorNetworkContent(){
  return <main className="overflow-hidden bg-[#F3EFE6] pt-[76px] text-[#1C1A17]">
    <section className="relative min-h-[780px] border-b border-[#CFC5B5] px-5 py-16 sm:px-8 sm:py-24">
      <div aria-hidden className="pointer-events-none absolute inset-0 opacity-[.045] [background-image:linear-gradient(#1C1A17_1px,transparent_1px),linear-gradient(90deg,#1C1A17_1px,transparent_1px)] [background-size:72px_72px]"/>
      <div aria-hidden className="absolute -left-48 top-24 size-[34rem] rounded-full bg-[#D10E63]/[.065] blur-3xl"/>
      <div className="editorial-shell relative grid gap-14 lg:grid-cols-[1.06fr_.94fr] lg:items-center">
        <div><p className="font-mono text-[10px] font-black uppercase tracking-[.22em] text-[#B00C54]">Programme pilote · Indépendants · France</p><h1 className="mt-7 max-w-4xl font-sf text-[clamp(3.6rem,7.2vw,7.7rem)] font-semibold leading-[.85] tracking-[-.078em]">Ne prenez pas<br/>une franchise.<br/><span className="text-[#D10E63]">Prouvez le métier.</span></h1><p className="mt-8 max-w-xl text-[18px] leading-8 text-[#4E483F]">Rejoignez un réseau progressif de professionnels indépendants capables de transformer une mission réelle en Collaborateur IA testé, gouverné et déployable.</p><div className="mt-9 flex flex-wrap gap-4"><a href="#candidature" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#D10E63] px-6 text-sm font-bold text-white">Candidater au pilote<ArrowDown className="size-4"/></a><Link href="/academy/formations/co-createur-ia" className="inline-flex min-h-12 items-center gap-2 border-b border-[#1C1A17] px-1 text-sm font-bold">Commencer par la formation<ArrowRight className="size-4"/></Link></div></div>
        <NetworkPassport/>
      </div>
      <div className="editorial-shell relative mt-16 grid border-y border-[#CFC5B5] sm:grid-cols-2 lg:grid-cols-4">{['Indépendant, pas salarié','Agrément progressif','Aucun revenu garanti','Pas d’exclusivité territoriale'].map((item,index)=><p key={item} className="flex min-h-16 items-center gap-3 border-b border-[#CFC5B5] py-4 text-xs font-bold last:border-b-0 sm:border-r sm:px-4 lg:border-b-0 lg:first:pl-0 lg:last:border-r-0"><span className="font-mono text-[9px] text-[#B00C54]">0{index+1}</span>{item}</p>)}</div>
    </section>

    <section className="bg-[#181615] px-5 py-20 text-[#FAF8F3] sm:px-8 sm:py-28"><div className="editorial-shell grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#F2A4C5]">Le contrat moral</p><h2 className="mt-5 font-sf text-[clamp(2.9rem,5.5vw,5.8rem)] font-semibold leading-[.9] tracking-[-.065em]">Le réseau ne vous vend pas un rêve d’entrepreneur.</h2></div><div className="lg:pt-16"><p className="text-[22px] font-semibold leading-9">Il vous donne une méthode, des outils et un standard de qualité. À vous de gagner la confiance des clients.</p><p className="mt-6 max-w-2xl text-[16px] leading-8 text-[#CFC6B8]">L’agrément ne promet ni chiffre d’affaires, ni prospects, ni territoire. Il atteste un niveau vérifié à une date donnée et peut être suspendu si les règles qualité ou les droits du client ne sont plus respectés.</p></div></div></section>

    <section className="border-b border-[#CFC5B5] px-5 py-20 sm:px-8 sm:py-28"><div className="editorial-shell"><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#B00C54]">Progression</p><h2 className="mt-5 max-w-5xl font-sf text-[clamp(3rem,5.8vw,6rem)] font-semibold leading-[.9] tracking-[-.067em]">Quatre niveaux.<br/><span className="text-[#D10E63]">Aucun raccourci.</span></h2><div className="mt-14 grid gap-px bg-[#CFC5B5] lg:grid-cols-4">{LEVELS.map(level=><article key={level.number} className={`${level.color} flex min-h-[500px] flex-col p-7`}><div className="flex items-center justify-between"><span className="font-mono text-sm font-black">{level.number}</span><span className="font-mono text-[9px] font-black tracking-[.16em] opacity-65">{level.status}</span></div><h3 className="mt-14 font-sf text-3xl font-bold leading-tight tracking-[-.045em]">{level.title}</h3><p className="mt-5 text-sm leading-7 opacity-75">{level.body}</p><div className="mt-auto border-t border-current/20 pt-6"><small className="font-mono text-[9px] font-black uppercase tracking-[.14em] opacity-60">Passage</small><p className="mt-2 text-xs font-bold">{level.gate}</p><p className="mt-5 text-xs opacity-70">{level.output}</p></div></article>)}</div></div></section>

    <section className="bg-[#EAE3D4] px-5 py-20 sm:px-8 sm:py-28"><div className="editorial-shell grid gap-14 lg:grid-cols-[.68fr_1.32fr]"><div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#B00C54]">La méthode Unitalk</p><h2 className="mt-5 font-sf text-[clamp(2.8rem,5vw,5.2rem)] font-semibold leading-[.92] tracking-[-.06em]">Une activité commence par du travail qui compte.</h2><p className="mt-6 text-[16px] leading-8 text-[#4E483F]">Pas par un logo, un territoire ou une promesse de revenu.</p></div><div className="border-l border-t border-[#C4BAAA] sm:grid sm:grid-cols-2">{METHOD.map(([title,body],index)=><article key={title} className="min-h-52 border-b border-r border-[#C4BAAA] p-6"><span className="font-mono text-[9px] font-black text-[#B00C54]">0{index+1}</span><h3 className="mt-8 font-sf text-2xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-[#625B50]">{body}</p></article>)}</div></div></section>

    <section className="border-y border-[#CFC5B5] px-5 py-20 sm:px-8 sm:py-28"><div className="editorial-shell"><div className="grid gap-10 lg:grid-cols-2"><div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#B00C54]">Échange de valeur</p><h2 className="mt-5 font-sf text-[clamp(2.8rem,5vw,5.3rem)] font-semibold leading-[.92] tracking-[-.06em]">Unitalk apporte le système.<br/>Vous apportez le terrain.</h2></div><p className="max-w-xl self-end text-[17px] leading-8 text-[#4E483F]">Un réseau utile sépare clairement ce qui est fourni par la tête de réseau et ce qui relève de l’activité indépendante.</p></div><div className="mt-12 grid gap-px bg-[#CFC5B5] lg:grid-cols-2"><Contribution title="Unitalk fournit" icon={<Building2/>} items={UNITalkProvides}/><Contribution title="Le membre apporte" icon={<UsersRound/>} items={MEMBERProvides} dark/></div></div></section>

    <section className="bg-[#181615] px-5 py-20 text-[#FAF8F3] sm:px-8 sm:py-28"><div className="editorial-shell"><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#F2A4C5]">Économie lisible</p><div className="mt-5 grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><h2 className="font-sf text-[clamp(3rem,5.8vw,6rem)] font-semibold leading-[.9] tracking-[-.067em]">Vous devez comprendre comment vous gagnez votre vie.</h2><p className="max-w-2xl text-[16px] leading-8 text-[#CFC6B8]">Le pilote testera le modèle avant toute évolution vers une animation territoriale. Les conditions définitives seront remises avant engagement.</p></div><div className="mt-14 grid gap-px bg-white/15 md:grid-cols-2 lg:grid-cols-4"><EconomicBlock number="100 %" title="Prestations humaines" body="Vous fixez et conservez le prix de vos missions de conseil, création, formation et suivi, hors apport d’affaires encadré."/><EconomicBlock number="50 €" title="Licence Co-créateur" body="Prix mensuel actuel par personne pour les droits produit de création, versionnage et publication."/><EconomicBlock number="30 %" title="Affiliation" body="Sur les abonnements éligibles encaissés la première année, selon attribution et conditions."/><EconomicBlock number="50 %" title="Programme Partner" body="Selon les conditions applicables lorsque vous prenez en charge la vente et le déploiement."/></div><p className="mt-7 max-w-4xl text-xs leading-6 text-[#8F8579]">Les commissions ne sont pas garanties et ne se cumulent pas sur une même vente, sauf accord explicite. L’abonnement Partner et les licences des clients restent distincts. Les règles exactes prévalant sont celles acceptées lors de l’adhésion.</p></div></section>

    <section className="bg-[#FBF9F3] px-5 py-20 sm:px-8 sm:py-28"><div className="editorial-shell grid gap-14 lg:grid-cols-[.78fr_1.22fr]"><div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#B00C54]">Pilote · 10 à 20 indépendants</p><h2 className="mt-5 font-sf text-[clamp(2.9rem,5vw,5.3rem)] font-semibold leading-[.92] tracking-[-.06em]">Avant d’étendre le réseau, nous mesurons ce qui fonctionne.</h2></div><div className="grid gap-px bg-[#D8D0C2] sm:grid-cols-2"><PilotMetric icon={<Store/>} title="Première vente" body="Un membre peut-il vendre une mission en moins de 60 jours ?"/><PilotMetric icon={<FileCheck2/>} title="Qualité homogène" body="Deux membres produisent-ils des livrables comparables ?"/><PilotMetric icon={<Bot/>} title="Adoption client" body="La mission devient-elle une capacité réellement utilisée ?"/><PilotMetric icon={<MapPinned/>} title="Viabilité locale" body="Le modèle soutient-il une activité indépendante durable ?"/></div></div></section>

    <section id="candidature" className="scroll-mt-24 bg-[#D10E63] px-5 py-20 text-white sm:px-8 sm:py-28"><div className="editorial-shell grid gap-14 lg:grid-cols-[1fr_1fr] lg:items-start"><div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-white/65">Candidatures pilote</p><h2 className="mt-5 font-sf text-[clamp(3.2rem,6vw,6.5rem)] font-semibold leading-[.87] tracking-[-.072em]">Nous cherchons des praticiens. Pas des revendeurs de promesses.</h2><p className="mt-7 max-w-xl text-[17px] leading-8 text-white/80">Présentez une expertise, un terrain client et une mission que vous aimeriez transformer. La candidature n’emporte ni admission, ni exclusivité, ni garantie de revenu.</p></div><div className="border border-white/25 bg-white/[.06] p-6 sm:p-8"><p className="font-mono text-[10px] font-black tracking-[.16em] text-white/65">PROFIL RECHERCHÉ</p><ul className="mt-6 space-y-4">{['Une expertise métier ou technique démontrable','La capacité d’écouter avant de proposer','Un premier problème client concret','Le goût du test et de la documentation','L’acceptation d’une revue qualité','Une activité indépendante déclarée avant contractualisation'].map(item=><li key={item} className="flex gap-3 text-sm font-semibold"><Check className="size-4 shrink-0"/>{item}</li>)}</ul><a href="mailto:reseau@unitalk.ai?subject=Candidature%20pilote%20R%C3%A9seau%20Co-cr%C3%A9ateurs&body=Bonjour%2C%0A%0AMon%20expertise%20%3A%0AMon%20terrain%20client%20%3A%0ALa%20mission%20que%20je%20veux%20transformer%20%3A%0AMon%20exp%C3%A9rience%20%3A%0AMon%20lien%20professionnel%20%3A%0A" className="mt-8 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-full bg-[#181615] px-6 text-sm font-bold text-white">Présenter ma candidature<ArrowRight className="size-4"/></a><p className="mt-4 text-center text-xs text-white/60">Votre messagerie s’ouvrira. Aucun dossier n’est transmis automatiquement.</p></div></div></section>
  </main>
}

function NetworkPassport(){return <aside className="relative mx-auto w-full max-w-lg"><div className="absolute inset-0 translate-x-4 translate-y-4 border border-[#CFC5B5] bg-[#EAE3D4]"/><div className="relative border border-[#1C1A17] bg-[#181615] p-6 text-white sm:p-8"><div className="flex items-center justify-between border-b border-white/15 pb-5"><span className="font-mono text-[10px] font-black tracking-[.18em] text-[#F2A4C5]">UNITALK / RÉSEAU</span><BadgeCheck className="size-5 text-[#F2A4C5]"/></div><p className="mt-8 font-mono text-[9px] uppercase tracking-[.16em] text-[#8F8579]">Statut actuel</p><h2 className="mt-2 font-sf text-4xl font-bold tracking-[-.05em]">Programme pilote</h2><div className="mt-8 space-y-4"><PassportRow label="Modèle" value="Agrément progressif"/><PassportRow label="Statut membre" value="Indépendant"/><PassportRow label="Territoire" value="Non exclusif"/><PassportRow label="Admission" value="Sur création évaluée"/></div><div className="mt-8 border border-[#D10E63]/50 bg-[#D10E63]/10 p-4"><p className="text-xs leading-6 text-[#F2C1D6]">Objectif du pilote : prouver la méthode, la qualité et l’économie avant toute forme de licence territoriale.</p></div></div></aside>}
function PassportRow({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-5 border-b border-white/10 pb-3 text-xs"><span className="text-[#8F8579]">{label}</span><strong className="text-right">{value}</strong></div>}
function Contribution({title,icon,items,dark=false}:{title:string;icon:React.ReactNode;items:string[];dark?:boolean}){return <article className={`${dark?'bg-[#181615] text-white':'bg-[#FBF9F3]'} p-7 sm:p-9`}><span className={`[&>svg]:size-6 ${dark?'text-[#F2A4C5]':'text-[#B00C54]'}`}>{icon}</span><h3 className="mt-7 font-sf text-3xl font-bold tracking-[-.04em]">{title}</h3><ul className="mt-7 grid gap-3 sm:grid-cols-2">{items.map(item=><li key={item} className={`flex gap-3 text-sm ${dark?'text-[#CFC6B8]':'text-[#4E483F]'}`}><Check className={`size-4 shrink-0 ${dark?'text-[#F2A4C5]':'text-[#D10E63]'}`}/>{item}</li>)}</ul></article>}
function EconomicBlock({number,title,body}:{number:string;title:string;body:string}){return <article className="min-h-72 bg-[#181615] p-6"><p className="font-sf text-5xl font-bold tracking-[-.06em] text-[#F2A4C5]">{number}</p><h3 className="mt-8 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-[#AFA397]">{body}</p></article>}
function PilotMetric({icon,title,body}:{icon:React.ReactNode;title:string;body:string}){return <article className="min-h-48 bg-[#FBF9F3] p-6"><span className="[&>svg]:size-5 text-[#B00C54]">{icon}</span><h3 className="mt-7 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-[#625B50]">{body}</p></article>}
