'use client'

import Link from 'next/link'
import { ArrowRight, Check, Cpu, Database, KeyRound, ShieldCheck, Users } from 'lucide-react'
import { useLanguage } from '@/lib/language-context'

const COPY={
  fr:{kicker:'Pourquoi Unitalk',title:'Votre entreprise ne loue pas seulement une réponse. Elle construit une capacité.',lead:'Unitalk réunit des identités IA professionnelles, des missions, des méthodes, des applications et une gouvernance que votre entreprise peut conserver et faire évoluer.',primary:'Commencer avec Alma',secondary:'Voir les tarifs',proofs:['Privé par défaut','Partagé par choix','Actions sensibles validées par un humain'],differenceTitle:'Un outil répond. Un Collaborateur IA prend une responsabilité.',difference:[['Identité durable','Une identité rattachée à votre entreprise, avec un responsable humain.',Users],['Contexte gouverné','Mémoire partagée et mémoire propre selon des droits explicites.',Database],['Capacité d’agir','Agent Hermes, compétences, applications et modèles autorisés.',Cpu],['Contrôle humain','Permissions, validations, escalades et journal des décisions.',ShieldCheck]],ownershipTitle:'Ce qui est appris reste gouverné par votre entreprise.',ownershipBody:'Les méthodes, corrections validées, documents et décisions ne deviennent pas automatiquement publics ou mutualisés. Votre entreprise choisit ce qui est privé, partagé ou publiable.',openTitle:'Ouvert dessous. Gouverné dessus.',openBody:'Hermes fournit le runtime agentique open source. Unitalk ajoute l’identité, les missions, les Stores, Workspace, Desktop, AI Gateway et les règles nécessaires au travail en entreprise.',priceTitle:'Une architecture lisible. Un prix composable.',priceBody:'Une Entreprise pour gouverner. Un Agent Hermes par identité. Une capacité IA par agent. Workspace & Desktop inclus.',priceItems:[['Alma Entreprise','Gouvernance, membres, Stores et Gateway','50 €/mois'],['Workspace & Desktop','Missions, activité et validations','Inclus'],['Agent Hermes','Identité, environnement et profils métier','49 €/mois'],['Capacité IA','Modèles et volume d’usage','0 à 100 €/mois']],finalTitle:'Commencez par une mission. Construisez ensuite votre capacité.',finalBody:'Alma cadre le besoin et prépare le bon Collaborateur IA. Le Collaborateur effectue la mission. Vous gardez les décisions qui engagent votre entreprise.'},
  en:{kicker:'Why Unitalk',title:'Your company is not merely renting an answer. It is building a capability.',lead:'Unitalk combines professional AI identities, missions, methods, applications and governance your organization can retain and evolve.',primary:'Start with Alma',secondary:'View pricing',proofs:['Private by default','Shared by choice','Sensitive actions approved by a human'],differenceTitle:'A tool answers. An AI Collaborator takes responsibility.',difference:[['Durable identity','An identity attached to your organization with a human owner.',Users],['Governed context','Shared and private memory under explicit permissions.',Database],['Ability to act','Hermes Agent, skills, applications and authorized models.',Cpu],['Human control','Permissions, approvals, escalation and decision log.',ShieldCheck]],ownershipTitle:'What is learned remains governed by your company.',ownershipBody:'Methods, approved corrections, documents and decisions do not automatically become public or pooled. Your organization chooses what remains private, shared or publishable.',openTitle:'Open underneath. Governed above.',openBody:'Hermes provides the open-source agentic runtime. Unitalk adds identity, missions, Stores, Workspace, Desktop, AI Gateway and enterprise work rules.',priceTitle:'A clear architecture. Composable pricing.',priceBody:'One Organization to govern. One Hermes Agent per identity. One AI capacity per agent. Workspace & Desktop included.',priceItems:[['Alma Organization','Governance, members, Stores and Gateway','€50/month'],['Workspace & Desktop','Missions, activity and approvals','Included'],['Hermes Agent','Identity, environment and job profiles','€49/month'],['AI capacity','Models and usage volume','€0 to €100/month']],finalTitle:'Start with one mission. Then build your capability.',finalBody:'Alma scopes the need and prepares the right AI Collaborator. The Collaborator performs the mission. You retain decisions that commit your company.'}
} as const

export function CollabWhyContent(){const{lang}=useLanguage();const t=COPY[lang];return <main className="bg-[#F5F5F7] text-[#1D1D1F]">
  <section className="bg-black px-5 pb-24 pt-36 text-white sm:px-8 sm:pt-44"><div className="mx-auto max-w-7xl"><p className="font-mono text-[11px] font-bold uppercase tracking-[.2em] text-[#F2A4C5]">{t.kicker}</p><h1 className="mt-8 max-w-6xl text-balance text-[clamp(3.3rem,8vw,8rem)] font-semibold leading-[.9] tracking-[-.07em]">{t.title}</h1><p className="mt-8 max-w-3xl text-xl leading-8 text-white/65">{t.lead}</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/decouvrir?source=pourquoi-unitalk" className="inline-flex min-h-12 items-center justify-center rounded-full bg-white px-7 text-sm font-bold text-black">{t.primary}<ArrowRight className="ml-2 size-4"/></Link><Link href="/tarifs" className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/20 px-7 text-sm font-bold">{t.secondary}</Link></div><ul className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-white/60">{t.proofs.map(item=><li key={item} className="flex gap-2"><Check className="size-4 text-[#F2A4C5]"/>{item}</li>)}</ul></div></section>
  <section className="px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><h2 className="max-w-5xl text-[clamp(2.6rem,6vw,6rem)] font-semibold leading-[.94] tracking-[-.065em]">{t.differenceTitle}</h2><div className="mt-14 grid gap-5 md:grid-cols-2">{t.difference.map(([title,body,Icon])=><article key={title as string} className="rounded-[34px] bg-white p-8 shadow-[0_25px_70px_-50px_rgba(0,0,0,.3)] sm:p-10"><Icon className="size-6 text-[#D10E63]"/><h3 className="mt-10 text-3xl font-semibold tracking-[-.045em]">{title}</h3><p className="mt-4 max-w-xl text-base leading-8 text-[#6E6E73]">{body}</p></article>)}</div></div></section>
  <section className="border-y border-black/5 bg-white px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><KeyRound className="size-7 text-[#D10E63]"/><h2 className="mt-8 text-[clamp(2.8rem,6vw,5.8rem)] font-semibold leading-[.94] tracking-[-.065em]">{t.ownershipTitle}</h2><p className="mt-7 max-w-2xl text-lg leading-8 text-[#6E6E73]">{t.ownershipBody}</p></div><div className="rounded-[40px] bg-[#F5F5F7] p-8 sm:p-12"><div className="grid gap-4 sm:grid-cols-3"><Memory title={lang==='fr'?'Privé':'Private'} body={lang==='fr'?'Secrets, notes et contexte propre.':'Secrets, notes and private context.'}/><Memory title={lang==='fr'?'Partagé':'Shared'} body={lang==='fr'?'Connaissance validée de l’entreprise.':'Approved organization knowledge.'}/><Memory title={lang==='fr'?'Public':'Public'} body={lang==='fr'?'Documentation publiée par choix.':'Documentation published by choice.'}/></div></div></div></section>
  <section className="bg-[#181615] px-5 py-24 text-white sm:px-8"><div className="mx-auto max-w-7xl"><p className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#F2A4C5]">Open source</p><h2 className="mt-7 max-w-5xl text-[clamp(2.8rem,6vw,6rem)] font-semibold leading-[.94] tracking-[-.065em]">{t.openTitle}</h2><p className="mt-7 max-w-3xl text-lg leading-8 text-white/65">{t.openBody}</p><div className="mt-12 grid gap-4 md:grid-cols-2"><Stack title="Hermes" items={lang==='fr'?['Runtime agentique open source','Navigation, fichiers et terminal','Mémoire et compétences','Tâches planifiées']:['Open-source agentic runtime','Browser, files and terminal','Memory and skills','Scheduled tasks']}/><Stack title="Unitalk AI" items={lang==='fr'?['Identités professionnelles','Missions et validations','Workspace, Desktop et Stores','AI Gateway et gouvernance']:['Professional identities','Missions and approvals','Workspace, Desktop and Stores','AI Gateway and governance']}/></div></div></section>
  <section className="px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><p className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#D10E63]">Tarifs</p><h2 className="mt-7 max-w-5xl text-[clamp(2.8rem,6vw,5.8rem)] font-semibold leading-[.94] tracking-[-.065em]">{t.priceTitle}</h2><p className="mt-7 max-w-3xl text-lg leading-8 text-[#6E6E73]">{t.priceBody}</p><div className="mt-12 overflow-hidden rounded-[34px] bg-white">{t.priceItems.map(([name,desc,price])=><div key={name} className="grid gap-3 border-b border-black/5 p-6 last:border-0 sm:grid-cols-[.8fr_1.4fr_auto] sm:items-center sm:p-8"><h3 className="text-xl font-semibold">{name}</h3><p className="text-sm leading-6 text-[#6E6E73]">{desc}</p><p className="text-lg font-bold text-[#D10E63]">{price}</p></div>)}</div><div className="mt-8 flex flex-wrap gap-4"><Link href="/tarifs" className="inline-flex min-h-12 items-center rounded-full bg-[#D10E63] px-7 text-sm font-bold text-white">{lang==='fr'?'Configurer mon équipe':'Configure my team'}<ArrowRight className="ml-2 size-4"/></Link><Link href="/documentation" className="inline-flex min-h-12 items-center rounded-full border border-black/10 bg-white px-7 text-sm font-bold">Documentation</Link></div></div></section>
  <section className="bg-[#EAE3D4] px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><h2 className="max-w-5xl text-[clamp(2.8rem,6vw,5.8rem)] font-semibold leading-[.94] tracking-[-.065em]">{t.finalTitle}</h2><p className="mt-7 max-w-3xl text-lg leading-8 text-[#625B50]">{t.finalBody}</p></div><Link href="/decouvrir?source=pourquoi-unitalk-final" className="inline-flex min-h-12 shrink-0 items-center rounded-full bg-[#D10E63] px-7 text-sm font-bold text-white">{t.primary}<ArrowRight className="ml-2 size-4"/></Link></div></section>
</main>}
function Memory({title,body}:{title:string;body:string}){return <article className="rounded-3xl bg-white p-6"><p className="font-mono text-[10px] font-black uppercase tracking-[.14em] text-[#D10E63]">{title}</p><p className="mt-4 text-sm leading-6 text-[#6E6E73]">{body}</p></article>}
function Stack({title,items}:{title:string;items:readonly string[]}){return <article className="rounded-[32px] border border-white/10 bg-white/[.05] p-8"><h3 className="text-3xl font-semibold">{title}</h3><ul className="mt-7 space-y-4">{items.map(item=><li key={item} className="flex gap-3 text-sm text-white/70"><Check className="size-4 shrink-0 text-[#F2A4C5]"/>{item}</li>)}</ul></article>}
