'use client'

import Link from 'next/link'
import { useLanguage } from '@/lib/language-context'

const PRINCIPLES = [
  ['Universal', 'Une interface de travail', 'Humains, Collaborateurs IA, applications et modèles se retrouvent dans le même environnement.'],
  ['Unique', 'Une identité durable', 'Chaque Collaborateur IA conserve son identité, sa mémoire et son histoire dans l’organisation.'],
  ['Unified', 'Une présence unifiée', 'La même présence travaille avec vos contacts externes et vos équipes internes.'],
  ['Useful', 'Du travail accompli', 'La valeur se mesure au travail utile accompli, pas au nombre de conversations.'],
  ['Ubiquitous', 'Les canaux autorisés', 'Web, email, téléphone, messageries, desktop et terminal restent reliés au même Collaborateur.'],
  ['Understanding', 'Le contexte de l’entreprise', 'Il utilise le contexte et les règles autorisés par votre organisation avant d’agir.'],
  ['Upgradeable', 'Des capacités qui progressent', 'Profils métier, compétences et applications évoluent sans recréer une nouvelle identité.'],
  ['User-controlled', 'Une intelligence sous votre contrôle', 'Votre organisation contrôle la mémoire, les accès, les modèles, les validations et le partage.'],
] as const

const PRINCIPLE_GROUPS = ['Environnement', 'Identité', 'Travail', 'Gouvernance'] as const

export function CollabWhyContent() {
  const { lang } = useLanguage()
  const fr = lang === 'fr'
  return (
    <main className="bg-[#F3EFE6] text-[#1C1A17]">

      <section className="scroll-mt-32 bg-[#151310] px-5 pb-14 pt-[8.75rem] text-[#F3EFE6] sm:px-8 sm:pb-16 sm:pt-[9.25rem]">
        <div className="mx-auto grid max-w-[1280px] items-center gap-8 lg:grid-cols-[minmax(0,1.2fr)_minmax(25rem,0.8fr)] lg:gap-12">
          <div>
            <Eyebrow dark>{fr ? 'Pourquoi Unitalk' : 'Why Unitalk'}</Eyebrow>
            <h1 className="mt-4 font-sf text-[clamp(2.45rem,5vw,4.1rem)] font-semibold leading-[1.02] tracking-[-0.045em]">
              <span className="block whitespace-nowrap lg:whitespace-normal xl:whitespace-nowrap">{fr ? 'Ne louez pas votre intelligence.' : 'Do not rent your intelligence.'}</span>
              <span className="block text-[#F2A4C5]">{fr ? 'Possédez-la.' : 'Own it.'}</span>
            </h1>
            <p className="mt-6 max-w-2xl text-[17px] leading-relaxed text-[#D1C8BC]">{fr ? 'Unitalk transforme l’IA en capacités de travail que votre entreprise peut conserver, faire progresser et gouverner.' : 'Unitalk turns AI into work capabilities your company can retain, improve and govern.'}</p>
            <p className="mt-3 max-w-2xl text-[15px] leading-relaxed text-[#AAA195]">{fr ? 'Humains et Collaborateurs IA travaillent dans la même organisation, avec un contexte, des applications et des règles partagés.' : 'Humans and AI Collaborators work in the same organization with shared context, applications and rules.'}</p>
            <div className="mt-6 flex flex-wrap gap-3"><Link href="/decouvrir" className="rounded-full bg-[#D10E63] px-7 py-3 text-sm font-bold text-white">{fr ? 'Créer mon Collaborateur IA' : 'Create my AI Collaborator'} →</Link><a href="#principes" className="rounded-full border border-white/20 px-7 py-3 text-sm font-bold">{fr ? 'Découvrir les principes' : 'Discover the principles'} ↓</a></div>
            <p className="mt-3 text-[13px] text-[#BDB4A8]">{fr ? 'Sept jours pour une première mission · Sans carte bancaire' : 'Seven days for a first mission · No credit card'}</p>
          </div>
          <HeroDiagram />
        </div>
      </section>

      <section className="scroll-mt-32 px-5 py-14 sm:px-8 sm:py-16"><div className="mx-auto max-w-[1200px]"><Eyebrow>{fr ? 'L’entreprise AI Native' : 'The AI Native company'}</Eyebrow><h2 className="mt-3 max-w-4xl font-sf text-[32px] font-bold tracking-[-0.03em] sm:text-[42px]">{fr ? 'Le travail devient hybride. La responsabilité reste humaine.' : 'Work becomes hybrid. Responsibility stays human.'}</h2><p className="mt-4 max-w-3xl leading-relaxed text-[#4E483F]">{fr ? 'Devenir AI Native consiste à organiser le travail pour que les humains et les Collaborateurs IA agissent ensemble, avec des rôles, des accès et des responsabilités clairement définis.' : 'Becoming AI Native means organizing work so humans and AI Collaborators act together with clear roles, access and responsibilities.'}</p><div className="mt-7 grid gap-4 lg:grid-cols-3"><Info title="Humains" items={['Définissent les objectifs','Apportent leur jugement','Prennent les décisions','Assument la responsabilité']} /><Info title="Même organisation" items={['Contexte partagé','Applications autorisées','Rôles définis','Validations humaines']} /><Info title="Collaborateurs IA" items={['Recherchent et préparent','Produisent','Exécutent','Coordonnent et suivent']} /></div><p className="mt-7 font-sf text-xl font-bold">Les humains gardent le contrôle. L’entreprise gagne en capacité.</p></div></section>

      <section id="principes" className="scroll-mt-32 bg-[#151310] px-5 py-14 text-[#F3EFE6] sm:px-8 sm:py-16"><div className="mx-auto max-w-[1200px]"><Eyebrow dark>{fr ? 'Les 8 U de Unitalk' : 'The 8 U’s of Unitalk'}</Eyebrow><h2 className="mt-3 font-sf text-[32px] font-bold sm:text-[42px]">{fr ? 'Huit principes. Une seule vision.' : 'Eight principles. One vision.'}</h2><p className="mt-4 max-w-3xl text-[#AAA195]">{fr ? 'Huit principes organisent la relation entre l’entreprise, ses Collaborateurs IA et son intelligence.' : 'Eight principles organize the relationship between the company, its AI Collaborators and its intelligence.'}</p><div className="mt-7 grid gap-px overflow-hidden rounded-2xl border border-[#2C2822] bg-[#2C2822] sm:grid-cols-2 lg:grid-cols-4">{PRINCIPLES.map(([u,title,body],i) => <article key={u} className="bg-[#151310] p-5"><div className="flex items-center justify-between gap-3"><p className="font-mono text-[10px] text-[#E8548C]">{String(i+1).padStart(2,'0')}</p><span className="font-mono text-[9px] uppercase tracking-[0.14em] text-[#81796D]">{PRINCIPLE_GROUPS[Math.floor(i/2)]}</span></div><p className="mt-4 font-mono text-sm font-bold"><span className="text-xl text-[#E8548C]">U</span>{u.slice(1)}</p><h3 className="mt-3 font-sf text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-[#AAA195]">{body}</p></article>)}</div></div></section>

      <section className="scroll-mt-32 px-5 py-14 sm:px-8 sm:py-16"><div className="mx-auto grid max-w-[1200px] gap-10 lg:grid-cols-[0.9fr_1.1fr]"><div><Eyebrow>{fr ? 'Un actif pour l’entreprise' : 'A company asset'}</Eyebrow><h2 className="mt-3 font-sf text-[32px] font-bold sm:text-[42px]">{fr ? 'Votre entreprise ne loue plus seulement un accès à l’IA.' : 'Your company no longer merely rents access to AI.'}</h2><p className="mt-4 leading-relaxed text-[#4E483F]">{fr ? 'Elle construit des capacités de travail qu’elle peut conserver, améliorer, versionner, réutiliser et partager selon ses droits.' : 'It builds work capabilities it can retain, improve, version, reuse and share under its own rights.'}</p><p className="mt-7 font-sf text-2xl font-bold">Privé par défaut. <span className="text-[#D10E63]">Partagé par choix.</span></p></div><AssetFlow /></div><p className="mx-auto mt-7 max-w-[1200px] font-sf text-lg font-bold">Une mission produit un résultat. Une méthode validée construit une capacité qui reste.</p></section>

      <section className="scroll-mt-32 px-5 py-14 sm:px-8 sm:py-16"><div className="mx-auto max-w-[1200px]"><h2 className="font-sf text-[32px] font-bold sm:text-[42px]">Une architecture. Plusieurs niveaux de valeur.</h2><p className="mt-4 max-w-3xl text-[#4E483F]">Unitalk crée de la valeur pour les entreprises qui utilisent, conçoivent, déploient ou intègrent des capacités.</p><div className="mt-7 grid gap-4 lg:grid-cols-2"><Link href="/collaborateurs-ia" className="rounded-3xl border border-[#D10E63]/30 bg-[#FAF8F3] p-7 lg:row-span-2"><h3 className="font-sf text-2xl font-bold">Pour votre entreprise</h3><p className="mt-3 text-[#4E483F]">Des Collaborateurs IA qui représentent votre activité, travaillent avec vos équipes et agissent dans vos applications.</p><span className="mt-5 inline-flex font-bold text-[#D10E63]">Découvrir les Collaborateurs IA →</span></Link><div className="grid auto-rows-fr gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-[#DED6C8] p-5"><Value title="Pour les créateurs" body="Créer et publier des profils métier, des compétences, des applications et des packs." /></div><Link href="/partenaires" className="rounded-2xl border border-[#DED6C8] p-5"><Value title="Pour les partenaires" body="Déployer des Collaborateurs IA et accompagner leurs clients." /></Link><Link href="/platform" className="rounded-2xl border border-[#DED6C8] p-5"><Value title="Pour les plateformes" body="Construire leurs propres expériences sur l’infrastructure Unitalk." /></Link></div></div></div></section>

      <section className="scroll-mt-32 bg-[#151310] px-5 py-14 text-[#F3EFE6] sm:px-8"><div className="mx-auto max-w-[1200px]"><Eyebrow dark>Propulsé par Hermes</Eyebrow><h2 className="mt-3 font-sf text-[32px] font-bold sm:text-[42px]">Ouvert dessous. Gouverné dessus.</h2><p className="mt-4 max-w-3xl text-[#AAA195]">Hermes fournit le moteur agentique open source. Unitalk ajoute l’identité professionnelle, l’organisation, le Workspace, l’AI Gateway, les applications et les règles de gouvernance.</p><div className="mt-7 grid gap-6 text-sm text-[#D1C8BC] md:grid-cols-2"><Info dark title="Hermes" items={['Agent autonome open source','Exécution de code','Navigation Internet','Tâches planifiées','Mémoire et compétences','Utilisation d’outils']} /><Info dark title="Unitalk" items={['Identité professionnelle','Organisation','Workspace','AI Gateway','Applications autorisées','Gouvernance et droits']} /></div><p className="mt-7 font-sf text-xl font-bold">Hermes donne la capacité d’agir. Unitalk permet à l’entreprise de la posséder et de la gouverner.</p><Link href="/agent-hermes" className="mt-5 inline-flex font-bold text-[#F2A4C5]">Découvrir Hermes →</Link></div></section>

      <section className="scroll-mt-32 px-5 py-16 text-center sm:px-8 sm:py-20"><div className="mx-auto max-w-3xl"><Eyebrow>{fr ? 'Une interface pour le travail qui vient' : 'An interface for the work ahead'}</Eyebrow><h2 className="mt-3 font-sf text-[32px] font-bold sm:text-[42px]">{fr ? 'Votre entreprise peut construire ses propres capacités de travail.' : 'Your company can build its own work capabilities.'}</h2><p className="mt-4 text-[#4E483F]">{fr ? 'Créez un premier Collaborateur IA et confiez-lui une mission.' : 'Create a first AI Collaborator and assign it a mission.'}</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/decouvrir" className="rounded-full bg-[#D10E63] px-7 py-3.5 text-sm font-bold text-white">Créer mon Collaborateur IA →</Link><Link href="/tarifs" className="rounded-full border border-[#DED6C8] px-7 py-3.5 text-sm font-bold">Voir les tarifs</Link></div><p className="mt-3 text-xs text-[#6E665A]">Sept jours d’essai · 1 million de tokens préchargés · Sans carte bancaire</p></div></section>
    </main>
  )
}

function Eyebrow({ children, dark=false }: { children: React.ReactNode; dark?: boolean }) { return <p className={`font-mono text-[10px] font-bold uppercase tracking-[0.18em] ${dark?'text-[#E8548C]':'text-[#B00C54]'}`}>{children}</p> }
function HeroDiagram() { return <div className="rounded-3xl border border-white/10 bg-white/[0.035] p-6"><div className="relative mx-auto grid max-w-md grid-cols-[1fr_5rem_1fr] items-center gap-x-3 gap-y-4"><div className="space-y-3">{['Équipes','Collaborateurs IA','Modèles d’IA'].map(label=><div key={label} className="rounded-lg border border-white/15 px-3 py-2 text-center text-xs font-semibold text-[#D1C8BC]">{label}</div>)}</div><div className="relative flex h-full items-center justify-center"><span aria-hidden className="absolute inset-y-[12%] left-1/2 w-px bg-[#E8548C]/35" /><span aria-hidden className="absolute left-0 right-0 top-1/2 h-px bg-[#E8548C]/35" /><div className="relative z-10 rounded-full bg-[#D10E63] px-3 py-2 text-center text-xs font-bold text-white">Unitalk</div></div><div className="rounded-lg border border-white/15 px-3 py-2 text-center text-xs font-semibold text-[#D1C8BC]">Applications</div></div><p className="mt-6 border-t border-white/10 pt-4 text-center text-sm text-[#F2A4C5]">Organisation · Contexte · Règles</p></div> }
function Info({ title, items, dark=false }: { title: string; items: string[]; dark?: boolean }) { return <article className={`rounded-2xl border p-5 ${dark?'border-white/10 bg-white/[0.03]':'border-[#DED6C8] bg-[#FAF8F3]'}`}><h3 className="font-sf text-lg font-bold">{title}</h3><ul className={`mt-3 space-y-2 text-sm ${dark?'text-[#D1C8BC]':'text-[#4E483F]'}`}>{items.map(x=><li key={x}>{x}</li>)}</ul></article> }
function AssetFlow() { const steps=[['Connaissances','Ce que votre entreprise sait'],['Méthodes','Comment elle accomplit le travail'],['Compétences','Les savoir-faire validés'],['Droits','Ce qui reste privé ou partagé']]; return <div className="rounded-3xl border border-[#DED6C8] bg-[#FAF8F3] p-6"><div className="relative grid gap-5 sm:grid-cols-4 sm:gap-3"><span aria-hidden className="absolute left-[10%] right-[10%] top-5 hidden h-px bg-[#D10E63]/30 sm:block" />{steps.map(([title,body],i)=><div key={title} className="relative"><span className="relative z-10 flex h-10 w-10 items-center justify-center rounded-full border border-[#D10E63]/30 bg-[#FAF8F3] font-mono text-xs font-bold text-[#D10E63]">{i+1}</span><p className="mt-3 text-xs font-bold uppercase tracking-[0.12em]">{title}</p><p className="mt-1 text-sm text-[#4E483F]">{body}</p></div>)}</div></div> }
function Value({ title, body }: { title: string; body: string }) { return <><h3 className="font-sf text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-[#4E483F]">{body}</p></> }
