'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Bot, Building2, Check, Mail, Plug, Server, ShieldCheck, UserRound } from 'lucide-react'
import { useLanguage } from '@/lib/language-context'
import { useState } from 'react'
import type { CollaboratorPage } from '@/lib/collaborator-pages'
import { CollaboratorEquipmentFlow } from '@/components/collaborator-equipment-flow'
import { Kicker } from '@/components/home/section-kicker'

const COPY = {
  fr: {
    publicProfile: 'Hugo · Collaborateur IA commercial',
    missionCta: (name: string) => `Confier une mission à ${name}`,
    customize: 'Personnaliser avec Alma',
    proofKicker: 'Mission commerciale · Démonstration illustrative',
    proofTitle: 'Hugo prépare la prospection. Votre équipe garde la décision.',
    proofLead: 'Il recherche et qualifie selon vos critères, prépare le CRM et s’arrête avant le premier contact tant que votre équipe n’a pas validé.',
    decision: 'Décision requise', approve: 'Approuver', modify: 'Modifier', decline: 'Refuser',
    identityKicker: 'Une identité professionnelle', identityTitle: 'Hugo travaille avec sa propre identité et ses propres accès.',
    organizationKicker: 'Une identité qui appartient à l’entreprise', organizationTitle: 'Le responsable peut changer. Le Collaborateur IA et le savoir-faire restent.',
    organizationBody: 'Le Collaborateur IA personnalisé pour votre organisation appartient à votre entreprise, pas à la plateforme Unitalk ni au compte personnel de son responsable. Si ce responsable change de rôle ou quitte l’entreprise, celle-ci peut réattribuer sa supervision sans recréer son identité, ses compétences ni les méthodes validées.',
    missionsTitle: 'Missions commerciales prêtes à personnaliser', allMissions: 'Voir toutes les missions Ventes',
    appsTitle: 'Hugo travaille dans votre environnement commercial.', appsBody: 'HubSpot, Salesforce, LinkedIn, Gmail, Outlook et vos agendas sont attribués selon vos droits. Plus de 3 000 connecteurs peuvent être disponibles selon la configuration.',
    modelsTitle: 'Le modèle adapté à chaque tâche, sous vos règles.', modelsBody: 'Hugo utilise uniquement les modèles autorisés par votre entreprise, dans les limites du budget défini.',
    continuity: ['Identité appartenant à l’entreprise', 'Supervision humaine réattribuable', 'Méthodes et compétences conservées', 'Accès révocables séparément'],
    finalTitle: 'Quelle première mission allez-vous confier à votre Collaborateur IA commercial ?', finalCta: 'Commencer avec Alma', pricing: 'Voir les tarifs',
  },
  en: {
    publicProfile: 'Hugo · Sales AI Collaborator',
    missionCta: (name: string) => `Assign a mission to ${name}`,
    customize: 'Customize with Alma',
    proofKicker: 'Sales mission · Illustrative demonstration',
    proofTitle: 'Hugo prepares prospecting. Your team keeps the decision.',
    proofLead: 'He researches and qualifies under your criteria, prepares the CRM and stops before first contact until your team approves.',
    decision: 'Decision required', approve: 'Approve', modify: 'Amend', decline: 'Decline',
    identityKicker: 'A professional identity', identityTitle: 'Hugo works with his own identity and access.',
    organizationKicker: 'An identity owned by the organization', organizationTitle: 'The supervisor can change. Hugo and the know-how remain.',
    organizationBody: 'Hugo belongs to the organization that deploys him, never to Unitalk or to his supervisor’s personal account. If that supervisor changes roles or leaves, the organization can reassign supervision without recreating Hugo, his skills or approved methods.',
    missionsTitle: 'Sales missions ready to customize', allMissions: 'View all Sales missions',
    appsTitle: 'Hugo works in your sales environment.', appsBody: 'HubSpot, Salesforce, LinkedIn, Gmail, Outlook and calendars are assigned under your permissions. More than 3,000 connectors may be available depending on setup.',
    modelsTitle: 'The right model for each task, under your rules.', modelsBody: 'Hugo only uses models authorized by your organization, within the defined budget.',
    continuity: ['Identity owned by the organization', 'Human supervision can be reassigned', 'Methods and skills retained', 'Access revoked separately'],
    finalTitle: 'What first mission will you assign to your Sales AI Collaborator?', finalCta: 'Start with Alma', pricing: 'View pricing',
  },
} as const

export function CollaborateurContent({ page }: { page: CollaboratorPage; equipmentId?: string }) {
  const { lang } = useLanguage()
  const t = COPY[lang]
  const { detail, missions } = page
  const name = detail.name
  const missionHref = `/missions?composer=1&collaborateur=${encodeURIComponent(detail.slug)}&source=collaborator-profile`
  const [decision, setDecision] = useState<'approved' | 'modified' | 'declined' | null>(null)
  const outcome = decision === 'approved' ? (lang === 'fr' ? 'Hugo prépare les premiers contacts autorisés.' : 'Hugo prepares the authorized first contacts.') : decision === 'modified' ? (lang === 'fr' ? 'Hugo reprend la sélection avec vos nouveaux critères.' : 'Hugo revises the selection under your new criteria.') : decision === 'declined' ? (lang === 'fr' ? 'Aucun contact n’est préparé. La sélection reste disponible.' : 'No contact is prepared. The selection remains available.') : null

  return <main className="bg-[#F3EFE6] text-[#1C1A17]">
    <section className="relative overflow-hidden pb-16 pt-28 sm:pb-20 sm:pt-36">
      <div aria-hidden className="absolute inset-0 opacity-[.04] [background-image:linear-gradient(#1C1A17_1px,transparent_1px),linear-gradient(90deg,#1C1A17_1px,transparent_1px)] [background-size:72px_72px]"/>
      <div className="editorial-shell relative grid gap-10 lg:grid-cols-[1fr_.72fr] lg:items-center">
        <div><Kicker>{t.publicProfile}</Kicker><h1 className="mt-6 max-w-4xl text-[clamp(3.2rem,7vw,7rem)] font-semibold leading-[.88] tracking-[-.075em]">{name}</h1><p className="mt-4 text-xl font-semibold text-[#B00C54]">{detail.role[lang]}</p><h2 className="mt-7 max-w-3xl text-[clamp(1.8rem,3vw,2.8rem)] font-semibold leading-[1.05] tracking-[-.04em]">{lang === 'fr' ? 'Hugo trouve et qualifie vos prochains prospects.' : 'Hugo finds and qualifies your next prospects.'}</h2><p className="mt-5 max-w-2xl text-[17px] leading-8 text-[#4E483F]">{lang === 'fr' ? 'Donnez-lui vos critères. Il recherche les entreprises, prépare les fiches CRM et organise les relances. Votre équipe valide le premier contact.' : 'Give him your criteria. He researches companies, prepares CRM records and organizes follow-ups. Your team approves the first contact.'}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={missionHref} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#D10E63] px-7 text-sm font-bold text-white">{t.missionCta(name)}<ArrowRight className="size-4"/></Link><a href="#equiper" className="inline-flex min-h-12 items-center justify-center rounded-full border border-[#D8D0C2] bg-[#FAF8F3] px-7 text-sm font-bold">{lang === 'fr' ? 'Personnaliser Hugo avec Alma' : 'Customize Hugo with Alma'}</a></div><p className="mt-7 text-sm font-semibold text-[#625B50]">{lang === 'fr' ? 'Exemple public · Supervisé par votre directeur commercial' : 'Public example · Supervised by your sales director'}</p></div>
        <div className="relative mx-auto w-full max-w-sm overflow-hidden rounded-[2rem] border border-[#D8D0C2] bg-[#FAF8F3] shadow-[0_30px_75px_-45px_rgba(28,26,23,.6)]"><div className="relative aspect-[4/5]"><Image src={detail.avatar} alt={`${name}, ${detail.role[lang]}`} fill priority sizes="(max-width:1024px) 90vw, 360px" className="object-cover"/></div><div className="flex items-center justify-between p-5"><div><p className="font-semibold">@{detail.slug}</p><p className="mt-1 text-xs text-[#625B50]">{lang === 'fr' ? 'Nature IA explicite' : 'Explicit AI identity'}</p></div><span className="rounded-full bg-[#D10E63]/10 px-3 py-1 text-xs font-bold text-[#B00C54]">{detail.department[lang]}</span></div></div>
      </div>
    </section>

    <section id="mission-en-action" className="scroll-mt-24 bg-[#FAF8F3] py-16 sm:py-20"><div className="editorial-shell grid gap-10 lg:grid-cols-[.78fr_1.22fr] lg:items-center"><div><p className="font-mono text-[10px] font-black uppercase tracking-[.18em] text-[#B00C54]">{t.proofKicker}</p><h2 className="mt-5 text-[clamp(2.4rem,5vw,4.8rem)] font-semibold leading-[.95] tracking-[-.06em]">{t.proofTitle}</h2><p className="mt-6 max-w-xl text-[16px] leading-8 text-[#4E483F]">{t.proofLead}</p></div><article className="overflow-hidden rounded-[24px] border border-[#D8D0C2] bg-white"><div className="border-b border-[#E8E0D3] p-5"><p className="font-mono text-[9px] font-black uppercase tracking-[.14em] text-[#857C6E]">{lang === 'fr' ? 'Mission VTE-018 · Exemple illustratif sur 34 entreprises' : 'Mission SLS-018 · Illustrative example using 34 companies'}</p><h3 className="mt-2 text-xl font-semibold">{lang === 'fr' ? 'Qualifier les nouveaux prospects' : 'Qualify new prospects'}</h3></div><ol className="space-y-4 p-5 text-sm"><Activity time="09:05">{lang === 'fr' ? '34 entreprises examinées selon les critères configurés.' : '34 companies reviewed under configured criteria.'}</Activity><Activity time="09:12">{lang === 'fr' ? '9 correspondent au segment cible.' : '9 match the target segment.'}</Activity><Activity time="09:18">{lang === 'fr' ? 'Fiches CRM et messages préparés. Aucun contact envoyé.' : 'CRM records and messages prepared. No contact sent.'}</Activity></ol><div className="m-5 mt-0 rounded-2xl border border-[#E0CFAE] bg-[#FFF7E6] p-4"><p className="font-mono text-[9px] font-black uppercase tracking-[.14em] text-[#9A6B1E]">{t.decision}</p><p className="mt-2 text-sm font-semibold">{lang === 'fr' ? 'Autoriser la préparation du premier contact ?' : 'Authorize first-contact preparation?'}</p><div className="mt-4 flex flex-wrap gap-2"><Decision primary onClick={() => setDecision('approved')}>{t.approve}</Decision><Decision onClick={() => setDecision('modified')}>{t.modify}</Decision><Decision onClick={() => setDecision('declined')}>{t.decline}</Decision></div>{outcome && <p role="status" className="mt-4 rounded-xl bg-white p-3 text-sm font-semibold text-[#4E483F]">{outcome}</p>}</div></article></div></section>

    <CollaboratorEquipmentFlow detail={detail}/>

    <section className="py-16 sm:py-20"><div className="editorial-shell"><Kicker>{t.identityKicker}</Kicker><h2 className="mt-5 max-w-4xl text-[clamp(2.4rem,5vw,4.8rem)] font-semibold leading-[.95] tracking-[-.06em]">{t.identityTitle}</h2><div className="mt-10 grid gap-px overflow-hidden rounded-[2rem] border border-[#D8D0C2] bg-[#D8D0C2] sm:grid-cols-2 lg:grid-cols-4"><Foundation icon={UserRound} title={lang === 'fr' ? 'Identité IA' : 'AI identity'} body={lang === 'fr' ? 'Prénom, avatar, nature IA explicite et profil public.' : 'Name, avatar, explicit AI nature and public profile.'}/><Foundation icon={Mail} title={lang === 'fr' ? 'Communication' : 'Communication'} body={lang === 'fr' ? 'E-mail, calendrier, messageries et téléphone si activé.' : 'Email, calendar, messaging and phone when enabled.'}/><Foundation icon={Server} title={lang === 'fr' ? 'Exécution privée' : 'Private execution'} body={lang === 'fr' ? 'Agent Hermes, mémoire propre, fichiers et environnement isolé.' : 'Hermes Agent, own memory, files and isolated environment.'}/><Foundation icon={ShieldCheck} title={lang === 'fr' ? 'Droits propres' : 'Own permissions'} body={lang === 'fr' ? 'Sources, actions, budgets et validations attribués séparément.' : 'Sources, actions, budgets and approvals assigned separately.'}/></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><Link href="/collaborateurs-ia/applications" className="group rounded-3xl border border-[#D8D0C2] bg-[#FAF8F3] p-6"><Plug className="size-5 text-[#D10E63]"/><h3 className="mt-7 text-2xl font-semibold">{t.appsTitle}</h3><p className="mt-4 text-sm leading-7 text-[#625B50]">{t.appsBody}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#B00C54]">{lang === 'fr' ? 'Voir les applications' : 'View applications'}<ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></span></Link><Link href="/ai-gateway" className="group rounded-3xl border border-[#D8D0C2] bg-[#FAF8F3] p-6"><Bot className="size-5 text-[#D10E63]"/><h3 className="mt-7 text-2xl font-semibold">{t.modelsTitle}</h3><p className="mt-4 text-sm leading-7 text-[#625B50]">{t.modelsBody}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#B00C54]">AI Gateway<ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></span></Link></div></div></section>

    <section className="bg-[#EAE3D4] py-16 sm:py-20"><div className="editorial-shell grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><Kicker>{t.organizationKicker}</Kicker><h2 className="mt-5 text-[clamp(2.4rem,5vw,4.8rem)] font-semibold leading-[.95] tracking-[-.06em]">{t.organizationTitle}</h2><p className="mt-6 max-w-xl text-[16px] leading-8 text-[#4E483F]">{t.organizationBody}</p></div><article className="rounded-[28px] border border-[#CFC5B5] bg-[#FAF8F3] p-6 sm:p-8"><div className="flex items-center gap-4 border-b border-[#DED6C8] pb-6"><Building2 className="size-10 rounded-full bg-[#D10E63]/10 p-2.5 text-[#B00C54]"/><div><p className="text-lg font-semibold">{lang === 'fr' ? 'Votre entreprise' : 'Your organization'}</p><p className="text-sm text-[#625B50]">{lang === 'fr' ? 'Propriétaire de l’identité IA et du savoir-faire validé' : 'Owner of the AI identity and approved know-how'}</p></div></div><ul className="mt-6 grid gap-4 sm:grid-cols-2">{t.continuity.map(item => <li key={item} className="flex gap-3 text-sm font-semibold"><Check className="mt-0.5 size-4 shrink-0 text-[#D10E63]"/>{item}</li>)}</ul></article></div></section>

    {missions.length > 0 && <section id="missions" className="scroll-mt-24 py-16 sm:py-20"><div className="editorial-shell"><h2 className="max-w-3xl text-[clamp(2.2rem,4vw,4rem)] font-semibold leading-[.98] tracking-[-.05em]">{t.missionsTitle}</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{missions.slice(0,4).map(mission => <Link key={mission.slug} href={`/missions/${mission.slug}`} className="group rounded-2xl border border-[#D8D0C2] bg-[#FAF8F3] p-5"><h3 className="text-lg font-semibold">{mission.title[lang]}</h3><p className="mt-3 text-sm leading-6 text-[#625B50]">{mission.objective[lang]}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#B00C54]">{lang === 'fr' ? 'Personnaliser' : 'Customize'}<ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></span></Link>)}</div><Link href={`/missions?categorie=${encodeURIComponent(detail.department.fr.toLowerCase())}`} className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#B00C54]">{t.allMissions}<ArrowRight className="size-4"/></Link></div></section>}
    <section className="bg-[#D10E63] py-16 text-white sm:py-20"><div className="editorial-shell flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><h2 className="max-w-4xl text-[clamp(2.6rem,5vw,5.2rem)] font-semibold leading-[.92] tracking-[-.065em]">{t.finalTitle}</h2><div className="flex min-w-60 flex-col gap-3"><a href="#equiper" className="inline-flex min-h-12 items-center justify-center rounded-full bg-[#181615] px-7 text-sm font-bold">{t.finalCta}</a><Link href="/tarifs" className="text-center text-sm font-bold underline decoration-white/40 underline-offset-4">{t.pricing}</Link></div></div></section>
  </main>
}

function Activity({ time, children }: { time: string; children: React.ReactNode }) { return <li className="flex gap-4"><span className="font-mono text-xs text-[#857C6E]">{time}</span><span>{children}</span></li> }
function Decision({ children, primary = false, onClick }: { children: React.ReactNode; primary?: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={`min-h-11 rounded-full px-5 text-xs font-bold ${primary ? 'bg-[#D10E63] text-white' : 'border border-[#D8D0C2] bg-white'}`}>{children}</button> }
function Foundation({ icon: Icon, title, body }: { icon: typeof UserRound; title: string; body: string }) { return <article className="bg-[#FAF8F3] p-6"><Icon className="size-5 text-[#D10E63]"/><h3 className="mt-9 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#625B50]">{body}</p></article> }
