'use client'

import Link from 'next/link'
import { Check, ShieldCheck } from 'lucide-react'
import { organizationMonthlyPrice, pricingAnnualTotal, pricingRecurringTotal, unitalkPricing } from '@/lib/unitalk-pricing'
import type { PurchaseDraft } from '@/lib/purchase-draft'

export function CommandeContent({ draft }: { draft: PurchaseDraft }) {
  const pricing = draft.pricing!
  const onboarding = draft.onboarding!
  const organizationPrice = organizationMonthlyPrice(pricing.organizationTier)
  const recurringTotal = pricingRecurringTotal(pricing)
  const annualTotal = pricingAnnualTotal(pricing)
  const company = onboarding.company.find((fact) => fact.key === 'name')?.value || 'Votre entreprise'

  return <main className="min-h-screen bg-[#F3EFE6] px-5 pb-20 pt-28 text-[#1C1A17] sm:px-8 sm:pt-32"><div className="editorial-shell"><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#B00C54]">Confirmation</p><h1 className="mt-5 max-w-4xl font-sf text-[clamp(2.8rem,6vw,5.8rem)] font-semibold leading-[.94] tracking-[-.065em]">Vérifiez votre configuration.</h1><p className="mt-6 max-w-2xl text-[17px] leading-8 text-[#4E483F]">Tout ce qui modifie le produit ou son prix a été choisi avant cette étape. Le bon de commande récapitule uniquement votre configuration.</p>
    <div className="mt-12 grid gap-6 lg:grid-cols-[1fr_380px]">
      <section className="overflow-hidden rounded-[28px] border border-[#CFC5B5] bg-[#FAF8F3]"><div className="border-b border-[#DED6C8] p-6 sm:p-8"><p className="font-mono text-[9px] font-bold uppercase tracking-[.16em] text-[#B00C54]">Votre Collaborateur IA</p><h2 className="mt-3 font-sf text-3xl font-semibold tracking-[-.04em]">{onboarding.collaboratorName}</h2><p className="mt-2 text-sm text-[#625B50]">{onboarding.profile.fr} · {company}</p></div><dl className="divide-y divide-[#DED6C8] px-6 sm:px-8"><Summary label="Première mission" value={onboarding.mission.title}/><Summary label="Facturation" value={pricing.billingPeriod === 'annual' ? 'Annuelle · 2 mois offerts' : 'Mensuelle'}/><Summary label="Licence Entreprise" value={`${unitalkPricing.organization[pricing.organizationTier].users} · ${pricing.billingPeriod === 'annual' ? `${organizationPrice * 10} €/an` : `${organizationPrice} €/mois`}`}/><Summary label="Collaborateurs IA" value={`${pricing.collaborators} × ${pricing.billingPeriod === 'annual' ? '490 €/an' : `${unitalkPricing.aiCollaborator.monthlyPrice} €/mois`}`}/><Summary label="Tokens IA inclus" value={`${pricing.collaborators} × 5 millions par mois`}/><Summary label="Assistants IA" value="Privés ou partagés · Illimités"/><Summary label="Workspace" value="Inclus"/></dl><div className="border-t border-[#DED6C8] p-6 sm:p-8"><Link href="/tarifs#detail-tarifs" className="text-sm font-bold text-[#B00C54] underline-offset-4 hover:underline">Modifier la configuration</Link></div></section>
      <aside className="h-fit rounded-[28px] bg-[#181615] p-7 text-white lg:sticky lg:top-28"><p className="font-mono text-[9px] font-bold uppercase tracking-[.16em] text-[#F2A4C5]">{pricing.billingPeriod === 'annual' ? 'Total annuel' : 'Total mensuel estimé'}</p><p className="mt-4 font-sf text-6xl font-semibold tracking-[-.07em]">{pricing.billingPeriod === 'annual' ? annualTotal : recurringTotal} €<span className="ml-1 text-xs font-normal text-[#AFA397]">/{pricing.billingPeriod === 'annual' ? 'an' : 'mois'}</span></p>{pricing.billingPeriod === 'annual' && <p className="mt-2 text-xs font-bold text-[#F2A4C5]">2 mois offerts · soit {(annualTotal / 12).toFixed(2).replace('.', ',')} €/mois</p>}<p className="mt-3 text-xs leading-5 text-[#AFA397]">5 millions de tokens mensuels inclus par Collaborateur IA.</p><div className="mt-7 rounded-2xl border border-white/10 bg-white/[.04] p-4"><p className="font-bold">À payer aujourd’hui : 0 €</p><p className="mt-2 text-xs leading-5 text-[#CFC6B8]">Première mission offerte · Sans carte bancaire</p></div><ul className="mt-6 space-y-3 text-sm text-[#D8D0C2]"><li className="flex gap-2"><Check className="size-4 text-[#F2A4C5]"/>Première mission conservée</li><li className="flex gap-2"><Check className="size-4 text-[#F2A4C5]"/>Aucun passage payant sans accord</li><li className="flex gap-2"><Check className="size-4 text-[#F2A4C5]"/>Applications connectées uniquement avec autorisation</li></ul><Link href="/workspace?demo=1" className="mt-7 inline-flex min-h-12 w-full items-center justify-center rounded-full bg-[#D10E63] px-6 text-sm font-bold text-white">Confirmer la simulation</Link><p className="mt-4 flex gap-2 text-[11px] leading-5 text-[#8F877A]"><ShieldCheck className="mt-0.5 size-4 shrink-0"/>Démonstration : aucune commande réelle, aucun abonnement et aucun Workspace privé ne sont créés.</p></aside>
    </div></div></main>
}

function Summary({label,value}:{label:string;value:string}){return <div className="grid gap-2 py-5 sm:grid-cols-[12rem_1fr]"><dt className="font-mono text-[9px] font-bold uppercase tracking-[.12em] text-[#8A8175]">{label}</dt><dd className="text-sm font-semibold leading-6">{value}</dd></div>}
