import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Check, CircleDollarSign, ExternalLink, Play } from 'lucide-react'
import { Kicker } from '@/components/home/section-kicker'
import { HERMES_CREATORS } from '@/lib/hermes-creators'
import { DOCUMENTATION, DOCUMENTATION_GROUPS, DOCUMENTATION_SLUGS, type DocumentationPage } from '@/lib/unitalk-documentation'

export function DocumentationIndexContent() {
  return <main id="main-content" tabIndex={-1} className="bg-[#F3EFE6] font-sf text-[#1C1A17]">
    <section className="relative overflow-hidden border-b border-[#D8D0C2] px-5 pb-16 pt-28 sm:px-8 sm:pb-20">
      <div aria-hidden className="pointer-events-none absolute inset-0 opacity-[.04] [background-image:linear-gradient(#1C1A17_1px,transparent_1px),linear-gradient(90deg,#1C1A17_1px,transparent_1px)] [background-size:72px_72px]"/>
      <div className="editorial-shell relative"><Kicker>Documentation Unitalk</Kicker><h1 className="hero-heading mt-5 max-w-5xl">Du moteur agentique au travail en entreprise.</h1><p className="mt-6 max-w-3xl text-[17px] leading-8 text-[#4E483F]">Comprenez Hermes, les identités IA, la mémoire gouvernée, les communications, les espaces de travail et les règles qui permettent aux humains et aux IA de collaborer.</p></div>
    </section>

    <section className="px-5 py-16 sm:px-8 sm:py-20">
      <div className="editorial-shell space-y-14">{DOCUMENTATION_GROUPS.map(group => { const pages = DOCUMENTATION_SLUGS.map(slug => DOCUMENTATION[slug]).filter(page => page.group === group); return <section key={group} aria-labelledby={`documentation-${group}`}><div className="flex items-center gap-4"><h2 id={`documentation-${group}`} className="font-mono text-[11px] font-black uppercase tracking-[.18em] text-[#B00C54]">{group}</h2><span aria-hidden className="h-px flex-1 bg-[#D8D0C2]"/></div><div className="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{pages.map(page => <DocumentationCard key={page.slug} page={page}/>)}</div></section> })}</div>
    </section>

    <section className="bg-[#181615] px-5 py-16 text-[#FAF8F3] sm:px-8 sm:py-20"><div className="editorial-shell"><Kicker dark>Principe</Kicker><h2 className="mt-5 max-w-5xl text-[34px] font-semibold leading-[1.06] tracking-[-.04em] sm:text-[44px]">Hermes exécute. <span className="text-[#F2A4C5]">Unitalk orchestre.</span></h2><p className="mt-6 max-w-3xl text-[16px] leading-8 text-[#CFC6B8]">Ensemble, ils déploient la collaboration à l’échelle de l’entreprise.</p></div></section>

    <HermesResources />
  </main>
}

export function DocumentationDetailContent({ page }: { page: DocumentationPage }) {
  return <main id="main-content" tabIndex={-1} className="bg-[#F3EFE6] font-sf text-[#1C1A17]">
    <section className="relative overflow-hidden px-5 pb-16 pt-28 sm:px-8 sm:pb-20"><div aria-hidden className="pointer-events-none absolute inset-0 opacity-[.04] [background-image:linear-gradient(#1C1A17_1px,transparent_1px),linear-gradient(90deg,#1C1A17_1px,transparent_1px)] [background-size:72px_72px]"/><div className="editorial-shell relative grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><Link href="/documentation" className="text-sm font-bold text-[#B00C54]">← Documentation</Link><p className="mt-8 font-mono text-[11px] font-bold uppercase tracking-[.18em] text-[#B00C54]">{page.number} · {page.group} · {page.eyebrow}</p><h1 className="hero-heading mt-5 max-w-5xl">{page.title}</h1><p className="mt-6 max-w-3xl text-[17px] leading-8 text-[#4E483F]">{page.summary}</p></div><aside className="min-w-[250px] rounded-3xl border border-[#D8D0C2] bg-[#FAF8F3] p-6"><CircleDollarSign className="size-5 text-[#D10E63]"/><p className="mt-5 text-2xl font-black">{page.price}</p>{page.included&&<p className="mt-2 text-sm font-bold text-[#257A43]">{page.included}</p>}</aside></div></section>
    <section className="border-y border-[#D8D0C2] bg-[#EAE3D4] px-5 py-8 sm:px-8"><div className="editorial-shell"><p className="max-w-4xl text-xl font-bold leading-8">{page.principle}</p></div></section>
    <section className="px-5 py-16 sm:px-8 sm:py-20"><div className="editorial-shell grid gap-5 md:grid-cols-2">{page.sections.map(section=><article key={section.title} className="rounded-3xl border border-[#D8D0C2] bg-[#FAF8F3] p-6 sm:p-7"><h2 className="text-2xl font-bold tracking-[-.035em]">{section.title}</h2>{section.intro&&<p className="mt-3 text-sm leading-7 text-[#625B50]">{section.intro}</p>}<ul className="mt-6 space-y-3">{section.items.map(item=><li key={item} className="flex gap-3 text-sm font-semibold leading-6"><Check className="mt-0.5 size-4 shrink-0 text-[#D10E63]"/>{item}</li>)}</ul></article>)}</div></section>
    <section className="bg-[#181615] px-5 py-16 text-white sm:px-8"><div className="editorial-shell"><h2 className="text-3xl font-bold tracking-[-.04em]">Entreprise et Collaborateur : deux périmètres.</h2><div className="mt-8 overflow-hidden rounded-3xl border border-white/10">{page.distinctions.map((row,index)=><div key={row.organization} className="grid gap-4 border-b border-white/10 p-5 last:border-b-0 md:grid-cols-[3rem_1fr_1fr] md:items-center"><span className="font-mono text-[10px] text-[#F2A4C5]">0{index+1}</span><p className="text-sm font-semibold">{row.organization}</p><p className="text-sm text-[#CFC6B8]">{row.collaborator}</p></div>)}</div>{page.officialSource&&<a href={page.officialSource.href} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#F2A4C5]">{page.officialSource.label}<ExternalLink className="size-4"/></a>}</div></section>
    <section className="px-5 py-14 sm:px-8"><div className="editorial-shell"><p className="font-mono text-[10px] font-black uppercase tracking-[.16em] text-[#B00C54]">Continuer</p><div className="mt-5 flex flex-wrap gap-3">{page.related.map(slug=><Link key={slug} href={`/documentation/${slug}`} className="inline-flex min-h-11 items-center rounded-full border border-[#D8D0C2] bg-[#FAF8F3] px-4 text-sm font-bold hover:border-[#D10E63]">{DOCUMENTATION[slug].title}<ArrowRight className="ml-2 size-4"/></Link>)}</div></div></section>
  </main>
}

function DocumentationCard({ page }: { page: DocumentationPage }) {
  return <Link href={`/documentation/${page.slug}`} className="group flex min-h-[280px] flex-col rounded-3xl border border-[#D8D0C2] bg-[#FAF8F3] p-6 transition hover:-translate-y-1 hover:border-[#D10E63]/40"><div className="flex items-center justify-between"><p className="font-mono text-[10px] font-black text-[#B00C54]">{page.number}</p><span className="font-mono text-[9px] font-black uppercase tracking-[.14em] text-[#857C6E]">{page.group}</span></div><h3 className="mt-7 text-2xl font-bold tracking-[-.035em]">{page.title}</h3><p className="mt-4 text-sm leading-7 text-[#625B50]">{page.summary}</p><div className="mt-auto flex items-center justify-between gap-3 pt-7"><span className="text-xs font-black text-[#625B50]">{page.price}</span><ArrowRight className="size-4 shrink-0 text-[#D10E63] transition group-hover:translate-x-1"/></div></Link>
}

function HermesResources() {
  const featured = HERMES_CREATORS.slice(0, 3)
  return <section className="px-5 py-16 sm:px-8 sm:py-20"><div className="editorial-shell"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><div><Kicker>Ressources Hermes</Kicker><h2 className="mt-5 text-balance text-[clamp(2.4rem,4.5vw,4.5rem)] font-semibold leading-[.95] tracking-[-.06em]">La référence officielle et des usages expliqués.</h2></div><p className="max-w-2xl text-[15px] leading-7 text-[#625B50]">Consultez la documentation technique de Hermes Agent, puis découvrez des tutoriels et retours d’expérience sélectionnés par Unitalk. Ces créateurs ne sont pas porte-parole de Unitalk ou Nous Research.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{featured.map(creator=><article key={creator.videoUrl} className="flex min-h-64 flex-col rounded-3xl border border-[#D8D0C2] bg-[#FAF8F3] p-6"><Image src={creator.avatarUrl} alt="" width={48} height={48} unoptimized className="size-12 rounded-full object-cover"/><p className="mt-5 font-mono text-[9px] font-black uppercase tracking-[.14em] text-[#B00C54]">{creator.language} · {creator.duration}</p><h3 className="mt-3 line-clamp-2 text-lg font-bold leading-6">{creator.name}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-[#625B50]">{creator.angle.fr}</p></article>)}</div><div className="mt-6 flex flex-wrap gap-4"><a href="https://hermes-agent.nousresearch.com/docs/" target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center rounded-full bg-[#181615] px-6 text-sm font-bold text-white">Documentation officielle<ExternalLink className="ml-2 size-4"/></a><Link href="/blog/hermes-agent-youtube" className="inline-flex min-h-12 items-center rounded-full border border-[#CFC5B5] px-6 text-sm font-bold">Voir les 10 créateurs<Play className="ml-2 size-4"/></Link></div></div></section>
}
