import Link from 'next/link'
import { getMission, getMissionCategory, getMissionCategoryHref } from '@/lib/missions-catalog'
import { MissionBreadcrumb } from '@/components/missions/mission-breadcrumb'

export const EMAIL_GUIDE_FAQ = [
  ['Le Collaborateur IA répond-il automatiquement à tous les emails ?', 'Non. Il qualifie la demande, prépare une réponse et applique les règles définies. Les engagements, exceptions et messages sensibles peuvent rester sous validation humaine.'],
  ['Comment retrouve-t-il le contexte utile ?', 'Il consulte uniquement les sources et informations que l’entreprise a autorisées pour cette mission. Une information absente ou incertaine est signalée au lieu d’être inventée.'],
  ['Peut-il envoyer la réponse ?', 'Seulement si le canal est réellement connecté et si les droits de la mission autorisent l’envoi. Préparation, validation et envoi peuvent avoir des règles distinctes.'],
  ['Que devient l’expérience après la mission ?', 'Seules les corrections et méthodes que l’entreprise choisit de conserver peuvent enrichir la compétence ou le contexte partagé avec les collaborateurs autorisés.'],
] as const

const mission = getMission('repondre-a-mes-clients')!
const category = getMissionCategory(mission.category)!

export function EmailGuideContent() {
  return <article className="bg-[#F3EFE6] text-[#1C1A17]">
    <section className="px-5 pb-16 pt-24 sm:px-8 sm:pt-28"><div className="mx-auto max-w-[1080px]"><MissionBreadcrumb items={[{label:'Missions',href:'/missions'},{label:category.label.fr,href:getMissionCategoryHref(category)},{label:mission.title.fr}]}/><p className="label mt-8">Mission · Service client</p><h1 className="mt-4 font-sf text-[44px] font-bold leading-[.98] tracking-[-.05em] sm:text-[66px]">Répondre aux emails clients.<span className="block text-[#6E665A]">Sans perdre le contexte.</span></h1><div className="mt-7 max-w-4xl space-y-3 text-[18px] leading-8 text-[#4E483F]"><p>Votre Collaborateur IA lit les demandes reçues, identifie leur objet, retrouve le contexte autorisé et prépare une réponse adaptée.</p><p>Il ne répond pas à tout aveuglément. Il signale les informations manquantes et les situations qui exigent une décision humaine.</p><p>Votre équipe garde le contrôle des engagements, des exceptions et des messages sensibles.</p></div></div></section>

    <Act n="01" title="Une réponse prête à relire, avec son contexte."><p>Le résultat distingue la demande reçue, les informations confirmées, les éléments manquants, la réponse proposée et la décision éventuellement attendue.</p><Example/></Act>
    <Act n="02" title="Une identité porte la relation dans la durée." muted><p>La mission est accomplie par votre Collaborateur IA avec son profil métier, son historique autorisé et les règles de votre entreprise. Il ne devient pas une boîte email autonome sans supervision.</p><Grid items={[['Mission','Le travail à accomplir.'],['Profil métier','La responsabilité de relation client.'],['Compétences','Qualifier, rechercher le contexte et préparer une réponse.'],['Applications','Les canaux et sources réellement autorisés.']]}/></Act>
    <Act n="03" title="Il mobilise uniquement le contexte autorisé."><Grid items={[['Catégories de demandes','Facturation, information, incident, réclamation ou autre classification validée.'],['Sources autorisées','Contrat, dossier client, base d’aide ou documents explicitement accessibles.'],['Règles de ton','Vocabulaire, niveau de formalité et éléments à ne jamais promettre.'],['Escalade','Situations sensibles, données manquantes et décisions qui restent humaines.']]}/><p className="mt-8 font-semibold">Une information confirmée est utilisée. Une information manquante ou incertaine est signalée.</p></Act>
    <Act n="04" title="Qualifier. Contextualiser. Préparer. Valider. Envoyer." muted><ol className="mt-8 border-t border-[#1C1A17]/15">{FLOW.map(([a,b],i)=><li key={a} className="grid gap-3 border-b border-[#1C1A17]/15 py-5 sm:grid-cols-[55px_170px_1fr]"><span className="font-mono text-xs text-[#B00C54]">0{i+1}</span><strong>{a}</strong><span>{b}</span></li>)}</ol></Act>
    <Act n="05" title="Le Collaborateur IA prépare. L’équipe décide."><p>Une réponse informative peut suivre une règle différente d’un remboursement, d’une remise, d’un engagement contractuel ou d’un message lié à un litige.</p><p className="mt-5 font-semibold">Préparation, validation et envoi sont trois actions distinctes.</p></Act>
    <Act n="06" title="Les corrections validées peuvent améliorer la prochaine réponse." muted><p>Le ton confirmé, les motifs d’escalade et les méthodes de recherche peuvent être conservés uniquement si l’entreprise le décide. Tous les emails ne deviennent pas automatiquement de la mémoire.</p></Act>
    <Act n="07" title="Le contrat de travail, en un regard."><dl className="mt-8 border-y border-[#1C1A17]/15"><Row l="Mission" v="Qualifier les demandes reçues et préparer une réponse contextualisée."/><Row l="Résultat" v="Une réponse prête à relire, accompagnée du contexte et des points à confirmer."/><Row l="Contexte" v="Catégories, sources, ton et historique explicitement autorisés."/><Row l="Validation humaine" v="Engagements, exceptions et messages sensibles selon les règles de l’entreprise."/><Row l="Envoi" v="Uniquement avec un canal réellement connecté et les droits nécessaires."/><Row l="Expérience conservée" v="Seulement les corrections et méthodes que l’entreprise choisit de mémoriser."/></dl></Act>

    <section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-[960px]"><h2 className="font-sf text-[36px] font-bold">Questions fréquentes</h2><div className="mt-6 border-t border-[#1C1A17]/15">{EMAIL_GUIDE_FAQ.map(([q,a])=><div key={q} className="border-b border-[#1C1A17]/15 py-5"><h3 className="font-sf text-xl font-bold">{q}</h3><p className="mt-2 leading-7 text-[#4E483F]">{a}</p></div>)}</div></div></section>
    <section className="bg-[#D10E63] px-5 py-16 text-white sm:px-8"><div className="mx-auto max-w-[1000px]"><h2 className="font-sf text-[42px] font-bold">Personnalisez le traitement de vos emails.</h2><div className="mt-5 max-w-3xl space-y-3 text-[17px] leading-8 text-white/80"><p>Donnez à Alma vos catégories de demandes, vos sources autorisées, votre ton, vos règles d’escalade et les réponses qui doivent rester sous validation humaine.</p><p>Elle vous aide à préparer la mission et le Collaborateur IA qui l’accomplira.</p></div><Link href="/decouvrir?mission=repondre-a-mes-clients" className="mt-7 inline-flex bg-[#151310] px-6 py-3 text-sm font-bold">Personnaliser cette mission avec Alma →</Link></div></section>
  </article>
}

const FLOW=[['Qualifier','Identifier l’objet, l’urgence et la catégorie de la demande.'],['Retrouver le contexte','Consulter uniquement les sources autorisées.'],['Préparer','Rédiger une réponse adaptée au ton et aux informations confirmées.'],['Signaler','Marquer les données manquantes, incertaines ou sensibles.'],['Valider','Demander une décision humaine lorsque les règles l’exigent.'],['Envoyer','Utiliser le canal connecté uniquement après autorisation.']]
function Act({n,title,muted,children}:{n:string;title:string;muted?:boolean;children:React.ReactNode}){return <section className={`${muted?'bg-[#EAE4D9]':''} px-5 py-16 sm:px-8 sm:py-20`}><div className="mx-auto max-w-[960px]"><p className="label">{n}</p><h2 className="mt-3 font-sf text-[36px] font-bold leading-tight sm:text-[50px]">{title}</h2><div className="mt-6 text-[17px] leading-8 text-[#4E483F]">{children}</div></div></section>}
function Grid({items}:{items:string[][]}){return <div className="mt-8 grid border-y border-[#1C1A17]/15 sm:grid-cols-2">{items.map(([a,b])=><div key={a} className="border-b border-[#1C1A17]/15 p-5 sm:odd:border-r"><h3 className="font-sf text-xl font-bold">{a}</h3><p className="mt-2 text-sm leading-6">{b}</p></div>)}</div>}
function Example(){return <section className="mt-10 border-y border-[#1C1A17]/15 py-7"><p className="label">Exemple fictif</p><h3 className="mt-3 font-sf text-2xl font-bold">Objet : Correction de la facture FA-2026-041</h3><p className="mt-2 text-sm text-[#6E665A]">Exemple fictif destiné à illustrer la structure du résultat.</p><dl className="mt-7 grid gap-6 sm:grid-cols-2"><EF l="Demande" v="Le client signale une quantité facturée incorrecte."/><EF l="Information confirmée" v="La commande et le bon de livraison indiquent 8 unités."/><EF l="Information manquante" v="Le pouvoir de valider un avoir n’est pas présent dans le contexte autorisé."/><EF l="Réponse préparée" v="Accuser réception, confirmer la vérification et indiquer qu’une correction sera proposée après validation."/><EF l="Décision humaine" v="Valider l’avoir et son montant avant tout engagement."/></dl></section>}
function EF({l,v}:{l:string;v:string}){return <div><dt className="font-semibold">{l}</dt><dd className="mt-1 leading-7 text-[#4E483F]">{v}</dd></div>}
function Row({l,v}:{l:string;v:string}){return <div className="grid gap-2 border-b border-[#1C1A17]/15 py-5 sm:grid-cols-[190px_1fr]"><dt className="label">{l}</dt><dd>{v}</dd></div>}
