'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowDown, ArrowRight, Check, Gauge, KeyRound, WalletCards } from 'lucide-react'
import { useLanguage } from '@/lib/language-context'
import { AlmaFace } from '@/components/alma-face'

type Workload = 'light' | 'daily' | 'intensive'

const T = {
  fr: {
    eyebrow: 'Capacité IA / Consommation', title: 'Donnez à vos Collaborateurs IA', accent: 'la capacité adaptée à leurs missions.', lead: 'Choisissez un volume de travail et un mode de paiement. Unitalk utilise uniquement les modèles autorisés par votre entreprise, sans vous obliger à gérer chaque route technique.',
    primary: 'Estimer ma capacité', models: 'Explorer les modèles disponibles', gateway: 'Comprendre le routage AI Gateway', proofs: ['Capacité ajustable', 'Consommation attribuée', 'BYOK disponible'],
    capacityKicker: 'Capacité mensuelle', capacityTitle: 'Dimensionnez un rythme de travail.', capacityBody: 'La capacité suit le Collaborateur IA. Vous pouvez l’ajuster sans changer son identité, ses missions ni son expérience validée.', workloadLabel: 'Rythme estimé', workloads: { light: 'Léger', daily: 'Quotidien', intensive: 'Intensif' },
    capacities: { light: { name: 'Quart-temps', tokens: '5 M', price: '25 €', cadence: 'Missions légères ou récurrentes', note: 'Offert jusqu’au 31 décembre 2026' }, daily: { name: 'Mi-temps', tokens: '10 M', price: '50 €', cadence: 'Prise en charge quotidienne', note: 'Ajustable à tout moment' }, intensive: { name: 'Temps plein', tokens: '20 M', price: '100 €', cadence: 'Processus complexes et volumes importants', note: 'Ajustable à tout moment' } },
    perMonth: '/ mois / Collaborateur IA', tokensLabel: 'tokens par mois', choose: 'Commander cette capacité',
    modesKicker: 'Modes de paiement', modesTitle: 'Mensuel, prépayé ou avec vos clés.', modes: [
      { icon: Gauge, tag: 'Prévisible', title: 'Capacité mensuelle', price: '25 à 100 €', body: 'Un volume mensuel affecté à chaque Collaborateur IA pour ses missions régulières.', points: ['5, 10 ou 20 M de tokens', 'Budget récurrent lisible', 'Capacité ajustable'], href: '/commande?offre=capacite-mensuelle' },
      { icon: WalletCards, tag: 'Sans engagement', title: 'Crédits prépayés', price: 'Dès 25 €', body: 'Rechargez un solde pour les besoins ponctuels, les modèles avancés ou les usages multimodaux.', points: ['Recharge ponctuelle', 'Budget maîtrisé', 'Consommation réelle'], href: '/commande?offre=credits-prepayes' },
      { icon: KeyRound, tag: 'Vos clés', title: 'BYOK', price: '0 € / mois', body: 'Connectez les clés API de votre entreprise et réglez directement les fournisseurs.', points: ['Prix direct fournisseur', 'Clés sous votre contrôle', 'Configuration hybride possible'], href: '/commande?offre=byok' },
    ],
    scopeTitle: 'Ce que cette page vous aide à décider.', scope: [['Volume', 'Combien de travail IA prévoir chaque mois.'], ['Paiement', 'Capacité mensuelle, crédits prépayés ou clés fournisseur.'], ['Budget', 'Quel coût attribuer à chaque Collaborateur IA.']],
    gatewayTitle: 'Le routage reste géré séparément.', gatewayBody: 'AI Gateway applique les autorisations, routes, replis, limites et budgets. La Marketplace présente les modèles disponibles.',
    finalTitle: 'Décrivez une mission. Alma estime la capacité utile.', finalBody: 'Alma vous aide à cadrer le rythme, les formats et le budget avant toute activation.', finalCta: 'Décrire ma mission', pricing: 'Voir tous les tarifs',
  },
  en: {
    eyebrow: 'AI capacity / Usage', title: 'Give your AI Collaborators', accent: 'the capacity their missions need.', lead: 'Choose a workload and payment method. Unitalk uses only models approved by your organization, without making you manage every technical route.',
    primary: 'Estimate capacity', models: 'Explore available models', gateway: 'Understand AI Gateway routing', proofs: ['Adjustable capacity', 'Attributed usage', 'BYOK available'],
    capacityKicker: 'Monthly capacity', capacityTitle: 'Size a work pace.', capacityBody: 'Capacity follows the AI Collaborator. Adjust it without changing identity, missions or validated experience.', workloadLabel: 'Estimated pace', workloads: { light: 'Light', daily: 'Daily', intensive: 'Intensive' },
    capacities: { light: { name: 'Quarter-time', tokens: '5M', price: '€25', cadence: 'Light or recurring missions', note: 'Free through December 31, 2026' }, daily: { name: 'Half-time', tokens: '10M', price: '€50', cadence: 'Daily workload', note: 'Adjust any time' }, intensive: { name: 'Full-time', tokens: '20M', price: '€100', cadence: 'Complex processes and high volumes', note: 'Adjust any time' } },
    perMonth: '/ month / AI Collaborator', tokensLabel: 'tokens per month', choose: 'Order this capacity',
    modesKicker: 'Payment methods', modesTitle: 'Monthly, prepaid or with your keys.', modes: [
      { icon: Gauge, tag: 'Predictable', title: 'Monthly capacity', price: '€25 to €100', body: 'A monthly volume assigned to each AI Collaborator for regular missions.', points: ['5, 10 or 20M tokens', 'Clear recurring budget', 'Adjustable capacity'], href: '/commande?offre=capacite-mensuelle' },
      { icon: WalletCards, tag: 'No commitment', title: 'Prepaid credits', price: 'From €25', body: 'Top up a balance for occasional needs, advanced models or multimodal uses.', points: ['One-off top-up', 'Controlled budget', 'Actual usage'], href: '/commande?offre=credits-prepayes' },
      { icon: KeyRound, tag: 'Your keys', title: 'BYOK', price: '€0 / month', body: 'Connect your organization API keys and pay providers directly.', points: ['Direct provider price', 'Keys under your control', 'Hybrid setup available'], href: '/commande?offre=byok' },
    ],
    scopeTitle: 'What this page helps you decide.', scope: [['Volume', 'How much AI work to plan each month.'], ['Payment', 'Monthly capacity, prepaid credits or provider keys.'], ['Budget', 'What cost to attribute to each AI Collaborator.']],
    gatewayTitle: 'Routing is managed separately.', gatewayBody: 'AI Gateway applies permissions, routes, fallbacks, limits and budgets. The Marketplace presents available models.',
    finalTitle: 'Describe a mission. Alma estimates useful capacity.', finalBody: 'Alma helps scope pace, formats and budget before activation.', finalCta: 'Describe my mission', pricing: 'View all pricing',
  },
} as const

export function ModelesIaContent() {
  const { lang } = useLanguage()
  const t = T[lang]
  const [workload, setWorkload] = useState<Workload>('light')
  const capacity = t.capacities[workload]

  return <main className="overflow-hidden bg-[#F3EFE6] font-sf text-[#1C1A17]">
    <section className="relative border-b border-[#D8D0C2] px-5 pb-16 pt-32 sm:px-8 sm:pb-20 sm:pt-40"><div aria-hidden className="absolute inset-0 opacity-[.045] [background-image:linear-gradient(#1C1A17_1px,transparent_1px),linear-gradient(90deg,#1C1A17_1px,transparent_1px)] [background-size:72px_72px]"/><div className="editorial-shell relative"><p className="font-mono text-[10px] font-black uppercase tracking-[.22em] text-[#B00C54]">{t.eyebrow}</p><div className="mt-7 grid gap-10 lg:grid-cols-[1.12fr_.88fr] lg:items-end"><h1 className="max-w-5xl text-[clamp(2.7rem,6vw,5.8rem)] font-semibold leading-[.9] tracking-[-.065em]">{t.title}<span className="block text-[#D10E63]">{t.accent}</span></h1><div><p className="text-[17px] leading-8 text-[#4E483F]">{t.lead}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row lg:flex-col xl:flex-row"><a href="#capacite" className="inline-flex min-h-12 items-center justify-center rounded-full bg-[#181615] px-6 text-sm font-bold text-white">{t.primary}<ArrowDown className="ml-2 size-4"/></a><Link href="/marketplace/modeles-ia" className="inline-flex min-h-12 items-center justify-center rounded-full border border-[#BFB5A5] bg-[#FAF8F3] px-6 text-sm font-bold">{t.models}</Link></div></div></div><ul className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-xs font-bold text-[#625B50]">{t.proofs.map(item=><li key={item} className="flex items-center gap-2"><Check className="size-4 text-[#D10E63]"/>{item}</li>)}</ul></div></section>

    <section id="capacite" className="scroll-mt-24 px-5 py-16 sm:px-8 sm:py-24"><div className="editorial-shell"><div className="grid gap-9 lg:grid-cols-[.72fr_1.28fr]"><SectionTitle kicker={t.capacityKicker} title={t.capacityTitle}/><div className="lg:pt-8"><p className="max-w-2xl text-[16px] leading-8 text-[#4E483F]">{t.capacityBody}</p><fieldset className="mt-7"><legend className="font-mono text-[9px] font-black uppercase tracking-[.18em] text-[#857C6E]">{t.workloadLabel}</legend><div className="mt-3 flex flex-wrap gap-2">{(Object.keys(t.workloads) as Workload[]).map(key=><button key={key} type="button" aria-pressed={workload===key} onClick={()=>setWorkload(key)} className={`min-h-11 rounded-full border px-5 text-sm font-bold ${workload===key?'border-[#D10E63] bg-[#D10E63] text-white':'border-[#CFC5B5] bg-[#FAF8F3] text-[#4E483F]'}`}>{t.workloads[key]}</button>)}</div></fieldset></div></div><div className="mt-12 grid overflow-hidden rounded-[2rem] border border-[#CFC5B5] bg-[#FAF8F3] shadow-[0_36px_80px_-60px_rgba(28,26,23,.7)] lg:grid-cols-[.75fr_1.25fr]"><div className="bg-[#D10E63] p-7 text-white sm:p-10"><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-white/70">{capacity.name}</p><p className="mt-12 text-[clamp(4.5rem,10vw,8rem)] font-semibold leading-none tracking-[-.08em]">{capacity.tokens}</p><p className="mt-2 text-sm font-bold text-white/75">{t.tokensLabel}</p></div><div className="flex flex-col justify-between p-7 sm:p-10"><div><p className="text-[clamp(3rem,7vw,6rem)] font-semibold leading-none tracking-[-.07em]">{capacity.price}</p><p className="mt-3 text-sm font-bold text-[#6E665A]">{t.perMonth}</p><p className="mt-9 max-w-xl text-xl font-semibold leading-8">{capacity.cadence}</p><p className="mt-3 text-sm text-[#6E665A]">{capacity.note}</p></div><Link href={`/commande?offre=capacite-${workload}`} className="mt-9 inline-flex min-h-12 w-fit items-center rounded-full bg-[#181615] px-6 text-sm font-bold text-white">{t.choose}<ArrowRight className="ml-2 size-4"/></Link></div></div></div></section>

    <section className="border-y border-[#D8D0C2] bg-[#EAE3D4] px-5 py-16 sm:px-8 sm:py-24"><div className="editorial-shell"><SectionTitle kicker={t.modesKicker} title={t.modesTitle}/><div className="mt-12 grid gap-4 lg:grid-cols-3">{t.modes.map(({icon:Icon,...mode})=><article key={mode.title} className="flex min-h-[410px] flex-col rounded-3xl border border-[#CFC5B5] bg-[#FAF8F3] p-7"><div className="flex items-center justify-between"><p className="font-mono text-[9px] font-black uppercase tracking-[.18em] text-[#B00C54]">{mode.tag}</p><Icon className="size-5 text-[#D10E63]"/></div><h3 className="mt-9 text-2xl font-semibold">{mode.title}</h3><p className="mt-3 text-[clamp(2.2rem,4vw,3.8rem)] font-semibold leading-none tracking-[-.06em]">{mode.price}</p><p className="mt-6 text-sm leading-7 text-[#625B50]">{mode.body}</p><ul className="mt-auto space-y-3 border-t border-[#D8D0C2] pt-6 text-sm font-semibold">{mode.points.map(point=><li key={point} className="flex gap-2.5"><Check className="mt-0.5 size-4 shrink-0 text-[#D10E63]"/>{point}</li>)}</ul><Link href={mode.href} className="mt-6 inline-flex min-h-11 items-center justify-center rounded-full bg-[#D10E63] px-5 text-sm font-bold text-white">{lang==='fr'?'Commander':'Order'}<ArrowRight className="ml-2 size-4"/></Link></article>)}</div></div></section>

    <section className="px-5 py-16 sm:px-8 sm:py-20"><div className="editorial-shell grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><h2 className="max-w-3xl text-[clamp(2.2rem,4vw,4rem)] font-semibold leading-[.96] tracking-[-.055em]">{t.scopeTitle}</h2><Link href="/ai-gateway" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#B00C54]">{t.gateway}<ArrowRight className="size-4"/></Link></div><div className="grid gap-px overflow-hidden rounded-2xl border border-[#CFC5B5] bg-[#CFC5B5] sm:grid-cols-3">{t.scope.map(([title,body])=><article key={title} className="bg-[#FAF8F3] p-6"><h3 className="font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#625B50]">{body}</p></article>)}</div></div><div className="editorial-shell mt-10 border-l-2 border-[#D10E63] pl-5"><p className="font-bold">{t.gatewayTitle}</p><p className="mt-2 max-w-3xl text-sm leading-7 text-[#625B50]">{t.gatewayBody}</p></div></section>

    <section className="bg-[#D10E63] px-5 py-16 text-white sm:px-8 sm:py-20"><div className="editorial-shell grid gap-9 lg:grid-cols-[1fr_auto] lg:items-end"><div><h2 className="max-w-5xl text-[clamp(2.4rem,5vw,4.8rem)] font-semibold leading-[.94] tracking-[-.06em]">{t.finalTitle}</h2><p className="mt-5 max-w-2xl text-[16px] leading-7 text-white/80">{withAlmaAvatar(t.finalBody)}</p></div><div className="flex flex-col gap-3"><Link href="/decouvrir?source=modeles-ia" className="inline-flex min-h-12 items-center justify-center rounded-full bg-[#181615] px-7 text-sm font-bold text-white">{t.finalCta}<ArrowRight className="ml-2 size-4"/></Link><Link href="/tarifs" className="text-center text-sm font-bold underline decoration-white/35 underline-offset-4">{t.pricing}</Link></div></div></section>
  </main>
}

function SectionTitle({ kicker, title }: { kicker: string; title: string }) { return <div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#B00C54]">{kicker}</p><h2 className="mt-5 max-w-4xl text-[clamp(2.3rem,4.7vw,4.7rem)] font-semibold leading-[.95] tracking-[-.06em]">{title}</h2></div> }
function withAlmaAvatar(value: string) { return value.split('Alma').map((part,index)=><span key={`${part}-${index}`}>{index>0&&<><AlmaFace/>Alma</>}{part}</span>) }
