import Link from 'next/link'
import { getMission, getMissionCategory, getMissionCategoryHref } from '@/lib/missions-catalog'
import { getStoreItemBySlug, storeItemHref, type StoreItem } from '@/lib/store-catalog'
import { MissionBreadcrumb } from '@/components/missions/mission-breadcrumb'

const SLUG = 'trouver-de-nouveaux-clients'
const mission = getMission(SLUG)!
const category = getMissionCategory(mission.category)!
const profile = getStoreItemBySlug('commercial')!
const skills = ['rechercher-des-entreprises','enrichir-une-fiche-prospect','verifier-une-information','detecter-un-signal-commercial','appliquer-un-scoring','dedupliquer-une-selection','documenter-une-recommandation','exporter-des-donnees-structurees'].map(getStoreItemBySlug).filter(Boolean) as StoreItem[]
const sources = ['linkedin'].map(getStoreItemBySlug).filter(Boolean) as StoreItem[]
const destinations = ['hubspot','salesforce','excel','google-sheets','csv'].map(getStoreItemBySlug).filter(Boolean) as StoreItem[]

export function ProspectsGuideContent() {
  return <article className="bg-[#F3EFE6] text-[#1C1A17]">
    <section className="px-5 pb-16 pt-24 sm:px-8 sm:pt-28"><div className="mx-auto max-w-[1180px]"><MissionBreadcrumb items={[{label:'Missions',href:'/missions'},{label:category.label.fr,href:getMissionCategoryHref(category)},{label:mission.title.fr}]}/><div className="mt-8 grid gap-12 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><p className="label">Mission · Prospection B2B</p><h1 className="mt-4 font-sf text-[42px] font-bold leading-[.98] tracking-[-.05em] sm:text-[64px]">Trouver des prospects qualifiés.<span className="block text-[#6E665A]">Et savoir exactement pourquoi.</span></h1><p className="mt-7 text-[18px] leading-8 text-[#4E483F]">Votre Collaborateur IA recherche les entreprises correspondant à votre cible, enrichit chaque fiche et applique votre méthode de scoring. Il explique chaque sélection avant validation et export.</p><p className="mt-3 text-[#4E483F]">Votre équipe commerciale garde la décision avant tout ajout au CRM ou toute prise de contact.</p><Link href={`/decouvrir?mission=${SLUG}`} className="mt-7 inline-flex bg-[#D10E63] px-6 py-3 text-sm font-bold text-white">Personnaliser cette mission →</Link></div><dl className="border-y border-[#1C1A17]/15"><Fact l="Résultat" v="Une sélection enrichie, scorée et expliquée, prête à être validée puis exportée."/><Fact l="Profil métier" v={profile.name.fr} href={storeItemHref(profile)}/><Fact l="Validation" v="Avant CRM ou prise de contact"/><Links l="Sources et recherche" items={sources} prefix="Navigateur · Sources autorisées"/><Links l="Destinations" items={destinations}/></dl></div></div></section>

    <Act n="01" eye="Le résultat" title="Une sélection que votre équipe peut décider d’utiliser."><p>Chaque prospect est enrichi, scoré et accompagné des raisons de sa sélection, des sources consultées et des points à vérifier.</p><section className="mt-10 border-y border-[#1C1A17]/15 py-7"><p className="label">Exemple fictif</p><h3 className="mt-3 font-sf text-3xl font-bold">Acme Industries</h3><p className="mt-2 text-sm text-[#6E665A]">Exemple fictif destiné à illustrer la structure du résultat.</p><div className="mt-8 grid gap-10 lg:grid-cols-2"><div><h4 className="label">Données enrichies</h4><dl className="mt-5 space-y-5"><EF l="Secteur" v="Industrie"/><EF l="Effectif observé" v="86 salariés"/><EF l="Signal récent" v="Recrutement de trois commerciaux"/><EF l="Sources" v="Site de l’entreprise · Offre d’emploi · Registre autorisé"/><EF l="Dernière vérification" v="12 août 2026"/></dl></div><div><h4 className="label">Score de qualification</h4><p className="mt-3 font-sf text-5xl font-bold">78 / 100</p><dl className="mt-5 space-y-2 text-sm"><Score l="Correspondance avec la cible" v="30 / 35"/><Score l="Signal commercial récent" v="20 / 25"/><Score l="Besoin observable" v="18 / 25"/><Score l="Fiabilité des informations" v="10 / 15"/></dl><div className="mt-7 space-y-5"><EF l="Pourquoi elle correspond" v="Secteur, taille et signal commercial correspondent à la cible."/><EF l="Niveau de confiance" v="Moyen — certaines informations restent à vérifier."/><EF l="Point à vérifier" v="Aucun responsable identifié pour le périmètre concerné."/><EF l="Destination après validation" v="CRM · Microsoft Excel · Google Sheets · CSV"/></div></div></div></section></Act>

    <Act n="02" eye="Le Collaborateur IA" title="Une identité porte la mission du début à la fin." muted><p>La mission est accomplie par votre Collaborateur IA avec son identité, son environnement et le contexte autorisé.</p><div className="mt-8 grid border-y border-[#1C1A17]/15 sm:grid-cols-2"><Concept t="Collaborateur IA" b="Une identité durable qui porte la responsabilité."/><Concept t="Profil métier" b="La responsabilité commerciale mobilisée dans la durée." href={storeItemHref(profile)}/><Concept t="Compétences" b="Les méthodes de recherche, d’enrichissement, de scoring et d’export."/><Concept t="Applications" b="Les sources et destinations autorisées."/></div></Act>

    <Act n="03" eye="Ce qu’il mobilise" title="Il n’invente ni votre cible ni votre scoring."><div className="grid border-y border-[#1C1A17]/15 sm:grid-cols-2"><Concept t="Votre contexte" b="Profil client idéal, critères, pondérations, exclusions, clients existants, sources, champs CRM, format d’export et validations."/><Concept t="Votre mémoire d’entreprise" b="Critères corrigés, motifs d’acceptation ou de refus, sources fiables, déduplication et formats que l’entreprise choisit de conserver."/><Concept t="Ses compétences" b="Rechercher, enrichir, vérifier, détecter, scorer, dédupliquer, documenter et exporter." links={skills}/><Concept t="Ses applications" b="Navigateur, CRM et destinations d’export autorisés." links={[...sources,...destinations]}/></div><p className="mt-8 font-sf text-2xl font-bold">Il applique la méthode que votre entreprise valide.</p></Act>

    <Act n="04" eye="Travail collaboratif" title="Rechercher. Enrichir. Scorer. Valider. Exporter." muted><ol className="mt-8 border-t border-[#1C1A17]/15">{FLOW.map(([a,b],i)=><li key={a} className="grid gap-3 border-b border-[#1C1A17]/15 py-5 sm:grid-cols-[55px_150px_1fr]"><span className="font-mono text-xs text-[#B00C54]">0{i+1}</span><strong>{a}</strong><span>{b}</span></li>)}</ol></Act>

    <Act n="05" eye="Ce qui reste" title="Le résultat est livré. La méthode reste dans l’entreprise."><p>Les corrections validées peuvent améliorer la prochaine sélection et être partagées avec les collaborateurs humains et IA autorisés.</p><p className="mt-7 font-sf text-2xl font-bold text-[#B00C54]">Validé une fois. Réutilisé par tous ceux qui y sont autorisés.</p></Act>

    <Act n="06" eye="Le contrat de travail" title="Une mission complète, en un regard." muted><dl className="mt-8 border-y border-[#1C1A17]/15"><Row l="Mission" v="Trouver les entreprises qui correspondent à notre cible."/><Row l="Enrichissement" v="Compléter chaque fiche avec les informations autorisées, leurs sources et leur date."/><Row l="Scoring" v="Appliquer notre grille et expliquer chaque score."/><Row l="Résultat" v="Une sélection enrichie, scorée, documentée et sans doublons."/><Row l="Validation humaine" v="L’équipe valide et peut corriger le score."/><Row l="Export" v="Transmettre au CRM ou exporter vers Microsoft Excel, Google Sheets ou CSV."/><Row l="Prise de contact" v="Aucun contact sans l’autorisation de l’entreprise."/><Row l="Expérience conservée" v="Critères, pondérations et corrections choisis par l’entreprise."/></dl><section className="mt-14"><h3 className="font-sf text-3xl font-bold">Questions fréquentes</h3>{FAQ.map(([q,a])=><div key={q} className="border-b border-[#1C1A17]/15 py-5"><h4 className="font-sf text-xl font-bold">{q}</h4><p className="mt-2">{a}</p></div>)}</section></Act>

    <section className="bg-[#D10E63] px-5 py-16 text-white sm:px-8"><div className="mx-auto max-w-[1000px]"><h2 className="font-sf text-[42px] font-bold">Personnalisez votre méthode de qualification.</h2><p className="mt-5 text-[17px] text-white/80">Donnez à Alma votre cible, vos règles d’enrichissement, votre scoring et la destination du résultat.</p><Link href={`/decouvrir?mission=${SLUG}`} className="mt-7 inline-flex bg-[#151310] px-6 py-3 text-sm font-bold">Personnaliser cette mission →</Link></div></section>
  </article>
}

const FLOW=[['Cadrer','Définir cible, exclusions, sources et scoring.'],['Rechercher','Identifier les entreprises correspondant aux critères.'],['Enrichir','Compléter les fiches avec sources et dates.'],['Scorer','Appliquer et expliquer les points.'],['Valider','Accepter, corriger ou refuser.'],['Exporter','Transmettre au CRM, Excel, Sheets ou CSV.'],['Conserver','Mémoriser uniquement les corrections choisies.']]
const FAQ=[['Comment le score est-il calculé ?','Selon les critères et pondérations définis par votre entreprise, avec une explication et un niveau de confiance.'],['Peut-on exporter la sélection ?','Après validation, vers le CRM autorisé, Microsoft Excel, Google Sheets ou CSV selon les droits.'],['Peut-il contacter automatiquement les prospects ?','Seulement si l’entreprise l’autorise.'],['Que devient l’expérience ?','Les corrections validées peuvent enrichir et partager la méthode avec les collaborateurs autorisés.']]
function Act({n,eye,title,muted,children}:{n:string;eye:string;title:string;muted?:boolean;children:React.ReactNode}){return <section className={`${muted?'bg-[#EAE4D9]':''} px-5 py-16 sm:px-8 sm:py-24`}><div className="mx-auto max-w-[1000px]"><p className="label">{n} · {eye}</p><h2 className="mt-4 font-sf text-[36px] font-bold leading-tight sm:text-[50px]">{title}</h2><div className="mt-6 text-[17px] leading-8 text-[#4E483F]">{children}</div></div></section>}
function Fact({l,v,href}:{l:string;v:string;href?:string}){return <div className="border-b border-[#1C1A17]/15 py-5"><dt className="label">{l}</dt><dd className="mt-2 font-sf text-xl font-bold">{href?<Link href={href}>{v}</Link>:v}</dd></div>}
function Links({l,items,prefix}:{l:string;items:StoreItem[];prefix?:string}){return <div className="border-b border-[#1C1A17]/15 py-5"><dt className="label">{l}</dt><dd className="mt-2 flex flex-wrap gap-3 text-sm">{prefix&&<span>{prefix}</span>}{items.map(x=><Link key={x.slug} href={storeItemHref(x)} className="underline">{x.name.fr}</Link>)}</dd></div>}
function EF({l,v}:{l:string;v:string}){return <div><dt className="font-bold">{l}</dt><dd className="mt-1">{v}</dd></div>}
function Score({l,v}:{l:string;v:string}){return <div className="flex justify-between"><dt>{l}</dt><dd className="font-bold">{v}</dd></div>}
function Concept({t,b,href,links}:{t:string;b:string;href?:string;links?:StoreItem[]}){return <div className="border-b border-[#1C1A17]/15 p-6"><h3 className="font-sf text-2xl font-bold">{href?<Link href={href}>{t}</Link>:t}</h3><p className="mt-3 text-sm">{b}</p>{links&&<div className="mt-4 flex flex-wrap gap-2">{links.map(x=><Link key={x.slug} href={storeItemHref(x)} className="text-xs text-[#B00C54] underline">{x.name.fr}</Link>)}</div>}</div>}
function Row({l,v}:{l:string;v:string}){return <div className="grid gap-2 border-b border-[#1C1A17]/15 py-5 sm:grid-cols-[190px_1fr]"><dt className="label">{l}</dt><dd>{v}</dd></div>}
