'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, BookOpenCheck, Boxes, BrainCircuit, BriefcaseBusiness, Check, GraduationCap, MessageSquare, Search, Sparkles } from 'lucide-react'
import { useLanguage } from '@/lib/language-context'
import { Kicker } from '@/components/home/section-kicker'
import { STORE_ITEMS, storeItemHref } from '@/lib/store-catalog'

const COUNTS={profiles:STORE_ITEMS.filter(i=>i.type==='profil').length,skills:STORE_ITEMS.filter(i=>i.type==='competence').length,apps:STORE_ITEMS.filter(i=>i.type==='application').length}
const FEATURED=['commercial','assistante-de-direction','responsable-seo','qualifier-un-prospect','preparer-une-reunion','google-sheets']

const COPY={
  fr:{kicker:'Unitalk Store',title:'Tout ce qui équipe votre équipe humain-IA.',lead:'Un seul point d’entrée pour découvrir les profils métier, compétences, applications, modèles et formations. Décrivez votre besoin à Alma ou explorez directement un univers.',ask:'Demander à Alma',placeholder:'Ex. Je veux qualifier mes prospects et mettre à jour mon CRM…',explore:'Explorer les univers',almaKicker:'La sélection d’Alma',almaTitle:'Alma ne vous laisse pas assembler le Store au hasard.',almaBody:'Elle part de la mission, vérifie l’identité existante, puis recommande seulement les profils, compétences, applications et modèles nécessaires, avec leurs droits et validations.',almaCta:'Parler à Alma',almaStore:'Explorer le Store d’Alma',almaProfiles:'Profils d’Alma',almaSkills:'Compétences d’Alma',universesTitle:'Six univers. Une seule architecture.',universesLead:'Chaque univers possède sa page de référence. Le Store central vous aide à comprendre ce qui doit être combiné.',featured:'Actifs populaires',featuredLead:'Des éléments réels du catalogue Unitalk, prêts à consulter et à adapter.',view:'Voir la fiche',creatorTitle:'Vous détenez une méthode, un outil ou une formation ?',creatorBody:'Les Co-créateurs et experts peuvent formaliser, tester, versionner et proposer leurs actifs dans le Store adapté.',create:'Créer avec Unitalk AI',learn:'Se former sur Unitalk Academy'},
  en:{kicker:'Unitalk Store',title:'Everything that equips your human-AI team.',lead:'One entry point for job profiles, skills, applications, models and training. Describe your need to Alma or browse an area directly.',ask:'Ask Alma',placeholder:'E.g. I want to qualify prospects and update my CRM…',explore:'Browse areas',almaKicker:'Alma’s selection',almaTitle:'Alma does not make you assemble the Store at random.',almaBody:'She starts from the mission, checks the existing identity, then recommends only the required profiles, skills, applications and models, with their permissions and approvals.',almaCta:'Talk to Alma',almaStore:'Explore Alma’s Store',almaProfiles:'Alma profiles',almaSkills:'Alma skills',universesTitle:'Six areas. One architecture.',universesLead:'Each area has one reference page. The central Store helps you understand what should be combined.',featured:'Popular assets',featuredLead:'Real Unitalk catalog items, ready to review and adapt.',view:'View details',creatorTitle:'Do you own a method, tool or training?',creatorBody:'Co-creators and experts can formalize, test, version and propose assets in the relevant Store.',create:'Create with Unitalk AI',learn:'Train with Unitalk Academy'}
} as const

export function UnitalkStoreHub(){const{lang}=useLanguage();const t=COPY[lang];const featured=FEATURED.map(slug=>STORE_ITEMS.find(item=>item.slug===slug)).filter(Boolean);const universes=[
  {icon:BriefcaseBusiness,title:lang==='fr'?'Profils métier':'Job profiles',count:`${COUNTS.profiles}`,body:lang==='fr'?'Les responsabilités durables attribuées à une identité IA.':'Lasting responsibilities assigned to an AI identity.',href:'/collaborateurs-ia/profils-metier',tone:'light'},
  {icon:Sparkles,title:lang==='fr'?'Compétences':'Skills',count:`${COUNTS.skills}`,body:lang==='fr'?'Les méthodes précises, testées et versionnées qu’elle peut appliquer.':'Precise, tested and versioned methods it can apply.',href:'/collaborateurs-ia/competences',tone:'light'},
  {icon:Boxes,title:lang==='fr'?'Applications':'Applications',count:`${COUNTS.apps}`,body:lang==='fr'?'Les outils, connecteurs et services accessibles selon les droits.':'Tools, connectors and services available under permissions.',href:'/collaborateurs-ia/applications/catalogue',tone:'light'},
  {icon:BrainCircuit,title:lang==='fr'?'Modèles IA':'AI models',count:'Gateway',body:lang==='fr'?'Les modèles et fournisseurs autorisés via Unitalk AI Gateway.':'Authorized models and providers through Unitalk AI Gateway.',href:'/modeles-ia',tone:'dark'},
  {icon:GraduationCap,title:lang==='fr'?'Formations':'Training',count:'Academy',body:lang==='fr'?'Les parcours pour apprendre à utiliser, créer et gouverner Unitalk.':'Paths to learn how to use, create and govern Unitalk.',href:'https://unitalk.fr',tone:'dark'},
  {icon:BookOpenCheck,title:lang==='fr'?'Missions':'Missions',count:'200+',body:lang==='fr'?'Le travail à accomplir qui détermine l’équipement réellement nécessaire.':'The work to perform that determines the equipment actually needed.',href:'/missions',tone:'dark'},
] as const;return <main className="bg-[#F3EFE6] font-sf text-[#1C1A17]">
  <section className="relative overflow-hidden px-5 pb-16 pt-28 sm:px-8 sm:pb-20"><div aria-hidden className="pointer-events-none absolute inset-0 opacity-[.04] [background-image:linear-gradient(#1C1A17_1px,transparent_1px),linear-gradient(90deg,#1C1A17_1px,transparent_1px)] [background-size:72px_72px]"/><div className="editorial-shell relative text-center"><Kicker>{t.kicker}</Kicker><h1 className="hero-heading mx-auto mt-5 max-w-5xl [font-size:clamp(2.6rem,6vw,5.2rem)]">{t.title}</h1><p className="mx-auto mt-6 max-w-3xl text-[17px] leading-8 text-[#4E483F]">{t.lead}</p><form action="/decouvrir" className="mx-auto mt-9 flex max-w-3xl flex-col gap-3 rounded-3xl border border-[#D8D0C2] bg-[#FAF8F3] p-3 shadow-[0_25px_60px_-40px_rgba(28,26,23,.4)] sm:flex-row"><label className="relative min-w-0 flex-1"><span className="sr-only">{t.placeholder}</span><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-[#857C6E]"/><input name="q" placeholder={t.placeholder} className="h-12 w-full bg-transparent pl-11 pr-4 text-sm outline-none"/></label><input type="hidden" name="source" value="unitalk-store"/><button className="inline-flex min-h-12 items-center justify-center rounded-full bg-[#D10E63] px-6 text-sm font-bold text-white">{t.ask}<ArrowRight className="ml-2 size-4"/></button></form><a href="#univers" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#B00C54]">{t.explore}<ArrowRight className="size-4 rotate-90"/></a></div></section>

  <section className="border-y border-[#D8D0C2] bg-[#EAE3D4] px-5 py-16 sm:px-8 sm:py-20"><div className="editorial-shell grid gap-10 lg:grid-cols-[.82fr_1.18fr] lg:items-center"><div><div className="flex items-center gap-4"><Image src="/alma-avatar.png" alt="Alma" width={64} height={64} className="size-16 rounded-full object-cover ring-2 ring-[#D10E63]/25"/><div><p className="font-mono text-[10px] font-black uppercase tracking-[.16em] text-[#B00C54]">{t.almaKicker}</p><p className="mt-1 font-bold">Alma · {lang==='fr'?'Coordinatrice de missions':'Mission coordinator'}</p></div></div><h2 className="mt-7 text-[34px] font-semibold leading-[1.06] tracking-[-.04em] sm:text-[44px]">{t.almaTitle}</h2><p className="mt-5 max-w-2xl text-[16px] leading-8 text-[#4E483F]">{t.almaBody}</p><div className="mt-7 flex flex-wrap gap-4"><Link href="/unitalk/@alma" className="inline-flex min-h-11 items-center rounded-full bg-[#D10E63] px-5 text-sm font-bold text-white">{t.almaCta}<ArrowRight className="ml-2 size-4"/></Link><Link href="/unitalk/@alma/store" className="inline-flex min-h-11 items-center text-sm font-bold text-[#B00C54]">{t.almaStore}</Link></div></div><div className="grid gap-4 sm:grid-cols-2"><AlmaAsset title={t.almaProfiles} items={lang==='fr'?['Coordinatrice de missions','Conseillère en adoption IA','Conseillère en transformation IA']:['Mission coordinator','AI adoption advisor','AI transformation advisor']}/><AlmaAsset title={t.almaSkills} items={lang==='fr'?['Cadrer une mission','Préparer les validations','Interviewer un expert','Recommander une capacité IA']:['Scope a mission','Prepare approvals','Interview an expert','Recommend AI capacity']}/></div></div></section>

  <section id="univers" className="scroll-mt-24 px-5 py-16 sm:px-8 sm:py-20"><div className="editorial-shell"><Kicker>Architecture du Store</Kicker><h2 className="mt-5 text-[34px] font-semibold tracking-[-.04em] sm:text-[44px]">{t.universesTitle}</h2><p className="mt-4 max-w-3xl text-[16px] leading-7 text-[#4E483F]">{t.universesLead}</p><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{universes.map(({icon:Icon,...u})=><Link key={u.title} href={u.href} className={`group flex min-h-[300px] flex-col rounded-3xl border p-7 transition hover:-translate-y-1 ${u.tone==='dark'?'border-white/10 bg-[#181615] text-[#FAF8F3]':'border-[#D8D0C2] bg-[#FAF8F3]'}`}><div className="flex items-start justify-between"><Icon className={u.tone==='dark'?'text-[#F2A4C5]':'text-[#D10E63]'}/><span className={`font-mono text-[10px] font-black uppercase tracking-[.14em] ${u.tone==='dark'?'text-[#F2A4C5]':'text-[#B00C54]'}`}>{u.count}</span></div><h3 className="mt-9 text-2xl font-bold">{u.title}</h3><p className={`mt-4 text-sm leading-7 ${u.tone==='dark'?'text-[#CFC6B8]':'text-[#625B50]'}`}>{u.body}</p><ArrowRight className={`mt-auto size-5 pt-8 box-content transition group-hover:translate-x-1 ${u.tone==='dark'?'text-[#F2A4C5]':'text-[#D10E63]'}`}/></Link>)}</div></div></section>

  <section className="border-y border-[#D8D0C2] bg-[#FAF8F3] px-5 py-16 sm:px-8"><div className="editorial-shell"><Kicker>{t.featured}</Kicker><h2 className="mt-5 text-[34px] font-semibold tracking-[-.04em] sm:text-[44px]">{t.featuredLead}</h2><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{featured.map(item=><article key={item!.slug} className="flex min-h-[230px] flex-col rounded-3xl border border-[#D8D0C2] bg-[#F3EFE6] p-6"><p className="font-mono text-[9px] font-black uppercase tracking-[.14em] text-[#B00C54]">{item!.type}</p><h3 className="mt-5 text-xl font-bold">{item!.name[lang]}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-[#625B50]">{item!.description[lang]}</p><Link href={storeItemHref(item!)} className="mt-auto inline-flex items-center gap-2 pt-6 text-sm font-bold text-[#B00C54]">{t.view}<ArrowRight className="size-4"/></Link></article>)}</div></div></section>

  <section className="bg-[#181615] px-5 py-16 text-[#FAF8F3] sm:px-8 sm:py-20"><div className="editorial-shell grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><Kicker dark>Contribuer au Store</Kicker><h2 className="mt-5 max-w-4xl text-[34px] font-semibold leading-[1.06] tracking-[-.04em] sm:text-[44px]">{t.creatorTitle}</h2><p className="mt-5 max-w-3xl text-[16px] leading-8 text-[#CFC6B8]">{t.creatorBody}</p></div><div className="flex flex-col gap-3"><Link href="/co-createur-ia" className="inline-flex min-h-12 items-center justify-center rounded-full bg-[#D10E63] px-6 text-sm font-bold">{t.create}<ArrowRight className="ml-2 size-4"/></Link><a href="https://unitalk.fr/formations/co-createur-ia?source=unitalk-store" className="text-center text-sm font-bold text-[#F2A4C5]">{t.learn}</a></div></div></section>
</main>}

function AlmaAsset({title,items}:{title:string;items:readonly string[]}){return <article className="rounded-3xl border border-[#D8D0C2] bg-[#FAF8F3] p-6"><h3 className="text-lg font-bold">{title}</h3><ul className="mt-5 space-y-3">{items.map(item=><li key={item} className="flex gap-2 text-sm font-semibold"><Check className="size-4 shrink-0 text-[#D10E63]"/>{item}</li>)}</ul></article>}
