export type SectorId = 'marketing' | 'commerce' | 'finance' | 'rh' | 'industrie' | 'entrepreneuriat'
export type Level = 'Découverte' | 'Intermédiaire' | 'Avancé'

export type LearningMission = { slug:string; title:string; result:string; duration:string; level:Level; sector:SectorId; skillSlugs:string[]; deliverable:string; evaluation:string; author:string; free?:boolean; steps:string[] }
export type LearningSkill = { slug:string; title:string; outcome:string; sector:SectorId; level:Level; missionSlugs:string[]; evidence:string; evaluation:string; author:string; version:string }
export type LearningPath = { slug:string; title:string; promise:string; sector:SectorId; missionSlugs:string[]; skillSlugs:string[]; audience:string; format:string }
export type AcademyNetwork = { id:SectorId; name:string; tagline:string; description:string; color:string; members:string; events:string }

export const NETWORKS: AcademyNetwork[] = [
  { id:'marketing', name:'Marketing', tagline:'Observer, positionner, créer, mesurer.', description:'Les méthodes pour comprendre un marché, construire une marque et piloter une acquisition responsable avec l’IA.', color:'#D10E63', members:'182 membres', events:'2 ateliers ce mois' },
  { id:'commerce', name:'Commerce', tagline:'Prospecter, qualifier, convaincre, fidéliser.', description:'Un réseau pour formaliser les meilleures pratiques commerciales et apprendre à travailler avec une équipe humain-IA.', color:'#C05A24', members:'146 membres', events:'1 classe ouverte' },
  { id:'finance', name:'Finance', tagline:'Analyser, contrôler, décider.', description:'Des missions et compétences pour fiabiliser l’analyse, la prévision et le contrôle sans abandonner le jugement humain.', color:'#3E6DA8', members:'96 membres', events:'1 étude de cas' },
  { id:'rh', name:'Ressources humaines', tagline:'Développer les personnes et les entreprises.', description:'Compétences de recrutement, formation, adoption et gouvernance des équipes humain-IA.', color:'#7562A8', members:'118 membres', events:'2 rencontres' },
  { id:'industrie', name:'Industrie', tagline:'Documenter, améliorer, transmettre.', description:'Le réseau des méthodes opérationnelles, de la qualité, de la maintenance et de la transmission des savoir-faire terrain.', color:'#2E7D4F', members:'84 membres', events:'1 atelier terrain' },
  { id:'entrepreneuriat', name:'Entrepreneuriat', tagline:'Concevoir une entreprise capable.', description:'Pour construire une activité augmentée, une offre claire et une entreprise qui combine humains et capacités IA.', color:'#1C1A17', members:'231 membres', events:'3 sessions ouvertes' },
]

export const MISSIONS: LearningMission[] = [
  { slug:'construire-veille-concurrentielle', title:'Construire une veille concurrentielle fiable', result:'Une synthèse sourcée accompagnée d’une recommandation justifiée.', duration:'2 h 30', level:'Intermédiaire', sector:'marketing', skillSlugs:['concevoir-methode-veille','verifier-sources'], deliverable:'Grille de veille, synthèse et recommandation', evaluation:'Revue par un pair selon la grille Veille v2', author:'Claire Martin · Experte stratégie', free:true, steps:['Définir le périmètre concurrentiel','Choisir et qualifier les sources','Construire la grille d’analyse','Produire une synthèse sourcée','Présenter et justifier une recommandation'] },
  { slug:'preparer-campagne-prospection', title:'Préparer une campagne de prospection responsable', result:'Une campagne ciblée avec critères, messages et règles de validation.', duration:'3 h', level:'Intermédiaire', sector:'commerce', skillSlugs:['qualifier-cible-commerciale','documenter-recommandation'], deliverable:'Cible, séquence et messages à valider', evaluation:'Évaluation par formateur et test sur cas fictif', author:'Marc Renard · Directeur commercial', free:true, steps:['Définir la cible','Documenter les critères','Préparer la séquence','Rédiger les messages','Valider les règles de contact'] },
  { slug:'cartographier-processus', title:'Cartographier un processus métier', result:'Une représentation claire des étapes, décisions, outils et exceptions.', duration:'2 h', level:'Découverte', sector:'industrie', skillSlugs:['cartographier-methode','identifier-controles'], deliverable:'Carte de processus versionnée', evaluation:'Auto-évaluation puis revue expert', author:'Sophie Laurent · Lean manager', free:true, steps:['Choisir le périmètre','Observer les étapes','Identifier les décisions','Documenter les exceptions','Faire valider la carte'] },
  { slug:'concevoir-feuille-route-ia', title:'Concevoir une feuille de route IA', result:'Des initiatives priorisées selon valeur, faisabilité, risques et dépendances.', duration:'4 h', level:'Avancé', sector:'entrepreneuriat', skillSlugs:['prioriser-initiatives-ia','gouverner-humain-ia'], deliverable:'Feuille de route argumentée sur 90 jours', evaluation:'Soutenance devant un expert', author:'Unitalk Academy', steps:['Clarifier les objectifs','Inventorier les opportunités','Évaluer les risques','Prioriser les initiatives','Construire le plan 90 jours'] },
  { slug:'analyser-couts-projet', title:'Analyser les coûts d’un projet', result:'Une analyse de coûts transparente avec hypothèses et scénarios.', duration:'2 h 30', level:'Intermédiaire', sector:'finance', skillSlugs:['construire-modele-couts','documenter-recommandation'], deliverable:'Modèle de coûts et note de décision', evaluation:'Cas pratique évalué', author:'Nadia Morel · DAF', steps:['Lister les postes','Documenter les hypothèses','Construire les scénarios','Tester les sensibilités','Préparer la décision'] },
  { slug:'preparer-politique-validation-ia', title:'Préparer une politique de validation humain-IA', result:'Des règles claires sur les actions autorisées, validées ou interdites.', duration:'2 h', level:'Avancé', sector:'rh', skillSlugs:['gouverner-humain-ia','identifier-controles'], deliverable:'Matrice droits, validations et escalades', evaluation:'Revue croisée RH et opérationnelle', author:'Unitalk Academy', steps:['Identifier les rôles','Classer les actions','Définir les validations','Préparer les escalades','Versionner la politique'] },
]

export const SKILLS: LearningSkill[] = [
  { slug:'concevoir-methode-veille', title:'Concevoir une méthode de veille', outcome:'Définir un périmètre, une cadence et une grille d’analyse reproductible.', sector:'marketing', level:'Intermédiaire', missionSlugs:['construire-veille-concurrentielle'], evidence:'Une grille appliquée à trois concurrents', evaluation:'Validée par Unitalk Academy selon la grille Veille v2', author:'Claire Martin', version:'2.0' },
  { slug:'verifier-sources', title:'Vérifier et citer ses sources', outcome:'Évaluer la fraîcheur, l’origine et le niveau de confiance d’une information.', sector:'marketing', level:'Découverte', missionSlugs:['construire-veille-concurrentielle'], evidence:'Journal de sources commenté', evaluation:'Revue par pair', author:'Unitalk Academy', version:'1.3' },
  { slug:'qualifier-cible-commerciale', title:'Qualifier une cible commerciale', outcome:'Transformer une intention commerciale en critères explicites et vérifiables.', sector:'commerce', level:'Intermédiaire', missionSlugs:['preparer-campagne-prospection'], evidence:'Grille de qualification expliquée', evaluation:'Cas pratique', author:'Marc Renard', version:'1.2' },
  { slug:'documenter-recommandation', title:'Documenter une recommandation', outcome:'Présenter les raisons, sources, réserves et validations d’une recommandation.', sector:'finance', level:'Intermédiaire', missionSlugs:['preparer-campagne-prospection','analyser-couts-projet'], evidence:'Note argumentée et sourcée', evaluation:'Revue expert', author:'Unitalk Academy', version:'2.1' },
  { slug:'cartographier-methode', title:'Cartographier une méthode de travail', outcome:'Rendre visibles les étapes, outils, décisions et exceptions.', sector:'industrie', level:'Découverte', missionSlugs:['cartographier-processus'], evidence:'Carte de processus validée', evaluation:'Revue terrain', author:'Sophie Laurent', version:'1.4' },
  { slug:'identifier-controles', title:'Identifier les contrôles humains', outcome:'Distinguer les actions autonomes, soumises à validation ou interdites.', sector:'rh', level:'Avancé', missionSlugs:['cartographier-processus','preparer-politique-validation-ia'], evidence:'Matrice de contrôle', evaluation:'Revue croisée', author:'Unitalk Academy', version:'1.1' },
  { slug:'prioriser-initiatives-ia', title:'Prioriser des initiatives IA', outcome:'Comparer valeur, faisabilité, risques et dépendances.', sector:'entrepreneuriat', level:'Avancé', missionSlugs:['concevoir-feuille-route-ia'], evidence:'Portefeuille priorisé', evaluation:'Soutenance', author:'Unitalk Academy', version:'1.0' },
  { slug:'gouverner-humain-ia', title:'Gouverner une équipe humain-IA', outcome:'Définir rôles, droits, décisions et mécanismes d’escalade.', sector:'rh', level:'Avancé', missionSlugs:['concevoir-feuille-route-ia','preparer-politique-validation-ia'], evidence:'Politique de gouvernance', evaluation:'Jury expert', author:'Unitalk Academy', version:'1.0' },
  { slug:'construire-modele-couts', title:'Construire un modèle de coûts', outcome:'Documenter hypothèses, scénarios et sensibilités pour éclairer une décision.', sector:'finance', level:'Intermédiaire', missionSlugs:['analyser-couts-projet'], evidence:'Modèle chiffré commenté', evaluation:'Cas pratique', author:'Nadia Morel', version:'1.2' },
]

export const PATHS: LearningPath[] = [
  { slug:'entreprendre-avec-ia', title:'Entreprendre avec l’IA', promise:'Concevoir une entreprise augmentée sans automatiser aveuglément.', sector:'entrepreneuriat', missionSlugs:['concevoir-feuille-route-ia','preparer-politique-validation-ia'], skillSlugs:['prioriser-initiatives-ia','gouverner-humain-ia'], audience:'Dirigeants, indépendants et entrepreneurs', format:'6 semaines · Hybride' },
  { slug:'co-createur-ia', title:'Devenir Co-créateur IA', promise:'Créer, tester et commercialiser des Collaborateurs IA à partir de missions réelles.', sector:'entrepreneuriat', missionSlugs:['cartographier-processus','preparer-politique-validation-ia'], skillSlugs:['cartographier-methode','identifier-controles','gouverner-humain-ia'], audience:'Experts, formateurs, consultants et intégrateurs', format:'8 semaines · Pratique accompagnée' },
  { slug:'responsable-marketing-augmente', title:'Responsable marketing augmenté', promise:'Observer, positionner, créer et mesurer avec une gouvernance IA claire.', sector:'marketing', missionSlugs:['construire-veille-concurrentielle','preparer-campagne-prospection'], skillSlugs:['concevoir-methode-veille','verifier-sources','documenter-recommandation'], audience:'Professionnels du marketing', format:'5 semaines · Missions' },
  { slug:'commercial-augmente', title:'Commercial augmenté par l’IA', promise:'Construire une pratique commerciale ciblée, documentée et responsable.', sector:'commerce', missionSlugs:['preparer-campagne-prospection'], skillSlugs:['qualifier-cible-commerciale','documenter-recommandation'], audience:'Commerciaux et responsables de vente', format:'4 semaines · Missions' },
]

export const academyNetwork = (id:string) => NETWORKS.find(item => item.id === id)
export const academyMission = (slug:string) => MISSIONS.find(item => item.slug === slug)
export const academySkill = (slug:string) => SKILLS.find(item => item.slug === slug)
export const academyPath = (slug:string) => PATHS.find(item => item.slug === slug)
