import type { Bilingual } from '@/lib/collaborators-catalog'

export type AiModel = {
  key: string
  title: string
  maker: string
  description: Bilingual
  modalities: readonly string[]
  capabilities?: readonly string[]
  type: 'proprietaire' | 'poids-ouverts' | 'open-source'
}

export const AI_MODELS: readonly AiModel[] = [
  { key: 'openai-gpt-5-6-luna', title: 'GPT-5.6 Luna', maker: 'OpenAI', description: { fr: 'Modèle rapide pour le chat, la classification, le raisonnement courant et les agents à fort volume.', en: 'Fast model for chat, classification, everyday reasoning and high-volume agents.' }, modalities: ['texte', 'multimodal'], capabilities: ['raisonnement'], type: 'proprietaire' },
  { key: 'openai-gpt-5-6-sol', title: 'GPT-5.6 Sol', maker: 'OpenAI', description: { fr: 'Modèle avancé pour le raisonnement complexe, le code et les workflows agentiques longs.', en: 'Advanced model for complex reasoning, coding and long-running agentic workflows.' }, modalities: ['texte', 'multimodal'], capabilities: ['raisonnement', 'code'], type: 'proprietaire' },
  { key: 'openai-gpt-5-6-terra', title: 'GPT-5.6 Terra', maker: 'OpenAI', description: { fr: 'Modèle équilibré pour le raisonnement, le code et les tâches professionnelles polyvalentes.', en: 'Balanced model for reasoning, coding and versatile professional tasks.' }, modalities: ['texte', 'multimodal'], capabilities: ['raisonnement', 'code'], type: 'proprietaire' },
  { key: 'openai-gpt-5-mini', title: 'GPT-5 mini', maker: 'OpenAI', description: { fr: 'Modèle compact et rapide pour les tâches courantes, le code et les agents à volume élevé.', en: 'Compact, fast model for everyday tasks, coding and high-volume agents.' }, modalities: ['texte', 'multimodal'], capabilities: ['raisonnement', 'code'], type: 'proprietaire' },
  { key: 'openai-gpt-5-nano', title: 'GPT-5 nano', maker: 'OpenAI', description: { fr: 'Modèle très léger pour la classification, l’extraction et les traitements simples à grande échelle.', en: 'Lightweight model for classification, extraction and simple processing at scale.' }, modalities: ['texte', 'multimodal'], capabilities: ['raisonnement'], type: 'proprietaire' },
  { key: 'anthropic-claude-opus-5', title: 'Claude Opus 5', maker: 'Anthropic', description: { fr: 'Modèle haut de gamme pour le raisonnement exigeant, le code et les agents de longue durée.', en: 'Premium model for demanding reasoning, coding and long-running agents.' }, modalities: ['texte', 'multimodal'], capabilities: ['raisonnement', 'code'], type: 'proprietaire' },
  { key: 'anthropic-claude-sonnet-5', title: 'Claude Sonnet 5', maker: 'Anthropic', description: { fr: 'Modèle polyvalent pour le code, les agents et le travail professionnel quotidien.', en: 'Versatile model for coding, agents and everyday professional work.' }, modalities: ['texte', 'multimodal'], capabilities: ['raisonnement', 'code'], type: 'proprietaire' },
  { key: 'anthropic-claude-fable-5', title: 'Claude Fable 5', maker: 'Anthropic', description: { fr: 'Modèle créatif pour la rédaction, la narration et la production de contenus nuancés.', en: 'Creative model for writing, storytelling and nuanced content production.' }, modalities: ['texte', 'multimodal'], capabilities: ['raisonnement', 'code'], type: 'proprietaire' },
  { key: 'anthropic-claude-haiku-4-5', title: 'Claude Haiku 4.5', maker: 'Anthropic', description: { fr: 'Modèle rapide et économique pour les tâches courantes, l’extraction et les agents à fort volume.', en: 'Fast, cost-efficient model for everyday tasks, extraction and high-volume agents.' }, modalities: ['texte', 'multimodal'], capabilities: ['raisonnement', 'code'], type: 'proprietaire' },
  { key: 'google-gemini-3-6-flash', title: 'Gemini 3.6 Flash', maker: 'Google', description: { fr: 'Modèle multimodal rapide pour le code, les agents et la compréhension de contenus.', en: 'Fast multimodal model for coding, agents and content understanding.' }, modalities: ['texte', 'multimodal'], capabilities: ['raisonnement', 'code'], type: 'proprietaire' },
  { key: 'openai-o3-deep-research', title: 'o3 Deep Research', maker: 'OpenAI', description: { fr: 'Modèle de recherche approfondie pour trouver, analyser et synthétiser de nombreuses sources dans un rapport documenté.', en: 'Deep research model for finding, analyzing and synthesizing many sources into a documented report.' }, modalities: ['texte'], capabilities: ['raisonnement', 'deep-research'], type: 'proprietaire' },
  { key: 'openai-o4-mini-deep-research', title: 'o4-mini Deep Research', maker: 'OpenAI', description: { fr: 'Modèle de recherche approfondie optimisé pour produire efficacement des analyses sourcées à partir du web et de documents.', en: 'Deep research model optimized to efficiently produce sourced analysis from the web and documents.' }, modalities: ['texte'], capabilities: ['raisonnement', 'deep-research'], type: 'proprietaire' },
  { key: 'google-veo-3-1', title: 'Veo 3.1', maker: 'Google', description: { fr: 'Modèle avancé de génération vidéo pour produire des séquences détaillées à partir d’instructions.', en: 'Advanced video generation model for producing detailed sequences from prompts.' }, modalities: ['video'], type: 'proprietaire' },
  { key: 'google-veo-3-1-fast', title: 'Veo 3.1 Fast', maker: 'Google', description: { fr: 'Version rapide de Veo pour générer et tester des séquences vidéo avec une latence réduite.', en: 'Fast Veo variant for generating and testing video sequences with lower latency.' }, modalities: ['video'], type: 'proprietaire' },
  { key: 'google-veo-3-1-lite', title: 'Veo 3.1 Lite', maker: 'Google', description: { fr: 'Version légère de Veo pour les créations vidéo courantes et les volumes importants.', en: 'Lightweight Veo variant for everyday video creation and high-volume workloads.' }, modalities: ['video'], type: 'proprietaire' },
  { key: 'kling-ai-video-3-0', title: 'Kling 3.0', maker: 'Kling AI', description: { fr: 'Modèle vidéo cinématographique générant des séquences multi-plans jusqu’à 15 secondes, avec audio natif, synchronisation labiale et cohérence des personnages.', en: 'Cinematic video model generating multi-shot sequences up to 15 seconds, with native audio, lip sync and consistent characters.' }, modalities: ['video', 'audio'], type: 'proprietaire' },
  { key: 'alibaba-wan-3-0', title: 'Wan 3.0', maker: 'Alibaba', description: { fr: 'Modèle créatif de génération vidéo à partir de texte ou d’images, conçu pour produire et transformer des contenus visuels variés.', en: 'Creative model for generating video from text or images, designed to produce and transform varied visual content.' }, modalities: ['video', 'multimodal'], type: 'proprietaire' },
  { key: 'bytedance-seedance-2-0', title: 'Seedance 2.0', maker: 'ByteDance', description: { fr: 'Modèle vidéo multimodal générant des séquences jusqu’à 15 secondes en 1080p à partir d’images, de vidéos et d’audio, avec édition et extension précises.', en: 'Multimodal video model generating sequences up to 15 seconds in 1080p from images, video and audio, with precise editing and extension.' }, modalities: ['video', 'audio', 'multimodal'], type: 'proprietaire' },
  { key: 'google-gemini-nano-banana-2', title: 'Nano Banana 2', maker: 'Google Gemini', description: { fr: 'Modèle de génération et d’édition d’images pour créer rapidement des visuels cohérents à partir d’instructions.', en: 'Image generation and editing model for quickly creating consistent visuals from prompts.' }, modalities: ['image'], type: 'proprietaire' },
  { key: 'google-gemini-nano-banana-pro', title: 'Nano Banana Pro', maker: 'Google Gemini', description: { fr: 'Modèle avancé de création et de retouche d’images pour les compositions détaillées et les usages professionnels.', en: 'Advanced image creation and editing model for detailed compositions and professional workflows.' }, modalities: ['image'], type: 'proprietaire' },
  { key: 'bytedance-seedream-5-0', title: 'Seedream 5.0', maker: 'ByteDance', description: { fr: 'Modèle de génération d’images conçu pour produire des visuels précis dans une grande variété de styles.', en: 'Image generation model designed to produce precise visuals across a wide range of styles.' }, modalities: ['image'], type: 'proprietaire' },
  { key: 'openai-chatgpt-images-2-0', title: 'ChatGPT Images 2.0', maker: 'OpenAI', description: { fr: 'Modèle de génération et d’édition d’images intégré aux workflows conversationnels et créatifs.', en: 'Image generation and editing model integrated into conversational and creative workflows.' }, modalities: ['image'], type: 'proprietaire' },
  { key: 'black-forest-flux-2-pro', title: 'Flux 2 Pro', maker: 'Black Forest', description: { fr: 'Modèle professionnel de génération d’images pour les rendus détaillés et les exigences de production.', en: 'Professional image generation model for detailed rendering and production requirements.' }, modalities: ['image'], type: 'proprietaire' },
  { key: 'black-forest-flux-2-flex', title: 'Flux 2 Flex', maker: 'Black Forest', description: { fr: 'Modèle flexible de génération et d’édition d’images pour adapter rapidement styles et compositions.', en: 'Flexible image generation and editing model for rapidly adapting styles and compositions.' }, modalities: ['image'], type: 'proprietaire' },
  { key: 'xai-grok-imagine', title: 'Grok Imagine', maker: 'xAI', description: { fr: 'Modèle de création d’images pour transformer des instructions en visuels et explorer rapidement plusieurs directions.', en: 'Image creation model for turning prompts into visuals and rapidly exploring multiple directions.' }, modalities: ['image'], type: 'proprietaire' },
  { key: 'ideogram-v4', title: 'Ideogram v4', maker: 'Ideogram', description: { fr: 'Modèle de génération d’images particulièrement adapté aux visuels intégrant du texte, aux affiches et aux compositions graphiques.', en: 'Image generation model particularly suited to visuals with text, posters and graphic compositions.' }, modalities: ['image'], type: 'proprietaire' },
  { key: 'deepseek-v4-flash', title: 'DeepSeek V4 Flash', maker: 'DeepSeek', description: { fr: 'Modèle ouvert efficace pour le code, le raisonnement et les agents.', en: 'Open model for efficient coding, reasoning and agent workflows.' }, modalities: ['texte'], capabilities: ['raisonnement', 'code'], type: 'open-source' },
  { key: 'tencent-hy3', title: 'Hy3', maker: 'Tencent', description: { fr: 'Modèle ouvert conçu pour le raisonnement, les agents et les usages en production.', en: 'Open model designed for reasoning, agents and production workloads.' }, modalities: ['texte'], capabilities: ['raisonnement'], type: 'open-source' },
  { key: 'z-ai-glm-5-3', title: 'GLM 5.3', maker: 'Z.ai', description: { fr: 'Modèle ouvert pour le raisonnement long, les agents et l’ingénierie logicielle.', en: 'Open model for long-form reasoning, agents and software engineering.' }, modalities: ['texte'], capabilities: ['raisonnement', 'code'], type: 'poids-ouverts' },
  { key: 'deepseek-v4-pro', title: 'DeepSeek V4 Pro', maker: 'DeepSeek', description: { fr: 'Modèle ouvert orienté raisonnement avancé, programmation et agents complexes.', en: 'Open model focused on advanced reasoning, programming and complex agents.' }, modalities: ['texte'], capabilities: ['raisonnement', 'code'], type: 'open-source' },
  { key: 'moonshot-kimi-k3', title: 'Kimi K3', maker: 'Moonshot AI', description: { fr: 'Modèle multimodal ouvert à contexte long pour le code, le raisonnement et le travail intellectuel complexe.', en: 'Open long-context multimodal model for coding, reasoning and complex knowledge work.' }, modalities: ['texte', 'multimodal'], capabilities: ['raisonnement', 'code'], type: 'poids-ouverts' },
  { key: 'flux-2-klein-4b', title: 'FLUX.2 [klein] 4B', maker: 'Black Forest Labs', description: { fr: 'Modèle open source rapide de génération et d’édition d’images, exécutable sur du matériel grand public.', en: 'Fast open-source image generation and editing model that runs on consumer hardware.' }, modalities: ['image'], type: 'open-source' },
  { key: 'mistral-large-3', title: 'Mistral Large 3', maker: 'Mistral AI', description: { fr: 'Modèle ouvert multimodal pour le raisonnement, le code et les tâches professionnelles complexes.', en: 'Open multimodal model for reasoning, coding and complex professional tasks.' }, modalities: ['texte', 'multimodal'], capabilities: ['raisonnement', 'code'], type: 'open-source' },
  { key: 'minimax-m3', title: 'MiniMax M3', maker: 'MiniMax', description: { fr: 'Modèle multimodal à contexte long pour le code, les agents et les raisonnements en plusieurs étapes.', en: 'Long-context multimodal model for coding, agents and multi-step reasoning.' }, modalities: ['texte', 'multimodal'], capabilities: ['raisonnement', 'code'], type: 'poids-ouverts' },
  { key: 'voxtral-stt', title: 'Voxtral Small 24B STT', maker: 'Mistral AI', description: { fr: 'Modèle de transcription et de compréhension audio multilingue.', en: 'Model for multilingual transcription and audio understanding.' }, modalities: ['audio'], capabilities: ['transcription'], type: 'open-source' },
  { key: 'gladia-transcription', title: 'Gladia', maker: 'Gladia', description: { fr: 'Modèle de transcription multilingue pour convertir rapidement la parole en texte exploitable.', en: 'Multilingual transcription model for quickly converting speech into usable text.' }, modalities: ['audio'], capabilities: ['transcription'], type: 'proprietaire' },
  { key: 'openai-whisper', title: 'Whisper', maker: 'OpenAI', description: { fr: 'Modèle de reconnaissance vocale multilingue pour la transcription et la traduction audio.', en: 'Multilingual speech recognition model for audio transcription and translation.' }, modalities: ['audio'], capabilities: ['transcription'], type: 'open-source' },
  { key: 'openai-gpt-4o-transcribe', title: 'GPT-4o Transcribe', maker: 'OpenAI', description: { fr: 'Modèle de transcription avancé pour restituer avec précision des enregistrements audio variés.', en: 'Advanced transcription model for accurately rendering varied audio recordings.' }, modalities: ['audio'], capabilities: ['transcription'], type: 'proprietaire' },
  { key: 'openai-gpt-4o-mini-transcribe', title: 'GPT-4o Mini Transcribe', maker: 'OpenAI', description: { fr: 'Modèle de transcription rapide et économique pour les traitements audio à fort volume.', en: 'Fast, cost-efficient transcription model for high-volume audio processing.' }, modalities: ['audio'], capabilities: ['transcription'], type: 'proprietaire' },
  { key: 'deepgram-nova-3', title: 'Nova-3', maker: 'Deepgram', description: { fr: 'Modèle de transcription en temps réel conçu pour les conversations, réunions et flux audio professionnels.', en: 'Real-time transcription model designed for conversations, meetings and professional audio streams.' }, modalities: ['audio'], capabilities: ['transcription'], type: 'proprietaire' },
  { key: 'elevenlabs-eleven-v3', title: 'Eleven v3', maker: 'ElevenLabs', description: { fr: 'Modèle de synthèse vocale expressif prenant en charge plus de 70 langues, la narration et les dialogues à plusieurs voix.', en: 'Expressive speech synthesis model supporting more than 70 languages, narration and multi-speaker dialogue.' }, modalities: ['audio'], capabilities: ['speech'], type: 'proprietaire' },
  { key: 'openai-gpt-4o-mini-tts', title: 'GPT-4o Mini TTS', maker: 'OpenAI', description: { fr: 'Modèle de synthèse vocale rapide qui transforme du texte en parole naturelle.', en: 'Fast speech synthesis model that converts text into natural-sounding speech.' }, modalities: ['audio'], capabilities: ['speech'], type: 'proprietaire' },
  { key: 'google-gemini-2-5-flash-tts', title: 'Gemini 2.5 Flash TTS', maker: 'Google Gemini', description: { fr: 'Modèle de synthèse vocale Gemini optimisé pour produire rapidement des voix naturelles et contrôlables.', en: 'Gemini speech synthesis model optimized for fast, natural and controllable voice generation.' }, modalities: ['audio'], capabilities: ['speech'], type: 'proprietaire' },
  { key: 'google-gemini-2-5-pro-tts', title: 'Gemini 2.5 Pro TTS', maker: 'Google Gemini', description: { fr: 'Modèle de synthèse vocale Gemini avancé pour les narrations et dialogues nécessitant un contrôle expressif précis.', en: 'Advanced Gemini speech synthesis model for narration and dialogue requiring precise expressive control.' }, modalities: ['audio'], capabilities: ['speech'], type: 'proprietaire' },
  { key: 'openai-audio', title: 'GPT Audio', maker: 'OpenAI', description: { fr: 'Modèle multimodal conversationnel acceptant du texte et de l’audio, et produisant des réponses textuelles ou audio.', en: 'Conversational multimodal model accepting text and audio and producing text or audio responses.' }, modalities: ['audio', 'multimodal'], type: 'proprietaire' },
]

export function getAiModelByKey(key: string): AiModel | undefined {
  return AI_MODELS.find(model => model.key === key)
}
