export type BlogBlock =
  | { type: 'p'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'h3'; text: string }
  | { type: 'ul'; items: string[] }
  | { type: 'ol'; items: string[] }
  | { type: 'quote'; text: string }

export type BlogArticle = {
  slug: string
  image: string
  category: { fr: string; en: string }
  readingTime: { fr: string; en: string }
  date: { fr: string; en: string }
  title: { fr: string; en: string }
  excerpt: { fr: string; en: string }
  /** Standalone two-line editorial lead written for the index cards (no truncation). */
  cardLead: { fr: string; en: string }
  body: { fr: BlogBlock[]; en: BlogBlock[] }
  seoTitle?: { fr: string; en: string }
  canonical?: string
  missionSlug?: string
  specializedLayout?: 'prospects-guide'
}

export const BLOG_ARTICLES: BlogArticle[] = [
  {
    slug: 'trouver-prospects-qualifies-ia',
    image: '',
    category: { fr: 'Prospection B2B', en: 'B2B prospecting' },
    readingTime: { fr: '', en: '' },
    date: { fr: '', en: '' },
    seoTitle: {
      fr: 'Trouver des prospects qualifiés avec l’IA | Unitalk',
      en: 'Find qualified prospects with AI | Unitalk',
    },
    canonical: '/blog/trouver-prospects-qualifies-ia',
    missionSlug: 'trouver-de-nouveaux-clients',
    specializedLayout: 'prospects-guide',
    title: {
      fr: 'Trouver des prospects qualifiés : une longue liste ne vaut pas une bonne sélection',
      en: 'Finding qualified prospects: a long list is no substitute for a good selection',
    },
    excerpt: {
      fr: 'Découvrez comment un Collaborateur IA recherche, enrichit et présélectionne des prospects pendant que votre équipe conserve les critères et la validation finale.',
      en: 'See how an AI Collaborator researches, enriches and preselects prospects while your team retains the criteria and final approval.',
    },
    cardLead: {
      fr: 'Comment confier la recherche de prospects sans automatiser un mauvais ciblage.',
      en: 'How to delegate prospect research without automating poor targeting.',
    },
    body: { fr: [], en: [] },
  },
  {
    slug: 'identite-collaborateur',
    image: '/blog/identite-collaborateur.png',
    category: { fr: 'Doctrine', en: 'Doctrine' },
    readingTime: { fr: '7 min de lecture', en: '7 min read' },
    date: { fr: 'Juillet 2026', en: 'July 2026' },
    title: {
      fr: 'Une IA sans identité ne devient jamais un collaborateur.',
      en: 'An AI with no identity never becomes a collaborator.',
    },
    excerpt: {
      fr: 'Une IA peut répondre avec intelligence et accomplir une tâche. Sans identité persistante, la relation reste celle d’un utilisateur avec un logiciel.',
      en: 'An AI can answer intelligently and complete a task. Without a persistent identity, the relationship stays that of a user with software.',
    },
    cardLead: {
      fr: 'Identité, rôle, mémoire : les fondations qui inscrivent un Collaborateur IA dans la durée.',
      en: 'Identity, role, memory: the foundations that make an AI Collaborator last.',
    },
    body: {
      fr: [
        { type: 'p', text: 'Une IA peut répondre avec intelligence, utiliser des outils et accomplir une tâche. Pourtant, si chaque échange recommence avec une instance anonyme, la relation reste celle d’un utilisateur avec un logiciel.' },
        { type: 'p', text: 'Un collaborateur existe dans la durée. Il a une identité, un rôle, des responsabilités et une histoire au sein de l’organisation. Cette continuité change profondément ce qu’une entreprise peut lui confier.' },
        { type: 'h2', text: 'Un nom ne suffit pas' },
        { type: 'p', text: 'Donner un prénom à une IA ne lui confère pas une identité. Ce n’est qu’un signe visible.' },
        { type: 'p', text: 'Son identité repose sur des éléments plus concrets :' },
        { type: 'ul', items: [
          'l’organisation à laquelle elle appartient ;',
          'les équipes avec lesquelles elle travaille ;',
          'les profils métier qu’elle exerce ;',
          'les missions qui lui sont confiées ;',
          'les compétences qu’elle maîtrise ;',
          'les outils qu’elle peut utiliser ;',
          'les règles qu’elle doit respecter ;',
          'les décisions qui restent humaines.',
        ] },
        { type: 'p', text: 'Ces éléments forment une continuité opérationnelle. Ils permettent de savoir qui agit, dans quel cadre et avec quelle légitimité.' },
        { type: 'p', text: 'Une IA commerciale et une IA chargée du support peuvent utiliser le même modèle de langage. Elles n’ont pourtant ni les mêmes responsabilités, ni les mêmes accès, ni les mêmes critères de réussite.' },
        { type: 'p', text: 'L’identité donne un sens organisationnel à leur intelligence.' },
        { type: 'h2', text: 'L’identité rend le travail attribuable' },
        { type: 'p', text: 'Lorsqu’une IA accomplit une mission, l’entreprise doit pouvoir répondre à des questions simples :' },
        { type: 'ul', items: [
          'Qui a réalisé le travail ?',
          'Quelle mission lui avait été confiée ?',
          'Quelles informations a-t-elle utilisées ?',
          'Quelles règles a-t-elle suivies ?',
          'Qui a validé le résultat ?',
          'Quelle version de ses compétences était active ?',
        ] },
        { type: 'p', text: 'Sans identité persistante, ces réponses se dispersent entre des conversations, des journaux techniques et des configurations temporaires.' },
        { type: 'p', text: 'Avec une identité, chaque action peut être rattachée à un Collaborateur IA identifiable. Son activité devient lisible. Ses responsabilités peuvent être définies. Ses résultats peuvent être évalués dans le temps.' },
        { type: 'p', text: 'L’entreprise ne supervise plus une succession de réponses anonymes. Elle suit le travail d’un acteur clairement situé dans son organisation.' },
        { type: 'h2', text: 'L’identité permet de progresser' },
        { type: 'p', text: 'Un collaborateur progresse parce que son expérience s’accumule.' },
        { type: 'p', text: 'Il comprend mieux les attentes de l’entreprise. Il apprend son vocabulaire, ses méthodes et ses règles. Il perfectionne son travail à partir des corrections reçues. Une mission réussie prépare la suivante.' },
        { type: 'p', text: 'Une IA sans continuité peut produire un excellent résultat puis tout oublier. La qualité obtenue reste attachée à un échange, à un prompt ou à la personne qui sait le reproduire.' },
        { type: 'p', text: 'Une identité persistante permet de rattacher l’expérience au bon Collaborateur IA :' },
        { type: 'ul', items: [
          'les préférences apprises restent disponibles ;',
          'les méthodes validées enrichissent ses compétences ;',
          'les erreurs corrigées modifient son cadre de travail ;',
          'les nouvelles responsabilités s’ajoutent à son parcours ;',
          'les droits évoluent avec son rôle.',
        ] },
        { type: 'p', text: 'Le Collaborateur IA de demain prolonge alors celui qui a travaillé aujourd’hui.' },
        { type: 'h2', text: 'Une même identité peut exercer plusieurs profils métier' },
        { type: 'p', text: 'Une identité persistante ne doit pas enfermer l’IA dans une fiche de poste figée.' },
        { type: 'p', text: 'Comme un humain, un Collaborateur IA peut mobiliser plusieurs profils métier. Il peut, par exemple, exercer des responsabilités en marketing, contribuer aux ventes et préparer certains travaux de direction. Ses profils déterminent les contextes dans lesquels il intervient. Ses compétences définissent ce qu’il sait réellement accomplir.' },
        { type: 'p', text: 'Cette distinction est importante.' },
        { type: 'p', text: 'Le profil métier situe le Collaborateur IA dans l’organisation. La compétence décrit une capacité précise, testée et réutilisable. La mission lui donne un objectif concret.' },
        { type: 'p', text: 'L’identité relie ces trois dimensions. Elle permet au Collaborateur IA d’évoluer sans perdre son histoire.' },
        { type: 'h2', text: 'L’identité structure la confiance' },
        { type: 'p', text: 'La confiance dans une IA ne vient pas seulement de la qualité de ses réponses. Elle repose aussi sur la prévisibilité de son comportement.' },
        { type: 'p', text: 'L’entreprise doit savoir :' },
        { type: 'ul', items: [
          'ce qu’elle peut lui déléguer ;',
          'dans quelles limites elle agit ;',
          'quelles données elle peut consulter ;',
          'quels outils elle peut utiliser ;',
          'à quel moment elle doit demander une validation ;',
          'qui peut modifier ses responsabilités.',
        ] },
        { type: 'p', text: 'Une identité stable rend ces règles applicables dans la durée. Les autorisations sont attribuées à un Collaborateur IA précis. Les validations sont enregistrées. Les responsabilités restent compréhensibles, même lorsque les modèles ou les outils utilisés évoluent.' },
        { type: 'p', text: 'Le modèle fournit une intelligence. L’identité lui donne une place et un cadre.' },
        { type: 'h2', text: 'L’entreprise doit pouvoir gouverner cette identité' },
        { type: 'p', text: 'L’identité d’un Collaborateur IA appartient à l’organisation qui l’emploie.' },
        { type: 'p', text: 'Elle ne devrait pas dépendre d’un modèle particulier, d’une conversation isolée ou d’un fournisseur unique. Une entreprise doit pouvoir changer de modèle, ajouter un outil ou déplacer son infrastructure tout en conservant :' },
        { type: 'ul', items: [
          'le rôle du Collaborateur IA ;',
          'ses compétences ;',
          'sa mémoire autorisée ;',
          'son historique de travail ;',
          'ses règles ;',
          'ses droits ;',
          'ses relations avec les équipes.',
        ] },
        { type: 'p', text: 'Cette indépendance protège la continuité du travail. Le moteur peut évoluer. L’identité demeure.' },
        { type: 'h2', text: 'Une nouvelle forme de continuité dans l’entreprise' },
        { type: 'p', text: 'Les entreprises savent déjà gérer l’identité de leurs collaborateurs humains. Elles définissent des postes, attribuent des accès, organisent les responsabilités et conservent une trace du travail accompli.' },
        { type: 'p', text: 'L’arrivée des Collaborateurs IA étend cette discipline.' },
        { type: 'p', text: 'Une IA identifiée peut recevoir des missions, développer des compétences et progresser avec l’organisation. Son travail devient attribuable. Son autonomie peut être gouvernée. Son expérience peut être conservée.' },
        { type: 'p', text: 'C’est cette continuité qui lui permet de prendre place dans l’entreprise.' },
      ],
      en: [
        { type: 'p', text: 'An AI can answer intelligently, use tools and complete a task. Yet if every exchange starts over with an anonymous instance, the relationship stays that of a user with software.' },
        { type: 'p', text: 'A collaborator exists over time. It has an identity, a role, responsibilities and a history within the organization. That continuity deeply changes what a company can entrust to it.' },
        { type: 'h2', text: 'A name is not enough' },
        { type: 'p', text: 'Giving an AI a first name does not grant it an identity. It is only a visible sign.' },
        { type: 'p', text: 'Its identity rests on more concrete elements:' },
        { type: 'ul', items: [
          'the organization it belongs to;',
          'the teams it works with;',
          'the job profiles it performs;',
          'the missions entrusted to it;',
          'the skills it masters;',
          'the tools it can use;',
          'the rules it must follow;',
          'the decisions that remain human.',
        ] },
        { type: 'p', text: 'These elements form an operational continuity. They make it possible to know who is acting, within what frame and with what legitimacy.' },
        { type: 'p', text: 'A sales AI and a support AI can use the same language model. Yet they do not share the same responsibilities, the same access or the same success criteria.' },
        { type: 'p', text: 'Identity gives their intelligence an organizational meaning.' },
        { type: 'h2', text: 'Identity makes the work attributable' },
        { type: 'p', text: 'When an AI completes a mission, the company must be able to answer simple questions:' },
        { type: 'ul', items: [
          'Who did the work?',
          'What mission had been entrusted to it?',
          'What information did it use?',
          'What rules did it follow?',
          'Who validated the result?',
          'Which version of its skills was active?',
        ] },
        { type: 'p', text: 'Without a persistent identity, these answers scatter across conversations, technical logs and temporary configurations.' },
        { type: 'p', text: 'With an identity, each action can be tied to an identifiable AI Collaborator. Its activity becomes legible. Its responsibilities can be defined. Its results can be assessed over time.' },
        { type: 'p', text: 'The company no longer supervises a stream of anonymous answers. It follows the work of an actor clearly located within its organization.' },
        { type: 'h2', text: 'Identity makes progress possible' },
        { type: 'p', text: 'A collaborator progresses because its experience accumulates.' },
        { type: 'p', text: 'It understands the company’s expectations better. It learns its vocabulary, its methods and its rules. It refines its work from the corrections it receives. A successful mission prepares the next one.' },
        { type: 'p', text: 'An AI without continuity can produce an excellent result and then forget everything. The quality obtained stays attached to an exchange, a prompt or the person who knows how to reproduce it.' },
        { type: 'p', text: 'A persistent identity makes it possible to tie the experience to the right AI Collaborator:' },
        { type: 'ul', items: [
          'learned preferences stay available;',
          'validated methods enrich its skills;',
          'corrected errors change its working frame;',
          'new responsibilities add to its path;',
          'rights evolve with its role.',
        ] },
        { type: 'p', text: 'Tomorrow’s AI Collaborator then extends the one that worked today.' },
        { type: 'h2', text: 'One identity can perform several job profiles' },
        { type: 'p', text: 'A persistent identity should not lock the AI into a fixed job description.' },
        { type: 'p', text: 'Like a human, an AI Collaborator can draw on several job profiles. It can, for example, hold marketing responsibilities, contribute to sales and prepare certain management work. Its profiles determine the contexts in which it operates. Its skills define what it can actually accomplish.' },
        { type: 'p', text: 'This distinction matters.' },
        { type: 'p', text: 'The job profile places the AI Collaborator within the organization. The skill describes a precise, tested and reusable capability. The mission gives it a concrete objective.' },
        { type: 'p', text: 'Identity links these three dimensions. It lets the AI Collaborator evolve without losing its history.' },
        { type: 'h2', text: 'Identity structures trust' },
        { type: 'p', text: 'Trust in an AI does not come only from the quality of its answers. It also rests on the predictability of its behavior.' },
        { type: 'p', text: 'The company must know:' },
        { type: 'ul', items: [
          'what it can delegate to it;',
          'within what limits it acts;',
          'what data it can consult;',
          'what tools it can use;',
          'when it must request a validation;',
          'who can change its responsibilities.',
        ] },
        { type: 'p', text: 'A stable identity makes these rules applicable over time. Authorizations are assigned to a specific AI Collaborator. Validations are recorded. Responsibilities remain understandable, even as the models or tools in use evolve.' },
        { type: 'p', text: 'The model provides intelligence. Identity gives it a place and a frame.' },
        { type: 'h2', text: 'The company must be able to govern this identity' },
        { type: 'p', text: 'An AI Collaborator’s identity belongs to the organization that employs it.' },
        { type: 'p', text: 'It should not depend on a particular model, an isolated conversation or a single provider. A company must be able to change model, add a tool or move its infrastructure while keeping:' },
        { type: 'ul', items: [
          'the AI Collaborator’s role;',
          'its skills;',
          'its authorized memory;',
          'its work history;',
          'its rules;',
          'its rights;',
          'its relationships with the teams.',
        ] },
        { type: 'p', text: 'This independence protects the continuity of the work. The engine can evolve. The identity remains.' },
        { type: 'h2', text: 'A new form of continuity within the company' },
        { type: 'p', text: 'Companies already know how to manage the identity of their human employees. They define positions, assign access, organize responsibilities and keep a record of the work done.' },
        { type: 'p', text: 'The arrival of AI Collaborators extends this discipline.' },
        { type: 'p', text: 'An identified AI can receive missions, develop skills and progress with the organization. Its work becomes attributable. Its autonomy can be governed. Its experience can be kept.' },
        { type: 'p', text: 'It is this continuity that lets it take its place in the company.' },
      ],
    },
  },
  {
    slug: 'resultat-vs-capacite',
    image: '/blog/resultat-vs-capacite.png',
    category: { fr: 'Méthode', en: 'Method' },
    readingTime: { fr: '8 min de lecture', en: '8 min read' },
    date: { fr: 'Juin 2026', en: 'June 2026' },
    title: {
      fr: 'Un agent produit un résultat. Un Collaborateur IA construit une capacité.',
      en: 'An agent produces a result. An AI Collaborator builds a capability.',
    },
    excerpt: {
      fr: 'Le résultat d’une mission répond à un besoin. La compétence issue de cette mission augmente durablement ce que l’entreprise sait accomplir.',
      en: 'A mission’s result meets a need. The skill drawn from that mission durably increases what the company can accomplish.',
    },
    cardLead: {
      fr: 'Comment une méthode validée devient une compétence durable, versionnée et réutilisable.',
      en: 'How a validated method becomes a durable, versioned and reusable skill.',
    },
    body: {
      fr: [
        { type: 'p', text: 'Un agent IA peut accomplir une tâche avec une efficacité remarquable. Il rassemble des informations, produit un document, appelle une application ou exécute une procédure.' },
        { type: 'p', text: 'Le résultat peut être excellent. Mais que reste-t-il après sa livraison ?' },
        { type: 'p', text: 'Souvent, la méthode disparaît avec l’exécution. Le contexte reste enfermé dans une conversation. Les corrections ne sont pas formalisées. Lorsqu’une demande similaire arrive, l’entreprise doit recommencer.' },
        { type: 'p', text: 'Un Collaborateur IA suit une autre logique. Il accomplit la mission, puis conserve ce que l’entreprise a appris en la réalisant.' },
        { type: 'h2', text: 'Le résultat répond au besoin immédiat' },
        { type: 'p', text: 'Prenons une mission simple : relancer des factures impayées.' },
        { type: 'p', text: 'Un agent générique peut recevoir une liste de factures, rédiger des messages et produire un tableau de suivi. La tâche est terminée lorsque les relances sont prêtes.' },
        { type: 'p', text: 'Ce résultat a de la valeur. Il répond au besoin du moment.' },
        { type: 'p', text: 'Mais l’entreprise a probablement apporté plusieurs corrections :' },
        { type: 'ul', items: [
          'certains clients doivent être contactés par téléphone ;',
          'les dossiers comportant un litige doivent être suspendus ;',
          'le ton dépend de l’ancienneté de la relation ;',
          'un montant élevé exige une validation ;',
          'le passage au contentieux reste une décision humaine.',
        ] },
        { type: 'p', text: 'Si ces règles restent dans la conversation, elles devront être redonnées la prochaine fois. L’entreprise a obtenu un résultat, sans acquérir la méthode qui permet de le reproduire.' },
        { type: 'h2', text: 'Une mission contient davantage que son livrable' },
        { type: 'p', text: 'Chaque mission révèle une partie du fonctionnement réel de l’entreprise.' },
        { type: 'p', text: 'Les procédures officielles ne suffisent pas toujours. Le travail dépend aussi d’arbitrages, d’exceptions et d’habitudes construites avec l’expérience. Une équipe sait qu’un client stratégique mérite une approche particulière. Elle connaît les informations qui doivent être vérifiées avant d’agir. Elle reconnaît les situations dans lesquelles une décision doit remonter.' },
        { type: 'p', text: 'Une mission confiée à un Collaborateur IA permet de rendre ce savoir explicite.' },
        { type: 'p', text: 'Le Collaborateur commence par clarifier :' },
        { type: 'ul', items: [
          'le résultat attendu ;',
          'les informations nécessaires ;',
          'les outils autorisés ;',
          'les étapes à suivre ;',
          'les exceptions connues ;',
          'les validations humaines ;',
          'les critères qui définissent un travail réussi.',
        ] },
        { type: 'p', text: 'Ce cadre sert à accomplir la mission. Il peut ensuite devenir une capacité durable.' },
        { type: 'h2', text: 'Une méthode validée devient une compétence' },
        { type: 'p', text: 'Une première exécution constitue rarement une compétence aboutie.' },
        { type: 'p', text: 'Le Collaborateur IA propose une méthode. L’équipe observe son travail, corrige ses choix et valide les étapes qui correspondent réellement au fonctionnement de l’entreprise. La méthode gagne en précision à chaque cycle.' },
        { type: 'p', text: 'Une fois éprouvée, elle peut devenir une compétence formalisée :' },
        { type: 'p', text: 'Suivre une facture impayée' },
        { type: 'ol', items: [
          'vérifier les litiges ouverts ;',
          'retrouver le dernier échange avec le client ;',
          'déterminer le niveau de relance ;',
          'préparer le message dans le ton attendu ;',
          'classer la réponse ;',
          'planifier la prochaine action ;',
          'demander une validation avant toute transmission au contentieux.',
        ] },
        { type: 'p', text: 'Cette compétence possède un propriétaire, un périmètre, une version et des limites. L’entreprise sait d’où elle vient, qui l’a validée et dans quelles situations elle peut être utilisée.' },
        { type: 'p', text: 'Le savoir-faire ne dépend plus d’un prompt conservé dans les favoris de quelqu’un.' },
        { type: 'h2', text: 'Une compétence doit pouvoir évoluer' },
        { type: 'p', text: 'Une méthode d’entreprise n’est jamais définitive.' },
        { type: 'p', text: 'Une nouvelle réglementation peut modifier la procédure. L’équipe peut adopter un nouvel outil. Un responsable peut décider qu’une validation devient obligatoire au-delà d’un certain montant. Le Collaborateur IA doit appliquer la méthode actuelle sans effacer les versions précédentes.' },
        { type: 'p', text: 'La gestion des compétences répond à ce besoin.' },
        { type: 'p', text: 'Chaque évolution peut être :' },
        { type: 'ul', items: [
          'proposée à partir du travail réel ;',
          'examinée par les personnes responsables ;',
          'testée sur un périmètre limité ;',
          'validée avant sa généralisation ;',
          'versionnée pour conserver sa traçabilité.',
        ] },
        { type: 'p', text: 'Cette discipline rapproche les compétences de l’IA du fonctionnement d’un produit interne. L’entreprise améliore progressivement sa manière de travailler.' },
        { type: 'h2', text: 'La capacité appartient à l’organisation' },
        { type: 'p', text: 'Une compétence prend toute sa valeur lorsqu’elle peut être réutilisée.' },
        { type: 'p', text: 'Elle peut rester privée à un Collaborateur IA, être partagée avec une équipe ou devenir disponible dans toute l’organisation. Un savoir-faire développé par la finance peut servir à plusieurs entités. Une méthode de qualification commerciale peut être adaptée à différents marchés. Une procédure de support peut être transmise à un nouveau Collaborateur IA.' },
        { type: 'p', text: 'Le partage doit rester gouverné. Toutes les connaissances ne sont pas destinées à circuler partout. Les accès dépendent des équipes, des données concernées et des responsabilités attribuées.' },
        { type: 'p', text: 'L’entreprise décide ce qui reste individuel, ce qui devient collectif et ce qui peut être utilisé à plus grande échelle.' },
        { type: 'h2', text: 'Le modèle devient interchangeable' },
        { type: 'p', text: 'Lorsque le savoir-faire repose sur un prompt adapté à un modèle précis, changer de technologie peut obliger l’entreprise à reconstruire son système.' },
        { type: 'p', text: 'Une compétence structurée résiste mieux à ces changements. Elle décrit le travail à accomplir, les étapes, les outils, les règles et les validations attendues. Le moteur peut alors sélectionner le modèle autorisé le plus adapté à chaque tâche.' },
        { type: 'p', text: 'Un modèle peut être meilleur pour raisonner sur un dossier complexe. Un autre peut suffire pour classer une réponse. Un modèle local peut être imposé lorsque les données exigent un niveau particulier de confidentialité.' },
        { type: 'p', text: 'La capacité reste stable pendant que les technologies évoluent.' },
        { type: 'h2', text: 'Le progrès devient cumulatif' },
        { type: 'p', text: 'Une entreprise devient plus performante lorsque ses apprentissages s’additionnent.' },
        { type: 'p', text: 'Si chaque usage de l’IA reste une expérience isolée, les équipes obtiennent une succession de gains ponctuels. Elles travaillent plus vite, mais continuent à reconstruire les mêmes méthodes.' },
        { type: 'p', text: 'Lorsque les missions enrichissent des compétences durables, le progrès change de nature :' },
        { type: 'ul', items: [
          'la première mission définit une méthode ;',
          'les suivantes l’éprouvent ;',
          'les corrections l’améliorent ;',
          'd’autres Collaborateurs IA peuvent l’utiliser ;',
          'l’organisation conserve l’expérience acquise.',
        ] },
        { type: 'p', text: 'Le résultat d’une mission répond à un besoin. La compétence issue de cette mission augmente durablement ce que l’entreprise sait accomplir.' },
      ],
      en: [
        { type: 'p', text: 'An AI agent can complete a task with remarkable efficiency. It gathers information, produces a document, calls an application or runs a procedure.' },
        { type: 'p', text: 'The result may be excellent. But what remains after it is delivered?' },
        { type: 'p', text: 'Often, the method disappears with the execution. The context stays locked in a conversation. The corrections are not formalized. When a similar request arrives, the company has to start over.' },
        { type: 'p', text: 'An AI Collaborator follows a different logic. It completes the mission, then keeps what the company learned in doing it.' },
        { type: 'h2', text: 'The result meets the immediate need' },
        { type: 'p', text: 'Take a simple mission: chasing unpaid invoices.' },
        { type: 'p', text: 'A generic agent can receive a list of invoices, draft messages and produce a tracking table. The task is done once the reminders are ready.' },
        { type: 'p', text: 'This result has value. It meets the need of the moment.' },
        { type: 'p', text: 'But the company has probably made several corrections:' },
        { type: 'ul', items: [
          'some clients must be contacted by phone;',
          'files with an open dispute must be suspended;',
          'the tone depends on the age of the relationship;',
          'a high amount requires a validation;',
          'moving to litigation remains a human decision.',
        ] },
        { type: 'p', text: 'If these rules stay in the conversation, they will have to be given again next time. The company obtained a result without acquiring the method that lets it reproduce it.' },
        { type: 'h2', text: 'A mission contains more than its deliverable' },
        { type: 'p', text: 'Every mission reveals part of how the company really works.' },
        { type: 'p', text: 'Official procedures are not always enough. The work also depends on trade-offs, exceptions and habits built with experience. A team knows that a strategic client deserves a particular approach. It knows which information must be checked before acting. It recognizes the situations where a decision must be escalated.' },
        { type: 'p', text: 'A mission entrusted to an AI Collaborator makes it possible to make this knowledge explicit.' },
        { type: 'p', text: 'The Collaborator starts by clarifying:' },
        { type: 'ul', items: [
          'the expected result;',
          'the necessary information;',
          'the authorized tools;',
          'the steps to follow;',
          'the known exceptions;',
          'the human validations;',
          'the criteria that define successful work.',
        ] },
        { type: 'p', text: 'This frame serves to complete the mission. It can then become a durable capability.' },
        { type: 'h2', text: 'A validated method becomes a skill' },
        { type: 'p', text: 'A first execution rarely amounts to a finished skill.' },
        { type: 'p', text: 'The AI Collaborator proposes a method. The team observes its work, corrects its choices and validates the steps that truly match how the company operates. The method gains precision with each cycle.' },
        { type: 'p', text: 'Once proven, it can become a formalized skill:' },
        { type: 'p', text: 'Follow up on an unpaid invoice' },
        { type: 'ol', items: [
          'check open disputes;',
          'retrieve the last exchange with the client;',
          'determine the reminder level;',
          'prepare the message in the expected tone;',
          'file the response;',
          'schedule the next action;',
          'request a validation before any transfer to litigation.',
        ] },
        { type: 'p', text: 'This skill has an owner, a scope, a version and limits. The company knows where it comes from, who validated it and in what situations it can be used.' },
        { type: 'p', text: 'The know-how no longer depends on a prompt kept in someone’s favorites.' },
        { type: 'h2', text: 'A skill must be able to evolve' },
        { type: 'p', text: 'A company method is never final.' },
        { type: 'p', text: 'A new regulation can change the procedure. The team can adopt a new tool. A manager can decide that a validation becomes mandatory above a certain amount. The AI Collaborator must apply the current method without erasing the previous versions.' },
        { type: 'p', text: 'Skill management answers this need.' },
        { type: 'p', text: 'Each evolution can be:' },
        { type: 'ul', items: [
          'proposed from real work;',
          'reviewed by the people responsible;',
          'tested on a limited scope;',
          'validated before being generalized;',
          'versioned to keep its traceability.',
        ] },
        { type: 'p', text: 'This discipline brings the AI’s skills closer to how an internal product works. The company gradually improves the way it works.' },
        { type: 'h2', text: 'The capability belongs to the organization' },
        { type: 'p', text: 'A skill reaches its full value when it can be reused.' },
        { type: 'p', text: 'It can stay private to an AI Collaborator, be shared with a team or become available across the whole organization. Know-how developed by finance can serve several entities. A sales qualification method can be adapted to different markets. A support procedure can be passed on to a new AI Collaborator.' },
        { type: 'p', text: 'Sharing must stay governed. Not all knowledge is meant to circulate everywhere. Access depends on the teams, the data concerned and the responsibilities assigned.' },
        { type: 'p', text: 'The company decides what stays individual, what becomes collective and what can be used at a larger scale.' },
        { type: 'h2', text: 'The model becomes interchangeable' },
        { type: 'p', text: 'When the know-how rests on a prompt tuned to a specific model, changing technology can force the company to rebuild its system.' },
        { type: 'p', text: 'A structured skill resists these changes better. It describes the work to be done, the steps, the tools, the rules and the expected validations. The engine can then select the authorized model best suited to each task.' },
        { type: 'p', text: 'One model may be better at reasoning over a complex file. Another may be enough to classify a response. A local model may be required when the data demands a particular level of confidentiality.' },
        { type: 'p', text: 'The capability stays stable while the technologies evolve.' },
        { type: 'h2', text: 'Progress becomes cumulative' },
        { type: 'p', text: 'A company becomes more capable when its learnings add up.' },
        { type: 'p', text: 'If every use of AI stays an isolated experiment, teams get a succession of one-off gains. They work faster but keep rebuilding the same methods.' },
        { type: 'p', text: 'When missions enrich durable skills, progress changes nature:' },
        { type: 'ul', items: [
          'the first mission defines a method;',
          'the following ones prove it;',
          'the corrections improve it;',
          'other AI Collaborators can use it;',
          'the organization keeps the experience gained.',
        ] },
        { type: 'p', text: 'A mission’s result meets a need. The skill drawn from that mission durably increases what the company can accomplish.' },
      ],
    },
  },
  {
    slug: 'autonomie-limites',
    image: '/blog/autonomie-limites.png',
    category: { fr: 'Confiance', en: 'Trust' },
    readingTime: { fr: '7 min de lecture', en: '7 min read' },
    date: { fr: 'Mai 2026', en: 'May 2026' },
    title: {
      fr: 'L’autonomie commence par des limites claires.',
      en: 'Autonomy starts with clear boundaries.',
    },
    excerpt: {
      fr: 'Une IA utile doit pouvoir agir. Une IA digne de confiance doit aussi savoir quand s’arrêter.',
      en: 'A useful AI must be able to act. A trustworthy AI must also know when to stop.',
    },
    cardLead: {
      fr: 'Les règles et validations qui permettent à un Collaborateur IA d’agir en confiance.',
      en: 'The rules and validations that let an AI Collaborator act with confidence.',
    },
    body: {
      fr: [
        { type: 'p', text: 'Une IA utile doit pouvoir agir. Une IA digne de confiance doit aussi savoir quand s’arrêter.' },
        { type: 'p', text: 'Entre l’assistant qui attend une instruction à chaque étape et l’agent qui agit sans contrôle, il existe un cadre plus opérationnel : une autonomie définie mission par mission, avec des règles, des droits et des validations explicites.' },
        { type: 'p', text: 'Cette autonomie ne se mesure pas au nombre d’actions accomplies sans humain. Elle se mesure à la qualité du travail réalisé dans le cadre confié.' },
        { type: 'h2', text: 'Toutes les décisions n’ont pas le même poids' },
        { type: 'p', text: 'Dans une même mission, certaines actions peuvent être automatisées sans difficulté. D’autres engagent l’entreprise.' },
        { type: 'p', text: 'Un Collaborateur IA chargé des factures impayées peut :' },
        { type: 'ul', items: [
          'identifier les échéances dépassées ;',
          'vérifier l’existence d’un litige ;',
          'retrouver les échanges précédents ;',
          'préparer une relance ;',
          'classer une réponse ;',
          'proposer la prochaine action.',
        ] },
        { type: 'p', text: 'La décision de transmettre un client au contentieux appartient à un autre niveau. Elle peut avoir des conséquences commerciales, financières et juridiques. Elle doit rester entre les mains d’une personne autorisée.' },
        { type: 'p', text: 'La mission doit donc distinguer trois catégories :' },
        { type: 'ol', items: [
          'ce que le Collaborateur IA peut accomplir seul ;',
          'ce qu’il peut préparer mais qui exige une validation ;',
          'ce qui reste exclusivement humain.',
        ] },
        { type: 'p', text: 'Cette distinction évite de traiter toute la mission comme un bloc unique.' },
        { type: 'h2', text: 'Le cadre se définit avant l’action' },
        { type: 'p', text: 'Une instruction comme « occupe-toi des impayés » exprime une intention, sans fournir un cadre suffisant.' },
        { type: 'p', text: 'Avant d’agir, le Collaborateur IA doit connaître :' },
        { type: 'ul', items: [
          'le résultat attendu ;',
          'son périmètre ;',
          'les données accessibles ;',
          'les outils autorisés ;',
          'les règles à appliquer ;',
          'les situations qui exigent une validation ;',
          'la personne responsable de cette validation ;',
          'les conditions qui interrompent la mission.',
        ] },
        { type: 'p', text: 'Ce travail de cadrage ne ralentit pas l’autonomie. Il la rend possible.' },
        { type: 'p', text: 'Une fois les limites établies, le Collaborateur IA peut avancer sans solliciter l’équipe pour chaque détail. Il demande une intervention lorsque la situation sort du cadre ou lorsqu’une décision réservée aux humains se présente.' },
        { type: 'h2', text: 'Les droits doivent suivre la mission' },
        { type: 'p', text: 'Un Collaborateur IA n’a pas besoin d’accéder à toute l’entreprise pour accomplir son travail.' },
        { type: 'p', text: 'Ses autorisations doivent correspondre à ses responsabilités. Pour préparer des relances, il peut avoir besoin de consulter les factures, l’historique des échanges et certaines données du CRM. Cela ne signifie pas qu’il doit pouvoir modifier les coordonnées bancaires d’un client ou déclencher une procédure contentieuse.' },
        { type: 'p', text: 'Chaque outil devrait préciser les opérations autorisées :' },
        { type: 'ul', items: [
          'consulter ;',
          'créer un brouillon ;',
          'modifier ;',
          'envoyer ;',
          'supprimer ;',
          'engager une décision.',
        ] },
        { type: 'p', text: 'Cette granularité réduit les risques et simplifie la supervision. L’entreprise sait ce que le Collaborateur IA peut réellement faire, au lieu de se fier à une consigne générale.' },
        { type: 'h2', text: 'La validation doit faire partie du travail' },
        { type: 'p', text: 'Dans de nombreux outils, la validation humaine intervient après coup. Une personne relit une série d’actions déjà réalisées et tente d’identifier ce qui demande son attention.' },
        { type: 'p', text: 'Un bon système place la validation au moment où elle devient nécessaire.' },
        { type: 'p', text: 'Le Collaborateur IA accomplit les étapes autorisées, rassemble le contexte utile et présente une décision claire :' },
        { type: 'quote', text: 'Client Dupont, 14 800 euros. Deux relances sont restées sans réponse. Aucun litige n’est ouvert. Souhaitez-vous transmettre ce dossier au contentieux ?' },
        { type: 'p', text: 'La personne responsable peut valider, modifier ou refuser. Elle ne reprend pas toute l’analyse. Elle intervient sur le point qui engage réellement l’entreprise.' },
        { type: 'p', text: 'La validation devient alors un mécanisme de travail, plutôt qu’un contrôle ajouté à la fin.' },
        { type: 'h2', text: 'Une limite doit produire un comportement précis' },
        { type: 'p', text: 'Dire à une IA d’être prudente ne suffit pas.' },
        { type: 'p', text: 'Une limite utile doit pouvoir être appliquée. Elle associe une condition à un comportement attendu :' },
        { type: 'ul', items: [
          'si un litige est ouvert, suspendre la relance ;',
          'si le montant dépasse le seuil défini, demander une validation ;',
          'si les informations se contredisent, signaler l’incertitude ;',
          'si le client demande une remise, transmettre la demande au responsable ;',
          'si une action échoue deux fois, interrompre la procédure.',
        ] },
        { type: 'p', text: 'Ces règles permettent au Collaborateur IA de reconnaître les situations où son autonomie s’arrête. Elles rendent aussi son comportement testable.' },
        { type: 'p', text: 'L’entreprise peut vérifier qu’une compétence respecte ses limites avant de l’autoriser sur des données ou des outils réels.' },
        { type: 'h2', text: 'La confiance se construit dans l’activité' },
        { type: 'p', text: 'La confiance ne résulte pas d’une promesse générale sur la puissance ou la sécurité de l’IA. Elle se construit en observant son travail.' },
        { type: 'p', text: 'L’équipe doit pouvoir consulter :' },
        { type: 'ul', items: [
          'la mission reçue ;',
          'les étapes accomplies ;',
          'les sources utilisées ;',
          'les actions réalisées dans les outils ;',
          'les validations demandées ;',
          'les décisions prises par les humains ;',
          'les erreurs et les interruptions.',
        ] },
        { type: 'p', text: 'Cette visibilité permet d’abord une supervision étroite. À mesure que le Collaborateur IA démontre sa fiabilité, l’entreprise peut élargir son périmètre, réduire certaines validations ou lui confier de nouvelles compétences.' },
        { type: 'p', text: 'L’autonomie progresse avec l’expérience validée.' },
        { type: 'h2', text: 'Chaque compétence possède ses propres limites' },
        { type: 'p', text: 'Un Collaborateur IA peut être fiable dans une mission et novice dans une autre.' },
        { type: 'p', text: 'Sa capacité à qualifier des prospects ne l’autorise pas automatiquement à modifier une proposition commerciale. Sa maîtrise du support courant ne lui donne pas la responsabilité de répondre à une réclamation juridique.' },
        { type: 'p', text: 'L’autonomie doit donc être attachée aux compétences, et non accordée globalement à une identité.' },
        { type: 'p', text: 'Pour chaque compétence, l’entreprise définit :' },
        { type: 'ul', items: [
          'le périmètre autorisé ;',
          'les outils accessibles ;',
          'les seuils de validation ;',
          'les exceptions ;',
          'les responsables ;',
          'les critères de qualité.',
        ] },
        { type: 'p', text: 'Le même Collaborateur IA peut ainsi disposer d’une forte autonomie sur une compétence éprouvée et travailler sous supervision rapprochée lorsqu’il en développe une nouvelle.' },
        { type: 'h2', text: 'L’autonomie est une responsabilité partagée' },
        { type: 'p', text: 'Le Collaborateur IA doit respecter son cadre, signaler les incertitudes et transmettre les décisions qui dépassent ses responsabilités.' },
        { type: 'p', text: 'L’entreprise doit, de son côté, définir ce cadre, attribuer les bons droits et identifier les personnes chargées de valider. Une mission mal définie produit une autonomie mal maîtrisée, quelle que soit la qualité du modèle utilisé.' },
        { type: 'p', text: 'La confiance apparaît lorsque chacun connaît son rôle.' },
        { type: 'p', text: 'Le Collaborateur IA agit. Les humains interviennent là où leur jugement, leur responsabilité ou leur autorité sont nécessaires. Cette répartition permet d’accélérer le travail tout en gardant les décisions importantes au bon endroit.' },
      ],
      en: [
        { type: 'p', text: 'A useful AI must be able to act. A trustworthy AI must also know when to stop.' },
        { type: 'p', text: 'Between the assistant that waits for an instruction at every step and the agent that acts without control, there is a more operational frame: autonomy defined mission by mission, with explicit rules, rights and validations.' },
        { type: 'p', text: 'This autonomy is not measured by the number of actions carried out without a human. It is measured by the quality of the work done within the entrusted frame.' },
        { type: 'h2', text: 'Not all decisions carry the same weight' },
        { type: 'p', text: 'Within a single mission, some actions can be automated without difficulty. Others commit the company.' },
        { type: 'p', text: 'An AI Collaborator in charge of unpaid invoices can:' },
        { type: 'ul', items: [
          'identify overdue deadlines;',
          'check whether a dispute exists;',
          'retrieve previous exchanges;',
          'prepare a reminder;',
          'file a response;',
          'propose the next action.',
        ] },
        { type: 'p', text: 'The decision to transfer a client to litigation belongs to another level. It can have commercial, financial and legal consequences. It must stay in the hands of an authorized person.' },
        { type: 'p', text: 'The mission must therefore distinguish three categories:' },
        { type: 'ol', items: [
          'what the AI Collaborator can accomplish alone;',
          'what it can prepare but which requires a validation;',
          'what remains exclusively human.',
        ] },
        { type: 'p', text: 'This distinction avoids treating the whole mission as a single block.' },
        { type: 'h2', text: 'The frame is defined before the action' },
        { type: 'p', text: 'An instruction like “handle the unpaid invoices” expresses an intention without providing a sufficient frame.' },
        { type: 'p', text: 'Before acting, the AI Collaborator must know:' },
        { type: 'ul', items: [
          'the expected result;',
          'its scope;',
          'the accessible data;',
          'the authorized tools;',
          'the rules to apply;',
          'the situations that require a validation;',
          'the person responsible for that validation;',
          'the conditions that interrupt the mission.',
        ] },
        { type: 'p', text: 'This framing work does not slow autonomy down. It makes it possible.' },
        { type: 'p', text: 'Once the limits are set, the AI Collaborator can move forward without asking the team about every detail. It requests an intervention when the situation falls outside the frame or when a decision reserved for humans arises.' },
        { type: 'h2', text: 'Rights must follow the mission' },
        { type: 'p', text: 'An AI Collaborator does not need access to the whole company to do its work.' },
        { type: 'p', text: 'Its authorizations must match its responsibilities. To prepare reminders, it may need to consult invoices, the history of exchanges and certain CRM data. That does not mean it should be able to change a client’s bank details or trigger a litigation procedure.' },
        { type: 'p', text: 'Each tool should specify the authorized operations:' },
        { type: 'ul', items: [
          'consult;',
          'create a draft;',
          'edit;',
          'send;',
          'delete;',
          'commit to a decision.',
        ] },
        { type: 'p', text: 'This granularity reduces risk and simplifies supervision. The company knows what the AI Collaborator can really do, instead of relying on a general instruction.' },
        { type: 'h2', text: 'Validation must be part of the work' },
        { type: 'p', text: 'In many tools, human validation happens after the fact. A person reviews a series of already completed actions and tries to identify what needs their attention.' },
        { type: 'p', text: 'A good system places validation at the moment it becomes necessary.' },
        { type: 'p', text: 'The AI Collaborator carries out the authorized steps, gathers the useful context and presents a clear decision:' },
        { type: 'quote', text: 'Client Dupont, 14,800 euros. Two reminders went unanswered. No dispute is open. Do you want to transfer this file to litigation?' },
        { type: 'p', text: 'The responsible person can approve, modify or refuse. They do not redo the whole analysis. They act on the point that genuinely commits the company.' },
        { type: 'p', text: 'Validation then becomes a working mechanism rather than a control added at the end.' },
        { type: 'h2', text: 'A limit must produce a precise behavior' },
        { type: 'p', text: 'Telling an AI to be careful is not enough.' },
        { type: 'p', text: 'A useful limit must be applicable. It ties a condition to an expected behavior:' },
        { type: 'ul', items: [
          'if a dispute is open, suspend the reminder;',
          'if the amount exceeds the defined threshold, request a validation;',
          'if the information is contradictory, flag the uncertainty;',
          'if the client asks for a discount, forward the request to the manager;',
          'if an action fails twice, interrupt the procedure.',
        ] },
        { type: 'p', text: 'These rules let the AI Collaborator recognize the situations where its autonomy stops. They also make its behavior testable.' },
        { type: 'p', text: 'The company can verify that a skill respects its limits before authorizing it on real data or tools.' },
        { type: 'h2', text: 'Trust is built in the activity' },
        { type: 'p', text: 'Trust does not result from a general promise about the power or safety of the AI. It is built by observing its work.' },
        { type: 'p', text: 'The team must be able to consult:' },
        { type: 'ul', items: [
          'the mission received;',
          'the steps completed;',
          'the sources used;',
          'the actions carried out in the tools;',
          'the validations requested;',
          'the decisions made by humans;',
          'the errors and the interruptions.',
        ] },
        { type: 'p', text: 'This visibility first enables close supervision. As the AI Collaborator demonstrates its reliability, the company can widen its scope, reduce certain validations or entrust it with new skills.' },
        { type: 'p', text: 'Autonomy grows with validated experience.' },
        { type: 'h2', text: 'Each skill has its own limits' },
        { type: 'p', text: 'An AI Collaborator can be reliable in one mission and a novice in another.' },
        { type: 'p', text: 'Its ability to qualify prospects does not automatically authorize it to modify a commercial proposal. Its command of everyday support does not give it the responsibility to answer a legal complaint.' },
        { type: 'p', text: 'Autonomy must therefore be attached to skills, not granted globally to an identity.' },
        { type: 'p', text: 'For each skill, the company defines:' },
        { type: 'ul', items: [
          'the authorized scope;',
          'the accessible tools;',
          'the validation thresholds;',
          'the exceptions;',
          'the responsible people;',
          'the quality criteria.',
        ] },
        { type: 'p', text: 'The same AI Collaborator can thus hold strong autonomy on a proven skill and work under close supervision when developing a new one.' },
        { type: 'h2', text: 'Autonomy is a shared responsibility' },
        { type: 'p', text: 'The AI Collaborator must respect its frame, flag uncertainties and hand over the decisions that exceed its responsibilities.' },
        { type: 'p', text: 'The company, for its part, must define that frame, assign the right rights and identify the people in charge of validating. A poorly defined mission produces poorly controlled autonomy, whatever the quality of the model used.' },
        { type: 'p', text: 'Trust appears when everyone knows their role.' },
        { type: 'p', text: 'The AI Collaborator acts. Humans step in where their judgment, their responsibility or their authority is needed. This division speeds up the work while keeping important decisions in the right place.' },
      ],
    },
  },
]

export function getBlogArticle(slug: string): BlogArticle | undefined {
  return BLOG_ARTICLES.find((a) => a.slug === slug)
}
