export type HermesCreator = {
  name: string
  channel: string
  channelUrl: string
  videoTitle: string
  videoUrl: string
  language: 'FR' | 'EN'
  duration: string
  published: string
  avatarUrl: string
  affiliateCode: string
  angle: { fr: string; en: string }
}

export const HERMES_CREATORS: HermesCreator[] = [
  { name: 'Practical AI', channel: '@practicalai_show', channelUrl: 'https://www.youtube.com/@practicalai_show', videoTitle: 'Hermes Agent: Agents that grow with you | Episode #357', videoUrl: 'https://www.youtube.com/watch?v=UTZhvPXnmwA', language: 'EN', duration: '47 min', published: '20 mai 2026', avatarUrl: 'https://yt3.googleusercontent.com/skbRIyLeSNBEdJFFoOgQQDXXo3wv-NtIuWqeq7CXGLK5Bgv8d-ksXtE3JHkRh9z_KsjnjDjyMg=s900-c-k-c0x00ffffff-no-rj', affiliateCode: 'PRACTICALAI30', angle: { fr: 'Entretien avec Jeffrey Quesnelle, cofondateur et CTO de Nous Research, sur les agents qui apprennent et progressent.', en: 'Interview with Nous Research co-founder and CTO Jeffrey Quesnelle about agents that learn and improve.' } },
  { name: 'NetworkChuck', channel: '@NetworkChuck', channelUrl: 'https://www.youtube.com/@NetworkChuck', videoTitle: 'you need to use Hermes RIGHT NOW!! (goodbye OpenClaw!!)', videoUrl: 'https://www.youtube.com/watch?v=QQEgIo4Juxg', language: 'EN', duration: '32 min', published: '20 mai 2026', avatarUrl: 'https://yt3.googleusercontent.com/ytc/AIdro_k01-_GpvVZW8w4ULtaQaa55ls8aMf2a5dXhIe56pjMvG0=s900-c-k-c0x00ffffff-no-rj', affiliateCode: 'NETWORKCHUCK30', angle: { fr: 'Retour d’usage, déploiement sur VPS, mémoire et création d’un agent spécialisé IT.', en: 'Hands-on review covering VPS deployment, memory and an IT-specialized agent.' } },
  { name: 'Tina Huang', channel: '@TinaHuang1', channelUrl: 'https://www.youtube.com/@TinaHuang1', videoTitle: 'Hermes Agent Fundamentals In 29 Minutes', videoUrl: 'https://www.youtube.com/watch?v=5_N84t1rUU0', language: 'EN', duration: '29 min', published: '20 juillet 2026', avatarUrl: 'https://yt3.googleusercontent.com/5Eyvt8Lqdea_DD_YRQoZ1EPrROHQuhbqfZmBfiiXrqYBv1PGU2cHAWGR0QzXKp3O9NVxTtOd=s900-c-k-c0x00ffffff-no-rj', affiliateCode: 'TINAHUANG30', angle: { fr: 'Introduction structurée aux fondamentaux de Hermes Agent et à son usage comme agent personnel.', en: 'Structured introduction to Hermes Agent fundamentals and personal-agent use.' } },
  { name: 'Tech With Tim', channel: '@TechWithTim', channelUrl: 'https://www.youtube.com/@TechWithTim', videoTitle: 'Hermes Agent - Full Course & Setup Guide - For COMPLETE Beginners', videoUrl: 'https://www.youtube.com/watch?v=mTYxpIRK7xA', language: 'EN', duration: '59 min', published: '5 juin 2026', avatarUrl: 'https://yt3.googleusercontent.com/ytc/AIdro_k15oXl74WcnpdL-uVBv6IHBgAfXEEnpUiS-IoEyV1auyY=s900-c-k-c0x00ffffff-no-rj', affiliateCode: 'TECHWITHTIM30', angle: { fr: 'Cours complet pour débuter : installation, configuration, VPS et connexion aux services.', en: 'Complete beginner course covering setup, configuration, VPS and service connections.' } },
  { name: 'Greg Isenberg', channel: '@GregIsenberg', channelUrl: 'https://www.youtube.com/@GregIsenberg', videoTitle: 'Hermes Agent Desktop: Full Setup + Real Use Cases', videoUrl: 'https://www.youtube.com/watch?v=EJm8Ka-gVOc', language: 'EN', duration: '43 min', published: '6 juin 2026', avatarUrl: 'https://yt3.googleusercontent.com/5wiiTxMamM0NnCmGOt0iJ6eoVRmFLNIGF-BEiTZ_AVqaS02YIxAsB-2XY6xwLCUWQfoENG1MHKo=s900-c-k-c0x00ffffff-no-rj', affiliateCode: 'GREGISENBERG30', angle: { fr: 'Démonstration de Desktop, des compétences, tâches planifiées, sous-agents et cas d’usage.', en: 'Desktop demonstration covering skills, scheduled tasks, subagents and real use cases.' } },
  { name: 'Sharbel A.', channel: '@sharbelxyz', channelUrl: 'https://www.youtube.com/@sharbelxyz', videoTitle: 'Learn 95% of Hermes Agent in 31 Minutes', videoUrl: 'https://www.youtube.com/watch?v=Ta2wg6xPaY4', language: 'EN', duration: '31 min', published: '9 août 2026', avatarUrl: 'https://yt3.googleusercontent.com/V-dwZnPAfiA6N0vT6sXL70MQ9ine4hcocrDNwQ98_JVlBeLRaQ1JPtc0Fl1jH6DwpbXs9GCE=s900-c-k-c0x00ffffff-no-rj', affiliateCode: 'SHARBEL30', angle: { fr: 'Guide avancé : Desktop, Telegram, CLI, modèles, mémoire, outils, cron et sous-agents.', en: 'Advanced guide to Desktop, Telegram, CLI, models, memory, tools, cron and subagents.' } },
  { name: 'Nate Herk', channel: '@nateherk', channelUrl: 'https://www.youtube.com/@nateherk', videoTitle: 'Hermes Agent: Zero to Personal AI Assistant (1 Hour Course)', videoUrl: 'https://www.youtube.com/watch?v=gb5TlGw6Uks', language: 'EN', duration: '58 min', published: '9 mai 2026', avatarUrl: 'https://yt3.googleusercontent.com/rjiskq1h4EjTgsqvP_BOsnpwCdHUHKvSo00RmUraoWqDuHQN6RAUMdo1ircHs0ZcKQrrWNvukEs=s900-c-k-c0x00ffffff-no-rj', affiliateCode: 'NATEHERK30', angle: { fr: 'Formation longue pour construire, déployer et automatiser un assistant IA personnel.', en: 'Long-form course for building, deploying and automating a personal AI assistant.' } },
  { name: 'Adrian Twarog', channel: '@AdrianTwarog', channelUrl: 'https://www.youtube.com/@AdrianTwarog', videoTitle: 'Hermes Agent - Crash Course for Beginners (AI Agent)', videoUrl: 'https://www.youtube.com/watch?v=4sAmpcSOVEw', language: 'EN', duration: '22 min', published: '21 juillet 2026', avatarUrl: 'https://yt3.googleusercontent.com/vid8YE1bhiQRe_UHZg2pCk8mZ8HBw9pQt9t0wgYW5fztogTsQGF3KzmjHxVxSV2g9-j-4XPytBU=s900-c-k-c0x00ffffff-no-rj', affiliateCode: 'ADRIANTWAROG30', angle: { fr: 'Installation locale ou cloud et découverte des interfaces terminal, web et desktop.', en: 'Local or cloud setup with terminal, web and desktop interface walkthroughs.' } },
  { name: 'Shubham Sharma', channel: '@Shubham_Sharma', channelUrl: 'https://www.youtube.com/@Shubham_Sharma', videoTitle: 'Hermes Agent — Guide complet 2026', videoUrl: 'https://www.youtube.com/watch?v=TkT_B_S6wNY', language: 'FR', duration: '41 min', published: '26 juin 2026', avatarUrl: 'https://yt3.googleusercontent.com/aA_aJqi7EO-6nmocjkKHLdaW0xJ-jg0O5N3Rjtu_bmhMm9ClchDpmk7EH3agMNhKjADlxQV9_Q=s900-c-k-c0x00ffffff-no-rj', affiliateCode: 'SHUBHAM30', angle: { fr: 'Guide francophone : installation, sécurité, auto-amélioration et déploiement sur serveur.', en: 'French-language guide to setup, security, self-improvement and server deployment.' } },
  { name: 'Renaud Dékode', channel: '@RenaudDekode', channelUrl: 'https://www.youtube.com/@RenaudDekode', videoTitle: 'Hermes Agent est encore plus DINGUE : tu DOIS le tester', videoUrl: 'https://www.youtube.com/watch?v=CFmFaWLzq94', language: 'FR', duration: '1 h 09', published: '4 juillet 2026', avatarUrl: 'https://yt3.googleusercontent.com/y_i7tT6FxhByrAdX2K9omL5h6v-ueM3NS8-lwR_3TIiPTw9qh2k3tF9cxPYvmaV-78w91Fq-=s900-c-k-c0x00ffffff-no-rj', affiliateCode: 'RENAUDDEKODE30', angle: { fr: 'Présentation francophone approfondie du dashboard web et du pilotage quotidien de Hermes.', en: 'In-depth French presentation of the web dashboard and daily Hermes operation.' } },
]

export const HERMES_AFFILIATE_DISCOUNT = 0.3

export function hermesCreatorByAffiliateCode(code: string) {
  const normalized = code.trim().toUpperCase()
  return HERMES_CREATORS.find((creator) => creator.affiliateCode === normalized)
}
