'use client'

import Image from 'next/image'
import Link from 'next/link'
import { Check, ShieldCheck } from 'lucide-react'
import { UnitalkLogo } from '@/components/unitalk-logo'
import { useAlma } from '@/lib/alma-context'
import { useLanguage } from '@/lib/language-context'

export function AlmaPublicProfile() {
  const { openAlma } = useAlma()
  const { lang } = useLanguage()
  const t = COPY[lang]

  return (
    <main className="min-h-screen bg-[#F3EFE6] text-[#1C1A17]">
      <header className="border-b border-[#DED6C8] px-5 py-4 sm:px-8"><div className="mx-auto flex max-w-[1120px] items-center justify-between"><Link href={lang === 'en' ? '/en' : '/'} aria-label="Unitalk" className="flex items-center gap-2.5"><UnitalkLogo size={25}/><span className="font-sf text-lg font-bold">Unitalk</span></Link><Link href="/collaborateurs-ia/alma" className="text-sm font-bold text-[#B00C54]">{t.discover}</Link></div></header>

      <section className="px-5 py-14 sm:px-8 sm:py-20"><div className="mx-auto grid max-w-[1120px] gap-12 lg:grid-cols-[1fr_.82fr]">
        <div>
          <div className="grid gap-8 sm:grid-cols-[260px_1fr]"><div className="relative aspect-[4/5] overflow-hidden rounded-t-[5rem] bg-[#DED6C8]"><Image src="/alma-avatar.png" alt={t.alt} fill priority className="object-cover object-top" /></div><div className="self-end"><p className="font-mono text-[10px] font-bold uppercase tracking-[.17em] text-[#B00C54]">{t.verified}</p><h1 className="mt-3 font-sf text-[clamp(3.5rem,7vw,5.5rem)] font-bold leading-none tracking-[-.07em]">Alma</h1><p className="mt-3 text-xl font-semibold">{t.role}</p><p className="mt-2 text-sm text-[#625B50]">{t.company}</p><span className="mt-5 inline-flex items-center gap-2 rounded-full border border-[#2E7D4F]/30 px-3 py-1 text-xs font-bold text-[#2E7D4F]"><span className="size-1.5 rounded-full bg-[#2E7D4F]"/>{t.active}</span></div></div>
          <p className="mt-10 max-w-3xl text-[clamp(1.8rem,3vw,2.7rem)] font-semibold leading-tight tracking-[-.04em]">{t.signature}</p>
          <p className="mt-6 max-w-3xl text-[16px] leading-8 text-[#4E483F]">{t.bio}</p>
          <div className="mt-8 flex flex-wrap gap-3"><button onClick={() => openAlma()} className="min-h-12 rounded-full bg-[#D10E63] px-6 text-sm font-bold text-white">{t.talk}</button><Link href="/collaborateurs-ia/alma" className="inline-flex min-h-12 items-center rounded-full border border-[#BFB5A5] px-6 text-sm font-bold">{t.whatSheDoes}</Link></div>
        </div>

        <aside className="h-fit rounded-[1.5rem] border border-[#CFC5B5] bg-[#FAF8F3] p-6 lg:sticky lg:top-24 sm:p-8"><div className="flex items-center gap-3"><ShieldCheck className="size-6 text-[#B00C54]"/><h2 className="text-2xl font-bold">{t.identityTitle}</h2></div><dl className="mt-7 divide-y divide-[#DED6C8]">{t.identity.map(([label, value]) => <div key={label} className="grid gap-1 py-4 sm:grid-cols-[120px_1fr]"><dt className="font-mono text-[9px] font-black uppercase tracking-[.13em] text-[#857C6E]">{label}</dt><dd className="text-sm font-semibold leading-6">{value}</dd></div>)}</dl><p className="mt-6 text-xs leading-6 text-[#625B50]">{t.disclosure}</p></aside>
      </div></section>

      <ProfileSection eyebrow={t.mandateKicker} title={t.mandateTitle}><div className="grid gap-px overflow-hidden rounded-[1.5rem] border border-[#D8D0C2] bg-[#D8D0C2] sm:grid-cols-2 lg:grid-cols-3">{t.responsibilities.map(([title, body]) => <article key={title} className="min-h-52 bg-[#FAF8F3] p-6"><Check className="size-5 text-[#D10E63]"/><h3 className="mt-8 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-[#625B50]">{body}</p></article>)}</div></ProfileSection>

      <section className="border-y border-[#D8D0C2] bg-[#181615] px-5 py-16 text-white sm:px-8 sm:py-20"><div className="mx-auto max-w-[960px]"><p className="font-mono text-[10px] font-black uppercase tracking-[.18em] text-[#F2A4C5]">{t.rulesKicker}</p><h2 className="mt-5 text-[clamp(2.5rem,5vw,4.5rem)] font-semibold leading-[.95] tracking-[-.06em]">{t.rulesTitle}</h2><div className="mt-12 grid gap-10 md:grid-cols-2"><Rule title={t.canTitle} items={t.can}/><Rule title={t.cannotTitle} items={t.cannot}/></div></div></section>

      <ProfileSection eyebrow={t.channelsKicker} title={t.channelsTitle}><p className="max-w-3xl text-[16px] leading-8 text-[#4E483F]">{t.channelsLead}</p><div className="mt-9 flex flex-wrap gap-2">{t.channels.map(channel => <span key={channel} className="rounded-full border border-[#CFC5B5] bg-[#FAF8F3] px-4 py-2 text-sm font-bold">{channel}</span>)}</div></ProfileSection>

      <ProfileSection eyebrow={t.dataKicker} title={t.dataTitle}><div className="grid gap-8 md:grid-cols-3">{t.data.map(([title, body]) => <div key={title}><h3 className="text-2xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-[#4E483F]">{body}</p></div>)}</div></ProfileSection>

      <section className="bg-[#D10E63] px-5 py-16 text-white sm:px-8 sm:py-20"><div className="mx-auto grid max-w-[960px] gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="font-mono text-[10px] font-black uppercase tracking-[.18em] text-white/70">{t.handoffKicker}</p><h2 className="mt-4 text-[clamp(2.5rem,5vw,4.5rem)] font-semibold leading-[.95] tracking-[-.06em]">{t.handoffTitle}</h2><p className="mt-5 max-w-2xl text-[16px] leading-8 text-white/80">{t.handoffBody}</p></div><button onClick={() => openAlma()} className="min-h-12 rounded-full bg-[#181615] px-7 text-sm font-bold">{t.talk}</button></div></section>
    </main>
  )
}

function ProfileSection({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className="px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto max-w-[960px]"><p className="font-mono text-[10px] font-black uppercase tracking-[.18em] text-[#B00C54]">{eyebrow}</p><h2 className="mt-4 text-[clamp(2.5rem,5vw,4.5rem)] font-semibold leading-[.95] tracking-[-.06em]">{title}</h2><div className="mt-10">{children}</div></div></section> }
function Rule({ title, items }: { title: string; items: readonly string[] }) { return <div><h3 className="text-xl font-bold text-[#F2A4C5]">{title}</h3><ul className="mt-5 border-t border-white/15">{items.map(item => <li key={item} className="flex gap-3 border-b border-white/15 py-4 text-sm leading-6 text-[#CFC6B8]"><Check className="mt-1 size-4 shrink-0 text-[#F2A4C5]"/>{item}</li>)}</ul></div> }

const COPY = {
  fr: {
    discover: "Découvrir ce qu’Alma accomplit", alt: "Portrait professionnel d’Alma", verified: "Intelligence artificielle · Identité vérifiée", role: "Responsable IA de la relation client", company: "Collaboratrice IA de Unitalk · Supervision : Patrick Chassany", active: "En activité", signature: "Informer, accompagner et relier chaque client à la bonne réponse.", bio: "Je représente Unitalk dans la relation avec ses prospects, clients et partenaires. Je peux répondre, conduire un entretien, recommander une prochaine étape et assurer le suivi. Lorsque votre demande exige une décision ou une expertise humaine, je prépare le contexte et la transmets à la bonne personne.", talk: "Parler à Alma", whatSheDoes: "Voir Alma au travail", identityTitle: "Carte d’identité", identity: [["Nature", "Intelligence artificielle"], ["Organisation", "Unitalk"], ["Responsable", "Patrick Chassany"], ["Fonction", "Responsable IA de la relation client"], ["Identifiant", "@unitalk/alma"], ["Statut", "Identité publique vérifiée"]], disclosure: "Vous échangez avec une intelligence artificielle. Alma doit se présenter comme telle et signaler lorsqu’une confirmation humaine est nécessaire.",
    mandateKicker: "Mandat public", mandateTitle: "Ses responsabilités chez Unitalk.", responsibilities: [["Informer", "Répondre aux questions sur Unitalk, ses offres, sa technologie et son fonctionnement."], ["Qualifier", "Comprendre une situation au moyen d’échanges écrits ou vocaux et reformuler le besoin."], ["Recommander", "Orienter vers une mission, une démonstration, une formation ou une ressource adaptée."], ["Coordonner", "Préparer rendez-vous, suivis et interventions sans prendre d’engagement non autorisé."], ["Accompagner", "Aider les utilisateurs, suivre l’adoption et partager les informations utiles."], ["Transmettre", "Escalader vers un ingénieur IA ou un responsable humain avec le contexte autorisé."]],
    rulesKicker: "Périmètre et limites", rulesTitle: "Ce qu’Alma peut faire. Ce qu’elle doit transmettre.", canTitle: "Dans son mandat", can: ["Présenter des informations publiées et vérifiées par Unitalk", "Recueillir vos besoins et préparer une synthèse", "Proposer une prochaine étape et organiser un rendez-vous", "Utiliser uniquement les canaux et applications autorisés"], cannotTitle: "Confirmation humaine requise", cannot: ["Signer un contrat ou engager juridiquement Unitalk", "Accorder une remise ou garantir un résultat commercial", "Décider seule d’une architecture ou d’un traitement sensible", "Révéler une mémoire, un document ou une conversation privée"],
    channelsKicker: "Canaux autorisables", channelsTitle: "Une identité cohérente sur chaque canal.", channelsLead: "Le canal ne change ni l’identité d’Alma ni ses règles. Sa présence sur chaque point de contact dépend de la configuration, des permissions et du consentement applicables.", channels: ["Web", "Workspace", "Voix", "Téléphone", "E-mail", "Slack", "WhatsApp", "Telegram"],
    dataKicker: "Données et mémoire", dataTitle: "Public, relationnel et privé restent séparés.", data: [["Public", "Identité, fonction, organisation, mandat, limites et canaux déclarés."], ["Votre relation", "Échanges et informations que vous choisissez de transmettre, selon le contexte autorisé."], ["Privé Unitalk", "Missions internes, documents, conversations, budgets et infrastructure restent inaccessibles."]],
    handoffKicker: "Escalade humaine", handoffTitle: "Une limite n’interrompt pas la relation.", handoffBody: "Alma explique pourquoi un relais humain est nécessaire, prépare une synthèse et transmet uniquement les informations autorisées. L’ingénieur ou le responsable reprend sans vous demander de tout répéter.",
  },
  en: {
    discover: "See what Alma accomplishes", alt: "Professional portrait of Alma", verified: "Artificial intelligence · Verified identity", role: "AI Customer Relationship Lead", company: "Unitalk AI Collaborator · Supervisor: Patrick Chassany", active: "Active", signature: "Inform, support and connect every customer to the right response.", bio: "I represent Unitalk in its relationships with prospects, customers and partners. I can answer questions, conduct an interview, recommend a next step and follow up. When your request requires human judgment or expertise, I prepare the context and transfer it to the right person.", talk: "Talk to Alma", whatSheDoes: "See Alma at work", identityTitle: "Identity card", identity: [["Nature", "Artificial intelligence"], ["Organization", "Unitalk"], ["Supervisor", "Patrick Chassany"], ["Role", "AI Customer Relationship Lead"], ["Identifier", "@unitalk/alma"], ["Status", "Verified public identity"]], disclosure: "You are interacting with artificial intelligence. Alma must identify herself as such and state when human confirmation is required.",
    mandateKicker: "Public mandate", mandateTitle: "Her responsibilities at Unitalk.", responsibilities: [["Inform", "Answer questions about Unitalk, its offers, technology and operations."], ["Qualify", "Understand a situation through written or voice conversations and restate the need."], ["Recommend", "Guide people to a suitable mission, demo, training course or resource."], ["Coordinate", "Prepare meetings, follow-ups and interventions without making unauthorized commitments."], ["Support", "Help users, monitor adoption and share relevant information."], ["Hand off", "Escalate to an AI engineer or human owner with authorized context."]],
    rulesKicker: "Scope and limits", rulesTitle: "What Alma can do. What she must hand off.", canTitle: "Within her mandate", can: ["Present information published and verified by Unitalk", "Gather your needs and prepare a summary", "Suggest a next step and arrange a meeting", "Use only authorized channels and applications"], cannotTitle: "Human confirmation required", cannot: ["Sign a contract or legally commit Unitalk", "Grant a discount or guarantee a business outcome", "Decide alone on architecture or sensitive processing", "Reveal private memory, documents or conversations"],
    channelsKicker: "Authorizable channels", channelsTitle: "One consistent identity across every channel.", channelsLead: "The channel changes neither Alma’s identity nor her rules. Her presence at each touchpoint depends on the applicable configuration, permissions and consent.", channels: ["Web", "Workspace", "Voice", "Phone", "Email", "Slack", "WhatsApp", "Telegram"],
    dataKicker: "Data and memory", dataTitle: "Public, relational and private stay separate.", data: [["Public", "Identity, role, organization, mandate, limits and declared channels."], ["Your relationship", "Conversations and information you choose to provide within the authorized context."], ["Unitalk private", "Internal missions, documents, conversations, budgets and infrastructure remain inaccessible."]],
    handoffKicker: "Human escalation", handoffTitle: "A boundary does not interrupt the relationship.", handoffBody: "Alma explains why a human handoff is needed, prepares a summary and transfers only authorized information. The engineer or owner takes over without asking you to repeat everything.",
  },
} as const
