'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { useAlma } from '@/lib/alma-context'

export function AlmaFinalContent() {
  const { openAlma } = useAlma()
  const [daily, setDaily] = useState(0)
  const [demoStep, setDemoStep] = useState(0)
  const [paused, setPaused] = useState(false)

  return (
    <main className="bg-[#F3EFE6] text-[#1C1A17]">
      <section className="px-5 pb-14 pt-24 sm:px-8 sm:pt-28"><div className="mx-auto grid max-w-[1180px] items-center gap-10 lg:grid-cols-[1.05fr_0.95fr]">
        <div><p className="font-mono text-[11px] font-bold uppercase tracking-[0.18em] text-[#B00C54]">Une seule identité IA. Plusieurs responsabilités.</p><h1 className="mt-4 font-sf text-[42px] font-bold leading-[0.98] tracking-[-0.05em] sm:text-[64px]">Alma coordonne les missions.<span className="block text-[#6E665A]">Ajoutez les expertises dont votre organisation a besoin.</span></h1><p className="mt-5 text-lg font-semibold">Coordinatrice de missions · Profil inclus</p><p className="mt-5 max-w-2xl text-[17px] leading-8 text-[#4E483F]">Alma clarifie votre besoin, sélectionne la mission et prépare les collaborateurs humains et IA nécessaires pour l’accomplir.</p><div className="mt-7 flex flex-wrap gap-4"><Link href="/collaborateurs-ia/alma/store" className="bg-[#D10E63] px-6 py-3 text-sm font-bold text-white">Équiper Alma</Link><button onClick={openAlma} className="border border-[#1C1A17] px-6 py-3 text-sm font-bold">Parler à Alma</button></div><p className="mt-5 font-sf text-xl font-bold">Son identité reste. Ses responsabilités évoluent.</p></div>
        <div className="grid gap-5 sm:grid-cols-[1fr_0.9fr]"><div className="relative aspect-[4/5] overflow-hidden bg-[#DED6C8]"><Image src="/alma-avatar.png" alt="Portrait professionnel d’Alma" fill priority className="object-cover" /></div><dl className="self-end border-y border-[#1C1A17]/15 text-sm"><Fact l="Alma" v="Collaboratrice IA · Unitalk" /><Fact l="Inclus" v="Coordinatrice de missions" /><Fact l="À ajouter" v="Transformation IA · Adoption IA · Compétences spécialisées" /><Fact l="Créée et supervisée par" v="Patrick Chassany" /><Fact l="Nature" v="Intelligence artificielle" /><Fact l="Statut" v="En activité" /></dl></div>
      </div></section>

      <Section eyebrow="Ce qu’Alma fait" title="Dites-lui ce que vous voulez accomplir."><p>Alma ne vous demande pas de configurer un agent. Elle mène l’entretien, comprend votre méthode et transforme votre objectif en mission prête à être confiée.</p><div className="mt-10 min-h-[440px] border border-[#1C1A17]/15 bg-[#FAF8F3] p-6 sm:p-9"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#B00C54]">Démonstration</p><p className="mt-4 font-bold">Sophie · Responsable relation client</p><blockquote className="mt-3 text-xl">« Je veux que chaque réclamation soit suivie jusqu’à sa résolution. »</blockquote><div className="mt-7"><p className="font-sf text-2xl font-bold">{DEMO[Math.min(demoStep, 3)].q}</p><p className="mt-3 text-[#4E483F]">{DEMO[Math.min(demoStep, 3)].a}</p>{demoStep === 3 && <div className="mt-7 border-t border-[#1C1A17]/15 pt-6"><p className="font-mono text-[10px] uppercase text-[#B00C54]">Mission préparée</p><h3 className="mt-2 font-sf text-2xl font-bold">Suivre chaque réclamation jusqu’à sa résolution</h3><p className="mt-3">Résultat, prochaine action, date de relance · Vérification après chaque appel · Validation humaine avant tout geste commercial.</p></div>}</div><div className="mt-8 flex gap-3"><button disabled={demoStep === 0} onClick={() => setDemoStep((s) => s - 1)} className="border border-[#DED6C8] px-4 py-2 text-sm disabled:opacity-30">Retour</button><button onClick={() => setDemoStep((s) => Math.min(3, s + 1))} className="bg-[#151310] px-4 py-2 text-sm text-white">Avancer</button><button onClick={() => setPaused(!paused)} className="ml-auto text-sm underline">{paused ? 'Reprendre' : 'Pause'}</button></div></div><h3 className="mt-8 font-sf text-[34px] font-bold">Un besoin exprimé. Une mission prête.</h3></Section>

      <section className="bg-[#151310] px-5 py-20 text-[#FAF8F3] sm:px-8"><div className="mx-auto max-w-[1080px]"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#F2A4C5]">Faire progresser avant de créer</p><h2 className="mt-4 max-w-4xl font-sf text-[38px] font-bold leading-tight sm:text-[54px]">Alma cherche d’abord qui peut accomplir la mission.</h2><p className="mt-5 max-w-3xl text-[#BDB7AC]">Elle examine les Collaborateurs IA déjà présents. Une nouvelle identité n’est recommandée que lorsqu’elle est réellement nécessaire.</p><div className="mt-10 grid gap-8 border-y border-white/15 py-8 lg:grid-cols-3"><DarkBlock title="Lucas · Collaborateur IA">Il connaît les clients, dispose des accès nécessaires et peut assumer cette responsabilité.</DarkBlock><DarkBlock title="Responsable relation client">Un profil métier durable pour suivre les réclamations et coordonner leur résolution.</DarkBlock><DarkBlock title="Compétences et droits">Qualifier, analyser, planifier, synthétiser, suivre et demander une validation humaine.</DarkBlock></div><h3 className="mt-10 font-sf text-[34px] font-bold">Le même Lucas. Une nouvelle responsabilité.</h3><p className="mt-5 text-[#BDB7AC]">Une mission définit le travail. Alma crée les profils métier et les compétences nécessaires pour l’accomplir.</p><button onClick={openAlma} className="mt-7 bg-[#D10E63] px-6 py-3 text-sm font-bold">Confier une mission à Alma</button></div></section>

      <Section eyebrow="Au quotidien" title="Elle accueille. Elle répond. Elle forme. Elle recommande."><div className="mt-9 flex flex-wrap gap-3">{DAILY.map((item, i) => <button key={item.title} onClick={() => setDaily(i)} className={`border px-4 py-2 text-sm font-bold ${daily === i ? 'border-[#D10E63] bg-[#D10E63] text-white' : 'border-[#DED6C8]'}`}>{item.title}</button>)}</div><div className="mt-8 min-h-[250px] border-y border-[#1C1A17]/15 py-8"><h3 className="font-sf text-3xl font-bold">Elle {DAILY[daily].title.toLowerCase()}</h3><p className="mt-4 max-w-3xl leading-8 text-[#4E483F]">{DAILY[daily].body}</p><p className="mt-5 font-semibold">{DAILY[daily].proof}</p></div></Section>

      <section className="bg-[#EAE4D9] px-5 py-20 sm:px-8"><div className="mx-auto max-w-[1080px]"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#B00C54]">Licences et crédits</p><h2 className="mt-4 font-sf text-[40px] font-bold sm:text-[56px]">Alma peut vous aider à aller plus loin.</h2><p className="mt-5 max-w-3xl text-[17px] leading-8 text-[#4E483F]">La licence donne accès. Les crédits financent l’usage et l’exécution.</p><div className="mt-10 grid border-y border-[#1C1A17]/15 sm:grid-cols-3"><Credit title="Crédits d’assistance">Pour cadrer, configurer et résoudre un besoin avec Alma ou un intervenant autorisé.</Credit><Credit title="Crédits IA">Pour augmenter la capacité des modèles de texte, image, audio et vidéo.</Credit><Credit title="Crédits de mission">Pour activer une mission Unitalk à périmètre et livrable définis.</Credit></div><button onClick={openAlma} className="mt-7 bg-[#151310] px-6 py-3 text-sm font-bold text-white">Acheter des crédits avec Alma →</button><p className="mt-4 text-sm text-[#6E665A]">Aucun produit Stripe n’est encore configuré sur ce site. Alma présente uniquement les produits officiels lorsqu’ils sont disponibles ; aucun achat n’est déclenché automatiquement.</p></div></section>

      <section className="bg-[#25211D] px-5 py-20 text-[#FAF8F3] sm:px-8"><div className="mx-auto max-w-[1080px]"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#F2A4C5]">Le réseau d’experts Unitalk</p><h2 className="mt-4 max-w-4xl font-sf text-[38px] font-bold leading-tight sm:text-[54px]">Lorsqu’une expertise humaine devient nécessaire, Alma trouve la bonne personne.</h2><div className="mt-10 grid gap-10 lg:grid-cols-2"><DarkBlock title="Alma prépare l’intervention">Objectif, résultat attendu, vérifications, données autorisées, durée, droits temporaires et budget validé.</DarkBlock><DarkBlock title="L’entreprise garde le contrôle">Identité, qualifications, périmètre, accès, coût et expiration sont visibles avant validation.</DarkBlock></div><p className="mt-10 font-sf text-2xl font-bold">L’expert intervient. Le Collaborateur IA progresse. L’entreprise conserve le savoir-faire.</p><Link href="/experts" className="mt-7 inline-flex bg-[#FAF8F3] px-6 py-3 text-sm font-bold text-[#151310]">Découvrir les experts Unitalk →</Link><p className="mt-3 text-xs text-[#BDB7AC]">Réseau en cours de déploiement · Interventions actuellement sur sélection</p></div></section>

      <section className="px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-[1080px] gap-10 lg:grid-cols-[0.7fr_1.3fr]"><Image src="/alma-avatar.png" alt="Alma" width={360} height={360} className="w-full max-w-sm" /><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#B00C54]">Parler à Alma</p><h2 className="mt-4 font-sf text-[42px] font-bold">Par quoi voulez-vous commencer ?</h2><textarea rows={3} placeholder="Décrivez une mission, une difficulté ou une question…" className="mt-7 w-full border border-[#DED6C8] bg-white p-4" /><div className="mt-4 flex flex-wrap gap-2">{['Préparer une mission','Faire évoluer un Collaborateur IA','Former mon équipe','Réduire notre consommation','Mobiliser un expert'].map(x=><span key={x} className="border border-[#DED6C8] px-3 py-1.5 text-xs">{x}</span>)}</div><button onClick={openAlma} className="mt-5 bg-[#D10E63] px-6 py-3 text-sm font-bold text-white">Parler à Alma</button><p className="mt-4 text-sm text-[#6E665A]">Alma conseille les entreprises au nom de Unitalk. Elle ne devient pas leur Collaboratrice IA : elle les aide à préparer les leurs.</p><p className="mt-7 font-sf text-2xl font-bold">Aider les humains et l’IA à travailler ensemble.</p></div></div></section>
    </main>
  )
}

const DEMO = [{q:'Quel résultat doit être visible ?',a:'Un état clair, une prochaine action et une date de relance.'},{q:'Quelle méthode doit être respectée ?',a:'Vérifier le dossier après chaque appel et relancer sous trois jours.'},{q:'Quelles décisions doivent rester humaines ?',a:'Tout geste commercial doit être validé.'},{q:'Mission prête',a:'Le besoin est maintenant structuré.'}]
const DAILY = [{title:'Accueille',body:'Alma accompagne l’arrivée des humains et des Collaborateurs IA, présente le Workspace et guide les premières missions.',proof:'Chacun sait quoi confier, à qui et dans quel cadre.'},{title:'Répond',body:'Elle constitue le premier point de contact Unitalk pour les questions techniques, commerciales, fonctionnelles, tarifaires et liées aux missions.',proof:'Une réponse immédiate, avec le bon contexte.'},{title:'Forme',body:'Elle accompagne les nouveaux utilisateurs, les métiers et les parcours de Unitalk Academy selon les droits définis.',proof:'La connaissance devient disponible au moment où l’équipe en a besoin.'},{title:'Recommande',body:'Elle filtre les évolutions des modèles, des applications, de Unitalk et de Hermes, puis les confronte aux missions de l’entreprise.',proof:'Alma ne vous informe pas davantage. Elle vous aide à mieux décider.'}]
function Section({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <section className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-[1080px]"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#B00C54]">{eyebrow}</p><h2 className="mt-4 max-w-4xl font-sf text-[38px] font-bold leading-tight sm:text-[54px]">{title}</h2><div className="mt-5 text-[17px] leading-8 text-[#4E483F]">{children}</div></div></section>}
function Fact({l,v}:{l:string;v:string}){return <div className="border-b border-[#1C1A17]/15 py-3"><dt className="font-mono text-[9px] uppercase text-[#6E665A]">{l}</dt><dd className="mt-1 font-semibold">{v}</dd></div>}
function DarkBlock({title,children}:{title:string;children:React.ReactNode}){return <div><h3 className="font-sf text-2xl font-bold">{title}</h3><p className="mt-3 leading-7 text-[#BDB7AC]">{children}</p></div>}
function Credit({title,children}:{title:string;children:React.ReactNode}){return <div className="border-b border-[#1C1A17]/15 py-6 sm:border-b-0 sm:border-r sm:px-6 sm:first:pl-0 sm:last:border-r-0"><h3 className="font-sf text-2xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-[#4E483F]">{children}</p></div>}
