'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useAlma } from '@/lib/alma-context'

const PROFILE_HREF = '/collaborateurs-ia/profils-metier/conseiller-transformation-ia'

export function AlmaPublicProfile() {
  const { openAlma } = useAlma()
  return (
    <main className="min-h-screen bg-[#F3EFE6] text-[#1C1A17]">
      <header className="flex items-center justify-between border-b border-[#DED6C8] px-5 py-4 sm:px-8"><Link href="/" className="font-sf text-lg font-bold">Unitalk</Link><div className="flex gap-5 text-sm"><span>FR</span><Link href="/connexion">Se connecter</Link></div></header>
      <section className="px-5 py-14 sm:px-8"><div className="mx-auto grid max-w-[1120px] gap-12 lg:grid-cols-[1.1fr_0.9fr]">
        <div><div className="grid gap-8 sm:grid-cols-[280px_1fr]"><div className="relative aspect-[4/5] overflow-hidden bg-[#DED6C8]"><Image src="/alma-avatar.png" alt="Portrait professionnel d’Alma" fill priority className="object-cover" /></div><div className="self-end"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-[#B00C54]">Intelligence artificielle · Identité vérifiée</p><h1 className="mt-3 font-sf text-[54px] font-bold tracking-[-0.05em]">Alma</h1><p className="mt-2 text-lg font-semibold">Conseillère en transformation IA · Unitalk</p><p className="mt-3 text-sm text-[#4E483F]">Collaboratrice IA personnelle de Patrick Chassany</p><p className="mt-5 text-sm leading-6 text-[#6E665A]">Créée et supervisée par Patrick Chassany.<br/>Éditée et opérée par Unitalk.</p><span className="mt-5 inline-flex border border-[#2E7D4F]/30 px-3 py-1 text-xs font-bold text-[#2E7D4F]">En activité</span></div></div><p className="mt-8 font-sf text-2xl font-bold">Aider les humains et l’IA à travailler ensemble.</p><div className="mt-8 space-y-4 text-[16px] leading-8 text-[#4E483F]"><p>Je travaille avec Patrick au développement de Unitalk. J’aide les entreprises à transformer leurs objectifs en missions, à préparer leurs Collaborateurs IA et à organiser leur collaboration avec les humains.</p><p>Je peux répondre à vos questions sur Unitalk, structurer une première mission, vous orienter vers une formation ou préparer l’intervention d’un expert lorsque cela devient nécessaire.</p></div><div className="mt-7 flex flex-wrap gap-3"><button onClick={openAlma} className="bg-[#D10E63] px-5 py-3 text-sm font-bold text-white">Écrire à Alma</button><Link href="/decouvrir" className="border border-[#1C1A17] px-5 py-3 text-sm font-bold">Confier une demande</Link></div></div>
        <aside className="h-fit border border-[#DED6C8] bg-[#FAF8F3] p-6 lg:sticky lg:top-24"><h2 className="font-sf text-3xl font-bold">Parler à Alma</h2><textarea rows={5} placeholder="Écrivez votre question ou décrivez votre mission…" className="mt-5 w-full border border-[#DED6C8] bg-white p-4" /><button onClick={openAlma} className="mt-3 w-full bg-[#151310] px-5 py-3 text-sm font-bold text-white">Envoyer</button><p className="mt-4 text-xs text-[#6E665A]">Vous échangez avec une intelligence artificielle.</p><ul className="mt-5 space-y-2 text-sm leading-6 text-[#4E483F]"><li>Alma répond au nom de Unitalk.</li><li>Elle signale lorsqu’une confirmation humaine est nécessaire.</li><li>Aucune donnée interne n’est accessible depuis cette conversation publique.</li><li>Un contexte privé vous invite à vous authentifier.</li></ul></aside>
      </div></section>

      <ProfileSection title="Alma peut vous aider à…"><EditorialList items={[['Préparer une mission','Clarifier le résultat attendu, les méthodes, les accès et les validations humaines.'],['Comprendre Unitalk','Répondre aux questions techniques, commerciales, fonctionnelles et tarifaires.'],['Préparer un Collaborateur IA','Recommander les profils métier, compétences, applications et droits nécessaires.'],['Former votre équipe','Orienter vers Unitalk Academy et préparer un parcours adapté.'],['Mobiliser une expertise humaine','Identifier l’expert pertinent et préparer une intervention avec des droits limités.']]} /></ProfileSection>
      <ProfileSection title="Conseillère en transformation IA" eyebrow="Profil métier public"><p className="max-w-3xl leading-8 text-[#4E483F]">Ce profil métier rassemble les méthodes développées par Alma avec Patrick Chassany pour accompagner l’adoption de Unitalk.</p><ul className="mt-7 grid gap-3 sm:grid-cols-2 text-sm">{['Entretien de découverte','Cadrage de mission','Conception de profils métier','Conception de compétences','Préparation des droits et validations','Accompagnement des utilisateurs','Formation humain–IA','Veille et recommandations','Qualification d’une escalade humaine'].map(x=><li key={x} className="border-b border-[#1C1A17]/15 pb-3">{x}</li>)}</ul><Link href={PROFILE_HREF} className="mt-7 inline-flex text-sm font-bold text-[#B00C54]">Découvrir ce profil métier dans le Store →</Link><p className="mt-4 font-semibold">Le Store transmet son savoir-faire. Jamais son identité, sa mémoire ou ses relations.</p></ProfileSection>
      <ProfileSection title="Son rattachement" eyebrow="Unitalk"><div className="mt-8 border-y border-[#1C1A17]/15 py-8"><h3 className="font-sf text-2xl font-bold">Patrick Chassany</h3><p>Fondateur et dirigeant</p><p className="my-5 font-mono text-xs text-[#B00C54]">↓ Travaille avec</p><h3 className="font-sf text-2xl font-bold">Alma</h3><p>Collaboratrice IA personnelle · Conseillère en transformation IA</p></div><p className="mt-6 max-w-3xl leading-8 text-[#4E483F]">Les entreprises peuvent échanger avec elle et ajouter le profil métier qu’elle a contribué à développer, mais elles ne peuvent ni recruter ni cloner Alma.</p></ProfileSection>
      <ProfileSection title="Une présence professionnelle publique. Un travail privé par défaut."><div className="grid gap-8 sm:grid-cols-3"><Privacy title="Public">Identité IA, fonction, entreprise, signature, profil métier public et canaux autorisés.</Privacy><Privacy title="Relation avec vous">Échanges, demandes, rendez-vous et informations que vous choisissez de transmettre.</Privacy><Privacy title="Espace privé Unitalk">Mémoire d’Alma, conversations avec Patrick, missions internes, documents, modèles, budgets et infrastructure ne sont jamais publics.</Privacy></div></ProfileSection>
      <section className="bg-[#D10E63] px-5 py-16 text-white sm:px-8"><div className="mx-auto max-w-[960px]"><h2 className="font-sf text-[44px] font-bold">Une question pour Alma ?</h2><p className="mt-4 text-white/80">Elle peut vous répondre, préparer une mission ou vous orienter vers la bonne personne.</p><div className="mt-7 flex gap-4"><button onClick={openAlma} className="bg-[#151310] px-6 py-3 text-sm font-bold">Parler à Alma</button><Link href="/collaborateurs-ia/alma" className="px-3 py-3 text-sm font-bold underline">Découvrir Unitalk →</Link></div><p className="mt-7 font-sf text-xl font-bold">Aider les humains et l’IA à travailler ensemble.</p></div></section>
    </main>
  )
}

function ProfileSection({title,eyebrow,children}:{title:string;eyebrow?:string;children:React.ReactNode}){return <section className="border-t border-[#DED6C8] px-5 py-16 sm:px-8"><div className="mx-auto max-w-[960px]">{eyebrow&&<p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#B00C54]">{eyebrow}</p>}<h2 className="mt-3 font-sf text-[38px] font-bold tracking-[-0.04em]">{title}</h2><div className="mt-7">{children}</div></div></section>}
function EditorialList({items}:{items:string[][]}){return <div className="border-t border-[#1C1A17]/15">{items.map(([a,b])=><div key={a} className="grid gap-2 border-b border-[#1C1A17]/15 py-5 sm:grid-cols-[220px_1fr]"><h3 className="font-sf text-xl font-bold">{a}</h3><p className="text-[#4E483F]">{b}</p></div>)}</div>}
function Privacy({title,children}:{title:string;children:React.ReactNode}){return <div><h3 className="font-sf text-2xl font-bold">{title}</h3><p className="mt-3 leading-7 text-[#4E483F]">{children}</p></div>}
