import Link from 'next/link'
import { ArrowRight } from 'lucide-react'
import { STORE_ITEMS, storeItemHref, type StoreItem } from '@/lib/store-catalog'

export function AlmaStoreContent() {
  const items = STORE_ITEMS.filter(item => item.compatibleWith?.includes('alma'))
  const foundation = items.find(item => item.slug === 'coordinatrice-missions')
  const extensions = items.filter(item => item.slug !== 'coordinatrice-missions')
  return <main className="bg-[#F3EFE6] px-5 pb-20 pt-28 font-sf text-[#1C1A17] sm:px-8"><div className="editorial-shell"><p className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#B00C54]">Store Alma</p><h1 className="hero-heading mt-5">Équipez Alma.<br/>Son identité reste.</h1><p className="mt-6 max-w-3xl text-[17px] leading-8 text-[#4E483F]">La coordination des missions est incluse avec votre Organisation. Ajoutez uniquement les profils et compétences spécialisés dont vos missions ont besoin.</p>{foundation&&<section className="mt-12"><h2 className="text-[32px] font-semibold tracking-[-.035em] sm:text-[40px]">Profil socle inclus</h2><StoreCard item={foundation} included/></section>}<section className="mt-14"><h2 className="text-[32px] font-semibold tracking-[-.035em] sm:text-[40px]">Extensions compatibles</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#6E665A]">Disponibilité et conditions confirmées avant installation. Aucun prix n’est affiché tant qu’il n’est pas publié.</p><div className="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{extensions.map(item=><StoreCard key={item.slug} item={item}/>)}</div></section><section className="mt-14 rounded-[18px] border border-[#DED6C8] bg-[#FAF8F3] p-7"><h2 className="text-2xl font-semibold">Installation gouvernée</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-[#4E483F]">Les données, applications, droits, validations et éventuelles conditions commerciales sont confirmés avant installation. Une extension n’est jamais activée silencieusement.</p></section></div></main>
}
function StoreCard({item,included=false}:{item:StoreItem;included?:boolean}){const feminine=item.labels?.feminine?.fr;const title=feminine??item.name.fr;return <Link href={storeItemHref(item)} className="group mt-6 flex min-h-[190px] flex-col rounded-[18px] border border-[#DED6C8] bg-[#FAF8F3] p-5 outline-none transition-colors hover:border-[#D10E63]/40 focus-visible:ring-2 focus-visible:ring-[#D10E63]"><p className={`font-mono text-[9px] font-bold uppercase tracking-[.14em] ${included?'text-[#257A43]':'text-[#B00C54]'}`}>{included?'Inclus avec la Licence Organisation':'Extension disponible selon configuration'}</p><h3 className="mt-4 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#4E483F]">{item.description.fr}</p><span className="mt-auto inline-flex items-center gap-2 pt-5 text-sm font-bold text-[#B00C54]">Voir le détail<ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></span></Link>}
