'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, Check, ExternalLink } from 'lucide-react'
import { Navbar } from '@/components/navbar'
import { SiteFooter } from '@/components/site-footer'
import { useLanguage } from '@/lib/language-context'
import { getAiArchitect } from '@/lib/ai-architects'

export function LeaderDetailContent({slug}:{slug:string}) {
  const { lang } = useLanguage()
  const leader = getAiArchitect(slug)
  if (!leader) return null
  return <div className="min-h-screen bg-[#F5F5F7] text-[#1D1D1F]"><Navbar/><main>
    <section className="px-5 pb-16 pt-32 sm:px-8 sm:pt-40"><div className="mx-auto max-w-7xl"><Link href="/leaders" className="inline-flex items-center gap-2 text-sm font-semibold text-[#6E6E73]"><ArrowLeft className="size-4"/>{lang==='fr'?'Tous les architectes':'All architects'}</Link><div className="mt-8 grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="font-mono text-[11px] font-bold uppercase tracking-[.2em] text-[#D10E63]">{leader.company}</p><h1 className="mt-6 text-[clamp(3.6rem,8vw,8rem)] font-semibold leading-[.88] tracking-[-.07em]">{leader.name}</h1><p className="mt-8 max-w-2xl text-2xl font-semibold leading-8 tracking-[-.025em]">{leader.tagline[lang]}</p><p className="mt-5 max-w-2xl text-lg leading-8 text-[#6E6E73]">{leader.focus[lang]}</p><div className="mt-8 flex flex-wrap gap-2">{leader.models.map(model=><span key={model} className="rounded-full bg-white px-4 py-2 text-sm font-semibold shadow-sm">{model}</span>)}</div></div><div className="relative aspect-[4/5] overflow-hidden rounded-[40px] bg-black shadow-[0_45px_100px_-45px_rgba(0,0,0,.5)]"><Image src={leader.image} alt={`Portrait de ${leader.name}`} fill priority sizes="(min-width:1024px) 50vw, 100vw" className="object-cover object-top"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-6 text-xs text-white/70">Image : {leader.imageSource}</div></div></div></div></section>
    <section className="bg-white px-5 py-20 sm:px-8"><div className="mx-auto max-w-6xl"><p className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#D10E63]">{lang==='fr'?'Lecture Unitalk':'Unitalk perspective'}</p><h2 className="mt-6 max-w-5xl text-[clamp(2.5rem,5vw,5rem)] font-semibold leading-[.96] tracking-[-.055em]">{lang==='fr'?'Choisir une architecture ne suffit pas. Il faut gouverner son usage.':'Choosing an architecture is not enough. Its use must be governed.'}</h2><div className="mt-12 grid gap-5 md:grid-cols-3"><Card title={lang==='fr'?'Ce que cette approche apporte':'What this approach brings'} body={leader.focus[lang]}/><Card title={lang==='fr'?'Ce que Unitalk ajoute':'What Unitalk adds'} body={lang==='fr'?'Identité, missions, droits, validations, mémoire gouvernée et traçabilité.':'Identity, missions, permissions, approvals, governed memory and traceability.'}/><Card title={lang==='fr'?'Ce qui reste humain':'What remains human'} body={lang==='fr'?'Le choix de la mission, les règles, les décisions sensibles et la responsabilité finale.':'Mission choice, rules, sensitive decisions and final accountability.'}/></div></div></section>
    <section className="bg-black px-5 py-20 text-white sm:px-8"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[1fr_.8fr]"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#F2A4C5]">Unitalk AI Gateway</p><h2 className="mt-6 text-[clamp(2.5rem,5vw,5rem)] font-semibold leading-[.96] tracking-[-.055em]">{lang==='fr'?'Le bon modèle, pour la bonne mission, sous vos règles.':'The right model, for the right mission, under your rules.'}</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-white/65">{lang==='fr'?'Alma coordonne : elle cadre le résultat, choisit le Collaborateur IA adapté et prépare les autorisations. Le Collaborateur IA effectue ensuite la mission avec le modèle autorisé.':'Alma coordinates: she scopes the outcome, selects the right AI Collaborator and prepares permissions. The AI Collaborator then performs the mission with the authorized model.'}</p><div className="mt-8 flex flex-wrap gap-4"><Link href={`/decouvrir?source=architecte-ia&fournisseur=${leader.slug}`} className="inline-flex min-h-12 items-center rounded-full bg-[#D10E63] px-7 text-sm font-bold">{lang==='fr'?'Préparer une mission avec Alma':'Prepare a mission with Alma'}<ArrowRight className="ml-2 size-4"/></Link><Link href="/tarifs" className="inline-flex min-h-12 items-center rounded-full border border-white/20 px-7 text-sm font-bold">{lang==='fr'?'Voir les tarifs':'View pricing'}</Link></div></div><aside className="rounded-[32px] border border-white/10 bg-white/[.06] p-7"><h3 className="text-xl font-semibold">{lang==='fr'?'Principes de déploiement':'Deployment principles'}</h3><ul className="mt-6 space-y-4 text-sm text-white/75">{(lang==='fr'?['Fournisseur et modèle explicitement autorisés','Budget et capacité définis par l’Entreprise','Fallback et routage visibles','Aucune affiliation implicite avec le fournisseur']:['Explicitly authorized provider and model','Budget and capacity defined by the Organization','Visible fallback and routing','No implied affiliation with the provider']).map(item=><li key={item} className="flex gap-3"><Check className="size-4 shrink-0 text-[#F2A4C5]"/>{item}</li>)}</ul><a href="/ai-gateway" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#F2A4C5]">{lang==='fr'?'Comprendre AI Gateway':'Understand AI Gateway'}<ExternalLink className="size-4"/></a></aside></div></section>
  </main><SiteFooter/></div>
}

function Card({title,body}:{title:string;body:string}){return <article className="rounded-[28px] bg-[#F5F5F7] p-7"><h3 className="text-xl font-semibold tracking-[-.03em]">{title}</h3><p className="mt-4 text-sm leading-7 text-[#6E6E73]">{body}</p></article>}
