'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Check } from 'lucide-react'
import { Navbar } from '@/components/navbar'
import { SiteFooter } from '@/components/site-footer'
import { useLanguage } from '@/lib/language-context'
import { AI_ARCHITECTS } from '@/lib/ai-architects'

export default function AiArchitectsPage() {
  const { lang } = useLanguage()
  return <div className="min-h-screen bg-[#F5F5F7] text-[#1D1D1F]"><Navbar/><main>
    <section className="px-5 pb-20 pt-36 text-center sm:px-8 sm:pt-44"><p className="font-mono text-[11px] font-bold uppercase tracking-[.2em] text-[#D10E63]">{lang==='fr'?'Architectes de l’IA':'AI architects'}</p><h1 className="mx-auto mt-7 max-w-6xl text-balance text-[clamp(3rem,7vw,7rem)] font-semibold leading-[.92] tracking-[-.065em]">{lang==='fr'?'Les idées et infrastructures derrière les modèles.':'The ideas and infrastructure behind the models.'}</h1><p className="mx-auto mt-8 max-w-3xl text-xl leading-8 text-[#6E6E73]">{lang==='fr'?'Unitalk AI Gateway vous permet de sélectionner des modèles et fournisseurs selon vos règles. Ces pages expliquent leurs approches — sans affiliation ni approbation implicite.':'Unitalk AI Gateway lets you select models and providers under your rules. These pages explain their approaches — without implied affiliation or endorsement.'}</p><div className="mx-auto mt-8 flex max-w-3xl flex-wrap justify-center gap-x-6 gap-y-3 text-sm font-semibold text-[#6E6E73]"><span className="flex gap-2"><Check className="size-4 text-[#D10E63]"/>{lang==='fr'?'Sources attribuées':'Attributed sources'}</span><span className="flex gap-2"><Check className="size-4 text-[#D10E63]"/>{lang==='fr'?'Aucune citation inventée':'No invented quotes'}</span><span className="flex gap-2"><Check className="size-4 text-[#D10E63]"/>{lang==='fr'?'Alma coordonne, le Collaborateur exécute':'Alma coordinates, the Collaborator executes'}</span></div></section>
    <section className="px-5 pb-24 sm:px-8"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-2 lg:grid-cols-4">{AI_ARCHITECTS.map((leader,index)=><Link key={leader.slug} href={`/leaders/${leader.slug}`} className={`group relative overflow-hidden rounded-[32px] bg-black ${index===0||index===5?'md:col-span-2':''}`}><div className={`relative ${index===0||index===5?'aspect-[16/10]':'aspect-[4/5]'}`}><Image src={leader.image} alt={`Portrait de ${leader.name}`} fill sizes="(min-width:1024px) 25vw, (min-width:768px) 50vw, 100vw" className="object-cover object-top transition duration-700 group-hover:scale-[1.025]"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/10 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-white/60">{leader.company}</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.045em]">{leader.name}</h2><p className="mt-3 max-w-md text-sm leading-6 text-white/75">{leader.tagline[lang]}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold">{lang==='fr'?'Explorer son approche':'Explore the approach'}<ArrowRight className="size-4 transition group-hover:translate-x-1"/></span></div></div></Link>)}</div></section>
    <section className="bg-black px-5 py-20 text-white sm:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#F2A4C5]">Unitalk AI Gateway</p><h2 className="mt-6 max-w-4xl text-[clamp(2.4rem,5vw,4.8rem)] font-semibold leading-[.98] tracking-[-.055em]">{lang==='fr'?'Le modèle est une ressource. La mission reste le point de départ.':'The model is a resource. The mission remains the starting point.'}</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-white/65">{lang==='fr'?'Alma cadre la mission et prépare le Collaborateur IA. Le Collaborateur accomplit le travail avec les modèles autorisés. Vous validez les décisions qui comptent.':'Alma scopes the mission and prepares the AI Collaborator. The Collaborator performs the work with authorized models. You approve the decisions that matter.'}</p></div><div className="flex flex-col gap-3"><Link href="/ai-gateway" className="inline-flex min-h-12 items-center justify-center rounded-full bg-white px-7 text-sm font-bold text-black">{lang==='fr'?'Découvrir AI Gateway':'Discover AI Gateway'}<ArrowRight className="ml-2 size-4"/></Link><Link href="/tarifs" className="text-center text-sm font-bold text-[#F2A4C5]">{lang==='fr'?'Voir les tarifs':'View pricing'}</Link></div></div></section>
  </main><SiteFooter/></div>
}
