'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { ArrowRight, Check, LockKeyhole, Plus, ShieldCheck } from 'lucide-react'
import { useLanguage, type Lang } from '@/lib/language-context'

type PersonaKey = 'hugo' | 'emma' | 'lea' | 'arthur'

const PERSONAS = {
  hugo: { name: 'Hugo', handle: '@hugo', avatar: '/images/hugo-avatar.png', profile: { fr: 'Commercial', en: 'Sales' }, mission: { fr: 'Qualifier les prospects entrants', en: 'Qualify inbound prospects' }, result: { fr: '9 prospects qualifiés · 1 validation attendue', en: '9 qualified leads · 1 approval pending' } },
  emma: { name: 'Emma', handle: '@emma', avatar: '/images/emma-avatar.png', profile: { fr: 'Assistante de direction', en: 'Executive assistant' }, mission: { fr: 'Préparer le comité de direction', en: 'Prepare the leadership meeting' }, result: { fr: 'Ordre du jour prêt · 3 décisions isolées', en: 'Agenda ready · 3 decisions isolated' } },
  lea: { name: 'Léa', handle: '@lea', avatar: '/images/lea-avatar.png', profile: { fr: 'Responsable éditoriale', en: 'Editorial lead' }, mission: { fr: 'Construire le calendrier éditorial', en: 'Build the editorial calendar' }, result: { fr: '12 sujets préparés · ligne éditoriale préservée', en: '12 topics prepared · editorial line preserved' } },
  arthur: { name: 'Arthur', handle: '@arthur', avatar: '/images/arthur-avatar.png', profile: { fr: 'Développeur', en: 'Developer' }, mission: { fr: 'Corriger un bug prioritaire', en: 'Fix a priority bug' }, result: { fr: 'Correctif testé · fusion à valider', en: 'Fix tested · merge awaiting approval' } },
} as const

const PERSONA_KEYS = Object.keys(PERSONAS) as PersonaKey[]

export function CollaborateurExperience() {
  const { lang } = useLanguage()
  const t = COPY[lang]
  const [active, setActive] = useState<PersonaKey>('hugo')
  const persona = PERSONAS[active]

  return <main className="overflow-hidden bg-[#F3EFE6] font-sf text-[#1C1A17]">
    <section className="relative min-h-[820px] border-b border-[#CFC5B5] px-5 pb-16 pt-28 sm:px-8 sm:pt-36 lg:flex lg:items-center">
      <div aria-hidden className="absolute inset-0 opacity-[.045] [background-image:linear-gradient(#1C1A17_1px,transparent_1px),linear-gradient(90deg,#1C1A17_1px,transparent_1px)] [background-size:72px_72px]" />
      <div className="editorial-shell relative w-full">
        <div className="grid gap-12 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:gap-16">
          <div>
            <p className="font-mono text-[10px] font-black uppercase tracking-[.22em] text-[#B00C54]">{t.heroKicker}</p>
            <h1 className="mt-7 max-w-[820px] text-[clamp(3.6rem,7vw,7.5rem)] font-semibold leading-[.84] tracking-[-.075em]">{t.heroTitle}<span className="block text-[#D10E63]">{t.heroAccent}</span></h1>
            <p className="mt-8 max-w-2xl border-l-2 border-[#D10E63] pl-5 text-[17px] leading-8 text-[#4E483F]">{t.heroBody}</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row"><PrimaryCta label={t.primaryCta} /><a href="#definition" className="inline-flex min-h-12 items-center justify-center rounded-full border border-[#BFB5A5] bg-[#FAF8F3] px-7 text-sm font-bold hover:border-[#D10E63]/50">{t.secondaryCta}</a></div>
            <p className="mt-4 text-xs font-semibold text-[#6E665A]">{t.trial}</p>
          </div>
          <IdentityDossier persona={persona} lang={lang} label={t.heroDossier} />
        </div>
      </div>
    </section>

    <section id="definition" className="scroll-mt-20 bg-[#181615] px-5 py-20 text-white sm:px-8 sm:py-28">
      <div className="editorial-shell">
        <p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#F2A4C5]">{t.definitionKicker}</p>
        <div className="mt-6 grid gap-10 lg:grid-cols-[1.18fr_.82fr] lg:items-end">
          <h2 className="max-w-5xl text-[clamp(3rem,6.4vw,6.8rem)] font-semibold leading-[.88] tracking-[-.07em]">{t.definitionTitle}</h2>
          <p className="max-w-xl text-[17px] leading-8 text-[#CFC6B8]">{t.definitionBody}</p>
        </div>
        <div className="mt-16 grid border-y border-white/15 md:grid-cols-3">{t.definitionPoints.map((item,index)=><article key={item.title} className="border-b border-white/15 py-7 md:border-b-0 md:border-r md:px-7 md:first:pl-0 md:last:border-r-0"><p className="font-mono text-[10px] font-black text-[#F2A4C5]">0{index+1}</p><h3 className="mt-8 text-2xl font-semibold">{item.title}</h3><p className="mt-4 text-sm leading-7 text-[#AFA397]">{item.body}</p></article>)}</div>
      </div>
    </section>

    <section className="px-5 py-20 sm:px-8 sm:py-28">
      <div className="editorial-shell">
        <div className="grid gap-9 lg:grid-cols-[.72fr_1.28fr]"><SectionTitle kicker={t.profilesKicker} title={t.profilesTitle}/><p className="max-w-2xl text-[16px] leading-8 text-[#4E483F] lg:pt-9">{t.profilesBody}</p></div>
        <div className="mt-12 overflow-hidden rounded-[2rem] border border-[#CFC5B5] bg-[#FAF8F3]">
          <div role="tablist" aria-label={t.profileTabs} className="flex overflow-x-auto border-b border-[#D8D0C2]">{PERSONA_KEYS.map(key=><button key={key} type="button" role="tab" aria-selected={active===key} onClick={()=>setActive(key)} className={`min-h-14 flex-1 shrink-0 px-5 text-sm font-bold outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#D10E63] ${active===key?'bg-[#D10E63] text-white':'hover:bg-[#F3EFE6]'}`}>{PERSONAS[key].name}</button>)}</div>
          <div role="tabpanel" className="grid lg:grid-cols-[.72fr_1.28fr]">
            <div className="flex items-center gap-5 border-b border-[#D8D0C2] p-7 lg:border-b-0 lg:border-r sm:p-9"><Image src={persona.avatar} alt="" width={112} height={140} className="aspect-[4/5] w-28 rounded-2xl object-cover"/><div><p className="font-mono text-[10px] font-black uppercase tracking-[.14em] text-[#B00C54]">{t.identityExample}</p><h3 className="mt-3 text-4xl font-semibold tracking-[-.05em]">{persona.name}</h3><p className="mt-1 text-sm text-[#625B50]">{persona.handle}</p><Link href={`/${persona.handle}`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#B00C54]">{t.seeProfile}<ArrowRight className="size-4"/></Link></div></div>
            <div className="p-7 sm:p-9"><p className="font-mono text-[10px] font-black uppercase tracking-[.14em] text-[#857C6E]">{t.defaultProfile}</p><p className="mt-3 text-3xl font-semibold tracking-[-.04em]">{persona.profile[lang]}</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><ProfileChip active label={persona.profile[lang]} detail={t.included}/><ProfileChip label={t.additionalOne} detail={t.available}/><ProfileChip label={t.additionalTwo} detail={t.available}/><Link href="/marketplace#metiers" className="flex min-h-20 items-center justify-between rounded-2xl border border-dashed border-[#BFB5A5] px-5 text-sm font-bold text-[#B00C54] hover:border-[#D10E63]"><span>{t.exploreProfiles}</span><Plus className="size-4"/></Link></div><p className="mt-6 text-sm leading-7 text-[#625B50]">{t.profileRule}</p></div>
          </div>
        </div>
      </div>
    </section>

    <section className="bg-[#D10E63] px-5 py-20 text-white sm:px-8 sm:py-28">
      <div className="editorial-shell grid gap-12 lg:grid-cols-[.78fr_1.22fr] lg:items-center">
        <div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-white/65">{t.missionKicker}</p><h2 className="mt-5 text-[clamp(3rem,5.5vw,5.8rem)] font-semibold leading-[.9] tracking-[-.07em]">{t.missionTitle}</h2><p className="mt-7 max-w-xl text-[16px] leading-8 text-white/80">{t.missionBody}</p></div>
        <MissionCard persona={persona} lang={lang} t={t}/>
      </div>
    </section>

    <section className="px-5 py-20 sm:px-8 sm:py-28">
      <div className="editorial-shell">
        <SectionTitle kicker={t.anatomyKicker} title={t.anatomyTitle}/>
        <div className="mt-12 grid gap-px overflow-hidden rounded-[2rem] border border-[#CFC5B5] bg-[#CFC5B5] sm:grid-cols-2 lg:grid-cols-3">{t.anatomy.map((item,index)=><Link key={item.title} href={item.href} className={`group min-h-56 p-7 sm:p-8 ${index===0?'bg-[#181615] text-white':'bg-[#FAF8F3] hover:bg-white'}`}><p className={`font-mono text-[10px] font-black ${index===0?'text-[#F2A4C5]':'text-[#B00C54]'}`}>0{index+1}</p><h3 className="mt-8 text-2xl font-semibold tracking-[-.035em]">{item.title}</h3><p className={`mt-4 text-sm leading-7 ${index===0?'text-[#AFA397]':'text-[#625B50]'}`}>{item.body}</p><ArrowRight className={`mt-7 size-4 transition-transform group-hover:translate-x-1 ${index===0?'text-[#F2A4C5]':'text-[#D10E63]'}`}/></Link>)}</div>
      </div>
    </section>

    <section className="bg-[#181615] px-5 py-20 text-white sm:px-8 sm:py-28">
      <div className="editorial-shell">
        <div className="grid gap-10 lg:grid-cols-[1.08fr_.92fr] lg:items-end"><div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#F2A4C5]">{t.stackKicker}</p><h2 className="mt-5 max-w-5xl text-[clamp(3rem,6vw,6.4rem)] font-semibold leading-[.88] tracking-[-.07em]">{t.stackTitle}</h2></div><p className="max-w-xl text-[17px] leading-8 text-[#CFC6B8]">{t.stackBody}</p></div>
        <div className="mt-14 grid gap-px overflow-hidden rounded-[2rem] border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-4">{t.stack.map((item,index)=><article key={item.title} className="min-h-72 bg-[#211E1B] p-7 sm:p-8"><p className="font-mono text-[10px] font-black text-[#F2A4C5]">0{index+1}</p><p className="mt-10 text-[clamp(2rem,3vw,3.6rem)] font-semibold leading-none tracking-[-.055em] text-white">{item.proof}</p><h3 className="mt-7 text-lg font-semibold">{item.title}</h3><p className="mt-3 text-sm leading-7 text-[#AFA397]">{item.body}</p></article>)}</div>
        <div className="mt-6 flex flex-col justify-between gap-5 border-t border-white/15 pt-6 sm:flex-row sm:items-center"><p className="max-w-3xl text-sm leading-7 text-[#AFA397]">{t.stackNote}</p><Link href="/ai-gateway" className="inline-flex shrink-0 items-center gap-2 text-sm font-bold text-[#F2A4C5]">{t.gatewayCta}<ArrowRight className="size-4"/></Link></div>
      </div>
    </section>

    <section className="border-y border-[#CFC5B5] bg-[#EAE3D4] px-5 py-20 sm:px-8 sm:py-28">
      <div className="editorial-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center">
        <div><SectionTitle kicker={t.governanceKicker} title={t.governanceTitle}/><p className="mt-7 max-w-xl text-[16px] leading-8 text-[#4E483F]">{t.governanceBody}</p><Link href="/documentation/licence-collaborateur-ia" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#B00C54]">{t.documentation}<ArrowRight className="size-4"/></Link></div>
        <div className="grid gap-4 sm:grid-cols-2">{t.governance.map((item,index)=><article key={item.title} className={`rounded-[1.5rem] p-6 ${index===0?'bg-[#181615] text-white':'border border-[#CFC5B5] bg-[#FAF8F3]'}`}>{index===0?<LockKeyhole className="size-5 text-[#F2A4C5]"/>:<ShieldCheck className="size-5 text-[#D10E63]"/>}<h3 className="mt-8 text-xl font-semibold">{item.title}</h3><p className={`mt-3 text-sm leading-7 ${index===0?'text-[#AFA397]':'text-[#625B50]'}`}>{item.body}</p></article>)}</div>
      </div>
    </section>

    <section className="px-5 py-20 sm:px-8 sm:py-28"><div className="editorial-shell grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><SectionTitle kicker="FAQ" title={t.faqTitle}/><div className="border-t border-[#CFC5B5]">{t.faq.map(item=><details key={item.q} className="group border-b border-[#CFC5B5]"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 py-6 text-lg font-semibold"><span>{item.q}</span><Plus className="size-4 shrink-0 transition-transform group-open:rotate-45"/></summary><p className="max-w-2xl pb-7 text-sm leading-7 text-[#625B50]">{item.a}</p></details>)}</div></div></section>

    <section className="bg-[#181615] px-5 py-20 text-white sm:px-8 sm:py-28"><div className="editorial-shell grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#F2A4C5]">{t.finalKicker}</p><h2 className="mt-5 max-w-5xl text-[clamp(3rem,6.5vw,6.8rem)] font-semibold leading-[.87] tracking-[-.075em]">{t.finalTitle}</h2><p className="mt-7 max-w-2xl text-[17px] leading-8 text-[#CFC6B8]">{t.finalBody}</p></div><div className="flex min-w-64 flex-col gap-3"><PrimaryCta label={t.primaryCta} light/><Link href="/tarifs" className="text-center text-sm font-bold text-[#F2A4C5] underline decoration-white/20 underline-offset-4">{t.pricing}</Link></div></div></section>
  </main>
}

function PrimaryCta({label,light=false}:{label:string;light?:boolean}) { return <Link href="/missions?composer=1&source=collaborateurs-ia" className={`group inline-flex min-h-12 items-center justify-center gap-2 rounded-full px-7 text-sm font-bold outline-none focus-visible:ring-2 ${light?'bg-[#F3EFE6] text-[#181615] focus-visible:ring-[#F2A4C5]':'bg-[#181615] text-white focus-visible:ring-[#D10E63]'}`}>{label}<ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></Link> }
function SectionTitle({kicker,title}:{kicker:string;title:string}) { return <div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#B00C54]">{kicker}</p><h2 className="mt-5 max-w-4xl text-[clamp(2.7rem,5.2vw,5.4rem)] font-semibold leading-[.92] tracking-[-.065em]">{title}</h2></div> }
function IdentityDossier({persona,lang,label}:{persona:typeof PERSONAS[PersonaKey];lang:Lang;label:string}) { return <aside className="relative mx-auto w-full max-w-[480px]"><div aria-hidden className="absolute -inset-7 rotate-3 rounded-[2.5rem] border border-[#CFC5B5] bg-[#EAE3D4]"/><div className="relative overflow-hidden rounded-[2rem] border border-[#292521] bg-[#181615] text-white shadow-[0_40px_90px_-45px_rgba(28,26,23,.8)]"><div className="flex items-center justify-between border-b border-white/10 px-6 py-4"><p className="font-mono text-[9px] font-black uppercase tracking-[.18em] text-[#F2A4C5]">{label}</p><span className="flex items-center gap-2 text-[9px] font-bold text-[#8CE5AB]"><span className="size-1.5 rounded-full bg-[#45C578]"/>ACTIF</span></div><div className="grid grid-cols-[128px_1fr] gap-6 p-6"><Image src={persona.avatar} alt={persona.name} width={128} height={160} priority className="aspect-[4/5] w-32 rounded-2xl object-cover"/><div className="self-end"><p className="text-4xl font-semibold tracking-[-.055em]">{persona.name}</p><p className="mt-2 font-mono text-xs text-[#F2A4C5]">{persona.handle}</p><p className="mt-5 text-sm font-semibold">{persona.profile[lang]}</p><p className="mt-1 text-xs text-[#AFA397]">Collaborateur IA</p></div></div><dl className="divide-y divide-white/10 border-t border-white/10 px-6"><DossierRow label={lang==='fr'?'Canaux propres':'Own channels'} value={lang==='fr'?'Email · Calendrier · Téléphone':'Email · Calendar · Phone'}/><DossierRow label={lang==='fr'?'Moteur':'Runtime'} value="Hermes · Open source · MIT"/><DossierRow label={lang==='fr'?'Profil par défaut':'Default profile'} value={persona.profile[lang]}/><DossierRow label={lang==='fr'?'Applications':'Applications'} value={lang==='fr'?'3 000+ intégrations selon configuration':'3,000+ integrations depending on setup'}/><DossierRow label={lang==='fr'?'Modèles IA':'AI models'} value={lang==='fr'?'Le plus pertinent parmi ceux autorisés':'Best fit among authorized models'}/><DossierRow label={lang==='fr'?'Propriétaire':'Owner'} value={lang==='fr'?'Votre entreprise':'Your organization'}/></dl></div></aside> }
function DossierRow({label,value}:{label:string;value:string}) { return <div className="grid grid-cols-[115px_1fr] gap-3 py-3"><dt className="font-mono text-[9px] font-bold uppercase tracking-[.1em] text-[#857C6E]">{label}</dt><dd className="text-xs font-semibold text-[#D8D0C2]">{value}</dd></div> }
function ProfileChip({label,detail,active=false}:{label:string;detail:string;active?:boolean}) { return <div className={`flex min-h-20 items-center gap-3 rounded-2xl border px-5 ${active?'border-[#D10E63] bg-[#FBEAF1]':'border-[#D8D0C2]'}`}>{active?<Check className="size-4 shrink-0 text-[#D10E63]"/>:<Plus className="size-4 shrink-0 text-[#857C6E]"/>}<div><p className="text-sm font-bold">{label}</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-[.08em] text-[#857C6E]">{detail}</p></div></div> }
function MissionCard({persona,lang,t}:{persona:typeof PERSONAS[PersonaKey];lang:Lang;t:typeof COPY.fr|typeof COPY.en}) { return <article className="overflow-hidden rounded-[2rem] border border-white/20 bg-[#181615] shadow-[0_35px_80px_-45px_rgba(28,26,23,.8)]"><div className="flex items-center gap-4 border-b border-white/10 p-5"><Image src={persona.avatar} alt="" width={48} height={48} className="size-12 rounded-full object-cover"/><div><p className="font-semibold">{persona.name} · {persona.profile[lang]}</p><p className="mt-1 text-xs text-[#AFA397]">{t.missionDemo}</p></div></div><div className="p-6 sm:p-8"><p className="font-mono text-[9px] font-black uppercase tracking-[.18em] text-[#F2A4C5]">{t.currentMission}</p><h3 className="mt-3 text-2xl font-semibold">{persona.mission[lang]}</h3><ol className="mt-8 space-y-5">{t.timeline.map(([time,text],index)=><li key={time} className="grid grid-cols-[44px_10px_1fr] gap-3 text-sm"><span className="font-mono text-[10px] text-[#857C6E]">{time}</span><span className={`mt-1 size-2 rounded-full ${index===t.timeline.length-1?'bg-[#F2A4C5]':'bg-[#45C578]'}`}/><span className="text-[#CFC6B8]">{text}</span></li>)}</ol><div className="mt-8 rounded-2xl border border-[#F2A4C5]/25 bg-[#D10E63]/10 p-5"><p className="font-mono text-[9px] font-black uppercase tracking-[.15em] text-[#F2A4C5]">{t.humanDecision}</p><p className="mt-3 text-sm font-semibold">{t.decisionQuestion}</p></div><p className="mt-5 flex items-center gap-2 text-xs font-semibold text-[#8CE5AB]"><Check className="size-4"/>{persona.result[lang]}</p></div></article> }

const COPY = {
  fr: {
    heroKicker:'Collaborateur IA pour entreprise', heroTitle:'Une identité professionnelle.', heroAccent:'Équipée pour travailler.', heroBody:'Un Collaborateur IA rejoint votre organisation avec son propre email, son calendrier, son numéro de téléphone, un profil métier par défaut et un responsable humain. Propulsé par Hermes, il mobilise les applications et les modèles autorisés pour accomplir ses missions.', primaryCta:'Décrire une première mission', secondaryCta:'Comprendre en 60 secondes', trial:'7 jours gratuits · Sans carte bancaire · Vous gardez le contrôle', heroDossier:'Identité professionnelle',
    definitionKicker:'La différence', definitionTitle:'Il ne répond pas seulement. Il prend une responsabilité.', definitionBody:'Un assistant attend une question. Un Collaborateur IA reçoit un travail, mobilise le contexte autorisé, produit un résultat et s’arrête lorsque votre décision est nécessaire.', definitionPoints:[{title:'Une identité durable',body:'Son prénom, sa mémoire, ses accès et son historique restent attachés à la même identité.'},{title:'Une place dans l’entreprise',body:'Il appartient à votre organisation et travaille sous la responsabilité d’un humain désigné.'},{title:'Un périmètre gouverné',body:'Chaque mission précise les sources, les applications, les actions permises et les validations.'}],
    profilesKicker:'Profils métier', profilesTitle:'Il commence avec un métier. Vous pouvez lui en apprendre d’autres.', profilesBody:'Chaque Collaborateur IA possède un profil métier par défaut lors de son arrivée. Ajoutez ensuite d’autres profils sans perdre son identité, sa mémoire ni les méthodes déjà validées.', profileTabs:'Exemples de Collaborateurs IA', identityExample:'Exemple de Collaborateur IA', seeProfile:'Voir le profil public', defaultProfile:'Profil métier par défaut', included:'Inclus au départ', available:'Peut être ajouté', additionalOne:'Chargé de veille', additionalTwo:'Coordinateur de projet', exploreProfiles:'Explorer les profils métier', profileRule:'Le profil définit une responsabilité, des missions types, des compétences et des limites. Une même identité peut cumuler plusieurs profils.',
    missionKicker:'Le travail avant la technologie', missionTitle:'Une mission entre. Un résultat vérifiable sort.', missionBody:'Vous décrivez le résultat attendu. Le Collaborateur utilise uniquement les ressources autorisées, documente son travail et remonte les décisions qui engagent votre entreprise.', missionDemo:'Démonstration fictive', currentMission:'Mission en cours', timeline:[['09:12','Contexte et critères autorisés vérifiés'],['09:16','Sources consultées et travail préparé'],['09:21','Résultat contrôlé selon vos règles'],['09:23','Une décision sensible vous est soumise']], humanDecision:'Décision humaine requise', decisionQuestion:'Autoriser l’action avant exécution ?',
    anatomyKicker:'Son équipement', anatomyTitle:'Une identité. Six couches que vous gouvernez.', anatomy:[{title:'Profils métier',body:'Son profil par défaut et les responsabilités que vous ajoutez.',href:'/marketplace#metiers'},{title:'Compétences',body:'Les méthodes précises qu’il sait appliquer et réutiliser.',href:'/marketplace#competences'},{title:'Applications',body:'Plus de 3 000 intégrations peuvent être disponibles selon votre configuration.',href:'/marketplace#applications'},{title:'Modèles IA',body:'AI Gateway route chaque tâche vers un modèle pertinent parmi ceux que vous autorisez.',href:'/marketplace#modeles-ia'},{title:'Serveur IA',body:'Son environnement privé pour exécuter et conserver le travail.',href:'/marketplace#serveurs-ia'},{title:'Workspace',body:'L’espace où humains et IA suivent, commentent et valident.',href:'/workspace'}],
    stackKicker:'Ouvert par architecture', stackTitle:'Hermes à l’intérieur. Vos choix restent ouverts.', stackBody:'Unitalk orchestre l’identité, les missions et la gouvernance autour du runtime agentique open source Hermes. Vous pouvez changer de modèles, connecter vos propres services et conserver la maîtrise de vos actifs.', stack:[{proof:'Email + agenda + téléphone',title:'Ses propres canaux',body:'Une identité professionnelle joignable et distincte, avec les outils de communication activés par votre entreprise.'},{proof:'3 000+ apps',title:'Votre environnement métier',body:'Connecteurs, outils MCP, API et applications autorisés selon la mission et votre configuration.'},{proof:'Multi-modèles',title:'Le bon modèle pour la tâche',body:'AI Gateway sélectionne une route pertinente parmi vos fournisseurs et modèles autorisés, sous votre budget.'},{proof:'MIT',title:'Propulsé par Hermes',body:'Un runtime agentique open source pour planifier, utiliser des outils, exécuter et apprendre des compétences.'}], stackNote:'Profils, compétences, fichiers et données restent conçus pour être consultables, exportables et portables. Unitalk accompagne l’import d’un Hermes existant et la migration d’agents compatibles ; la portabilité effective dépend des formats et services tiers utilisés.', gatewayCta:'Découvrir AI Gateway',
    governanceKicker:'Votre entreprise garde la main', governanceTitle:'Ce qu’il apprend reste gouverné. Et exportable.', governanceBody:'Le Collaborateur IA ne transforme pas automatiquement vos conversations en mémoire. Seuls le contexte utile, les corrections et les méthodes validées peuvent être conservés selon vos règles, puis consultés, modifiés et exportés.', documentation:'Lire la documentation de la licence', governance:[{title:'Pas de verrou propriétaire',body:'Hermes est open source sous licence MIT. Vos profils, compétences et données ne dépendent pas d’un modèle IA unique.'},{title:'Migration accompagnée',body:'Importez un Hermes existant ou préparez la migration d’un agent compatible avec ses dépendances.'},{title:'Accès explicites',body:'Une application disponible ne donne aucun droit automatique. Chaque accès est autorisé.'},{title:'Décisions humaines',body:'Les actions sensibles restent bloquées jusqu’à la décision d’une personne habilitée.'}],
    faqTitle:'Les questions qui comptent.', faq:[{q:'Est-ce simplement un assistant IA avec un prénom ?',a:'Non. Le prénom rend l’identité visible, mais la différence tient surtout à sa place dans l’organisation, à ses missions, à ses accès propres, à sa mémoire gouvernée et à sa supervision humaine.'},{q:'Pourquoi un profil métier par défaut ?',a:'Pour qu’il arrive avec une responsabilité claire et un premier périmètre de travail. Vous pouvez ensuite ajouter d’autres profils métier à la même identité.'},{q:'Puis-je choisir son prénom, son visage et sa voix ?',a:'Oui. L’identité est personnalisable avant son déploiement. Hugo, Emma, Léa et Arthur sont des exemples publics de configurations.'},{q:'Quel modèle IA utilise-t-il ?',a:'Seulement les modèles autorisés par votre entreprise. Le modèle peut varier selon la tâche, les règles et le budget configurés.'},{q:'Que se passe-t-il si son responsable quitte l’entreprise ?',a:'La supervision est réattribuée. L’identité, la mémoire et les méthodes validées restent dans votre entreprise.'}],
    finalKicker:'Commencer par le réel', finalTitle:'Quel travail voulez-vous lui confier ?', finalBody:'Partez d’une mission que votre équipe connaît déjà. Alma vous aide à préciser le résultat, recommande un profil et prépare les validations nécessaires.', pricing:'Voir les tarifs',
  },
  en: {
    heroKicker:'AI Collaborator for business', heroTitle:'A professional identity.', heroAccent:'Equipped to work.', heroBody:'An AI Collaborator joins your organization with its own email, calendar, phone number, a default job profile and a human owner. Powered by Hermes, it uses authorized applications and models to complete missions.', primaryCta:'Describe a first mission', secondaryCta:'Understand in 60 seconds', trial:'7 days free · No credit card · You stay in control', heroDossier:'Professional identity',
    definitionKicker:'The difference', definitionTitle:'It does not merely answer. It takes responsibility.', definitionBody:'An assistant waits for a question. An AI Collaborator receives work, uses authorized context, produces an outcome and stops when your decision is needed.', definitionPoints:[{title:'A durable identity',body:'Its name, memory, access and history remain attached to the same identity.'},{title:'A place in the company',body:'It belongs to your organization and works under a designated human owner.'},{title:'A governed scope',body:'Each mission defines sources, applications, permitted actions and approvals.'}],
    profilesKicker:'Job profiles', profilesTitle:'It starts with one profession. You can teach it others.', profilesBody:'Each AI Collaborator has a default job profile when joining. Add more profiles later without losing identity, memory or previously approved methods.', profileTabs:'AI Collaborator examples', identityExample:'AI Collaborator example', seeProfile:'View public profile', defaultProfile:'Default job profile', included:'Included initially', available:'Can be added', additionalOne:'Research officer', additionalTwo:'Project coordinator', exploreProfiles:'Explore job profiles', profileRule:'A profile defines responsibility, typical missions, skills and limits. One identity can hold multiple profiles.',
    missionKicker:'Work before technology', missionTitle:'A mission goes in. A verifiable outcome comes out.', missionBody:'Describe the expected outcome. The Collaborator only uses authorized resources, documents the work and escalates decisions that bind your company.', missionDemo:'Fictional demonstration', currentMission:'Mission in progress', timeline:[['09:12','Authorized context and criteria verified'],['09:16','Sources reviewed and work prepared'],['09:21','Outcome checked against your rules'],['09:23','A sensitive decision is submitted to you']], humanDecision:'Human decision required', decisionQuestion:'Authorize the action before execution?',
    anatomyKicker:'Its equipment', anatomyTitle:'One identity. Six layers under your governance.', anatomy:[{title:'Job profiles',body:'Its default profile and the responsibilities you add.',href:'/marketplace#metiers'},{title:'Skills',body:'The precise methods it knows how to apply and reuse.',href:'/marketplace#competences'},{title:'Applications',body:'More than 3,000 integrations may be available depending on your setup.',href:'/marketplace#applications'},{title:'AI models',body:'AI Gateway routes each task to a relevant model among those you authorize.',href:'/marketplace#modeles-ia'},{title:'AI server',body:'Its private environment for executing and retaining work.',href:'/marketplace#serveurs-ia'},{title:'Workspace',body:'Where humans and AI track, comment and approve.',href:'/workspace'}],
    stackKicker:'Open by architecture', stackTitle:'Hermes inside. Your choices stay open.', stackBody:'Unitalk orchestrates identity, missions and governance around the open-source Hermes agentic runtime. You can change models, connect your own services and retain control of your assets.', stack:[{proof:'Email + calendar + phone',title:'Its own channels',body:'A distinct, reachable professional identity with communication tools enabled by your organization.'},{proof:'3,000+ apps',title:'Your business environment',body:'Connectors, MCP tools, APIs and applications authorized by mission and configuration.'},{proof:'Multi-model',title:'The right model for the task',body:'AI Gateway selects a relevant route among your authorized providers and models, under your budget.'},{proof:'MIT',title:'Powered by Hermes',body:'An open-source agentic runtime for planning, tool use, execution and learning skills.'}], stackNote:'Profiles, skills, files and data are designed to remain viewable, exportable and portable. Unitalk supports importing an existing Hermes setup and migrating compatible agents; effective portability depends on the formats and third-party services used.', gatewayCta:'Discover AI Gateway',
    governanceKicker:'Your organization stays in control', governanceTitle:'What it learns remains governed. And exportable.', governanceBody:'The AI Collaborator does not automatically turn conversations into memory. Only useful context, corrections and approved methods may be retained under your rules, then viewed, edited and exported.', documentation:'Read the license documentation', governance:[{title:'No proprietary lock-in',body:'Hermes is open source under the MIT License. Your profiles, skills and data do not depend on one AI model.'},{title:'Supported migration',body:'Import an existing Hermes setup or prepare migration of a compatible agent and its dependencies.'},{title:'Explicit access',body:'An available application grants no automatic rights. Every access is authorized.'},{title:'Human decisions',body:'Sensitive actions remain blocked until an authorized person decides.'}],
    faqTitle:'The questions that matter.', faq:[{q:'Is this simply an AI assistant with a name?',a:'No. The name makes the identity visible, but the difference lies in its organizational place, missions, individual access, governed memory and human supervision.'},{q:'Why a default job profile?',a:'So it joins with a clear responsibility and initial scope of work. You can then add other job profiles to the same identity.'},{q:'Can I choose its name, face and voice?',a:'Yes. The identity can be customized before deployment. Hugo, Emma, Léa and Arthur are public configuration examples.'},{q:'Which AI model does it use?',a:'Only models authorized by your organization. The model may vary by task, rules and configured budget.'},{q:'What if its human owner leaves?',a:'Supervision is reassigned. Identity, memory and approved methods remain in your organization.'}],
    finalKicker:'Start from reality', finalTitle:'What work do you want to assign?', finalBody:'Start with a mission your team already understands. Alma helps clarify the outcome, recommends a profile and prepares the required approvals.', pricing:'View pricing',
  },
} as const
