'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useRef, useState } from 'react'
import { ArrowRight, CircleCheck } from 'lucide-react'
import { useLanguage, type Lang } from '@/lib/language-context'

type FormatKey = 'text' | 'image' | 'audio' | 'video' | 'code'
const FORMAT_KEYS: FormatKey[] = ['text', 'image', 'audio', 'video', 'code']

export function CollaborateurExperience() {
  const { lang } = useLanguage()
  const t = COPY[lang]

  return <main className="overflow-hidden bg-[#F3EFE6] font-sf text-[#1C1A17]">
    <section className="relative border-b border-[#CFC5B5] px-5 pb-14 pt-28 sm:px-8 sm:pt-36">
      <div aria-hidden className="absolute inset-0 opacity-[.045] [background-image:linear-gradient(#1C1A17_1px,transparent_1px),linear-gradient(90deg,#1C1A17_1px,transparent_1px)] [background-size:72px_72px]" />
      <div className="editorial-shell relative">
        <p className="font-mono text-[10px] font-black uppercase tracking-[.22em] text-[#B00C54]">{t.heroKicker}</p>
        <div className="mt-7 grid gap-12 lg:grid-cols-[1.08fr_.92fr] lg:items-end lg:gap-16">
          <div>
            <h1 className="max-w-[860px] whitespace-pre-line text-[clamp(3rem,6.2vw,6.4rem)] font-semibold leading-[.9] tracking-[-.07em]">{t.heroTitle}</h1>
            <p className="mt-7 max-w-2xl text-[17px] leading-8 text-[#4E483F]">{t.heroBody}</p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row">
              <PrimaryCta label={t.primaryCta} />
              <a href="#mission-en-action" className="inline-flex min-h-12 items-center justify-center rounded-full border border-[#BFB5A5] bg-[#FAF8F3] px-7 text-sm font-bold hover:border-[#D10E63]/50">{t.secondaryCta}</a>
            </div>
            <p className="mt-4 text-xs font-semibold text-[#6E665A]">{t.trial}</p>
          </div>
          <MissionSnapshot lang={lang} />
        </div>
        <div className="mt-14 grid border-y border-[#CFC5B5] sm:grid-cols-3">{t.heroProofs.map((proof, index) => <div key={proof.title} className="border-b border-[#CFC5B5] py-5 last:border-b-0 sm:border-b-0 sm:border-r sm:px-6 sm:first:pl-0 sm:last:border-r-0"><p className="font-mono text-[9px] font-black text-[#B00C54]">0{index + 1}</p><p className="mt-2 text-sm font-bold">{proof.title}</p><p className="mt-1 text-xs leading-5 text-[#625B50]">{proof.body}</p></div>)}</div>
      </div>
    </section>

    <section id="mission-en-action" className="scroll-mt-20 bg-[#181615] px-5 py-20 text-white sm:px-8 sm:py-28">
      <div className="editorial-shell">
        <div className="grid gap-9 lg:grid-cols-[.72fr_1.28fr]"><SectionTitle dark kicker={t.demoKicker} title={t.demoTitle} /><div className="lg:pt-8"><p className="max-w-2xl text-[16px] leading-8 text-[#CFC6B8]">{t.demoBody}</p><p className="mt-4 inline-flex rounded-full border border-white/15 px-3 py-1.5 font-mono text-[9px] font-bold uppercase tracking-[.14em] text-[#AFA397]">{t.demoDisclosure}</p></div></div>
        <div className="mt-14 overflow-hidden rounded-[2rem] border border-white/10 bg-[#211E1B]">
          <div className="grid border-b border-white/10 lg:grid-cols-[.72fr_1.28fr]"><div className="p-6 sm:p-8"><p className="font-mono text-[9px] font-black uppercase tracking-[.18em] text-[#F2A4C5]">Mission CX-014</p><h3 className="mt-4 text-2xl font-semibold tracking-[-.035em]">{t.demoMission}</h3><p className="mt-3 text-sm leading-7 text-[#AFA397]">Lucas · {t.demoProfile}</p></div><div className="border-t border-white/10 p-6 lg:border-l lg:border-t-0 sm:p-8"><p className="font-mono text-[9px] font-black uppercase tracking-[.18em] text-[#F2A4C5]">{t.allowedSources}</p><div className="mt-4 flex flex-wrap gap-2">{t.sources.map((source) => <span key={source} className="rounded-full border border-white/15 px-3 py-1.5 text-xs font-semibold text-[#D8D0C2]">{source}</span>)}</div></div></div>
          <ol className="divide-y divide-white/10">{t.timeline.map(([time, title, body], index) => <li key={time} className="grid gap-4 p-6 sm:grid-cols-[80px_1fr_1.25fr] sm:items-center sm:p-8"><p className="font-mono text-[11px] font-black text-[#F2A4C5]">{time}</p><div className="flex items-center gap-3"><span className={`size-2 rounded-full ${index === t.timeline.length - 1 ? 'bg-[#F2A4C5]' : 'bg-[#45C578]'}`} /><h4 className="font-semibold">{title}</h4></div><p className="text-sm leading-7 text-[#AFA397]">{body}</p></li>)}</ol>
          <div className="grid gap-px border-t border-white/10 bg-white/10 lg:grid-cols-2"><div className="bg-[#2A211F] p-6 sm:p-8"><p className="font-mono text-[9px] font-black uppercase tracking-[.18em] text-[#F2A4C5]">{t.humanApproval}</p><p className="mt-4 text-xl font-semibold">{t.approvalQuestion}</p><div className="mt-6 flex gap-2"><span className="rounded-full bg-[#D10E63] px-4 py-2 text-xs font-bold">{t.approve}</span><span className="rounded-full border border-white/15 px-4 py-2 text-xs font-bold text-[#CFC6B8]">{t.modify}</span></div></div><div className="bg-[#20241F] p-6 sm:p-8"><p className="font-mono text-[9px] font-black uppercase tracking-[.18em] text-[#8CE5AB]">{t.result}</p><p className="mt-4 text-xl font-semibold">{t.resultValue}</p><p className="mt-3 text-sm leading-7 text-[#AFC9B7]">{t.resultDetail}</p></div></div>
        </div>
      </div>
    </section>

    <section className="px-5 py-20 sm:px-8 sm:py-28"><div className="editorial-shell"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><SectionTitle kicker={t.startKicker} title={t.startTitle} /><ol className="border-t border-[#CFC5B5]">{t.steps.map((step, index) => <li key={step.title} className="grid gap-3 border-b border-[#CFC5B5] py-7 sm:grid-cols-[64px_.72fr_1.28fr] sm:items-center"><span className="font-mono text-[10px] font-black text-[#B00C54]">0{index + 1}</span><h3 className="text-2xl font-semibold tracking-[-.035em]">{step.title}</h3><p className="text-sm leading-7 text-[#625B50]">{step.body}</p></li>)}</ol></div></div></section>

    <section className="border-y border-[#D8D0C2] bg-[#EAE3D4] px-5 py-20 sm:px-8 sm:py-28"><div className="editorial-shell"><SectionTitle kicker={t.formatsKicker} title={t.formatsTitle} /><p className="mt-6 max-w-3xl text-[16px] leading-8 text-[#4E483F]">{t.formatsBody}</p><FormatTabs lang={lang} /></div></section>

    <section className="px-5 py-20 sm:px-8 sm:py-28"><div className="editorial-shell grid gap-5 lg:grid-cols-2">
      <article className="rounded-[2rem] border border-[#CFC5B5] bg-[#FAF8F3] p-7 sm:p-9"><p className="font-mono text-[10px] font-black uppercase tracking-[.18em] text-[#B00C54]">{t.controlKicker}</p><h2 className="mt-5 text-[clamp(2.2rem,4vw,3.8rem)] font-semibold leading-[.98] tracking-[-.05em]">{t.controlTitle}</h2><div className="mt-8 divide-y divide-[#D8D0C2] border-y border-[#D8D0C2]">{t.permissions.map(([action, status, tone]) => <div key={action} className="flex items-center justify-between gap-4 py-4"><span className="text-sm font-semibold">{action}</span><span className={`rounded-full px-3 py-1.5 text-[10px] font-black uppercase tracking-[.08em] ${tone === 'ok' ? 'bg-[#DDF2E4] text-[#257A43]' : tone === 'review' ? 'bg-[#FCEAF2] text-[#B00C54]' : 'bg-[#E7E1D6] text-[#625B50]'}`}>{status}</span></div>)}</div><p className="mt-6 text-sm leading-7 text-[#625B50]">{t.controlBody}</p></article>
      <article className="rounded-[2rem] bg-[#D10E63] p-7 text-white sm:p-9"><p className="font-mono text-[10px] font-black uppercase tracking-[.18em] text-white/70">{t.memoryKicker}</p><div className="mt-7 flex items-center gap-4"><Image src="/images/lucas-avatar.png" alt="" width={64} height={64} className="size-16 rounded-full object-cover ring-2 ring-white/30" /><div><h2 className="text-2xl font-semibold">Lucas</h2><p className="mt-1 text-xs text-white/70">{t.demoDisclosure}</p></div></div><h3 className="mt-8 text-[clamp(2.2rem,4vw,3.8rem)] font-semibold leading-[.98] tracking-[-.05em]">{t.memoryTitle}</h3><ul className="mt-8 space-y-4">{t.memoryItems.map((item) => <li key={item} className="flex gap-3 text-sm font-semibold leading-7"><CircleCheck className="mt-1 size-4 shrink-0" />{item}</li>)}</ul><p className="mt-8 border-t border-white/20 pt-6 text-sm leading-7 text-white/80">{t.memoryBody}</p></article>
    </div></section>

    <section className="bg-[#181615] px-5 py-20 text-white sm:px-8 sm:py-28"><div className="editorial-shell"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><SectionTitle dark kicker={t.productKicker} title={t.productTitle} /><p className="max-w-2xl text-[16px] leading-8 text-[#CFC6B8] lg:pt-8">{t.productBody}</p></div><figure className="mt-12 overflow-hidden rounded-[2rem] border border-white/10 bg-[#211E1B]"><div className="relative aspect-[16/9] min-h-[300px]"><Image src="/images/unitalk-collaborative-workspace.png" alt={t.workspaceAlt} fill sizes="(min-width: 1024px) 1152px, 100vw" className="object-cover object-top" /></div><figcaption className="flex flex-col justify-between gap-4 border-t border-white/10 p-5 text-xs text-[#AFA397] sm:flex-row"><span>{t.workspaceCaption}</span><Link href="/workspace" className="font-bold text-[#F2A4C5]">{t.workspaceCta} →</Link></figcaption></figure></div></section>

    <section className="px-5 py-16 sm:px-8"><div className="editorial-shell"><p className="font-mono text-[10px] font-black uppercase tracking-[.18em] text-[#B00C54]">{t.detailsKicker}</p><div className="mt-7 grid gap-px overflow-hidden rounded-3xl border border-[#CFC5B5] bg-[#CFC5B5] sm:grid-cols-2 lg:grid-cols-4">{t.detailLinks.map((item) => <Link key={item.href} href={item.href} className="group min-h-44 bg-[#FAF8F3] p-6 hover:bg-white"><p className="text-lg font-semibold">{item.title}</p><p className="mt-3 text-sm leading-6 text-[#625B50]">{item.body}</p><ArrowRight className="mt-6 size-4 text-[#D10E63] transition-transform group-hover:translate-x-1" /></Link>)}</div></div></section>

    <section className="bg-[#D10E63] px-5 py-20 text-white sm:px-8 sm:py-24"><div className="editorial-shell grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="font-mono text-[10px] font-black uppercase tracking-[.18em] text-white/70">{t.finalKicker}</p><h2 className="mt-5 max-w-5xl text-[clamp(2.7rem,6vw,5.8rem)] font-semibold leading-[.92] tracking-[-.065em]">{t.finalTitle}</h2><p className="mt-7 max-w-2xl text-[17px] leading-8 text-white/80">{t.finalBody}</p><p className="mt-6 text-sm font-semibold">{t.trial}</p></div><div className="flex min-w-64 flex-col gap-3"><PrimaryCta label={t.primaryCta} dark /><Link href="/tarifs" className="text-center text-sm font-bold text-white underline decoration-white/35 underline-offset-4">{t.fullPrice}</Link></div></div></section>
  </main>
}

function PrimaryCta({ label, dark = false }: { label: string; dark?: boolean }) { return <Link href="/missions?composer=1&source=collaborateurs-ia" className={`group inline-flex min-h-12 items-center justify-center gap-2 rounded-full px-7 text-sm font-bold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 ${dark ? 'bg-[#181615] text-white focus-visible:ring-white focus-visible:ring-offset-[#D10E63]' : 'bg-[#181615] text-white focus-visible:ring-[#D10E63] focus-visible:ring-offset-[#F3EFE6]'}`}>{label}<ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></Link> }

function MissionSnapshot({ lang }: { lang: Lang }) { const t = COPY[lang]; return <aside className="overflow-hidden rounded-[2rem] border border-[#292521] bg-[#181615] text-white shadow-[0_35px_80px_-45px_rgba(28,26,23,.85)]"><div className="flex items-center justify-between border-b border-white/10 p-5"><div className="flex items-center gap-3"><Image src="/images/lucas-avatar.png" alt="" width={40} height={40} className="size-10 rounded-full object-cover" /><div><p className="text-sm font-bold">Lucas</p><p className="text-[10px] text-[#AFA397]">{t.snapshotRole}</p></div></div><span className="rounded-full bg-[#D10E63]/15 px-3 py-1.5 font-mono text-[9px] font-black uppercase tracking-[.12em] text-[#F2A4C5]">{t.demoDisclosure}</span></div><div className="p-6"><p className="font-mono text-[9px] font-black uppercase tracking-[.18em] text-[#F2A4C5]">{t.currentMission}</p><h2 className="mt-3 text-xl font-semibold">{t.demoMission}</h2><div className="mt-7 space-y-4">{t.snapshotEvents.map(([time, event], index) => <div key={time} className="flex gap-4"><span className="font-mono text-[10px] text-[#857C6E]">{time}</span><span className={`mt-1.5 size-2 shrink-0 rounded-full ${index === t.snapshotEvents.length - 1 ? 'bg-[#F2A4C5]' : 'bg-[#45C578]'}`} /><p className="text-xs leading-5 text-[#CFC6B8]">{event}</p></div>)}</div><div className="mt-7 rounded-2xl border border-[#D10E63]/30 bg-[#D10E63]/10 p-4"><p className="font-mono text-[9px] font-black uppercase tracking-[.14em] text-[#F2A4C5]">{t.humanApproval}</p><p className="mt-2 text-sm font-semibold">{t.approvalQuestion}</p></div></div></aside> }

function FormatTabs({ lang }: { lang: Lang }) { const t = COPY[lang]; const [active, setActive] = useState<FormatKey>('text'); const refs = useRef<Record<FormatKey, HTMLButtonElement | null>>({ text: null, image: null, audio: null, video: null, code: null }); const item = t.formats[active]; function onKeyDown(event: React.KeyboardEvent<HTMLButtonElement>, index: number) { let next = index; if (event.key === 'ArrowRight') next = (index + 1) % FORMAT_KEYS.length; else if (event.key === 'ArrowLeft') next = (index - 1 + FORMAT_KEYS.length) % FORMAT_KEYS.length; else if (event.key === 'Home') next = 0; else if (event.key === 'End') next = FORMAT_KEYS.length - 1; else return; event.preventDefault(); const key = FORMAT_KEYS[next]; setActive(key); refs.current[key]?.focus() } return <div className="mt-10"><div role="tablist" aria-label={t.formatsTabLabel} className="flex gap-2 overflow-x-auto pb-2">{FORMAT_KEYS.map((key, index) => <button key={key} ref={(node) => { refs.current[key] = node }} id={`format-tab-${key}`} role="tab" type="button" aria-selected={active === key} aria-controls={`format-panel-${key}`} tabIndex={active === key ? 0 : -1} onClick={() => setActive(key)} onKeyDown={(event) => onKeyDown(event, index)} className={`min-h-11 shrink-0 rounded-full border px-5 text-sm font-bold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#D10E63] ${active === key ? 'border-[#D10E63] bg-[#D10E63] text-white' : 'border-[#CFC5B5] bg-[#FAF8F3]'}`}>{t.formatLabels[key]}</button>)}</div><div id={`format-panel-${active}`} role="tabpanel" aria-labelledby={`format-tab-${active}`} tabIndex={0} className="mt-6 grid overflow-hidden rounded-[2rem] border border-[#CFC5B5] bg-[#FAF8F3] lg:grid-cols-3">{(['request', 'work', 'result'] as const).map((field) => <div key={field} className="border-b border-[#D8D0C2] p-6 last:border-b-0 lg:border-b-0 lg:border-r lg:last:border-r-0 sm:p-8"><p className="font-mono text-[9px] font-black uppercase tracking-[.18em] text-[#B00C54]">{t.flowLabels[field]}</p><p className="mt-5 text-[16px] font-semibold leading-7">{item[field]}</p></div>)}</div><p className="mt-5 text-xs leading-6 text-[#6E665A]">{t.formatsNote}</p></div> }

function SectionTitle({ kicker, title, dark = false }: { kicker: string; title: string; dark?: boolean }) { return <div><p className={`font-mono text-[10px] font-black uppercase tracking-[.2em] ${dark ? 'text-[#F2A4C5]' : 'text-[#B00C54]'}`}>{kicker}</p><h2 className="mt-5 max-w-4xl text-[clamp(2.4rem,5vw,5rem)] font-semibold leading-[.95] tracking-[-.06em]">{title}</h2></div> }

const COPY = {
  fr: {
    heroKicker: 'Collaborateur IA pour entreprise', heroTitle: 'Son identité IA reste la même.\nSes responsabilités évoluent.', heroBody: 'Confiez une mission récurrente à une identité IA qui travaille dans vos outils, conserve les méthodes validées et vous demande l’autorisation avant toute action sensible.', primaryCta: 'Décrire une première mission', secondaryCta: 'Voir une mission en action', trial: '7 jours gratuits · Sans carte bancaire · Configuration ajustable', heroProofs: [{ title: 'Une mission réelle', body: 'Vous partez du résultat attendu, pas d’un projet informatique.' }, { title: 'Vos règles', body: 'Sources, accès et validations sont définis avant l’exécution.' }, { title: 'Une expérience réutilisable', body: 'Les méthodes validées restent attachées à la même identité.' }],
    snapshotRole: 'Collaborateur IA · Démonstration', currentMission: 'Mission en cours', demoDisclosure: 'Démonstration fictive', demoMission: 'Répondre aux demandes clients reçues par email', snapshotEvents: [['09:12','3 nouveaux messages identifiés'],['09:14','Dossiers clients retrouvés dans le CRM autorisé'],['09:17','3 réponses préparées selon la politique v3'],['09:18','1 décision attend une validation humaine']],
    demoKicker: 'Une mission en action', demoTitle: 'Du travail confié au résultat validé.', demoBody: 'Un même fil montre ce qui a été lu, produit, bloqué et soumis à votre décision. Les accès présentés ici sont limités à cette mission.', allowedSources: 'Sources autorisées', sources: ['Boîte support', 'CRM clients', 'Politique de réponse v3'], demoProfile: 'Profil Relation client', timeline: [['09:12','Messages identifiés','Trois demandes sont classées selon leur urgence et leur objet.'],['09:14','Contexte retrouvé','Les dossiers correspondants sont consultés dans le CRM autorisé.'],['09:17','Réponses préparées','Les réponses appliquent la politique de réponse client validée, version 3.'],['09:18','Décision signalée','Une demande de remise commerciale sort du périmètre autonome.']], humanApproval: 'Validation humaine', approvalQuestion: 'Autoriser une remise commerciale de 10 % ?', approve: 'Autoriser', modify: 'Modifier', result: 'Résultat', resultValue: '2 réponses prêtes à envoyer', resultDetail: 'Une décision reste en attente. Aucun message sensible n’est envoyé sans validation.',
    startKicker: 'Commencer', startTitle: 'Une première mission, pas un projet informatique.', steps: [{ title: 'Décrivez', body: 'Expliquez le résultat attendu avec vos propres mots.' }, { title: 'Cadrez', body: 'Alma prépare les sources, droits et validations nécessaires.' }, { title: 'Validez', body: 'Le Collaborateur produit le résultat et vous soumet les décisions sensibles.' }],
    formatsKicker: 'Livrables', formatsTitle: 'Le format dépend du travail à accomplir.', formatsBody: 'Texte, image, audio, vidéo ou code : votre Collaborateur IA utilise seulement les modèles et outils autorisés pour la mission.', formatsTabLabel: 'Formats de travail', formatLabels: { text: 'Texte', image: 'Image', audio: 'Audio', video: 'Vidéo', code: 'Code' }, flowLabels: { request: 'Demande', work: 'Travail', result: 'Livrable' }, formats: { text: { request: 'Répondre à une demande client avec son contexte.', work: 'Retrouver les informations autorisées et appliquer les règles de réponse.', result: 'Une réponse contextualisée prête à valider.' }, image: { request: 'Comparer deux versions d’un visuel produit.', work: 'Relever les écarts visibles et documenter les modifications.', result: 'Une comparaison exploitable par l’équipe.' }, audio: { request: 'Transformer une réunion en décisions et actions.', work: 'Transcrire, distinguer les intervenants et structurer les décisions.', result: 'Un compte rendu avec responsables et échéances.' }, video: { request: 'Préparer une démonstration pour publication.', work: 'Identifier les séquences utiles et préparer chapitres et sous-titres.', result: 'Une vidéo documentée prête pour la validation éditoriale.' }, code: { request: 'Réconcilier deux exports de ventes.', work: 'Écrire et tester un script dans un environnement contrôlé.', result: 'Un fichier nettoyé, les anomalies et le script versionné.' } }, formatsNote: 'Disponibilité selon les modèles, l’infrastructure et les droits configurés. Code est un format de production ; le Terminal est un moyen d’exécution distinct.',
    controlKicker: 'Contrôle humain', controlTitle: 'Les limites sont visibles avant le travail.', permissions: [['Lire les demandes','Autorisé','ok'],['Préparer une réponse','Autorisé','ok'],['Accorder une remise','Validation','review'],['Modifier les tarifs','Interdit','no']] as const, controlBody: 'Une intégration disponible ne donne aucun droit automatique. Les permissions sont attribuées mission par mission.',
    memoryKicker: 'Ce que Lucas conserve', memoryTitle: 'La prochaine mission ne repart pas de zéro.', memoryItems: ['Politique de réponse client · version 3', 'Règles de qualification commerciale · version 2', 'Corrections approuvées par l’équipe'], memoryBody: 'L’expérience conservée correspond uniquement aux méthodes, corrections et décisions que votre entreprise a validées. Un historique importé ne devient jamais automatiquement une mémoire fiable.',
    productKicker: 'Aperçu produit', productTitle: 'Le travail, les blocages et les validations dans le même espace.', productBody: 'Workspace réunit le fil de mission, les fichiers produits, les actions effectuées et les décisions attendues. Vos équipes voient où intervenir sans relire toute la conversation.', workspaceAlt: 'Aperçu de l’interface collaborative Unitalk Workspace', workspaceCaption: 'Aperçu de l’interface Unitalk Workspace. Les données affichées sont illustratives.', workspaceCta: 'Découvrir Workspace',
    detailsKicker: 'Approfondir', detailLinks: [{ title: 'Modèles IA', body: 'Routage, budgets et modèles autorisés.', href: '/ai-gateway' }, { title: 'Architecture', body: 'Isolation, exécution et infrastructure privée.', href: '/architecture' }, { title: 'Applications', body: 'Intégrations et applications métier autorisées.', href: '/collaborateurs-ia/applications' }, { title: 'Desktop', body: 'Fichiers et terminal local selon les droits.', href: '/desktop' }],
    finalKicker: 'Votre première mission', finalTitle: 'Commencez par le travail que vous connaissez déjà.', finalBody: 'Décrivez le résultat attendu. Alma prépare le cadre, recommande le profil adapté et vous laisse les décisions qui engagent votre entreprise.', fullPrice: 'Voir le prix complet',
  },
  en: {
    heroKicker: 'AI Collaborator for business', heroTitle: 'The AI identity stays the same.\nIts responsibilities evolve.', heroBody: 'Entrust a recurring mission to an AI identity that works in your tools, retains approved methods and asks permission before any sensitive action.', primaryCta: 'Describe a first mission', secondaryCta: 'See a mission in action', trial: '7 days free · No credit card · Adjustable setup', heroProofs: [{ title: 'Real work', body: 'Start from the expected outcome, not an IT project.' }, { title: 'Your rules', body: 'Sources, access and approvals are defined before execution.' }, { title: 'Reusable experience', body: 'Approved methods remain attached to the same identity.' }],
    snapshotRole: 'AI Collaborator · Demonstration', currentMission: 'Current mission', demoDisclosure: 'Fictional demonstration', demoMission: 'Answer customer requests received by email', snapshotEvents: [['09:12','3 new messages identified'],['09:14','Customer records found in the authorized CRM'],['09:17','3 replies prepared under policy v3'],['09:18','1 decision awaiting human approval']],
    demoKicker: 'A mission in action', demoTitle: 'From entrusted work to an approved result.', demoBody: 'One thread shows what was read, produced, blocked and submitted for your decision. Access shown here is limited to this mission.', allowedSources: 'Authorized sources', sources: ['Support inbox', 'Customer CRM', 'Response policy v3'], demoProfile: 'Customer relations profile', timeline: [['09:12','Messages identified','Three requests are classified by urgency and subject.'],['09:14','Context retrieved','Matching records are consulted in the authorized CRM.'],['09:17','Replies prepared','Replies apply approved customer response policy version 3.'],['09:18','Decision flagged','A discount request falls outside the autonomous scope.']], humanApproval: 'Human approval', approvalQuestion: 'Authorize a 10% commercial discount?', approve: 'Authorize', modify: 'Modify', result: 'Result', resultValue: '2 replies ready to send', resultDetail: 'One decision remains pending. No sensitive message is sent without approval.',
    startKicker: 'Get started', startTitle: 'One first mission, not an IT project.', steps: [{ title: 'Describe', body: 'Explain the expected outcome in your own words.' }, { title: 'Scope', body: 'Alma prepares the required sources, permissions and approvals.' }, { title: 'Approve', body: 'The Collaborator produces the result and submits sensitive decisions.' }],
    formatsKicker: 'Deliverables', formatsTitle: 'The format follows the work.', formatsBody: 'Text, image, audio, video or code: your AI Collaborator only uses models and tools authorized for the mission.', formatsTabLabel: 'Work formats', formatLabels: { text: 'Text', image: 'Image', audio: 'Audio', video: 'Video', code: 'Code' }, flowLabels: { request: 'Request', work: 'Work', result: 'Deliverable' }, formats: { text: { request: 'Answer a customer request with its context.', work: 'Retrieve authorized information and apply response rules.', result: 'A contextual reply ready for approval.' }, image: { request: 'Compare two versions of a product visual.', work: 'Identify visible differences and document changes.', result: 'An actionable comparison for the team.' }, audio: { request: 'Turn a meeting into decisions and actions.', work: 'Transcribe, identify speakers and structure decisions.', result: 'Meeting notes with owners and deadlines.' }, video: { request: 'Prepare a demonstration for publication.', work: 'Identify useful sequences and prepare chapters and subtitles.', result: 'A documented video ready for editorial approval.' }, code: { request: 'Reconcile two sales exports.', work: 'Write and test a script in a controlled environment.', result: 'A cleaned file, anomalies and a versioned script.' } }, formatsNote: 'Availability depends on configured models, infrastructure and permissions. Code is a production format; Terminal is a separate execution method.',
    controlKicker: 'Human control', controlTitle: 'Limits are visible before work starts.', permissions: [['Read requests','Allowed','ok'],['Prepare a reply','Allowed','ok'],['Grant a discount','Approval','review'],['Change prices','Forbidden','no']] as const, controlBody: 'An available integration grants no automatic access. Permissions are assigned mission by mission.',
    memoryKicker: 'What Lucas retains', memoryTitle: 'The next mission does not start from zero.', memoryItems: ['Customer response policy · version 3', 'Sales qualification rules · version 2', 'Corrections approved by the team'], memoryBody: 'Retained experience only includes methods, corrections and decisions approved by your company. Imported history never automatically becomes reliable memory.',
    productKicker: 'Product preview', productTitle: 'Work, blockers and approvals in one space.', productBody: 'Workspace brings together the mission thread, produced files, completed actions and pending decisions. Teams see where to step in without rereading the whole conversation.', workspaceAlt: 'Preview of the Unitalk collaborative Workspace interface', workspaceCaption: 'Preview of Unitalk Workspace. Displayed data is illustrative.', workspaceCta: 'Discover Workspace',
    detailsKicker: 'Go deeper', detailLinks: [{ title: 'AI models', body: 'Routing, budgets and authorized models.', href: '/ai-gateway' }, { title: 'Architecture', body: 'Isolation, execution and private infrastructure.', href: '/architecture' }, { title: 'Applications', body: 'Authorized integrations and business applications.', href: '/collaborateurs-ia/applications' }, { title: 'Desktop', body: 'Local files and terminal under permissions.', href: '/desktop' }],
    finalKicker: 'Your first mission', finalTitle: 'Start with work you already know.', finalBody: 'Describe the expected outcome. Alma prepares the scope, recommends the right profile and leaves company-binding decisions with you.', fullPrice: 'View full pricing',
  },
} as const
