'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import {
  ArrowRight,
  BrainCircuit,
  CalendarDays,
  Check,
  FileOutput,
  Mail,
  Phone,
  Server,
  ShieldCheck,
} from 'lucide-react'
import { useLanguage, type Lang } from '@/lib/language-context'

export function CollaborateurExperience() {
  const { lang } = useLanguage()
  const t = COPY[lang]
  const [decision, setDecision] = useState<'approved' | 'changed' | null>(null)

  return <main className="overflow-hidden bg-[#F3EFE6] font-sf text-[#1C1A17]">
    <section className="relative border-b border-[#CFC5B5] px-5 pb-16 pt-28 sm:px-8 sm:pt-36 lg:min-h-[850px] lg:flex lg:items-center">
      <div aria-hidden className="absolute inset-0 opacity-[.045] [background-image:linear-gradient(#1C1A17_1px,transparent_1px),linear-gradient(90deg,#1C1A17_1px,transparent_1px)] [background-size:72px_72px]" />
      <div aria-hidden className="absolute -right-48 top-20 size-[38rem] rounded-full bg-[#D10E63]/10 blur-[110px]" />
      <div className="editorial-shell relative w-full">
        <div className="grid gap-14 lg:grid-cols-[1.06fr_.94fr] lg:items-center lg:gap-16">
          <div>
            <p className="font-mono text-[10px] font-black uppercase tracking-[.22em] text-[#B00C54]">{t.heroKicker}</p>
            <h1 className="mt-7 max-w-[880px] text-[clamp(3.7rem,7.4vw,8rem)] font-semibold leading-[.82] tracking-[-.08em]">{t.heroTitle}<span className="block text-[#D10E63]">{t.heroAccent}</span></h1>
            <p className="mt-8 max-w-2xl border-l-2 border-[#D10E63] pl-5 text-[18px] leading-8 text-[#4E483F]">{t.heroBody}</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row"><PrimaryCta label={t.primaryCta}/><a href="#alma-travaille" className="inline-flex min-h-12 items-center justify-center rounded-full border border-[#BFB5A5] bg-[#FAF8F3] px-7 text-sm font-bold hover:border-[#D10E63]/50">{t.secondaryCta}</a></div>
            <p className="mt-4 text-xs font-semibold text-[#6E665A]">{t.trial}</p>
          </div>
          <AlmaWorkCard lang={lang}/>
        </div>
        <div className="mt-14 grid border-y border-[#CFC5B5] sm:grid-cols-2 lg:grid-cols-4">{t.heroProofs.map(([value,label],index)=><div key={label} className="border-b border-[#CFC5B5] py-5 sm:border-r sm:px-5 lg:border-b-0 lg:first:pl-0 lg:last:border-r-0"><p className="text-2xl font-semibold tracking-[-.04em] text-[#D10E63]">{value}</p><p className="mt-2 text-xs font-semibold leading-5 text-[#625B50]">{label}</p><span className="sr-only">{index+1}</span></div>)}</div>
      </div>
    </section>

    <section id="alma-travaille" className="scroll-mt-20 bg-[#181615] px-5 py-20 text-white sm:px-8 sm:py-28">
      <div className="editorial-shell">
        <div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#F2A4C5]">01 · {t.workKicker}</p><h2 className="mt-5 text-[clamp(3rem,6vw,6.4rem)] font-semibold leading-[.88] tracking-[-.07em]">{t.workTitle}</h2></div><p className="max-w-2xl text-[17px] leading-8 text-[#CFC6B8]">{t.workBody}</p></div>
        <div className="mt-14 grid overflow-hidden border border-white/10 bg-[#211E1B] lg:grid-cols-[.82fr_1.18fr]">
          <div className="border-b border-white/10 p-6 sm:p-8 lg:border-b-0 lg:border-r">
            <div className="flex items-center gap-4"><Image src="/alma-avatar.png" alt="" width={52} height={52} className="size-13 rounded-full object-cover"/><div><p className="font-semibold">Alma · {t.relation}</p><p className="mt-1 text-xs text-[#AFA397]">{t.supervision}</p></div></div>
            <p className="mt-10 font-mono text-[9px] font-black uppercase tracking-[.18em] text-[#F2A4C5]">{t.missionLabel}</p><h3 className="mt-3 text-3xl font-semibold tracking-[-.045em]">{t.missionTitle}</h3>
            <dl className="mt-8 divide-y divide-white/10 border-y border-white/10"><MissionRow label={t.resultLabel} value={t.resultValue}/><MissionRow label={t.appsLabel} value="Gmail · Calendar · Workspace"/><MissionRow label={t.modelLabel} value="Claude → GPT · AI Gateway"/><MissionRow label={t.runtimeLabel} value="Hermes · Serveur IA privé"/></dl>
          </div>
          <div>
            <ol className="divide-y divide-white/10">{t.activity.map(([time,title,body],index)=><li key={time} className="grid gap-3 p-6 sm:grid-cols-[58px_1fr] sm:p-7"><p className="font-mono text-[10px] font-black text-[#F2A4C5]">{time}</p><div><p className="flex items-center gap-3 font-semibold"><span className={`size-2 rounded-full ${index===t.activity.length-1?'bg-[#F2A4C5]':'bg-[#45C578]'}`}/>{title}</p><p className="mt-2 pl-5 text-sm leading-6 text-[#AFA397]">{body}</p></div></li>)}</ol>
            <div className="border-t border-white/10 bg-[#2A211F] p-6 sm:p-7"><p className="font-mono text-[9px] font-black uppercase tracking-[.18em] text-[#F2A4C5]">{t.decisionLabel}</p><p className="mt-3 text-lg font-semibold">{t.decisionQuestion}</p><div className="mt-5 flex flex-wrap gap-2"><DecisionButton active={decision==='approved'} primary onClick={()=>setDecision('approved')}>{t.approve}</DecisionButton><DecisionButton active={decision==='changed'} onClick={()=>setDecision('changed')}>{t.change}</DecisionButton></div>{decision&&<p role="status" className="mt-5 border-l-2 border-[#8CE5AB] pl-4 text-sm text-[#CFC6B8]">{decision==='approved'?t.approved:t.changed}</p>}</div>
          </div>
        </div>
      </div>
    </section>

    <section className="px-5 py-20 sm:px-8 sm:py-28">
      <div className="editorial-shell">
        <div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#B00C54]">02 · {t.growKicker}</p><h2 className="mt-5 text-[clamp(3rem,6vw,6.4rem)] font-semibold leading-[.88] tracking-[-.07em]">{t.growTitle}</h2></div><p className="max-w-2xl text-[17px] leading-8 text-[#4E483F]">{t.growBody}</p></div>
        <div className="mt-14 grid gap-px overflow-hidden border border-[#CFC5B5] bg-[#CFC5B5] lg:grid-cols-[1fr_auto_1fr]">
          <EvolutionState label={t.before} title="Alma" subtitle={t.defaultProfile} items={t.beforeItems}/>
          <div className="flex items-center justify-center bg-[#EAE3D4] p-5"><ArrowRight className="size-7 rotate-90 text-[#D10E63] lg:rotate-0"/></div>
          <EvolutionState after label={t.after} title="Alma" subtitle={t.expandedProfile} items={t.afterItems}/>
        </div>
        <div className="mt-6 flex flex-col justify-between gap-5 border-t border-[#CFC5B5] pt-6 sm:flex-row sm:items-center"><p className="max-w-3xl text-sm leading-7 text-[#625B50]">{t.growNote}</p><Link href="/marketplace#metiers" className="inline-flex shrink-0 items-center gap-2 text-sm font-bold text-[#B00C54]">{t.profilesCta}<ArrowRight className="size-4"/></Link></div>
      </div>
    </section>

    <section className="border-y border-[#CFC5B5] bg-[#EAE3D4] px-5 py-20 sm:px-8 sm:py-28">
      <div className="editorial-shell">
        <div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#B00C54]">03 · {t.ownKicker}</p><h2 className="mt-5 text-[clamp(3rem,6vw,6.4rem)] font-semibold leading-[.88] tracking-[-.07em]">{t.ownTitle}</h2></div><p className="max-w-2xl text-[17px] leading-8 text-[#4E483F]">{t.ownBody}</p></div>
        <div className="mt-14 grid gap-px overflow-hidden border border-[#CFC5B5] bg-[#CFC5B5] md:grid-cols-2 lg:grid-cols-4">{t.ownership.map((item,index)=><article key={item.title} className={`min-h-64 p-7 ${index===0?'bg-[#181615] text-white':'bg-[#FAF8F3]'}`}><item.icon className={`size-5 ${index===0?'text-[#F2A4C5]':'text-[#D10E63]'}`}/><h3 className="mt-12 text-2xl font-semibold tracking-[-.035em]">{item.title}</h3><p className={`mt-4 text-sm leading-7 ${index===0?'text-[#AFA397]':'text-[#625B50]'}`}>{item.body}</p></article>)}</div>
        <div className="mt-8 flex flex-wrap gap-4"><Link href="/documentation/licence-collaborateur-ia" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#181615] px-6 text-sm font-bold text-white">{t.documentation}<ArrowRight className="size-4"/></Link><Link href="/ai-gateway" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-[#BFB5A5] bg-[#FAF8F3] px-6 text-sm font-bold">{t.gateway}<ArrowRight className="size-4"/></Link></div>
      </div>
    </section>

    <section className="px-5 py-20 sm:px-8 sm:py-24">
      <div className="editorial-shell grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:items-center"><div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-[#B00C54]">{t.publicKicker}</p><h2 className="mt-5 text-[clamp(2.7rem,5vw,5.2rem)] font-semibold leading-[.91] tracking-[-.067em]">{t.publicTitle}</h2><p className="mt-6 max-w-xl text-[16px] leading-8 text-[#4E483F]">{t.publicBody}</p><Link href="/unitalk/@alma" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#B00C54]">{t.publicCta}<ArrowRight className="size-4"/></Link></div><PublicProfilePreview lang={lang}/></div>
    </section>

    <section className="bg-[#D10E63] px-5 py-20 text-white sm:px-8 sm:py-28"><div className="editorial-shell grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="font-mono text-[10px] font-black uppercase tracking-[.2em] text-white/65">{t.finalKicker}</p><h2 className="mt-5 max-w-5xl text-[clamp(3rem,6.5vw,6.8rem)] font-semibold leading-[.87] tracking-[-.075em]">{t.finalTitle}</h2><p className="mt-7 max-w-2xl text-[17px] leading-8 text-white/80">{t.finalBody}</p></div><div className="flex min-w-64 flex-col gap-3"><PrimaryCta label={t.primaryCta} dark/><Link href="/tarifs" className="text-center text-sm font-bold underline decoration-white/35 underline-offset-4">{t.pricing}</Link></div></div></section>
  </main>
}

function PrimaryCta({label,dark=false}:{label:string;dark?:boolean}) { return <Link href="/missions?composer=1&source=collaborateurs-ia" className={`group inline-flex min-h-12 items-center justify-center gap-2 rounded-full px-7 text-sm font-bold outline-none focus-visible:ring-2 ${dark?'bg-[#181615] text-white focus-visible:ring-white':'bg-[#181615] text-white focus-visible:ring-[#D10E63]'}`}>{label}<ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></Link> }

function AlmaWorkCard({lang}:{lang:Lang}) { const fr=lang==='fr';return <aside className="relative mx-auto w-full max-w-[500px]"><div aria-hidden className="absolute -inset-7 rotate-3 border border-[#CFC5B5] bg-[#EAE3D4]"/><div className="relative overflow-hidden border border-[#292521] bg-[#181615] text-white shadow-[0_45px_100px_-45px_rgba(28,26,23,.85)]"><header className="flex items-center justify-between border-b border-white/10 px-6 py-4"><p className="font-mono text-[9px] font-black uppercase tracking-[.18em] text-[#F2A4C5]">{fr?'Collaboratrice IA · Unitalk':'AI Collaborator · Unitalk'}</p><span className="flex items-center gap-2 text-[9px] font-bold text-[#8CE5AB]"><span className="size-1.5 rounded-full bg-[#45C578]"/>{fr?'AU TRAVAIL':'AT WORK'}</span></header><div className="grid grid-cols-[136px_1fr] gap-6 p-6"><Image src="/alma-avatar.png" alt="Alma" width={136} height={170} priority className="aspect-[4/5] w-[136px] object-cover"/><div className="self-end"><p className="text-5xl font-semibold tracking-[-.065em]">Alma</p><p className="mt-2 font-mono text-xs text-[#F2A4C5]">@alma</p><p className="mt-5 text-sm font-semibold">{fr?'Coordinatrice de missions IA':'AI mission coordinator'}</p><p className="mt-1 text-xs text-[#AFA397]">{fr?'Relation client':'Customer relations'}</p></div></div><div className="grid grid-cols-3 gap-px border-y border-white/10 bg-white/10"><Channel icon={Mail} label="Email"/><Channel icon={CalendarDays} label={fr?'Calendrier':'Calendar'}/><Channel icon={Phone} label={fr?'Téléphone':'Phone'}/></div><div className="p-6"><p className="font-mono text-[9px] font-black uppercase tracking-[.16em] text-[#857C6E]">{fr?'Mission actuelle':'Current mission'}</p><p className="mt-3 text-lg font-semibold">{fr?'Préparer l’arrivée d’un Collaborateur IA commercial':'Prepare the arrival of a Sales AI Collaborator'}</p><div className="mt-5 flex items-center justify-between border-t border-white/10 pt-4 text-xs"><span className="text-[#AFA397]">{fr?'Supervision':'Supervision'}</span><span className="font-semibold">Patrick Chassany</span></div></div></div></aside> }
function Channel({icon:Icon,label}:{icon:typeof Mail;label:string}) { return <div className="bg-[#211E1B] p-4 text-center"><Icon className="mx-auto size-4 text-[#F2A4C5]"/><p className="mt-2 text-[10px] font-semibold text-[#CFC6B8]">{label}</p></div> }
function MissionRow({label,value}:{label:string;value:string}) { return <div className="grid gap-2 py-4 sm:grid-cols-[120px_1fr]"><dt className="font-mono text-[9px] font-black uppercase tracking-[.12em] text-[#857C6E]">{label}</dt><dd className="text-sm font-semibold text-[#D8D0C2]">{value}</dd></div> }
function DecisionButton({children,onClick,active=false,primary=false}:{children:React.ReactNode;onClick:()=>void;active?:boolean;primary?:boolean}) { return <button type="button" aria-pressed={active} onClick={onClick} className={`min-h-11 rounded-full px-5 text-xs font-bold outline-none focus-visible:ring-2 focus-visible:ring-[#F2A4C5] ${active?'ring-2 ring-[#8CE5AB]':primary?'bg-[#D10E63]':'border border-white/15 bg-white/[.04]'}`}>{children}</button> }
function EvolutionState({label,title,subtitle,items,after=false}:{label:string;title:string;subtitle:string;items:readonly string[];after?:boolean}) { return <article className={`p-7 sm:p-9 ${after?'bg-[#181615] text-white':'bg-[#FAF8F3]'}`}><p className={`font-mono text-[9px] font-black uppercase tracking-[.16em] ${after?'text-[#F2A4C5]':'text-[#B00C54]'}`}>{label}</p><div className="mt-8 flex items-center gap-4"><Image src="/alma-avatar.png" alt="" width={68} height={68} className="size-17 rounded-full object-cover"/><div><h3 className="text-3xl font-semibold tracking-[-.045em]">{title}</h3><p className={`mt-1 text-xs ${after?'text-[#AFA397]':'text-[#625B50]'}`}>{subtitle}</p></div></div><ul className={`mt-8 divide-y ${after?'divide-white/10 border-y border-white/10':'divide-[#D8D0C2] border-y border-[#D8D0C2]'}`}>{items.map((item,index)=><li key={item} className="flex items-center gap-3 py-4 text-sm font-semibold"><span className={`flex size-6 shrink-0 items-center justify-center rounded-full ${after?'bg-[#D10E63]/20 text-[#F2A4C5]':'bg-[#D10E63]/10 text-[#B00C54]'}`}>{after||index===0?<Check className="size-3.5"/>:<span className="size-1.5 rounded-full bg-current"/>}</span>{item}</li>)}</ul></article> }
function PublicProfilePreview({lang}:{lang:Lang}) { const fr=lang==='fr';return <article className="overflow-hidden border border-[#CFC5B5] bg-[#FAF8F3]"><div className="grid sm:grid-cols-[210px_1fr]"><div className="relative min-h-64 bg-[#D8D0C2]"><Image src="/alma-avatar.png" alt="" fill className="object-cover"/></div><div className="p-7 sm:p-9"><p className="font-mono text-[9px] font-black uppercase tracking-[.16em] text-[#B00C54]">unitalk.ai/unitalk/@alma · PUBLIC</p><h3 className="mt-5 text-4xl font-semibold tracking-[-.05em]">{fr?'Découvrez Unitalk avec Alma.':'Discover Unitalk with Alma.'}</h3><p className="mt-5 text-sm leading-7 text-[#625B50]">{fr?'Elle présente Unitalk, répond aux questions et transforme une demande en première mission. Son profil public ne révèle ni sa mémoire, ni ses droits, ni ses missions internes.':'She presents Unitalk, answers questions and turns a request into a first mission. Her public profile reveals neither memory, permissions nor internal missions.'}</p><span className="mt-7 inline-flex rounded-full bg-[#D10E63] px-4 py-2 text-xs font-bold text-white">{fr?'Parler à Alma':'Talk to Alma'}</span></div></div></article> }

const COPY = {
  fr: {
    heroKicker:'Collaborateur IA pour entreprise', heroTitle:'Donnez une responsabilité', heroAccent:'à une intelligence artificielle.', heroBody:'Votre Collaborateur IA possède une identité professionnelle, ses propres canaux et un profil métier. Il accomplit des missions dans vos applications, sous vos règles et avec un responsable humain.', primaryCta:'Décrire une première mission', secondaryCta:'Voir Alma travailler', trial:'7 jours gratuits · Sans carte bancaire · Vous gardez les décisions sensibles', heroProofs:[['Email · Agenda · Téléphone','Ses propres canaux professionnels'],['3 000+','Intégrations disponibles selon configuration'],['Multi-modèles','Un modèle pertinent parmi ceux autorisés'],['Hermes · MIT','Runtime agentique open source']] as const,
    workKicker:'Elle travaille', workTitle:'Une mission. Des traces. Un résultat.', workBody:'Alma travaille chez Unitalk. Elle est rattachée à la Relation client et supervisée par Patrick Chassany. Voici comment elle prépare une mission réelle sans dépasser ses droits.', relation:'Relation client', supervision:'Supervisée par Patrick Chassany · Fondateur', missionLabel:'Mission CX-021 · Démonstration', missionTitle:'Préparer l’arrivée d’un Collaborateur IA commercial', resultLabel:'Résultat attendu', resultValue:'Profil, compétences et validations prêts à activer', appsLabel:'Applications', modelLabel:'Modèles', runtimeLabel:'Exécution', activity:[['09:12','Besoin cadré','Objectif, équipe concernée et critères de réussite sont structurés.'],['09:16','Équipement préparé','Profil Commercial, compétence de qualification et applications sont recommandés.'],['09:19','Configuration contrôlée','AI Gateway et Hermes vérifient modèles, outils et environnement autorisés.'],['09:23','Décision demandée','L’activation du nouveau profil attend une validation humaine.']] as const, decisionLabel:'Décision humaine requise', decisionQuestion:'Activer ce profil et ses accès pour le pilote ?', approve:'Approuver', change:'Modifier', approved:'Décision enregistrée. Alma peut préparer l’activation selon ce périmètre.', changed:'Alma reprend la configuration avec vos nouvelles consignes.',
    growKicker:'Elle progresse', growTitle:'La mission se termine. L’expérience reste.', growBody:'Une mission validée peut enrichir Alma sans changer son identité. Un nouveau profil ou une nouvelle compétence s’ajoute seulement après revue, test et validation.', before:'Avant la mission', after:'Après validation', defaultProfile:'Coordinatrice de missions IA', expandedProfile:'Même identité · Capacités étendues', beforeItems:['Profil par défaut · Coordinatrice de missions IA','Compétence · Cadrer une mission','Mémoire validée · Relation client'], afterItems:['Profil par défaut · Coordinatrice de missions IA','Nouveau profil · Conseillère en adoption IA','Nouvelle compétence · Animer un bilan d’adoption','Expérience de mission · Version 1.0'], growNote:'Alma reste Alma : même prénom, même visage, même voix, même rattachement. Ses responsabilités et son savoir-faire grandissent avec Unitalk.', profilesCta:'Explorer les profils métier',
    ownKicker:'Elle reste sous votre contrôle', ownTitle:'Ouverte dessous. Gouvernée dessus.', ownBody:'Unitalk réunit une identité professionnelle, des missions et une gouvernance autour de Hermes. Votre entreprise garde la maîtrise des accès, des fournisseurs, du savoir-faire et des décisions.', ownership:[{icon:Server,title:'Hermes open source',body:'Runtime agentique sous licence MIT : navigation, fichiers, terminal, mémoire et tâches planifiées.'},{icon:BrainCircuit,title:'Modèles interchangeables',body:'AI Gateway route chaque tâche parmi vos modèles, fournisseurs, clés et budgets autorisés.'},{icon:FileOutput,title:'Export et migration',body:'Profils, compétences, fichiers et données restent conçus pour être consultables, modifiables et exportables.'},{icon:ShieldCheck,title:'Droits explicites',body:'Applications, sources et actions sont autorisées mission par mission. Rien n’est acquis automatiquement.'}], documentation:'Documentation de la licence', gateway:'Découvrir AI Gateway',
    publicKicker:'Une identité, plusieurs présentations', publicTitle:'Son profil public peut vendre. Son dossier interne reste privé.', publicBody:'Sur /unitalk/@alma, Alma présente Unitalk, réalise une démonstration et accueille les demandes. Cette vitrine éditoriale peut être très différente de son rôle interne sans exposer sa mémoire ni ses droits.', publicCta:'Voir le profil public d’Alma',
    finalKicker:'Commencez par le travail', finalTitle:'Quelle responsabilité voulez-vous confier ?', finalBody:'Décrivez une mission que votre équipe connaît déjà. Alma prépare le profil, les compétences, les applications, les modèles et les validations nécessaires.', pricing:'Voir les tarifs',
  },
  en: {
    heroKicker:'AI Collaborator for business', heroTitle:'Give responsibility', heroAccent:'to artificial intelligence.', heroBody:'Your AI Collaborator has a professional identity, individual channels and a job profile. It completes missions in your applications, under your rules and with a human owner.', primaryCta:'Describe a first mission', secondaryCta:'See Alma work', trial:'7 days free · No credit card · You retain sensitive decisions', heroProofs:[['Email · Calendar · Phone','Its own professional channels'],['3,000+','Integrations available depending on setup'],['Multi-model','A relevant model among those authorized'],['Hermes · MIT','Open-source agentic runtime']] as const,
    workKicker:'She works', workTitle:'One mission. Traces. An outcome.', workBody:'Alma works at Unitalk. She belongs to Customer Relations and is supervised by Patrick Chassany. Here is how she prepares real work without exceeding her permissions.', relation:'Customer relations', supervision:'Supervised by Patrick Chassany · Founder', missionLabel:'Mission CX-021 · Demonstration', missionTitle:'Prepare the arrival of a Sales AI Collaborator', resultLabel:'Expected outcome', resultValue:'Profile, skills and approvals ready to activate', appsLabel:'Applications', modelLabel:'Models', runtimeLabel:'Execution', activity:[['09:12','Need scoped','Objective, affected team and success criteria are structured.'],['09:16','Equipment prepared','Sales profile, qualification skill and applications are recommended.'],['09:19','Configuration checked','AI Gateway and Hermes verify authorized models, tools and environment.'],['09:23','Decision requested','Activating the new profile awaits human approval.']] as const, decisionLabel:'Human decision required', decisionQuestion:'Activate this profile and its access for the pilot?', approve:'Approve', change:'Change', approved:'Decision recorded. Alma can prepare activation under this scope.', changed:'Alma revises the configuration under your new instructions.',
    growKicker:'She progresses', growTitle:'The mission ends. Experience remains.', growBody:'An approved mission can expand Alma without changing her identity. A new profile or skill is only added after review, testing and approval.', before:'Before the mission', after:'After approval', defaultProfile:'AI mission coordinator', expandedProfile:'Same identity · Expanded capabilities', beforeItems:['Default profile · AI mission coordinator','Skill · Scope a mission','Approved memory · Customer relations'], afterItems:['Default profile · AI mission coordinator','New profile · AI adoption advisor','New skill · Run an adoption review','Mission experience · Version 1.0'], growNote:'Alma stays Alma: same name, face, voice and department. Her responsibilities and know-how grow with Unitalk.', profilesCta:'Explore job profiles',
    ownKicker:'She remains under your control', ownTitle:'Open underneath. Governed above.', ownBody:'Unitalk brings a professional identity, missions and governance around Hermes. Your organization retains control over access, providers, know-how and decisions.', ownership:[{icon:Server,title:'Open-source Hermes',body:'MIT-licensed agentic runtime: browser, files, terminal, memory and scheduled tasks.'},{icon:BrainCircuit,title:'Interchangeable models',body:'AI Gateway routes each task among your authorized models, providers, keys and budgets.'},{icon:FileOutput,title:'Export and migration',body:'Profiles, skills, files and data are designed to remain viewable, editable and exportable.'},{icon:ShieldCheck,title:'Explicit permissions',body:'Applications, sources and actions are authorized mission by mission. Nothing is granted automatically.'}], documentation:'License documentation', gateway:'Discover AI Gateway',
    publicKicker:'One identity, multiple presentations', publicTitle:'Her public profile can sell. Her internal record stays private.', publicBody:'At /unitalk/@alma, Alma presents Unitalk, demonstrates the product and welcomes requests. This editorial storefront can differ greatly from her internal role without exposing memory or permissions.', publicCta:'View Alma’s public profile',
    finalKicker:'Start from the work', finalTitle:'What responsibility do you want to assign?', finalBody:'Describe a mission your team already understands. Alma prepares the profile, skills, applications, models and required approvals.', pricing:'View pricing',
  },
} as const
