import type { Metadata } from 'next'
import Link from 'next/link'
import { EditorialPage } from '@/components/academy/editorial-page'
import { AcademyAlmaHero } from '@/components/academy/academy-alma-hero'

export const metadata:Metadata={title:'Créer son premier Collaborateur IA gratuitement',description:'En 60 minutes, cadrez une mission réelle et préparez le premier Collaborateur IA capable de l’accomplir.'}
const items=[['Partir d’un vrai problème','Choisir un travail qu’une personne ou une entreprise veut réellement voir accompli.'],['Définir le résultat','Préciser ce qui doit être livré, quand, sous quelle forme et comment la valeur sera jugée.'],['Donner un rôle au Collaborateur IA','Définir sa responsabilité, ses compétences et les limites de son intervention.'],['Lister les sources et les outils','Identifier les informations, fichiers et applications qu’il pourra utiliser.'],['Garder l’humain dans la boucle','Décider ce qu’il peut faire seul, ce qui doit être validé et ce qui reste interdit.'],['Préparer le premier test','Assembler un cas concret que vous pourrez exécuter avec Alma puis montrer à un client.']].map(([title,body])=>({title,body}))

export default function Page(){return <><EditorialPage kicker="Cadrage gratuit · 60 minutes" title="Commencez par une mission réelle." body="En une heure, cadrez le problème et préparez votre premier Collaborateur IA. Sans engagement, sans carte bancaire." items={items}/><AcademyAlmaHero title="Faites ce cadrage avec Alma." body="Créez votre compte, choisissez votre objectif et décrivez le travail. Alma personnalise la suite dans votre espace Formations." cta="Commencer maintenant"/><section className="border-y border-[#d8d0c2] bg-[#fffdf9] px-5 py-14"><div className="academy-reading"><p className="academy-kicker">Après le cadrage</p><h2 className="mt-5 text-3xl font-semibold tracking-[-.04em]">Choisissez un brief réel et produisez votre première preuve.</h2><p className="mt-4 text-sm leading-7 text-[#625b50]">Le cadrage de 60 minutes prépare votre projet. Une mission ouverte de 2 à 3 heures vous permet ensuite de confronter la méthode à un vrai résultat.</p><Link href="/academy/missions?gratuit=1" className="academy-text-link mt-6">Choisir parmi les 3 briefs gratuits</Link></div></section><section className="bg-[#181512] px-5 py-16 text-[#f8f1e7]"><div className="academy-shell"><p className="academy-kicker text-[#f2a4c5]">Construire</p><h2 className="academy-heading mt-5">Construisez-le avec Alma. Apprenez ensuite à le vendre.</h2><div className="mt-8 flex flex-wrap gap-4"><Link href="/academy/onboarding" className="academy-button academy-button-primary">Créer avec Alma</Link><Link href="/academy/formations/co-createur-ia" className="academy-button academy-button-secondary">Voir la formation Co-créateur</Link></div></div></section></>}
